freqtrade/freqtrade

.pylintrc, analyze.py, main.py, rpc/telegram.py, utils.py
This PR fixes a bunch of fairly trivial warnings from PyLint linter. Easiest to review commit-by-commit.
=> Linter fixes

main.py, rpc/telegram.py
Moved the condition of whether the `TraderThread` should stop to it's internal attribute. So instead of a module global variable, you can now just call `get_instance().stop()`. The big change block is just moving the `def get_instance` to be declared after the `TradeThread` class.
=> Move _should_stop from module global to class variable

README.md, analyze.py, requirements.txt
Now we use TA-lib for calculating MACD and StochRSI. This PR removes the manual calculation of StochRSI and the whole `stockstats` library.
Commit c2d7854 (that adds the TA-lib to requirements.txt) is the same that is also in PR #7 .
=> Use TA-lib for MACD and StochRSI

analyze.py
When moving to TA-lib, I disabled the EMA plots that were calculated automatically by `stockstats`. This PR restores those plots using TA-libs EMA indicators.
=> Restore EMA plots

README.md, config.json.example, main.py, utils.py
Added parameter `stoploss` to config that will trigger instant sell of the trade if profit dips below a given stop-loss (for example -10%).
=> Add a stop-loss feature

README.md, config.json.example, main.py, misc.py, test/test_main.py, test/test_telegram.py
`ask_last_balance` sets the bidding price. Value `0.0` will use `ask` price, `1.0` will
use the `last` price and values between those interpolate between ask and last price. Using `ask` price will guarantee quick success in bid, but bot will also end up paying more then would probably have been necessary.
=> Set balance for bid price between ask and last

test/test_backtesting.py
Disable debug level logging when running backtesting. The verbose debug logging doubles the time it takes to run a full backtesting.
=> Disable debug level logging when running backtesting

analyze.py
Trader crashes when an empty dataframe is retrieved. This handles the empty state safely
=> dataframe empty check

rpc/telegram.py
Currently the Telegram API is used when disabled via config and raises a `telegram.error.InvalidToken` with the default token value of `token`.
=> Telegram: Fix being optional

analyze.py, config.json.example, test/test_backtesting.py
This PR introduces both a new buy algorithm, and adjusts the ROI settings.
Running a months worth of data for 10 coins in backtesting, the old algo with old ROI settings gave:
`Made 454 buys. Average profit -0.76%. Total profit was -3.428. Average duration 1349.6 mins.`
With the new buy algorithm we get:
`Made 839 buys. Average profit 0.51%. Total profit was 4.300. Average duration 599.0 mins.`
When we adjust the ROI settings with the old algorithm, we got:
`Made 468 buys. Average profit 0.78%. Total profit was 3.633. Average duration 361.6 mins.`
and with both the new algorithm and new ROI settings, we get:
`Made 847 buys. Average profit 1.41%. Total profit was 11.946. Average duration 161.7 mins.`
So in purely simulated environment, this PR changes our revenue from `-3x` losses to `11x` …
=> Better buy strategy and sell criteria

freqtrade/exchange.py, freqtrade/tests/test_main.py, freqtrade/tests/test_telegram.py
`get_markets()` was still unpatched in some tests, with this PR tests should no longer depend on successful api calls
=> patch missing calls

.coveragerc, .travis.yml, requirements.txt, setup.cfg, setup.py
Currently coverage included all test files. This PR changes from `coverage` to `pytest-cov` and configures coverage to omit tests files.
=> Fix coverage

.dockerignore, Dockerfile, README.md
I have reorganized the `Dockerfile` and added a `.dockerignore` file so that:
- Changes in the code that do not touch `requirements.txt` will not cause the build process to reinstall dependencies, only the last two layers are redone. Such builds only take a couple of seconds now.
- Building excludes unnecessary artifacts such as the ta-lib source code, build folders and tarball, as well as the .git tree of the app, so images are smaller.
- The image specifically omits `config.json`, promoting the user to bind mount it. This means that images are distributable, they can be checked in to a registry (as they don't contain credentials) and containers are more easily reconfigurable.
I documented the last part in the README file, also explaining to users how to bind mount the database file as …
=> More efficient and flexible Docker builds

freqtrade/rpc/telegram.py, requirements.txt, setup.py
Adds a `/help` command that lists all available commands.
Fixes #48 .
=> Help command to Telegram bot

freqtrade/tests/test_backtesting.py, freqtrade/tests/test_hyperopt.py
This PR does two things (sorry about mixing two changes to one commit):
- switches to a lot better objective function for HyperOpt
- includes the trading results in HyperOpt summary
The objective function works like this:
where `p` is total profit and `t` is trade count. And the darker the red, the more Hyperopt will prefer the result.
Summary of running HyperOpt after this PR looks like this now:
```
====================== HYPEROPT BACKTESTING REPORT ================================
Best parameters {'adx': 1, 'adx-value': 15.160153353316526, 'below_sma': 0, 'cci': 1, 'cci-value': -188.55517165634524, 'fastd': 0, 'mfi': 0, 'over_sar': 0, 'over_sma': 0, 'trigger': 0, 'uptrend_sma': 0}
Result: Made 1292 buys. Average profit 0.39%. Total profit was 4.977. Average duration 88.2 mins.
```
=> Better hyperopt objective

freqtrade/analyze.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_backtesting.py
This PR drops the time it takes to run backtesting by 49%.
This is done by:
- removing 16 million unnecessary string to datetime conversions
- using `.itertuples` instead of `.iterrows`
- using `.ix` instead of `.loc`
=> Performance improvements for backtesting

freqtrade/tests/test_backtesting.py, freqtrade/tests/test_hyperopt.py
Change where we mock to reduce the memory consumption drastically from
```
dict          51266     +1717
MagicProxy    34188     +1554
```
to
```
dict              15917      +303
MagicProxy         1776      +222
```
=> Reduce memory use in backtesting

.travis.yml, freqtrade/tests/test_hyperopt.py
We've had too many PR's that break the backtesting because the developer does not remember to run those tests. This PR adds them so that Travis will run two parallel builds, one with only unit tests and the other with backtesting and hyperopt. For hyperopt I dropped the number of eval rounds to 4 so it mainly checks that it works.
This is how it looked when we had a broken the backtesting but unit tests worked fine.
=> Parallel build in Travis

freqtrade/exchange/__init__.py, freqtrade/main.py, freqtrade/rpc/telegram.py, freqtrade/tests/test_telegram.py
This PR re-enables real values for `/performance` and `/profit` in combination with `dry_run: true`.
It also fixes float precision rendering issues for some telegram commands.
=> rework dry_run

freqtrade/tests/conftest.py, freqtrade/tests/test_backtesting.py, freqtrade/tests/test_hyperopt.py
Moved testdata file loading to a shared pytest fixture so so that they are loaded once and cached. Now hyperopt does not load the json's again and again for each eval.
=> Share pytest fixtures. Cache testfile loading.

freqtrade/analyze.py, freqtrade/main.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_backtesting.py, freqtrade/tests/test_hyperopt.py
Considerably reduce the memory consumption of hyperopt backtesting. Few other optimizations included also.
Here's a screenshot of memory consumption at around 2000 evaluations of hyperopt:
=> Memory fix hyperopt

freqtrade/analyze.py
With the new set of test data from #107 , this buy strategy change goes from:
```
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
TOTAL              732  0.44%         3.24785698 BTC           233.44
```
to
```
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
TOTAL             1277  0.82%         10.47936485 BTC          199.13
```
which doubles the avg profit and triples the total profit while making avg duration shorter.
With the old set of test data we go from:
`Made 872 buys. Average profit 0.35%. Total profit was 3.044. Average duration 96.8 mins.`
to
`Made 1264 buys. Average profit 0.40%. Total profit …
=> New buy strategy

.pylintrc, freqtrade/__init__.py, freqtrade/analyze.py, freqtrade/exchange/__init__.py, freqtrade/tests/__init__.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_backtesting.py, freqtrade/tests/test_exchange.py, freqtrade/tests/test_hyperopt.py, freqtrade/tests/test_main.py, freqtrade/tests/test_misc.py, freqtrade/tests/test_telegram.py
Fixes bunch of Pylint and Mypy warnings. Disables few rules in specific files where they make no sense. Improvement:
`Your code has been rated at 9.65/10 (previous run: 8.95/10, +0.70)`
=> Pylint cleanups

freqtrade/tests/test_backtesting.py, freqtrade/tests/test_hyperopt.py
Aligns numbers in Hyperopt print-out for easier reading:
```
103/6000: Made     71 buys. Average profit -0.29%. Total profit was  -0.204. Average duration 408.7 mins.
104/6000: Made     15 buys. Average profit -0.63%. Total profit was  -0.095. Average duration 417.0 mins.
105/6000: Made     15 buys. Average profit -0.94%. Total profit was  -0.141. Average duration 452.0 mins.
106/6000: Made   5437 buys. Average profit -0.27%. Total profit was -14.414. Average duration 369.1 mins.
107/6000: Made    321 buys. Average profit -0.24%. Total profit was  -0.769. Average duration 382.5 mins.
108/6000: Made      5 buys. Average profit  0.03%. Total profit was   0.002. Average duration 220.0 mins.
```
=> align numbers in hyperopt print out

freqtrade/main.py, freqtrade/tests/test_main.py
This PR should fix #132.
Turns out we don't need to apply fees ourselfs when opening a LIMIT_BUY order.
Fees are now only considered while calculating the profit.
=> fix LIMIT_BUY amount calculation

freqtrade/analyze.py, freqtrade/misc.py, freqtrade/tests/conftest.py, freqtrade/tests/test_backtesting.py, freqtrade/tests/test_misc.py
Implements a trade count lock to ensure the boundaries of `max_open_trades`. It also fixes a off-by-one issue during iteration.
NOTE: The logic is not perfect because some trades can overlap, to avoid this we need to sort all ticker data to process the data with the longest history first (not covered with this PR).
=> implement trade count lock for backtesting

freqtrade/misc.py, freqtrade/tests/test_backtesting.py, freqtrade/tests/test_misc.py
I may be wrong, but the way I understand the backtesting loop, we iterate through all buy signals regardless of their relative positions to sell signal, which might get us in the following situation:
```
if > is a buy signal, and < a sell signal:
(1)   (2) (3)  (4)  (5)
->-----<--->---->----<--
-----     ---------: Trades to keep
----: overlapping trades that make no sense
```
That is because when we sell, we don't change the loop that looks for buy signals, so when (3) buys, we sell at (5), but the next iteration will be (4), with again a sell signal at (5). The recent addition of `max_open_trades` doesn't help with this problem.
Instead, this PR ensures that when we iterate on (4), the `lock_pair_until` will let us know that we should ignore this signal.
I chose to ignore any buy signal …
=> In backtesting, ensure we don't buy the same pair again before selling

config.json.example, freqtrade/main.py, freqtrade/misc.py
Add support to configure experimental features, to quickly test new strategies and untested features.
This PR also adds the `use_sell_signal` which is set to `false` per default.
```
"experimental": {
"use_sell_signal": false
}
```
=> add experimental flag support

README.md, freqtrade/main.py, freqtrade/misc.py, freqtrade/tests/test_misc.py
This pull request is an answer to the issue #98 
It allows overriding the number of currencies used by `--dynamic-whitelist` (by default 20).
It does not change the current behavior of `--dynamic-whitelist`, it only extends it.
**By Default**  
Get the 20 currencies based on BaseVolume.  
```bash
freqtrade --dynamic-whitelist
```
**Customize the number of currencies to retrieve**  
Get the 30 currencies based on BaseVolume.  
```bash
freqtrade --dynamic-whitelist 30
```
=> Allow to change the number of currencies used by dynamic-whitelist

README.md, freqtrade/main.py, freqtrade/misc.py, freqtrade/persistence.py
Add a command line param `--dry-run-db ` that will use `tradesv3.dry_run.sqlite` instead of memory.
1. Works only if dry run is enabled.
2. Is ignored if dry run is disabled.
3. Create `tradesv3.dry_run.sqlite` if does not exist
```
--dry-run-db          Force dry run to use a local DB
"tradesv3.dry_run.sqlite" instead of memory DB. Work
only if dry_run is enabled.
```
=> Add param for Dry run to use a DB file instead of memory

freqtrade/rpc/telegram.py, freqtrade/tests/test_rpc_telegram.py
The PR is to improve the `/daily`command on Telegram.
Long story short...
Since the `/daily` command was pushed we saw few UX issues: 
* Command keyboard is not readible anymore, words are truncated
* The result format from `/daily` is not readible
* There is no default number on `/daily`, clicking on it send us to an error message, not a great UX
=> Improve  /daily command

freqtrade/rpc/telegram.py, freqtrade/tests/test_rpc_telegram.py
The command `/profit` doesn't calculate the ROI on closed trade only, but on all trades. This is confusing especially when the `/help`says `/profit: Lists cumulative profit from all finished trades`.
The picture below shows the current behavior when I call 3 times in a row `/profit`.
The ROI change because it compares close + open with the current market.
This PR solves this issue, by showing the ROI for closed trades only + the global ROI (Open + Closed)
=> Improve telegram /profit command

.gitignore, README.md, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/test_misc.py, freqtrade/tests/test_optimize_backtesting.py
This PR targets two pain points with Backtesting:
1. How to easily backtest the coin the user has set in his config file
2. How to easily update the testdata with up-to-date data from Bittrex.
This PR change from where Backtesting retrieves the pairs to use.  Instead of changing a static list in `optimize/__init__.py`, backtesting will simply use the pairs from the config file. Users will not have to update any code to test different scenarios.
The goal is to backtest our strategy against the pairs we will use later in production mode.
**Example:** 
**As a user, I can test my strategy only on for coins I have in my config file.**
If the user has in his config file 'NEO', 'BAT', 'MYST', 'RCN', Backtesting will directly retrieve and store the information from Bittrex to testdata/ folder. …
=> Add backtesting param --refresh-pairs-cached to update testdata files

freqtrade/persistence.py, freqtrade/rpc/telegram.py, freqtrade/tests/test_rpc_telegram.py
The goal of the PR is to handle trades with open order correctly.
**Scenario:** Bot decides to create a trade for `BTC_QTUM` and places a `LIMIT_BUY` order. `BTC_QTUM` soars and the order will no longer be fulfilled. Issuing `/forcesell` just raises `INSUFFICIENT_FUNDS` and doesn't the attached order.
should fix #102
How it will be handled with this PR:
* If there is an open LIMIT_BUY order attached: cancel the order.
(It is possible that some amount of the order got filled already, as stated in the TODO, but I would like to tackle this in another PR).
* IF there is an open LIMIT_SELL order attached: do nothing.
*EDIT:* I've also fixed some indentation and formatting issues in `rpc/telegram.py`
=> /forcesell: handle trades with open orders

.travis.yml, README.md, freqtrade/main.py, freqtrade/misc.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/persistence.py, freqtrade/rpc/telegram.py, freqtrade/tests/test_main.py, freqtrade/tests/test_misc.py, freqtrade/tests/test_optimize_backtesting.py, freqtrade/tests/test_rpc_telegram.py, setup.cfg
This PR enforces PEP8 conform code for each CI build to succeed.
I've also fixed all open PEP8 warnings within this PR.
The configuration for `flake8` is specified in `setup.cfg`:
```
[flake8]
#ignore =
max-line-length = 100
max-complexity = 12
```
I would like to keep the `max-line-length = 100`, because 80 is too restrictive on modern screens.
We should lower the `max-complexity` though (default is 10). I had to raise it for now, because `hyeropt.optimizer` and `main()` need to be refactored for this.
Should be merged after #192
=> CI: enforce PEP8 conform code

.gitignore, freqtrade/optimize/__init__.py, freqtrade/optimize/hyperopt.py, freqtrade/optimize/hyperopt_conf.py, freqtrade/tests/test_optimize_hyperopt_config.py
This PR fixes the regression of Hyperopt that does not work anymore when MongoDB is used.
This solution returns to the previous version of Hyperopt logic, where a static pairs list was set in the code (previously `freqtrade/optimize/__init__.py`).
Returned to a static list of pairs (but not anymore in `__init__`. Instead of having to update `freqtrade/optimize/__init__.py` and `freqtrade/optimize/hyperopt.py` to setup HyperOpt as we did previously, I have decided to move the hyperopt configuration into `freqtrade/optimize/hyperopt_conf.py`. This file is untracked, users can modify without risking to push it on git.
I was not able when HyperOpt uses MongoDB to dynamically pass the params from the config file.
Because the path to the config file can change with the param `-c`, I cannot only …
=> Fix hyperopt when using MongoDB

freqtrade/exchange/bittrex.py, freqtrade/main.py, freqtrade/optimize/backtesting.py, freqtrade/persistence.py, freqtrade/rpc/telegram.py, freqtrade/tests/conftest.py, freqtrade/tests/test_main.py, freqtrade/tests/test_persistence.py, freqtrade/tests/test_rpc_telegram.py
This PR fixes the issues #176 and #141 
Long story short, with this PR we change how the fee calculation is made.  
**Before:** The bot applied 2x0.25% on the closing rate, that is not how Bittrex applies fees. It means fee on the table column `close_profit`, are currently wrong.
**Now:**  By merging this PR, we apply the exact Bittrex fee calculation. 0.25% of the open rate then, 0.25% of the close rate. New closed trade will have the right `close_profit` column
* Change the Open and close trade mock to follow a real Bittrex transaction (See scenario below)
* Rename `Trade::calc_profit` to `Trade::calc_profit_percent`
* Refactor `Trade::calc_profit`
* Add fee calculation method breakdown: `Trade::calc_open_trade_price`, `Trade::calc_close_trade_price` and `Trade::calc_open_trade_price` …
=> Fix the fee calculation

freqtrade/optimize/hyperopt.py
- Consider eval with zero trades made a failure. This way I was able to remove all the `nan` filtering etc.
- Log result string only when eval round is better than any before on this run, otherwise prints a dot.
- Make log results go to a new line so they align and are easy to read.
- Shorten and remove noise from logged lines from hyperopt.
After changes the logging normally looks like this:
```
.................
5803/10000:    160 trades. Avg profit  0.45%. Total profit  0.00682250 BTC. Avg duration  43.6 mins.
.....................................................................................
5889/10000:    178 trades. Avg profit  0.41%. Total profit  0.00682182 BTC. Avg duration  43.6 mins.
..................................
```
=> Logging improvements to Hyperopt

freqtrade/exchange/bittrex.py, freqtrade/tests/test_exchange_bittrex.py
This PR catches `MIN_TRADE_REQUIREMENT_NOT_MET` as non fatal exception.
The root cause will be fixed in another PR.
Bittrex has a minimum trade value of  100,000 Satoshis [(src)](https://support.bittrex.com/hc/en-us/articles/115003004171-What-are-my-trade-limits-), since our fee calculation is now more precise it could happen that we try to create an invalid LIMIT_BUY order. This happens especially with coins that are only worth some satoshis. @glonlas My assumption is that this happens because of an precision rounding error:
```
Status: Got OperationalException:
File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 73, in _process
state_changed = create_trade(float(_CONF['stake_amount']))
File …
```
=> catch MIN_TRADE_REQUIREMENT_NOT_MET as non-critical exception

freqtrade/persistence.py, freqtrade/tests/test_main.py, freqtrade/tests/test_persistence.py
Just for the fun, more unit tests more coverage \o/
=> Add more unit tests

freqtrade/optimize/__init__.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_main.py
Refactor Optimize unit tests and add more tests.
**Changelog:**
* Move unit tests for `optimize/__init__.py` that was in `test_optimize_backtesting.py` into  `test_optimize.py`
* Add more tests for `optimize/__init__.py`, want to cover [This part](https://coveralls.io/builds/14822772/source?filename=freqtrade%2Foptimize%2F__init__.py#L66), [This part](https://coveralls.io/builds/14822772/source?filename=freqtrade%2Foptimize%2F__init__.py#L30)
* Fix logging on [download_backtesting_testdata](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/__init__.py#L103-L104)
=> Refactor Optimize tests, and add more unit tests

freqtrade/main.py, freqtrade/tests/test_main.py
Change the logic, so that a sell-signal is unconditionally executed.
See issue https://github.com/gcarq/freqtrade/issues/166
=> execute sell if get_signal OR ROI reached

freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_acl_pair.py
There was a bug in my previous PR, which raised the testing time from 16s to 2m.
B.T.W do you know why following wont work? First line uses a num variable holding a positive value.
And by expressing [-num:]  we want to trim an array or list so the last num items are kept.
It wont work and I get the full list (thats where the bug came from).
The fix is just to put a static number.
+        # new[pair] = pair_data[-num:]
+        new[pair] = pair_data[-100:]
=> Tests dec29

README.md, freqtrade/main.py, freqtrade/misc.py, freqtrade/tests/test_main.py
Fix for issue #248 
When `telegram._forcesell()`is executed it call `main.execute_sell()` outside of the main context. `main.py` populate the _CONF. However; when `_forcesell()` called `main.execute_sell()` _CONF is empty `{}` and the function cannot find what crypto-currency and fiat currency must be used.
This is not a beautiful workaround, I am not proud of it, but a redesigning of main.py and telegram.py will be necessary for a better integration. Any better solution is welcome.
=> Fix issue #248: missing configuration when executing /forcesell

config.json.example
Very simple PR. Add the new  `pair_blacklist` param in the `config.json.example`.
Otherwise, it will become a hidden feature.
=> Add pair_blacklist in config.json.example

freqtrade/main.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_main.py
This PR fix issue #273 and a request made on Slack to change profit to loss when profit is in fact negative
=> Removing tilde and change profit to loss when negative profit is made

CONTRIBUTING.md
Small documentation fix - As per pytest documentation at https://docs.pytest.org/en/latest/usage.html (Run tests by node ids)
=> Fixed pytest typo

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
`tabulate` has nice aligning of numbers but we were not using them because the columns contained `%` and `BTC`. I moved those to column headers. `tabulate` also has support for formatting so I could clean up the code a little.
Typical result now looks like:
```
====================== BACKTESTING REPORT ================================
pair         buy count    avg profit %    total profit BTC    avg duration
---------  -----------  --------------  ------------------  --------------
BTC_NAV            139            1.45          0.00601754            45.2
BTC_DGB            530           -0.09         -0.00154370            56.2
BTC_LSK            220           -0.25         -0.00164937            38.5
BTC_TRIG           157            1.12          0.00523099            44.3
BTC_XMR …
```
=> Improve backtesting result formatting

config.json.example, freqtrade/main.py, freqtrade/misc.py, freqtrade/tests/test_main.py
Have you been upset with the bot when your selling strategy sells a trade with a big loss (e.g -29%)?
Did you wonder if you could force the bot to retain a losing trade until it goes up later (days, weeks)?
When you activate the experimental feature `use_sell_signal` it overrides your `stoploss` and `minimal_roi`. Means the bot can with a loss even if you have setup it to only sell with profit.
In the following example, my configuration is
```json
{
"max_open_trades": 10,
"stake_currency": "BTC",
"stake_amount": 0.002,
"fiat_display_currency": "EUR",
"dry_run": true,
"minimal_roi": {
"30":  0.01,
"20":  0.02,
"0":  0.04
},
"stoploss": -1.00,
...
"experimental": {
"use_sell_signal": true
},
...
}
```
We see the `stoploss` is enable only if the bot loses -100% of the trade, and the …
=> Add experimental feature to sell only if we make a profit

freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc_telegram.py
this PR aim is to add the number of trades of each pair, a nicer evolution could be to have both the number of trades with a profit and thoose with a loss.
=> Add trades count foreach pair in performance command

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
This PR makes two improvements to backtesting speed:
- Faster date range printing
- Less data passing in the core loop
First is 136x faster than the original, on my laptop it reduces roughly 7 seconds off from backtest run.
Second picks just the columns we need from the dataframe before converting them to tuples. This makes the tuples faster to create and reduces garbage collection too.
The whole backtesting run on my laptop went from:
`python freqtrade/main.py backtesting  76.48s user 0.48s system 98% cpu 1:17.90 total`
to
`python freqtrade/main.py backtesting  51.60s user 0.91s system 98% cpu 53.067 total`
Total time was reduced by 32%.
=> Backtesting speed optimizations

README.md, config.json.example, docs/configuration.md, freqtrade/main.py, freqtrade/misc.py, freqtrade/tests/conftest.py, freqtrade/tests/test_main.py
For issues #150 and #229.
Added the ability to cancel any orders that exceed the parameter `opentradetimeout`.
Works for incomplete buy and sell orders
Works for partially completed buy orders (sets the stake_amount to what was fulfilled at the time)
No handling for partially complete sell orders - not sure how to handle these. Suggestions welcome :)
=> Added order timeout handling

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
This PR aims at taking into account various parameters from the config file : 
- use_sell_signal (which was by default always activated)
- sell_profit_only
- stoploss
- add a profit/loss counter
- adding the sell_signal in backtest function
- adding sell_profit_only and stoploss in backtest function
=> Add stoploss, sell_only_profit and use_sell_signal conf parameters to backtest function

freqtrade/optimize/backtesting.py
Very simple PR to add named argument on `backtest()` call in `backtesting.py`
- Use named argument on `backtest()`
The PR #297 has added more params to `backtest()`
I just use named parameter to ensure we do not mixed the order parameters.
Before 
```python
results = backtest(
config['stake_amount'], preprocessed, max_open_trades, args.realistic_simulation,
config.get('experimental', {}).get('sell_profit_only', False), config.get('stoploss'),
config.get('experimental', {}).get('use_sell_signal', False)
)
```
After
```python
results = backtest(
stake_amount=config['stake_amount'],
processed=preprocessed,
max_open_trades=max_open_trades,
realistic=args.realistic_simulation,
sell_profit_only=config.get('experimental', {}).get('sell_profit_only', False), …
```
=> Use named argument for backtest()

freqtrade/main.py, freqtrade/tests/conftest.py, freqtrade/tests/test_main.py
In detecting unfilled order timeouts, the order time from the exchange is now used. Also a bit of re-factoring. Had to re-write some unit tests as a result.
Solve the issue: Comments in pull requrest #295 by @ermakus. Using a seperate pull request to avoid any git-merging issues. 
- In detecting unfilled order timeouts, the order open time from the exchange is used.
=> Unfilled order timeouts - now using timestamps from exchange

freqtrade/optimize/backtesting.py
Since backtesting has now 2 more columns `profit` and `loss`, the backtesting header is not aligned anymore. 
- Update the backtesting result header (Because UI matter :) )
A very cool backtesting result header with equal '=' from both sides.
**Before :(**
```
2018-01-04 23:09:37,811 - freqtrade.optimize.backtesting - INFO -
====================== BACKTESTING REPORT ================================
pair         buy count    avg profit %    total profit BTC    avg duration    profit    loss
---------  -----------  --------------  ------------------  --------------  --------  ------
BTC_ADA              6            2.56          0.00030613          2497.5         6       0
BTC_NEO              8            2.52          0.00039928          2564.4         8       0 …
```
=> Fix Backtesting header alignment

freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py
The first commit lifts out the file-load part from optimize.load_data().
The file-load part is put into load_tickerdata_file() function.
By doing so we enable the possibility to test targets that uses load_data().
In where we mock load_data(), replacing it, but still want to use the file-load part in our testcase.
An example of this is found in the next commit.
One small kludge introduced by this commit is in the logic where we do a retry of  load_tickerdata_file() in the function load_data(). The logic is correct, but perhaps not so beautiful stated.
A simple test case is also added, even though it doesn't increase the coverage it is warranted by the one-test-per-function policy.
The second commit is the objective of this commit. The commented-out testcase in tests_backtesting.py is now …
=> tests cover more backtesting

freqtrade/main.py, freqtrade/tests/test_main.py
Change the experimental `sell_profit_only` to apply only when sell signal would trigger the sell. Currently it also overrides the ROI table which shouldn't happen.
=> Fix profit experimental

freqtrade/main.py, freqtrade/misc.py, freqtrade/tests/test_main.py, freqtrade/tests/test_misc.py, scripts/plot_dataframe.py
Grasping for two improvements with this patchset.
First three patches introduces a parse_args_common() function. It will take your argument list and return an parsing object. This object contains information on how to handle common parsing options.
It is then (as usual) further extended with parse options specific to the program being runned.
The third patch shows usage of this, where we extend the script/plot_dataframe.py with a --pair argument.
The fourth patch is trying to decouple parse_args() by making it non-continuation, and thus reducing its functionallity scope to parsing only.
The only improvement with this is that  it makes the call stack look nicer because the parse_args() is removed. It also somewhat prepares for modules handling, where handling of those would take place in …
=> Parsing: common options, reduce function scope

docs/hyperopt.md, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
This PR improve how Hyperopt display best parameters results.
We saw on Slack and also on Github, users do not understand clearly the result provided by hyperopt. With this PR why try to make it clearer.
Solve the issue: #162; #304, #309
- Improve the display of best parameter. Instead of displaying Raw Json, we display the name of the guards and triggers.
**Before**
```python
Best parameters:
{
"adx": 1,
"adx-value": 15.0,
"fastd": 1,
"fastd-value": 40.0,
"green_candle": 1,
"mfi": 0,
"over_sar": 0,
"rsi": 1,
"rsi-value": 37.0,
"trigger": 0,
"uptrend_long_ema": 1,
"uptrend_short_ema": 0,
"uptrend_sma": 0
}
```
**After**
```python
Best parameters:
{
"adx": {
"enabled": false
},
"fastd": {
"enabled": false
},
"green_candle": {
"enabled": false
},
"mfi": {
"enabled": false
},
"over_sar": { …
```
=> Make readable hyperopt best parameters result

freqtrade/fiat_convert.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_fiat_convert.py
This PR fix the issue caused by Pymarketcap when you use the bot without network connections (Hyperopt, Backtesting).
Solve the issue: #322
- Solve the exception raised when the bot is used without network connection
=> Fix _coinmarketcap that fails backtesting and Hyperopt when no network

docs/backtesting.md, docs/bot-usage.md, docs/hyperopt.md, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_dataframe.py
This argument enables usage of different backtesting directories.
Useful if one wants compare backtesting performance over time.
=> --datadir <path> argument

docs/backtesting.md, docs/bot-usage.md, docs/hyperopt.md, freqtrade/exchange/__init__.py, freqtrade/exchange/bittrex.py, freqtrade/exchange/interface.py, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/rpc/telegram.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_dataframe.py, requirements.txt
For each trades opened, the telegram bot was fetching the last bid price making a request towards bittrex.com. This PR allow the use of cached values retrieved in the _process function and fix issue #278. 
By opportunity all calls to get the bid prices where replaced in the Bot.
=> The /status table command was getting slower when we had multiple trades opened

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
This PR aims to fix the issue with Hyperopt that throw an error when no parameter was found. It happens when we execute Hyperopt with too few epochs. 
Solve the issue: #337 
- Try/catch the `fmin()`, and return a message to the user
All issue details in the issue #337.
**Error message returned to the user**
```
Using config: config.json ...
Validating configuration ...
Best parameters:
{}
Best Result:
Sorry, Hyperopt was not able to find good parameters. Please try with more epochs (param: -e).
```
=> Fix hypeopt issue when no result found

.travis.yml, freqtrade/analyze.py, freqtrade/tests/test_fiat_convert.py
We were stuck in an old version of `flake8`. This PR makes the build always use the latest.
Due to pip dependency caching we use in Travis, we would always get the same version of flake8 and coveralls. Using the `--upgrade` switch for pip, we force it to check for newer versions available.
=> Upgrade flake8

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
Add `stoploss` to the hyper optimized parameters.
- Define search space for `stoploss` in Hyperopt
- Adjust objective function to take in to account the average trade duration
=> Add stoploss to the hyperopt parameters

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
Hyperopt search space for stoploss was using value range that was 100x the intended.
=> Fix hyperopt stoploss

freqtrade/main.py
Finite default timeout for requests library 
Solve the issue: #127
Monkey patch requests to prevent bot stuck forever in connect(..) syscall
=> Set requests default timeout

freqtrade/exchange/bittrex.py, freqtrade/main.py
Set timeout only for bittrex API to avoid side effects
Solve the issue: #127 
Correct way to set timeout, use python-bittrex hook instead of monkey-patching
Based on this comment https://github.com/gcarq/freqtrade/issues/127#issuecomment-356599037
=> Set timeout for bittrex only

freqtrade/exchange/bittrex.py, freqtrade/tests/exchange/test_exchange_bittrex.py
Refactoring the ticker analysis to better handle tickers with null values
Solve the issue: #341
- fix the logic for analyzing the ticker
- add unit test covering this bug and one to check for an empty ticker
=> Fixing the ticker analysis with null values

freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc_telegram.py
Show estimated BTC and fiat amount by /balance command (like in bittrex wallets section)
Example:
*Currency*: BTC
*Available*: 12.0
*Balance*: 10.0
*Pending*: 0.0
*Est. BTC*:  10.00000000
*Estimated Value*:
*BTC*:  10.00000000
*USD*:  150000.00
=> Show estimated BTC and fiat balance

freqtrade/main.py, freqtrade/tests/test_main.py
Added RPC messaging when unfilled order is timed out. Also fixed bug where order may be filled before check_handle_timedout runs.
Solve the issue: #385 
- Added RPC messaging when  unfilled orders time out
- Fixed bug where a check_handle_timedout attempts to run on filled orders
=> Order timeouts - added exception catching and rpc messaging

docs/configuration.md, freqtrade/analyze.py, freqtrade/main.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_main.py
The aim of this **PR** is to handle properly **SELL/BUY** signals firing at the same time
This **PR** should fix issue #316 
- Trade is not created if **BUY** triggers and **SELL** triggers at the same time
- Trade is not closed if **SELL** triggers and **BUY** triggers at the same time
- Trade is not closed if ROI reached and **BUY** triggers at the same time
- Sell profit only is no longer reserved  for the **"use_sell_signal"**  flag
=> Fix signal overlaps

docs/backtesting.md, docs/hyperopt.md, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_misc.py
Add an --timeperiod argument to hyperopt and backtesting.
The code was already there in testing, so just moved it in.
Example:
freqtrade backtesting --timeperiod -200
freqtrade hyperopt --timeperiod -200
Above examples will use the last 200 timeframes of tickerdata, instead of using the whole timespan.
This could be useful to quickly find out if an algorithm is feasible before expanding the testset.
=> Timeperiod

README.md, docs/backtesting.md
PR #357 and #328 has introduced markdown render mistakes in the `backtesting.md`
This PR fix the formatting of `backtesting.md`
- Fix formatting issue on `backtesting.md`
=> Fix markdown mistakes in backtesting doc

freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc_telegram.py
Very simple PR that add the number of trades in /daily report.
Solve the issue: #408 
- Add number of trades made during the day when using `/daily` command
=> Add number of trades in /daily command

freqtrade/exchange/bittrex.py, freqtrade/tests/exchange/test_exchange_bittrex.py
This PR fixes handling of data fetched from Bittrex sever with bad content in the ticker
Solve the issue: #406 
- analyze the ticker and throw a ContentDecodingError is one of Bid, Ask, Last is incoherent
- add a unit test
=> fixing handling of data fetched from Bittrex server with bad content in the ticker

freqtrade/main.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_main.py
Fix the issue since interval_ticker was introduced. 
Solve the issue: #413
- add the missing parameter interval to `get_signal()`
- update the unittests
=> Fix the issue get_signal() missing 1 required positional argument: Interval

freqtrade/optimize/backtesting.py
In backtesting.py::start() `optimize.load_data()` is called twice. There is a wrong refactoring here. One call is enough.
- Remove duplicate `optimize.load_data()` call in `backtesting.py::start()`
Clean and Optimize backtesting.py
The initial code was:
```python
logger.info('Using local backtesting data (using whitelist in given config) ...')
data = optimize.load_data(args.datadir, pairs=pairs, ticker_interval=ticker_interval,
refresh_pairs=args.refresh_pairs)
logger.info('Using stake_currency: %s ...', config['stake_currency'])
logger.info('Using stake_amount: %s ...', config['stake_amount'])
timerange = misc.parse_timerange(args.timerange)
data = optimize.load_data(args.datadir, pairs=pairs, ticker_interval=args.ticker_interval,
refresh_pairs=args.refresh_pairs,
timerange=timerange) …
```
=> Remove optimize.load_data() that is called twice

freqtrade/fiat_convert.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_fiat_convert.py, freqtrade/tests/test_main.py
Speed up unit test from 60s to 6s by Change `CryptoToFiatConverter()` to a Singleton. 
The issue is `CryptoToFiatConverter()` call `Pymarketcap()` lib at the `__init__`. When `Pymarketcap()` get instanced, it calls some other services. It results in a latency of 2 sec.
By changing `CryptoToFiatConverter()` to a Singleton, we avoid to init `Pymarketcap()` every time.
Solve the issue: #420
- Change `CryptoToFiatConverter()` to a Singleton. The bot will instance `Pymarketcap()` only once.
- Accelerate Unit test
- Accelerate every time the bot calls `CryptoToFiatConverter()`
Faster unit tests, Faster bot.
Below the new performance of the tests.
|    |   Test  | Original duration | New duration |
|----|---------|-------------------|--------------|
| [x] | …
=> Convert CryptoToFiatConverter into a Singleton

freqtrade/optimize/__init__.py
Remove the filename conversion `filename.replace('USDT_BTC', 'BTC_FAKEBULL')`. This is useless, and add trouble when users are backtesting with USDT
Solve the issue: #397 
- Remove the filename conversion `filename.replace('USDT_BTC', 'BTC_FAKEBULL')` when backtesting is downloading USDT_BTC pair.
=> Remove useless USDT_BTC filename conversion

freqtrade/persistence.py, freqtrade/tests/test_persistence.py
Solve the issue: #385
This issue happens when we start a dry_run with a DB that contains `open_order_id`.
This PR clean up the dry run DB from `open_order_id` generated by a previous dry_run session (Change the value to NULL).
It does not clean `open_order_id` from a prod session.
- Remove previous dry_run `open_order_id`
=> Fix dry_run db issue when open_order_id already exist

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
First of multiple Hyperopting PR:s coming. This PR makes Hyperopt optimize to find ROI table that maximizes profits.
Tries to find four step ROI table that would maximize protfit. It does this by using 6 new hyperopt variables `roi_t1`, `roi_t2`, `roi_t3`, `roi_p1`, `roi_p2`, `roi_p3` that map to the ROI table like this:
By adjusting the uniform space and step values of these variables you can set the limits for how far and wide will the suitable times and profit percentages be searched by Hyperopt.
=> ROI table Hyperopting

freqtrade/tests/test_persistence.py
The `test_clean_dry_run_db` test can fail because it is reusing existing Trade session.
- Fix the faulty test `test_clean_dry_run_db`
```
>       assert len(Trade.query.filter(Trade.open_order_id.isnot(None)).all()) == 3
E       assert 10 == 3
...
freqtrade\tests\test_persistence.py:354: AssertionError
```
=> Fix test_clean_dry_run_db failing test

freqtrade/optimize/hyperopt.py
Lower the precision of most search space variables for hyperopt.
Makes hyperopt step size 5.0 instead of 1.0 for variables like RSI, ADX, MFI etc.
Makes stoploss search step 2% at time.
These changes should:
1. Lower the size of search space to 1/10000 of what it was
2. Reduce the unnecessary overfitting to a specific dataset
=> Lower precision for most search space variables

docs/plotting.md, requirements.txt, scripts/plot_dataframe.py, scripts/plot_profit.py
Convert both plotting scripts to use Plotly. Results in HTML pages with WebGL optimized graphs.
No need for DISPLAY backends for different environments, instead plots are in a html file that is easy to save, transfer or serve from a container.
Users will need to run `pip install plotly` to get the new plotting library. It is by default commented out in the `requirements.txt`.
=> Replace matplotlib with Plotly

freqtrade/analyze.py
The PR fixes the bad detection of old dataframe mechanism when using tickers > 5 minutes
- A `dataframe` is considered old when it has not been updated after ticker_interval + 5 minutes
=> Fixing wrong 'old dataframe detection mechanism' for long tickers

docs/installation.md
Add `pip3.6 install --upgrade pip` in the linux installation procedure.
I saw the virtual env can still use an old version of pip and fails the installation of modules.
```bash
python3.6 -m venv .env
source .env/bin/activate
pip3.6 install --upgrade pip
pip3.6 install -r requirements.txt
pip3.6 install -e .
```
- Update the install on linux/macOS documentation
=> Update doc: add --upgrade pip

README.md, config_full.json.example, docs/installation.md, setup.sh
This PR adds a script to Install/Update/Reset the bot on MacOS and Linux. It was created to help users to install the bot.
The script `setup.sh` can
- Install the bot from scratch
- Update dependencies on an existing bot
- Reset a branch and virtual env
- Configure config.json
```
$ ./setup.sh
usage:
-i,--install    Install freqtrade from scratch
-u,--update     Command git pull to update.
-r,--reset      Hard reset your develop/master branch.
-c,--config     Easy config generator (Will override your existing file).
-p,--plot       Install dependencies for Plotting scripts.
```
=> Add setup.sh script to install and update the bot

docs/plotting.md, docs/pre-requisite.md
Adding the fact that conversation must be started before running freqtrade
Solve the issue: none
- Add new bullet point 1.6 for detail
=> Adding 1.6 comment into telegram pre-requirements

freqtrade/optimize/backtesting.py
Since PR #469 backtesting is showing bad results.
The sell event was mis-fired due to mis-calculation of the buy event which was always on (preventing the sell event to be executed)
- fixing the buy event calculation
*Before*
```
pair       buy count    avg profit %    total profit BTC    avg duration    profit    loss
-------  -----------  --------------  ------------------  --------------  --------  ------
BTC_XVG           22            0.25          0.00005391           154.1        20       2
BTC_LTC           12            0.90          0.00010606           104.2        12       0
BTC_XRP           36            0.12          0.00004152           201.0        33       3
TOTAL             70            0.29          0.00020149           169.6        65       5
```
*After*
```
pair …
```
=> Fixing bug in backtesting preventing sell events to be executed

freqtrade/misc.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/test_main.py
Backtesting and Hyperopt had the same bug with `ticker_interval`. 
As you know we have 3 way to define the `ticker_interval` to use
1. inside the strategy
2. from the config.json (override the strategy)
3. from the cli param -i/--ticker-interval (override the configuration)
Until know only `-i/--ticker-interval` was taken into consideration. The param from `config.json` and `ticker_interval` from the strategy was ignored.
Solve the issue: #478
- Fix the `ticker_interval` behavior on backtesting and hyperopt
=> Fix Backtesting / Hyperopt ticker_interval download

docs/bot-optimization.md, docs/bot-usage.md, freqtrade/misc.py, freqtrade/strategy/strategy.py, freqtrade/tests/strategy/test_strategy.py
Remove the fallback behavior when a strategy is not found or cannot be loaded. Previously when a custom strategy cannot be loaded the bot fallback to the default_strategy.
- Remove fallback behavior when a strategy cannot be loaded
- Display an error message with the reason
```
2018-01-31 22:34:43,853 - freqtrade.strategy.strategy - INFO - Load strategy class: IncompleteStrategy (user_data.strategies.incomplete_strategy.py)
2018-01-31 22:34:43,853 - freqtrade.strategy.strategy - ERROR - Impossible to load Strategy 'user_data/strategies/incomplete_strategy.py'. This file does not exist or contains Python code errors
2018-01-31 22:34:43,854 - freqtrade.strategy.strategy - ERROR - The error is:
Can't instantiate abstract class IncompleteStrategy with abstract methods populate_buy_trend, …
```
=> Remove Strategy fallback to default strategy

setup.sh
Since #497 was merged, the config generator in `setup.sh` is broken. This PR fixes this issue.
- Change the Sed expression `your_instagram_*` for `your_telegram_*`
=> Fix config generation on setup.sh

freqtrade/misc.py
To avoid duplication and mistakes, switched to using variable substitution in help texts for argument parsing.
=> Use substitution in argparse help texts

freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py
Make backtesting again a lot faster (65% on  my laptop) by switching to use indexed dates.
- move from integer indexing to date indexing in ticker dataframes in backtesting
- calculate trade duration by real date comparison because index difference is not available anymore
Previously someone refactored our backtesting to use date comparisons instead of integer indexes. This was done carelessly without changing the indexing, result: 50% slower backtesting. This PR fixes that.
=> Date indexing for backtesting

freqtrade/main.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/strategy/strategy.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/strategy/test_strategy.py
This PR makes backtesting and hyperopt roughly **five times** faster than before.
Speed up is mainly accomplished by iterating over regular arrays instead dataframe's `.itertuples()` which for a regular three month backtesting data removes creation of roughly 1 billion tuples.
=> Make backtesting 5x faster

docs/hyperopt.md, freqtrade/misc.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
Letting Hyperopt optimize everything is a huuuuge search space. Often it might make more sense to start by just searching for initial buy algorithm. Or maybe you just want to optimize your stoploss or roi table for that awesome new buy strategy you have. Now you can!
Adds a commandline flag to hyperopt called `--spaces` that allows selecting what Hyperopt will optimize. Legal values are:
- `all`: optimize everything
- `buy`: just search for a new buy strategy
- `sell`: not supported yet
- `roi`: just optimize the minimal profit table for your strategy
- `stoploss`: search for the best stoploss value
- comma-separated list of any of the above values for example `--spaces roi,stoploss`
=> Allow selecting Hyperopt search space

freqtrade/indicator_helpers.py, freqtrade/strategy/default_strategy.py, freqtrade/tests/test_indicator_helpers.py
- Adds simple helpers `went_up` and `went_down` that are same as `df['x'] > df['x'].shift(1)` and `df['x'] < df['x'].shift(1)`.
- Adds generic Fisher's Inverse Transform that can be fed with any indicator that goes from 0 to 100, like RSI, MFI, CyberCycle. Also has built-in smoothing.
- Adds a very low-lag Ehler's Super Smoother. Here a chart with close price and super smoothed price:
=> Random indicator helpers

freqtrade/misc.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py
Few fixes and refactorings to Hyperopt and backtesting to make the results match between them:
- change realistic simulation to default to false and allow enabling it from both hyperopt and backtesting with `--realistic-simulation`
- combine CLI flags that are shared by both hyperopt and backtesting
- make CLI flags available to the optimizer in hyperopt
- use `--spaces` flag properly in hyperopt instead of hacky guessing from `params`
- fix that backtest ignored the given stoploss
After this PR, the call to backtest is quite different from Hyperopt than it is from backtesting.py, but these cleanups are necessary prework.
=> Cleaning up backtesting/hyperopt

Dockerfile
unit tests, and is your code PEP8 conformant? [More details](https://github.com/gcarq/freqtrade/blob/develop/CONTRIBUTING.md)
all tests Passing, no new tests required
Update dockerfile to python:3.6.4-slim-stretch
By using the "slim" version of the image, the final size of the image goes from 1.37GB down to 1.02GB while maintaining all functions.
also updated python to the lasest 3.6.4 version, as the minor hop from 3.6.2 to 3.6.4 will not be breaking.
- update python from 3.6.2 to 3.6.4 in Dockerfile
- Change to slim version to reduce size of final image
Smaller size of the docker image.
=> Update dockerfile to python:3.6.4-slim-stretch

README.md, docs/installation.md
unit tests, and is your code PEP8 conformant? [More details](https://github.com/gcarq/freqtrade/blob/develop/CONTRIBUTING.md)
Update documentation to bind /etc/localtime to Docker container to have correct local time
- Updates documentation to include -v /etc/localtime:/etc/localtime:ro on docker run commands
* changed documentation for Docker run
* tested on linux (arch and debian stretch)
* should be working on Mac (please refview if possible, i have no way of testing that)
* will not work on Windows - bot neither will the existing `docker run` commands
=> Update documentation for docker

freqtrade/tests/conftest.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_acl_pair.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_dataframe.py, freqtrade/tests/test_main.py, freqtrade/tests/test_persistence.py
Fix some tests for ccxt branch
Not all tests are working yet, but I hope it helps @shusso to complete work on the ccxt branch
Fixed tests necessary to support ccxt:
some datastructures have changed type, therefore a change in the test-structure was necessary as well. 
* freqtrade/tests/test_main.py
* freqtrade/tests/test_persistence.py
* freqtrade/tests/test_acl_pair.py
Partially fixed tests: 
* freqtrade/tests/rpc/test_rpc_telegram.py  (2 still failing, down from 8)
no file outside of tests/ folder has been touched.
Please note that Travis build is expected to fail as not all tests pass yet.
* Help test coverage in CCXT branch
=> Fix some tests for ccxt branch

docs/backtesting.md, docs/plotting.md
align documentation to use `python3 ./freqtrade/main.py`.
- documentation - calls adjusted
To create consistency within the document (all lines should use the same calling convention - previously,  `python3`, `python3.6` and sometimes `freqtrade` was used.
=> Align calling convention in backtesting and plotting docu

freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_dataframe.py
This fixes the test_dataframe when not run together with test_analyz
- initialize default strategy first
Running pytest over all files works.
running pytest with the following works as well (because the analyze-tests initialize Strategy correctly.
```
pytest freqtrade/tests/test_analyze.py freqtrade/tests/test_dataframe.py
```
When running pytest "standalone" on the dataframe test, the test fails, as Strategy is not properly initialized.
```
$ pytest freqtrade/tests/test_dataframe.py
.
.
.
def populate_indicators(self, dataframe: DataFrame) -> DataFrame:
"""
Populate indicators that will be used in the Buy and Sell strategy
:param dataframe: Raw data from the exchange and parsed by parse_ticker_dataframe()
:return: a Dataframe with all mandatory indicators for the strategies
"""
> …
```
=> Fix test_dataframe when ran standalone

freqtrade/analyze.py, freqtrade/freqtradebot.py, freqtrade/strategy/strategy.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
This PR simplify the usage of ticker_interval in `FraqtradeBot()` class. 
`Strategy()` class already define the right ticker_interval to use (1. Select the value in the strategy file, then 2. override it if set in config file or passed in cli arguments).
However, the bot is mostly using the ticker_interval set in the config file and ignore the ticker_interval recommended by the Strategy logic. This PR fixes this issue.
- Remove from FraqtradeBot() methods the ticker_interval passed in parameter
- Remove duplicate code
- Avoid using a wrong ticker interval
=> Use the ticker_interval defined by Strategy()

freqtrade/misc.py
Solves issue: #534
- allow `max_open_trades` to be 0
Modifies `CONF_SCHEMA` and sets 0 as the minimum required value of allows `max_open_trades`.
This allows to only sell existing open orders and not creating any new ones.
=> allow max_open_trades to be 0

bin/freqtrade
Fixes a `TypeError` when launching the bot via the bin wrapper.
```
$ freqtrade
File "freqtrade/.env/bin/freqtrade", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "freqtrade/bin/freqtrade", line 6, in <module>
main()
TypeError: main() missing 1 required positional argument: 'sysargv'
```
- adapt `bin/freqtrade` wrapper to call set_loggers() and pass required arguments to main().
=> adapt bin/freqtrade to pass required parameters

freqtrade/freqtradebot.py, freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
Rename `FreqtradeBot._state` to `FreqtradeBot.state` and drop unneeded methods `update_state()` and `get_state()`. These were required in the past for synchronization puroposes, but are no longer required since #537 .
- Make state a public property on `FreqtradeBot`
=> Make state a public property on FreqtradeBot

config.json.example, config_full.json.example, freqtrade/__init__.py, freqtrade/analyze.py, freqtrade/exchange/__init__.py, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/tests/conftest.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_acl_pair.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_persistence.py
this will fix a few tests in objectify.
Also, rolling back the change of the OHLVC format - this would complicate things a lot and make all saved dataframes worthless.
- changed all tests in root and rpc folders
- backtesting / dry mode on binance working
- revert OHLVC format so existing dataframes are not broken
CCXT work is not complete with this, but i hope it helps bring ccxt objectify forward.
Currently mainly interresting for @shusso 
Tests are expected to fail as not all tests are fixed yet.
=> objectify ccxt fix backtesting and some tests

freqtrade/optimize/backtesting.py
reverts regression introduced in c62356438a60ec40c7e724fa4f0e8dff898751f4.
* revert change in trade export format.
Tick-frame was exported on position 4 in the array - the fix in feature/objectify exports date - don't think  this change in behavior is intentional as the date is available in fields 2 and 3 already in a different format.
Looking at https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L195-L198
``` python
records.append((pair, trade_entry[1],
row.date.strftime('%s'),
row2.date.strftime('%s'),
row.date, trade_entry[3]))
```
we see `row.date` exported twice - once in second-format, once in date format.
This was not the case before c62356438a60ec40c7e724fa4f0e8dff898751f4.
Objectify fixed the resulting exception, but left the format to duplicate …
=> fix backtest --export format

config_full.json.example, docs/bot-optimization.md, docs/bot-usage.md, docs/configuration.md, freqtrade/analyze.py, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/main.py, freqtrade/strategy/interface.py, freqtrade/strategy/resolver.py, freqtrade/tests/strategy/test_strategy.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py
Further improvements to abstract `user_data` from core: Adds `--strategy-path` parameter to add a custom strategy path which gets checked first. Also this PR simplifies `StrategyResolver` (mostly dropping redundant code).
Relates to issue: #435
- Add `--strategy-path` parameter
- Simplify `StrategyResolver`
```
$ mkdir -p /tmp/strategy  # create temp directory
$ cp user_data/strategies/test_strategy.py /tmp/strategy  # copy existing strategy file
$ freqtrade --strategy TestStrategy --strategy-path /tmp/strategy  # execute freqtrade with custom strategy path
2018-03-27 16:43:50,637 - freqtrade.configuration - INFO - Log level set to INFO
2018-03-27 16:43:50,638 - freqtrade.configuration - INFO - Using max_open_trades: 10 ...
2018-03-27 16:43:50,638 - freqtrade.configuration - INFO - …
```
=> Add --strategy-path parameter and simplify StrategyResolver

freqtrade/analyze.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_analyze.py
Aggregate ticks in `parse_ticker_dataframe` and group them by date to remove duplicates.
This should bring backtesting results slightly closer to production performance (See #477).
Solve the issue: #590
- Aggregate duplicate ticks in `parse_ticker_dataframe` and group them by date
Below are the backtesting results from different branches (using `ticker_interval=5`),
the feature branch did one buy less (3064 != 3065) compared to `develop`, so there are even duplicates with a low `ticker_interval`:
```
==================================== BACKTESTING REPORT ====================================
pair       buy count    avg profit %    total profit BTC    avg duration    profit    loss
-------  -----------  --------------  ------------------  --------------  --------  ------
BTC_ETH …
```
=> Aggregate ticks in parse_ticker_dataframe

freqtrade/freqtradebot.py
Revert regression introduced in refactoring for objectify related to dynamic whitelist - which enables this by default without possibility to Disable dynamic whitelist.
- Disable dynamic whitelist if not specified in comand line
run freqtrade with a config with only one Asset in whitelist (without parameter --dynamic-whitelist) still uses dynamic-whitelist with a default of 20.
* Running freqtrade without `--dynamic-whitelist` disables dynamic whitelisting and only uses the assets specified in the configuration.
* Running freqtrade with `--dynamic-whitelist` defaults to 20 assets (as previously)
* Running freqtrade with `--dynamic-whitelist 5` runs with 5 assets (as before objectify).
=> Disable dynamic whitelist if not specified

freqtrade/misc.py, freqtrade/tests/test_misc.py, scripts/convert_backtestdata.py
Add conversion script for Ticker history from bittrex to ccxt format
- add conversion script
- add handling for gzip files in file_dump_json (could be useful in other places, when downloading longer history maybe)
Tests are expected to fail, as work on ccxt is ongoing.
=> Conversion script for Ticker history data

freqtrade/configuration.py, freqtrade/tests/test_configuration.py
Fix check_exchange_supported
* fixes new feature introduced in 052404ffbd36d9754d824af3211e3f9247997396, which caused an Exception as the class-object (self.config) is not yet loaded.
* Tests will not pass in this branch yet
* not sure if the function shouldn't be made private as it's only used from within the Class.
=> use local config-object for check_exchange (fixes Nonetype Attribute error when starting the bot)

.travis.yml, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/test_fiat_convert.py, freqtrade/tests/test_persistence.py
Allow test-execution to be randomized - Tests should be independent, without breaking if the order is different.
* Tests don't fail when run multiple times having `pytest-random-order` installed.
Before this PR, tests do fail at a random rate (depending on which tests run first).
Execution time is slightly higher (~6.4s vs. 5.7s from before) - however i think the benefit of beeing able to run tests in any order outweights the 0.7s delay.
I'm not familiar enough with TravisCI (and did not find anything obvious in google) to know if there is a setting to enable random execution, or if `pytest-random-order` should be in the requirements file so Travis randomizes tests.
=> Fix tests run in random order

freqtrade/freqtradebot.py
The bot doesn't write any log when there are only trades ready to be sold, so in my case I was monitoring the logs and I thought that the bot had stopped working.
- Write logs when trying to sell trades
=> Write logs when trying to sell opened trades

freqtrade/exchange/__init__.py
Pass `enableRateLimit: True` to ccxt constructor to avoid hitting exchange rate limits.
Fixes open TODO from #603, previous discussion: #585
- Let cctx handle rate limits internally
=> let ccxt handle rate limits internally

freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
Add mocks for `exchange.get_fee` because ccxt does a HTTP request for this.
Fixes the testsuite if no internet connection is available, reproducible at 1332ab397ff52ea75a31cd0c32d234bf47ad012d with:
```
sudo unshare -n pytest freqtrade
```
* Backtesting calls exchange.get_fee quite frequently within `_get_sell_trade_entry`. We should call get_fee() once in `Backtesting.__init__` and reuse this value.
=> add mocks for exchange.get_fee

Dockerfile
Update docker image `python-3.6.4-slim-stretch` to `python-3.6.5-slim-stretch`.
Requires a full rebuild of the image - but updates to the latest and greatest version of python.
=> update Docker image to python-3.6.5-slim-stretch

freqtrade/tests/optimize/test_hyperopt.py
fix a test-fluke which appeared in hyperopt:
reproduce running `pytest  --random-order-seed=194824`
Will solve the test-failure which appeared in : #658
=> Fix testfluke in hyperopt

freqtrade/fiat_convert.py, freqtrade/tests/conftest.py, freqtrade/tests/test_fiat_convert.py, freqtrade/tests/test_freqtradebot.py
This will reenable convert to fiat (which was broken by a combination of updating coinmarketcap to 5.xx and coinmarketcap.com changing the api.
Solve the issue: #661 
- dynamically load available coins
- Adapt to new format
- slight refactoring of some tests to support testing the new functionality
For details on the bug refer to  issue #661 
I know we should not test external libraries - however the change to the API was intentional (forced by coinmarketcap.com - but that doesn't really matter), and the test-suite did not catch it correctly (mostly because all external calls are mocked).
=> Fix fiat convert

freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
Fixed `/balance` bot functionality. The functionality was broken after moving to CCXT library.
Also I've redesigned a balance message a little bit. Here is the example of the message:
Solve the issue: `/balance` crash
- fixed `/balance` crash
- balance message redesign
=> Fixed bot crash while requesting the current balance

docs/plotting.md, freqtrade/arguments.py, scripts/plot_dataframe.py
Make plot_dataframe.py able to show buy and sell trades stored in database.
- Introduce '--db-url' argument
- Implement feature in plot_dataframe.py
- Update plotting.md
=> Make plot_dataframe able to show trades stored in database.

docs/installation.md
New versions of Docker will not start in OSX using the cmd in these instructions as /etc/localtime cannot be mounted. 
The change provides an alternate command that does work. 
`docker run --rm -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` -v `pwd`/config.json:/freqtrade/config.json -it freqtrade`
More info is in this thread: 
https://github.com/docker/for-mac/issues/2396
unit tests, and is your code PEP8 conformant? [More details](https://github.com/gcarq/freqtrade/blob/develop/CONTRIBUTING.md)
Solve the issue: #___Start Docketr instructions change. 
No code …
=> OSX docker start cmd updated

freqtrade/fiat_convert.py, freqtrade/tests/test_fiat_convert.py
Catch network exceptions when initializing coinmarketcap (Fiat convert should never cause the bot to stop!!)
Solve the issue: #732
- Catch base-class of Requests exceptions (based on [this](http://docs.python-requests.org/en/master/_modules/requests/exceptions/)).
- Added test to verify network-exceptions are successfully cought.
=> Fix fiat initialization

freqtrade/optimize/__init__.py, freqtrade/tests/optimize/test_optimize.py
The current implementation of freqtrade contains the following issue: if you try to run backtesting for the period when the pair was not listed on the exchange(for example BCN/BTC on Binance on February) the bot re-downloads the data for that pair. It happens because the bot could not find the data on the disk and then re-downloads it form the exchange. It is a pain when you try to do backtesting on all the pairs on an exchange.
This PR makes the bot to download data only if `--refresh-pairs-cached` is set. If the data doesn't exist for the requested period of time the bot will show a notice about it.
- download pair data only if `--refresh-pairs-cached` is set
=> Do not download pairs if --refresh-pairs-cached isn't set

freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc.py
Sell filled amount or an open limit buy order in forcesell.
Currently forcesell only cancels an open limit buy order and doesn't sell the filled amount.
After this change, forcesell will also update trade's amount to filled amount and sell the filled amount.
=> Sell filled amount or an open limit buy order in forcesell.

freqtrade/optimize/__init__.py, freqtrade/tests/optimize/test_optimize.py
When backtesting/hyperopt does not have the pair in cache it asks to use `--update-pairs-cached`, but this param does not exist. The right param is `--refresh-pairs-cached`.
- Fix the backtesting/hyperopt hint `No data for pair %s, use --update-pairs-cached to download the data` for `No data for pair %s, use --refresh-pairs-cached to download the data`
=> Fix wrong hint '--update-pairs-cached' from Backtesting/Hyperopt

freqtrade/configuration.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_configuration.py
Because datadir has a default value, bot will always print:
`Parameter --datadir detected: freqtrade/tests/testdata`
which is misleading. Instead we would now print:
`Using data folder: freqtrade/tests/testdata`
=> change misleading logging for datadir

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
Fix test of: #706
the initial PR #706 looked good to me - however the source-repo has been deleted so pushing a fix for the Test is not possible anymore.
Full credit for this PR needs to go to @rymdluo.
Small options tweak to make the backtesting report markdown ready and much easier to share reports on many markdown publishing tools and editors that already support Markdown Extra with just a copy and paste.
Example:
=> Make backtesting report markdown shareable (resubmit)

freqtrade/optimize/hyperopt.py
This very simple PR fixing the in-progress '.' that is not displayed during a Hyperopt. The fault to my refactoring, when I forgot a `sys.stdout.flush()`.
No behavior change, only provide a better user experience during Hyperopt.
- In-progress '.' used during Hyperopt are now displayed all the time.
=> Fix the in-progress dot that does not show up during a Hyperopt run

.gitignore, .travis.yml, freqtrade/analyze.py, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/exchange/__init__.py, freqtrade/fiat_convert.py, freqtrade/freqtradebot.py, freqtrade/indicator_helpers.py, freqtrade/misc.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/persistence.py, freqtrade/rpc/rpc.py, freqtrade/rpc/rpc_manager.py, freqtrade/rpc/telegram.py, freqtrade/strategy/interface.py, freqtrade/strategy/resolver.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_configuration.py, setup.cfg
Apply typechecking with travis to verify Types are used correctly.
This is still a Work in Progress, so please don't merge yet.
Travis is expected to fail - mainly testing the .travis configuration and gathering feedback on this PR.
- add mypy to travis configuration
- Improve typehint quality by actively checking for it
- Fixed issues 
**Notes**:
`type: ignore` is applied to most timerange objects.
My intend is to change this to a class in a separate PR as having this as `Optional[Tuple[Tuple, Optional[int], Optional[int]]]` is confusing (at least to me).
=> add mypy typechecking

freqtrade/constants.py, freqtrade/exchange/__init__.py, freqtrade/fiat_convert.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/test_fiat_convert.py
This PR fix `get_ticker_history()` that does not work with GDAX/Coinbase. 
The issue is the ticker history received from GDAX is ordered DESC when Bittrex/Binance is ordered ASC. Because of that, the get_ticker_history() fall in a very long loop when the tickers are sorted DESC. Means it downloads more ticker than needed and you could get throttle by GDAX.
In addition, this PR allows the usage of EUR and USD as `stake_currency` Means you can try trading with FIAT on an exchange that supports it
- Allow using EUR or USD as `stake_currency`. 
- Fix backtesting with GDAX and certainly more exchanges
- First phase to make the bot compatible with GDAX
Provide the ability to backtest with GDAX and even more testing trading with EUR or USD.
I have not tested trading on GDAX yet. Only running …
=> Enable Backtesting with GDAX and allow trading with EUR/USD

docs/bot-usage.md
Backtesting and Hyperopt have involved with the time, but we forgot to update the documentation.
This PR changes in [Bot usage documentation file](https://github.com/gcarq/freqtrade/blob/develop/docs/bot-usage.md):
From
```
usage: freqtrade backtesting [-h] [-l] [-i INT] [--realistic-simulation]
[-r]
optional arguments:
-h, --help            show this help message and exit
-l, --live            using live data
-i INT, --ticker-interval INT
specify ticker interval (default: '5m')
--realistic-simulation
uses max_open_trades from config to simulate real
world limitations
-r, --refresh-pairs-cached
refresh the pairs files in tests/testdata with 
the latest data from the exchange. Use it if you want
to run your backtesting with up-to-date data.
```
To
```
usage: main.py backtesting [-h] [-i …
```
=> Update Backtesting/Hyperopt usage documentation

freqtrade/__main__.py
If you have tried to launch the bot from a command like `python3 freqtrade`, you certainly saw the message `can't find '__main__' module in 'freqtrade'`.
This PR fix this issue.
With this PR you can start the bot from `python3 freqtrade`. It behave like an alias to `python3 freqtrade/main.py`.
|  Command | Alias |
|----------|---------|
| `python3 freqtrade/main.py` | `python3 freqtrade` |
| `python3 freqtrade/main.py --help` | `python3 freqtrade --help` | 
| `python3 freqtrade/main.py backtesting` | `python3 freqtrade backtesting` | 
| `python3 freqtrade/main.py backtesting --help` | `python3 freqtrade backtesting --help` | 
| `python3 freqtrade/main.py hyperopt` | `python3 freqtrade hyperopt` | 
| `python3 freqtrade/main.py hyperopt --help` | `python3 freqtrade hyperopt --help` | 
- Add …
=> Add __main__.py to improve how to launch the bot

docs/backtesting.md, docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
allow export of backtesting-results to different files
Currently, we need to run backtest  with `--export=trades` - move the resulting json to another folder and rerun backtest for another strategy to be able to compare the results.
This PR will allow specifying a different filename per backtest-run by specifying 
`--export=trades --export-filename=Standardstrat_binance.json` in backtest arguments.
- add --export-filename for backtesting
** Note**
why do we need to specify `--export=trades` and not just `--export` (as bollean)? the possibility to export is backtesting trades, so it seems kind of pointless ...
Is the intend here to export more detailed stuff in the future?
=> allow export of backtesting-results to different files

.travis.yml, docs/backtesting.md, freqtrade/arguments.py, freqtrade/configuration.py, scripts/download_backtest_data.py
Makes `scripts/download_backtest_data.py` use better defaults.
- shows default exchange in the help
- uses exchange specific default folder. For example, binance tickers will download to `user_data/data/binance`.
- uses `pairs.json` found in the export folder by default. For binance, tries to use `user_data/data/binance/pairs.json`.
- updated documentation for this script
=> Improve ticker downloader

docs/backtesting.md, freqtrade/arguments.py, scripts/download_backtest_data.py
`download_backtest_data.py` previously always downloaded 1minute and 5min tickers. Now you can choose timeframes with `--timeframes`.
Add `--timeframes` flag which takes space-separated list of tickers, like `--timeframes 5m 1h 4h`.
Merge this only after #840 .
=> Choose tickers to download

freqtrade/arguments.py, freqtrade/constants.py
- Add constants for 3 minute, 8 hour and 3 day tickers.
- Remove support for 1 month ticker.
=> Add support for more timeframes

docs/configuration.md, freqtrade/constants.py
There are use-cases that need to build the base pair to consider price of whitelist pairs. 
On Binance the base pair is USDT not USD. 
USDT cannot be set in conifg.json as a fiat_display_currency as constants.py blocks it. 
This change does not break existing functionality as coinmarket allows conversion to USDT price. 
As example use-case here I use BTC/USDT to compare price gains for whitelist pairs. 
> /Users/creslin/PycharmProjects/freqtrade_new/scripts/report_correlation.py --timerange=1527595200-1527618600
> 2018-06-04 16:41:27,088 - freqtrade.configuration - INFO - Log level set to INFO
> 2018-06-04 16:41:27,088 - freqtrade.configuration - INFO - Using max_open_trades: 200 ...
> 2018-06-04 16:41:27,088 - freqtrade.configuration - INFO - Parameter --timerange detected: …
=> To be able to start with USDT in fiat_display_currency in config.json

requirements.txt
Use pyup filter to exclude `networkx==1.11` from updates.
Solve the issue: #853
=> exclude networkx from pyup

freqtrade/arguments.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_arguments.py
Refactor to get rid of the complicated and irritating type we had for Timeframes `Optional[Tuple[Tuple, Optional[int], Optional[int]]]`.
The new NamedTuple will be simpler to use as the objects can be referenced by name instead of index.
Numbers are initialized to 0 as the type defines if they have meaning or not.
`timeframe[0][1] ` becomes `timeframe.starttype`
In addition to that, it will remove some `type:ignore` hints previously used.
- Introduce TimeFrame NamedTuple
- removes some `type: ignore` statements
=> Refactor Timeframe fake-type into NamedTuple

freqtrade/exchange/__init__.py, freqtrade/tests/exchange/test_exchange.py
this readds ticker caching for rpc operations as `/status table` becomes very slow (takes a few seconds to respond - but does not need up to the second accurate data).
Solve the issue: #856
- Reinstate ticker caching (was half-intentionally dropped during ccxt move as we didn't think to require it).
- Add tests to verify it's correct implementation.
=> Re-add ticker caching for rpc operations

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
Use buy/sell signal from previous candle, not current to avoid seeing to the future. Quick improvement to one issue mentioned in https://github.com/freqtrade/freqtrade/issues/746 
I will update/fix tests only if we decide to go with this change.
=> Avoid look-ahead in backtesting

freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc.py
Currently, the bot sums the percentage as well as the absolute profit when `/profit` is called.
for Profit, this is fine, however percentage should not be summed up.
Solve the issue: #629
- use mean for percentage (aligend with backtesting)
backtesting example:
https://github.com/freqtrade/freqtrade/blob/ad510b8b5f259efc1b730d397dc86e351bba9461/freqtrade/optimize/backtesting.py#L80
before on a well-worn database of a now stopped testing bot
```
ROI: Close trades
∙ -0.12266488 ETH (-122.54%)
∙ -74.616 USD
ROI: All trades
∙ -0.14937144 ETH (-149.22%)
∙ -90.861 USD
Total Trade Count: 142
First Trade opened: 23 days ago
Latest Trade opened: 2 days ago
Avg. Duration: 1 day, 11:55:55
Best Performing: VEN/ETH: 10.08%
```
after: 
```
ROI: Close trades
∙ -0.12266488 ETH (-0.90%)
∙ -74.616 USD
ROI: …
```
=> fix /profit percentage calculation

config_full.json.example, docs/bot-usage.md, docs/configuration.md, docs/installation.md, freqtrade/__init__.py, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/freqtradebot.py, freqtrade/main.py, freqtrade/persistence.py, freqtrade/tests/conftest.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_persistence.py, scripts/plot_dataframe.py
This PR removes `--dry-run-db` flag and replaces it with `--db-url`.
This argument takes a string and defaults to `sqlite:///tradesv3.sqlite` if not specified. It still defaults to `sqlite://` if dry_run is enabled.
The motivation for this change it to allow more flexible deployments.
To get a persistent db in dry_run the new command would look like this:
```
$ freqtrade --db-url sqlite:///tradesv3.dryrun.sqlite
```
Solve the issue: #274
- drop `--dry-run-db` and replace it with `--db-url`
```
usage: freqtrade [-h] [-v] [--version] [-c PATH] [-d PATH] [-s NAME]
[--strategy-path PATH] [--dynamic-whitelist [INT]]
[--db-url PATH]
{backtesting,hyperopt} ...
Simple High Frequency Trading Bot for crypto currencies
positional arguments:
{backtesting,hyperopt}
backtesting         backtesting …
```
=> Allow custom sqlite database path

docs/installation.md
this is after i struggled with it myself.
improve windows installation documentation (mainly regarding ta-lib installation)
* removed a reference to checkout the develop-branch - which has become the default branch - so this step was unnecessary.
* improved steps for windows install
* referenced ta-lib wheel installation (as does the official documentation)
* make markdownlint a "little" happier ... (even though not all issues are fixed since we don't test for it anyway
=> update windows install documentation

freqtrade/analyze.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_misc.py
Continuing the efforts towards fixing https://github.com/freqtrade/freqtrade/issues/746 . After merging the look-ahead fix for backtesting in #855 , this PR continues by disabling similar behaviour in live operations by removing the last candle which almost always is a partial candle from the indicator calculations so that strategies do not get thrown off by the intra-candle fluctuations of a partial candle.
=> Partial candle removal

freqtrade/configuration.py, freqtrade/exchange/__init__.py, freqtrade/tests/test_configuration.py, scripts/plot_profit.py
Improve exception handling if config.json wasn't found and set correct process exit codes in all cases.
Docker invokation with missing mounts before and after this PR:
**before:**
```
$ docker run freqtrade:latest
Config file "config.json" not found. Please create your config file
Fatal exception!
File "/freqtrade/freqtrade/configuration.py", line 61, in _load_config_file
with open(path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
During handling of the above exception, another exception occurred:
File "/freqtrade/freqtrade/main.py", line 39, in main
config = Configuration(args).get_config()
File "/freqtrade/freqtrade/configuration.py", line 229, in get_config
self.config = …
```
=> improve error handling

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/exchange/__init__.py, freqtrade/fiat_convert.py, freqtrade/freqtradebot.py
First batch of changes to take fstrings into use.
Reasoning: makes the code a bit more readable imho, and a slight speed increase
```
s = 'foobar'
n = 123
timeit -r1 -n1000 f'{s}/{n}'
26.9 ns ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
timeit -r1 -n1000 '{}/{}'.format(s,n)
439 ns ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
timeit -r1 -n1000 '/'.join((s,str(n)))
464 ns ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)
```
If no one objects, I'll go through the rest of the code and f-stringify everything.
Read more about f-strings [here](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498)
=> fstrings in use

.travis.yml
We had 4 parallel jobs defined and `after_success` block is run after _each_ so coveralls report was uploaded 4 times which in turn caused these multiple comment posts by coveralls.io.
=> avoid running coveralls 4 times

docs/telegram-usage.md, freqtrade/freqtradebot.py, freqtrade/main.py, freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/state.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_main.py
Implements the functionality to reload the bot config without retarting the process. The telegram command for this is `/reload_conf`, which sets the application state to `State.RELOAD_CONF` to trigger the reload.
Solve the issue: #72
- Allow to reload bot config without restarting (`/reload_conf`)
=> Reload bot config without restarting

CONTRIBUTING.md
Encourage developers to install git pre-commit hook for `flake8` check.
=> Add note about flake8 pre-commit hooks

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
Fix ungracefull termination (-> crash) when no backtest data is found and `--refresh-pairs-cached` is not supplied.
added test for this specific condition (which is not that uncommon i think).
fix ungracefull termination:
```
2018-06-10 22:21:33,694 - freqtrade.optimize.backtesting - INFO - Ignoring max_open_trades (realistic_simulation not set) ...
File "/home/xmatt/development/pythonvirtenv/trade/bin/freqtrade", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "/home/xmatt/development/python/cryptos/freqtrade/bin/freqtrade", line 7, in <module>
main(sys.argv[1:])
File "/home/xmatt/development/python/cryptos/freqtrade/freqtrade/main.py", line 32, in main
args.func(args)
File …
```
=> Check if no backtest data is found and fail gracefully

.github/ISSUE_TEMPLATE.md
Since we receive many issues related to ccxt lately, i would suggest to include the ccxt version in the issue template. this will help debugging eventual crashes resulting from ccxt as well as opening an eventual upstream bug.
- Ask for ccxt version in issue template
=> update issue template to include ccxt version

scripts/plot_dataframe.py, scripts/plot_profit.py
running the plot-profit script without supplying --datadir resulted in an error as args.datadir is empty in that case.
use the default supplied by the configuration-object instead (can be overwritten by `--datadir abcd`.
**update**
was broken in plot_dataframe too...
=> fix default datadir not working in plot-script

freqtrade/rpc/rpc.py, freqtrade/rpc/rpc_manager.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_manager.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
I would like to implement a discord RPC client. This PR is the first step in this direction. It contains mostly code cleanups and preparations for that. No breaking changes.
* Removed telegram member variable (a instance of each running module is now in `self.registered_modules`)
* Make `cleanup` and `send_msg` more abstract to handle all modules in `self.registered modules`
* Add some abstract methods to call `name`, `cleanup` and `send_msg` via RPCManager in a more abstract way.
* Refactored tuple return madness (this is now handled via RPCException)
* python-telegram-bot is no longer imported at runtime if telegram has been disabled in config.
=> Simplify RPCManager and RPC module to implement other clients

docs/backtesting.md, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py
This PR will close all open trades at the end of the backtest period (no matter if they are currently profitable or not).
Note: this PR is not ready for merging yet but is functional should someone want to test. Please feel free to review already - but expect some changes to be still happening.
i don't like to do this much work in one PR - but having a "proper" type simplifies analyzing the backtest-results (i hate going by list-column index as i always forget the column sequence...)
Solve the issue: #866
- Force-closes all open trades at the end of backtesting
- Introduce NamedTuple BacktestResults to simplify analysis
Timeframe: 20180601-20180605
exchange: binance_ETH
pairs: `["LTC/ETH", "IOTA/ETH", "XMR/ETH", "XRP/ETH", "NCASH/ETH", "MTH/ETH", "AST/ETH", "TNT/ETH", "ETC/ETH"]`
both …
=> Display open trades after backtest period

freqtrade/tests/test_fiat_convert.py
Some mockups where missing - causing (silent) exceptions when running pytest without network.
Also, this could cause slower runnig tests (as network-traffic was generated by `coinmarketcap.listings()`).
* quicker unittests with slow/no internt connection
=> Fix fiat_convert missing mockups

.coveragerc, freqtrade/tests/test_configuration.py
Increase test-coverage for `configuration.py` 
* adding edge-cases to the tests to get full test coverage for this file 
* exclude __main__.py from coveralls - 
testing `if __name__ == '__main__':` is close to impossible
=> increase test-coverate for configuration

.travis.yml, freqtrade/tests/optimize/test_hyperopt.py
fix hyperopt test when no `config.json` exists.
travis does not complain as the example-file was copied beforehand, but my pc did as i don't have a plain `config.json`.
=> fix hyperopt test when no config.json exists

docs/installation.md
in #891 it was brought to my attention that we lack documentation on backtesting with Docker.
This PR will add just this.
=> Update Documentation to include backtesting with docker

freqtrade/analyze.py, freqtrade/exchange/__init__.py, freqtrade/freqtradebot.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/rpc/rpc.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_acl_pair.py, freqtrade/tests/test_analyze.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_main.py, scripts/download_backtest_data.py, scripts/plot_dataframe.py
Change exchange from beeing a global variable to a class.
This will bring the work started with #537 onward, moving further towards object oriented code. I read somewhere (but can't find it anymore) that exchange was left as is to not obstruct work on ccxt - which has since been merged - so i think it makes sense to bring this forward.
It will increase code-coverage (some by nature, some by adding tests).
- change exchange from beeing a collection of functions to a class
- increase code coverage by adding some missing tests
- updated scripts to work with the exchange object
=> Objectify exchange

freqtrade/rpc/api_server.py
Moved registering application urls out of the app run def and into their own defs.
Added 404 handling
Split registration of URLs that use rpc.rpc and others into
own defs. Seems logical to be able to register separately for later hygiene.
=> Moved registering application urls out of the run def

config.json.example, config_full.json.example, docs/configuration.md, freqtrade/analyze.py, freqtrade/constants.py, freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
Introduce an option to only sell if no buy-signal is present.
Currently, we can have the case that the bot sells due to ROI reached - but has the buy-signal still active. This results in the bot selling - and then rebuying the same currency again one iteration later.
While it's technically not a problem, it will reduce the overall profit as the buy/sell fee is paid for nought.
Solve the enhancement #318 , and inspired by the discussion in  #713
- introduce optional `ignore_roi_if_buy_signal`
- add tests for the new option
I took it almost exactly as outlined in #318 - but shortened the parameter a bit
For some strategies, it improves backtest - for others it worsens results (depending on the strategy used).
=> Introduce ignore_roi_if_buy_signal parameter to avoid sell/buy scenarios

freqtrade/persistence.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/test_persistence.py
Remove global config `_CONF` from `freqtrade.persistence` because it is no longer needed.
=> Remove global config from persistence module

freqtrade/strategy/resolver.py, freqtrade/tests/strategy/test_strategy.py
Fixes a FileNotFoundError in StrategyResolver if user_data wasn't found (a warning is printed instead). Also it uses the bot invocation path to find `user_data` instead of script path.
This should yield a working install with `python setup.py install`
Solve the issue: #435
=> StrategyResolver: Don't fail if user_data isn't present

freqtrade/arguments.py, scripts/download_backtest_data.py
Don't automatically delete data when downloading a shorter period
Fixes the following case (which happened to me today)
* data exists from 2018-01-01 - 2018-06-01
* run script with --days 24 (today is the 24th)
* wait for download
* check timerange - now i only got data form 2018-06-01 to 2018-06-24 - data from January til June has been deleted
- don't automatically delete existing backtest data
- introduce --erase option to delete existing pair data
- removal of duplicated code by calling the same method than `backtesting --refresh-pairs-cached`
=> slight rework of download script

config.json.example, config_full.json.example, docs/configuration.md, freqtrade/constants.py, freqtrade/freqtradebot.py, freqtrade/tests/conftest.py, freqtrade/tests/test_freqtradebot.py
Based on work from @nullart (and with his agreement), i extracted the separated unfilled timeout.
This is part of #968, which i feel will be very difficult to merge as it mixes a ton of different features, so extracting them one by one should make merging easier.
* allow configuration of separate timeouts for buy and sell.
* reduce the default config to something more reasonable
=> separating unfulfilled timeouts for buy and sell

freqtrade/tests/exchange/test_exchange.py
This will remove a lot of test code duplication, as all ccxt functions which have the `@retrier` decorator should catch these ccxt exceptions.
This will mostly simplify adding new functions / tests for new functions as the "default" exceptions can be easily cought.
* improve code coverage of exchange class
* Abstract retrier / exceptionhandling
=> Rewrite standard ccxt exception handling

freqtrade/analyze.py, freqtrade/tests/test_analyze.py
Fix `Outdated history for pair` message when using longer timeframes (longer than 5m!!)
Solve the issue: #995
The best explanation is probably in the ticket, but to summarize assume the following:
it's now 9:55am (utc), we use 2h candles.
my last valid candle is the one from 6am (6am -8am).
the candle which opens at 8am will be closed in 5 minutes.
The current logic will flag this as "outdated" 99% of the time - as it goes back 2h+5m. (to 7:50am).
However, my valid candle starts at 6am. So we go back twice the tickerframe (in this case 4 hours) + a window of 5 minutes.
- increase allowed "non-available" time.
- use `arrow.shift()` instead of timedelta - to reduce necessary imports and code complexity
=> don't flag data as outdated which isn't

freqtrade/tests/optimize/test_backtesting.py
This will add a test to verify the result of the backtest does match match the input-data.
this is a preparational step for an upcomming PR which should fix #961 ... 
but i want to have tests in place first, so the difference is obvious.
* Added test
=> Test backtest results

freqtrade/analyze.py
Slightly optimize backtesting by reducing a call to calc_profit_percent.
Don't expect wonders out of this as it's just one fewer call (incl. subcalls) ... but one thing to the other, it could impact hyperopt-performance (assuming this is called thousands of times ...
=> reduce calculation effort by removing a call to calc_profit_percent

freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
Use Open-rate for backtesting.
For an explanation as to why, se either ticket or the explanation below.
TL,DR: we use buy/sell signals from ticker the previous ticker - so we need to use open-rate, otherwise we use a different price (eventually a few hours later - when using hour/2h tickers).
Solve the issue: #961
- Use open as trade-open / close rate while backtesting
thanks to @creslinux for the great paper he wrote explaining this issue, i will shamelessly copy/paste his report below
=> Use open-rates for backtesting

freqtrade/freqtradebot.py, freqtrade/main.py, freqtrade/rpc/__init__.py, freqtrade/rpc/rpc.py, freqtrade/rpc/rpc_manager.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_manager.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
Contains some cherry-picks from #938 to unblock #937
The most notable change is that rpc.send_msg takes a `dict` with arbitrary data as argument.
=> Rewrite RPC module

freqtrade/rpc/rpc.py
it seems that mypy version upgrade from 0.610 o 0.620 broke travis
=> rpc: dont re-use variables with different types

freqtrade/exchange/__init__.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py
for bug: #978 
Handle if ticker_interval in config.json is not supported on exchange.
Tested positive and negative data.
The ticker list in constants.py may be obsolete now, im not sure.
Returns:
```
raise OperationalException(f'Invalid ticker {timeframe}, this Exchange supports {timeframes}')
freqtrade.OperationalException: Invalid ticker 14m, this Exchange supports {'1m': '1m', '3m': '3m', '5m': '5m', '15m': '15m', '30m': '30m', '1h': '1h', '2h': '2h', '4h': '4h', '6h': '6h', '8h': '8h', '12h': '12h', '1d': '1d', '3d': '3d', '1w': '1w', '1M': '1M'}
```
=>  Handle if ticker_interval in config.json is not supported on exchange.

freqtrade/strategy/resolver.py, freqtrade/tests/strategy/test_strategy.py
Update the config-dict with values loaded from the strategy.
This should allow consistent use of the config object without the need to check if the attribute is not configured and came from the Strategy.
Solve the issue: #998, helps #979 which relies on having ticker_interval in the config dict after loading.
- Updates the config dictionary
=> Update config dict with attributes loaded from strategy

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/main.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_main.py
Allow several levels of verbosity, helping debug issues with libraries if necessary.
- add flags `-v`, `-vv`, `-vvv` to show debug-messages from requests / ccxt.
- fix bug where `-v` would output requests messages
=> Add more verbosity levels

docs/backtesting.md, docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_configuration.py
This PR will remove the `--realistic-simulation` flag and replace it with `--enable-position-stacking` and `--disable-max-market-positions`.
Solve the issue: #1035
The `--realistic-simulation` flag (referenced as `--realistic` from now on) did 2 things - enable max_open_trades in backtest and disable "position stacking" - buying the same pair multiple times.
Having this combined creates a lot of confusion (see slack discussion yesterday evening) - and limits the usefullness of backtesting as it limts what different scenarios can be tested.
The default is now a `--realistic` mode - simulating how the bot should behave in production (i know we're not there yet), as the assumption is that new users will want to experiment with this first, and dive into the other options once they are …
=> replace --realistic with 2 separate flags

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/main.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_main.py
Resubmitting this PR after the first did not set the loglevel at all.
- add multiple verbosity levels
- allow debugging requests / ccxt calls by using higher verbosity levels
=> Add multiple verbosity levels

freqtrade/fiat_convert.py, freqtrade/tests/test_fiat_convert.py
Fiat convert should under no circumstance cause the bot to stop functioning, therefore all exceptions from the API should be cought (coinmarketcap may have a bad day and return rubbish or whatever ... but it's not vital for the bot so if it doesn't work we can ignore it.
This was in place for find_price, but not for the initialization of the library.
Solve the issue: #1052
- Catch all exceptions
=> Catch all exceptions from fiat-convert api calls

freqtrade/tests/test_freqtradebot.py
Found another instance of a mock not being in place, causing my tests to fail on the plane.
- Fix mocking for get_markets where it was missing
=> Add missing mock

freqtrade/persistence.py, freqtrade/tests/test_persistence.py
Small bugfix to solve a bot crash at startup if a database is in a specific state
this happens if `fee_open` and `fee_close` exist but a migration is still necessary 
* remove fix in persistence.py - but leave the test there
```
File "/freqtrade/freqtrade/main.py", line 45, in main
freqtrade = FreqtradeBot(config)
File "/freqtrade/freqtrade/freqtradebot.py", line 55, in __init__
self._init_modules()
File "/freqtrade/freqtrade/freqtradebot.py", line 64, in _init_modules
persistence.init(self.config)
File "/freqtrade/freqtrade/persistence.py", line 56, in init
check_migrate(engine)
File "/freqtrade/freqtrade/persistence.py", line 119, in check_migrate
""")
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2075, in execute
return …
```
=> fix a bug in the database migration script

docs/backtesting.md, freqtrade/freqtradebot.py, freqtrade/optimize/backtesting.py, freqtrade/persistence.py, freqtrade/rpc/rpc.py, freqtrade/strategy/interface.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_persistence.py
Stores sell_reason in the database.
Solve the issue: #1017
Storing the reason for the sell (stop-loss / trailing-stop / ROI / sell-signal) will enable us to better diagnose problems / issues with sells. it should also enable a "post run" analysis of a strategy, checking if stop-loss / sell-signal causes losses.
The information is currently in the logs, however this makes analysis very difficult (and requires a high log-level as "stop-loss" is a debug signal.
added the small table in the middle Suggestions for improving this are welcome
```
================================================= BACKTESTING REPORT ==================================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH |   avg duration |   profit |   loss | …
```
=> Record sell reason

freqtrade/optimize/backtesting.py
Trivial change: you should use Pandas' own `min` and `max` instead of Python's built-in. In this case it's over 300 times faster. With 54 days of 5min ticker data, this shaved off over 10% of the total backtest time.
=> Use pandas own min and max

README.md
Make the quickstart usable by anyone.
Solve the issue: The order of the commands in quickstart are incorrect
- Changed the order of the quickstart commands
=> Error fixed in the quickstart documentation

freqtrade/freqtradebot.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_freqtradebot.py
Extract `get_history` network call from `get_signal` to allow async / parallel processing of the download all at once.
Solve step 1 of the solution for  issue: #1046 (will not solve it!)
- remove network-call from get_signal
- adjusted function interface (due to not needing the exchange, but a ticker-history in the function
=> Extract get history from get_signal call

freqtrade/constants.py
As per CCXT docs some exchanges require Password in addition to API Key/Secret. 
Adding into config.json and allowing in constants provides this. 
Tested working on GDAX 
The _API tells us the required fields. 
CCXT API setup docs
> API Keys Setup
> The API credentials usually include the following:
> 
> apiKey. This is your public API Key and/or Token. This part is non-secret, it is included in your request header or body and sent over HTTPS in open text to identify your request. It is often a string in Hex or Base64 encoding or an UUID identifier.
> secret. This is your private key. Keep it secret, don't tell it to anybody. It is used to sign your requests locally before sending them to exchanges. The secret key does not get sent over the internet in the request-response process and …
=> add Password option to API login, GDAX as example requires. 

config_full.json.example, docs/configuration.md, docs/stoploss.md, freqtrade/constants.py, freqtrade/strategy/interface.py, freqtrade/tests/test_freqtradebot.py
add offset to trailing stop loss positive - otherwise it stops trailing with -1% (for example) once the profit is 0 - which is still a red trade.
Solve the issue: #1020 
- introduce new parameter for trailing stop loss Positive
=> add offset for positive trailing stop loss

freqtrade/tests/rpc/test_rpc.py
Another flight - another unmocked test.
- Add missing RPC mocking which is required for these tests to not use network connections
=> fix rpc test going to network

freqtrade/optimize/__init__.py
there is #1023 and there is alot of discussion related to `ujson` and windows support. This PR takes another approach to #1023 so that it should be possible to use `ujson` if it exists in the system. Otherwise we use the default `json` module.
=> backtesting: try to load data with ujson if it exists

config.json.example, config_full.json.example, freqtrade/exchange/__init__.py
The CCXT rate limit is too strict. it slows down async fetching. 
- adding a config in exchange (ccxt_rate_limit)
- using above variable in ccxt initializer instead of hardcoded "True"
=> Initializing CCXT with rate_limit parameter optional (default to true) [EDITED]

freqtrade/exchange/__init__.py, freqtrade/exchange/exchange_helpers.py, freqtrade/freqtradebot.py, freqtrade/optimize/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_freqtradebot.py, scripts/plot_dataframe.py
renamed/refactored get_ticker_history to get_candle_history
As the def does not fetch any ticker data only candles
Its causing confusion when developers are talking about candles /tickers and meaning the opposite data feed from the exchange.
OHLCV (candles/klines) and Tickers are two seperate datafeeds from the exchange, with separate calls to CCXT. 
As examples from CCXT:
- To fetch a candle from CCXT we use `fetchOHLCV `
- To fetch a ticker from CCXT we use `fetch_ticker`
And as examples from an exchange:
- get a candle: https://api.binance.com/api/v1/klines?symbol=LTCBTC&interval=15m&limit=1
` [[1533201300000,"0.01012200","0.01014200","0.01011900","0.01012500","1191.43000000",1533202199999,"12.06536378",139,"496.99000000","5.03477609","0"]]`
- get a ticker: …
=> renamed/refactored get_ticker_history to get_candle_history to stop confusion

docs/backtesting.md, docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py
This PR will allow backtesting multiple strategies at once efficiently, as startup/spindown time of backtest makes most of the time (loading data, ...).
- introduce new command line option `--strategy-list`
the backtesting output is printed once per strategy (with the strategy-name)
The strategy-comparison table is only printed if more than 1 strategy is selected.
the full output of 2 strategies backtested would look as follows:
```
2018-07-29 13:07:53,724 - freqtrade.optimize.backtesting - INFO - 
Result for strategy BinHV27
2018-07-29 13:07:53,750 - freqtrade.optimize.backtesting - INFO - 
================================================== BACKTESTING REPORT =================================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH …
```
=> Allow multi strategy backtest without data reload

README.md
Binance uses BNB for fees. If an account does not own Fees, but a trade is made on BNB, subsequent trades use up this BNB balance for their trading fees.
This creates a problem for the BNB position, as the amount reduces and the trade is finally not completed due to lack of balance.
Solve the issue: #1084
- add documentation to exclude BNB on binance
=> Add note to readme for binance users

scripts/get_market_pairs.py
A python script to return
- all exchanges supported by CCXT
- all markets on a exchange
Invoked as `python get_market_pairs.py` it will list exchanges
Invoked as `python get_market_pairs binance` it will list all markets on binance
Sample output: `python get_market_pairs.py`
```
Supported exchanges: _1broker, _1btcxe, acx, allcoin, anxpro, anybi
```
Sample output: `python get_market_pairs.py binance `
```
binance has 384 symbols: ['ADA/BNB', 'ADA/BTC', 'ADA/ETH', 'ADA/USDT', 'ADX/BNB', 'ADX/BTC', 'ADX/ETH', 'AE/BNB', 'AE/BTC', 'AE/ETH', 'AGI/BNB', 'AGI/BTC', 'AGI/ETH', 'AION/BNB', 'AION/BTC', 'AION/ETH', 'AMB/BNB', 'AMB/BTC', 'AMB/ETH', 'APPC/BNB', 'APPC/BTC', 'APPC/ETH', 'ARDR/BNB', 'ARDR/BTC', 'ARDR/ETH', 'ARK/BTC', 'ARK/ETH', 'ARN/BTC', 'ARN/ETH', 'AST/BTC', 'AST/ETH', 'BAT/BNB', …
```
=> Script to get market pairs

freqtrade/constants.py
XBT is the official market symbol for Bitcoin, used on some exchanges. 
Added to constants.py to allow bot to start against these.
=> XBT missing as a market symbol for BTC in constants

freqtrade/tests/test_dataframe.py
Fix failing test if metadata is used as shown in #1119.
This only impacts tests, but was missed in the initial pr #1044 
- Adapt test to work if metadata-dict is used
=> Fix failing tests when metadata in `analyze_ticker` is actually used

freqtrade/exchange/__init__.py, freqtrade/freqtradebot.py, freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py, freqtrade/tests/test_talib.py
More RPC/Telegram information when bot starts.
- Updated freqtradebot.py - added startup messages function
- Updated rpc/rpc.py - added new RPC types (Warning, Custom)
- Update rpc/telegram.py - added codes to handle new RPC types
- Updated exchange/__init__.py - mypy fix
- Updated tests/test_talib.py - pytest fix
* Dry run warning
```
Warning: Dry run is enabled. All trades are simulated.
```
* Configuration details
```
Exchange: binance
Stake per trade: 0.01 BTC
Minimum ROI: {'0': 0.02}
Ticker Interval: 3m
Strategy: ADXMomentum
```
* Static Whitelist or Dynamic Whitelist information
```
Status: Searching for whitelisted BTC pairs to buy and sell...                          
TUSD/BTC
```
```
Status: Searching for top 20 BTC pairs to buy and sell...
```
=> Informative startup

requirements.txt
updates plotly frorm 3.0.0 to 3.1.1.
This is not covered by pyupbot as it's commented in the requiremnets file.
=> update plotly dependency

Dockerfile, freqtrade/strategy/__init__.py, setup.sh
This will fix the issue of the bot crashing on strategy-loading with python 3.7.
Solve the issue: #1064 
- hack-fix the "cannot pickle _abc_data" error
- update setup.sh to support systems without python 3.6
unfortunately, travis cannot run against 3.7 yet (https://github.com/travis-ci/travis-ci/issues/9815)
i'll try in a different pr to support this.
=> fix running freqtrade on python3.7

freqtrade/persistence.py, freqtrade/strategy/resolver.py, freqtrade/tests/strategy/test_strategy.py, freqtrade/tests/test_persistence.py
print min-roi settings from config if used from config-file (same as done with stoploss or ticker_interval
Also removed unnecessary escaping - if string is in double-quotes, `'` does need no escaping.
Database migration logging slightly changed to not always info-log which tables have been tried in a migration scenario.
old:
```
Override strategy 'minimal_roi' with value in config file.
```
new:
```
Override strategy 'minimal_roi' with value in config file: {'0': 0.5}.
```
=> Output min-roi setting when overwriting from config

freqtrade/tests/strategy/test_interface.py
This adds a simple explicit test to check if `min_roi_reached` is working as expected.
I had to think twice about the logic and noticed that while test-coverage is there, it's not correctly covered as no explicit check is done to determine the different ROI settings are applied correcty.
=> Add explicit test on handling min_roi_reached

freqtrade/exchange/__init__.py, freqtrade/tests/exchange/test_exchange.py
remove amount_to_lots (deprecated / removed)
was removed from ccxt in https://github.com/ccxt/ccxt/commit/527f082e59e1cd3698cb7ae95bdcaae4459ea218
in addition to that, we didn't use this anywhere anyway.
=> remove amount_to_lots (deprecated / removed)

freqtrade/exchange/__init__.py, freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc.py
For `/balance`, we're using `get_ticker` to get the latest rate. This fails if a coin is not yet listed on the exchange, breaking `/balance` until the coin is listed or the balance is somehow removed from the account.
This should not happen as the balance for all other coins is still valid.
While this is an edge-case with VTHO, it could happen with other coins which are either unlisted, or have a similar introduction than VTHO.
Solve the issue: #1111 
- Add test for failed case
- Catch error and skip this coin
=> Fix /balance rpc call if coin is not properly listed

config_full.json.example, docs/sandbox-testing.md, freqtrade/constants.py, freqtrade/strategy/interface.py
Add a parameter to dynamically change `outdated_ticker` offset.
This is needed for gdax sanbox support - but also for others. 
As shown in the sandbox configuration document changes, it'll greatly simplify usage as no change to the base-code is necessary.
to simplify usage of sandbox usage introduced in  #1078
- introduce new config parameter
=> parametrize outdated_offset to simplify sandbox usage

README.md, docs/configuration.md, freqtrade/constants.py, freqtrade/strategy/interface.py, freqtrade/strategy/resolver.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/strategy/test_strategy.py
This is the last cut that was in #1117 before i closed that PR
This PR allows a user to set the flag `ta_on_candle` in their config.json
This will change the behaviour of the the bot to only process indicators
when there is a new candle to be processed for that pair.
the problem being addressed is in a 5 minute candle the same dataframe with no new 
candle data will be processed by TA indicators looking at only candle data 100 times. 
In a 4 hour timeframe this is many thousands of if times. 
the bot then has to deal with expensive CPU load slowing the system and ignoring thouands of false buy/sell signals. 
The new behavour is optional, the default is no change in current behaviour. 
The test is against a dict of  {'pair': candle last processed date} not matching current last candle row …
=> ta_on_candle (not loop, with optional flag in config.json) Resubmitting - because GIT.

docs/hyperopt.md
Be explicit in hyperopt documentation to require more than 1core.
Solve the issue: #1133
=> explicitly ask for more ressources in hyperopt documentation

Dockerfile
use --no-cache can save about 90M
``` bash
➜  freqtrade git:(develop) ✗ docker images freq
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
freq                latest              b15db8341067        7 minutes ago       800MB
➜  freqtrade git:(develop) ✗ docker images freq_nocache
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
freq_nocache        latest              e5731f28ac54        20 seconds ago      709MB
```
=> use --no-cache-dir for docker build

freqtrade/optimize/backtesting.py
Backtesting is very verbose.
the "left-open-trades" table should not contain pairs which were not left open.
- Reduce number of non-meaningfull lines in output for backtesting
before:
```
================================================== BACKTESTING REPORT =================================================
| pair      |   buy count |   avg profit % |   cum profit % |   total profit ETH | avg duration   |   profit |   loss |
|:----------|------------:|---------------:|---------------:|-------------------:|:---------------|---------:|-------:|
| LTC/ETH   |          51 |          -0.04 |          -2.26 |        -0.00225942 | 2:04:00        |       24 |     27 |
| IOTA/ETH  |          61 |           0.11 |           6.58 |         0.00659000 | 2:10:00        |       38 |     23 |
| XMR/ETH …
```
=> don't print "NAN" lines in "left_open_trades"

freqtrade/exchange/__init__.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
Refactoring -  as promised in #1101 -  to remove load_markets from `validate_pairs` - as it really doesn't belong into this function.
Solve part 1 of the issue: #1196
- move load_markets into it's own function.
- simplify mocking by having (almost) 1 central place to mock exchange
=> refactor load_markets out of validate_pairs

README.md, docs/installation.md, freqtrade/exchange/__init__.py, install_ta-lib.sh
Fix the installation of ta-lib for mac-users (`sed -i "pattern"` is invalid in bsd-versions.
Adding .bak after the -i generates a backup file of the previous version - which works on both macos and linux. 
- documentation and install-script fix
=> Fix mac install documentation

freqtrade/tests/test_acl_pair.py
change calls to `default_config()` to use a pytest fixture instead.
this removes a warning appearing in pytest 3.7.0 about not calling fixtures directly.
=> Remove direct call to pytest fixture to elliminate pytest warning

README.md, freqtrade/exchange/__init__.py
Add 5s offset to cover very slight time-differences (1s should in theory be enough - but better be safe in this case as it doesn't do any harm to get 5s more trades).
Solve the issue: #1185, #1086
- add offset to get trade if the exchange-time is slightly behind (or ours is ahead).
=> Add offset to "get_trades_for_order"

freqtrade/arguments.py, freqtrade/configuration.py, scripts/plot_dataframe.py
Fix plot_dataframe script 
Solve the issue: #1217 
- Load latest backtesting files correctly
- set default-argument for db-url in configuration, not arguments - as it's overwritten there anyway and introduces a bug on plot_dataframe.py.
=> Fix plot dataframe

freqtrade/optimize/backtesting.py
Strategy was loaded twice during backtest, filling a unneeded variable (strat).
=> Only load strategy once during backtesting

freqtrade/tests/test_freqtradebot.py
Exchange / network calls should be properly patch to avoid random test-failures.
=> Patch exchange to not cause network delays during tests

freqtrade/optimize/hyperopt.py, freqtrade/strategy/__init__.py, freqtrade/tests/optimize/test_hyperopt.py, requirements.txt
Fix hyperopt to work with new version of scikit-learn
Solve the issue shown after the update of scikit-learn to 0.20.0:  #1242
Potentially fixes #1232 - but will need further testing.
- Show error if `--strategy` is used with hyperopt. 
methods from the strategy are not used anyway, so using a custom strategy does not provide gains here - as currently the hyperopt file needs to be modified
The problem comes from hyperopt-processes not properly finding the strategy class - and therefore pickle shows an error on load. This is caused by the fact on how we load strategies.
```
2018-09-28 12:34:38,933 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
sklearn.externals.joblib.externals.loky.process_executor._RemoteTraceback: 
'''
Traceback (most recent call …
```
=> Fix hyperopt pickle

config.json.example, config_full.json.example, docs/configuration.md, docs/telegram-usage.md, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/exchange/__init__.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/test_configuration.py, scripts/download_backtest_data.py
Allow usage of any ccxt configuration option. see [CCXT documentation](https://ccxt.readthedocs.io/en/latest/manual.html#instantiation) for details on what is possible for each exchange.
Proxy support for asyncio was moved to an attribute of ccxt in https://github.com/ccxt/ccxt/issues/3867 . While not a problem, we have no easy way to set custom options in ccxt.
CCXT uses every key as attribute, and every value as it's value and initializes with these settings. This allwos overwriting of almost all ccxt options from within these 2 dictionaries, seperated between async and sync (not everything will make sense for both).
Solve the issue: #1207
- allow setting of any possible (or impossible) ccxt attribute to support as many options as possible
- deprecate `ccxt_rate_limit`, as it cannot be …
=> Add general ccxt configuration options

freqtrade/rpc/rpc.py
`/forcesell 1` does flush the session at the end.
`/forcesell all` does not as it exits before doing the flush, causing trades to show up in status-table after /forcesell.
=> flush session for /forcesell all

freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc_telegram.py
Showing very low balances (called "dust" - at least on binance) does not make sense.
Solve the issue: #1274
XRP is not showing in this example:
=> Hide low value balances from `/balance`

freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
Enable analytical telegram commands in `stopped` state.
Solve the issue: #326
Enables when stopped:
- `/status`
- `/status table`
- `/performance`
`/balance` does already work in stopped state.
=> Enable analytical telegram commands when stopped

freqtrade/optimize/__init__.py, freqtrade/tests/optimize/test_optimize.py
Shows a warning if backtesting data is selected by date - and not all data is available.
ran into this myself - data for 1 pair was not complete and caused flawed backtesting results.
-Show warning
shows the warning during backtest startup:
```
...
2018-10-14 14:42:03,133 - freqtrade.optimize.backtesting - INFO - Using stake_currency: ETH ...
2018-10-14 14:42:03,133 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 0.1 ...
2018-10-14 14:42:03,134 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
2018-10-14 14:42:05,116 - freqtrade.optimize - WARNING - Missing data at end for pair TRX/ETH, data ends at 2018-09-02 18:00:00
...
=> Show warning if part of backtest data is missing

freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
Solve the issue: #1298
- include pairs from open trades to active-whitelist to make sure ticker-data is downloaded
- don't overwrite pair-whitelist in config dict to avoid facing an empty list if markets where down for a short amount of time when not using dynamic whitelist.
=> Fix no tickerdata for pair for open trades

docs/configuration.md, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/tests/test_configuration.py
max_open_trades should be ignored if it is -1. 
That means potentially unlimited open positions.
This will come handy for Edge further refactoring regarding position sizing.
=> Ignoring max_open_trades if it is -1 in config.

freqtrade/tests/optimize/test_backtesting.py
running tests  left a file called `test_.json` behind - this is anoying... as it creates a dirty git state.
=> Fix missing mock in backtesting

config_full.json.example, docs/configuration.md, freqtrade/constants.py, freqtrade/exchange/__init__.py, freqtrade/freqtradebot.py, freqtrade/strategy/default_strategy.py, freqtrade/strategy/interface.py, freqtrade/strategy/resolver.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/strategy/test_strategy.py, freqtrade/tests/test_freqtradebot.py, user_data/strategies/test_strategy.py
As mentioned in #1326, there is a pretty simple way to support different order types.
Solves issue: #893
- Add order mapping between buy/sell/stoploss - allowing different types for each order
this is a very quick drawup on how i immagine this to work, and it's nowhere near production ready.
=> Add support for different order types

freqtrade/freqtradebot.py
For some reason there were two lines of 
`self.exchange.refresh_tickers(self.active_pair_whitelist, self.strategy.ticker_interval)`
Removed one of them.
=> Fix twice refresh ticker call

docs/configuration.md
as pointed out [here](https://github.com/freqtrade/freqtrade/commit/d72e605cb70ffda6622601df0441ce60f84bf92a#commitcomment-31404278) - we should add a note to the docs that not all exchanges support all ordertypes.
=> Add Note about order types support

freqtrade/exchange/__init__.py, freqtrade/exchange/exchange_helpers.py, freqtrade/tests/exchange/test_exchange.py
Remove non-used method (everything related to this has been moved to async)
Only sort candles when necessary
Solve the issue: #1196 
- remove `get_candle_history`
- migrated sorted tests to async
- sort only when necessary
=> async followup PR

freqtrade/edge/__init__.py, freqtrade/tests/edge/test_edge.py
When Edge doesn't have a stoploss for a pair it should return strategy stoploss, otherwise the bot crashes.
Solve the issue: #1370
=> Should fallback to strategy stoploss if Edge cannot provide.

freqtrade/freqtradebot.py, freqtrade/rpc/rpc_manager.py, freqtrade/tests/rpc/test_rpc_manager.py
refactor startup_messages to rpc_manger
this cleans up freqtradebot slightly, as this method/class is overly crouded and long.
* also adds test.
=> refactor startup_messages to rpc_manger

build_helpers/publish_docker.sh
Add commit and message to container
without this, we have no (easy) way of knowing which commit the latest / develop container is running, which makes debugging problems in containers almost impossible.
output:
```
docker run -it --entrypoint bash freqtradeorg/freqtrade:feat_improve_travis
root@40204a56b46c:/freqtrade# cat freqtrade_commit
3a086aac58f4f2fd3530910d1adc3154e9c3ea73 Add commit and message to container
```
=> Add commit and message to container

freqtrade/configuration.py, freqtrade/tests/test_configuration.py
without doing that, it exclusiveMaximum raises an exception
as jsonschema defaults to the latest version (Draft6)
which changes behaviour of this property.
fixes #1233
Once jsonschema is updated to stable version 3.0.0 we can switch the validatior to Draf6, however version 2.6.0 does not support that yet.
*for the future*: Note that this change will require a slight change in how `exclusiveMaximum` is used, so we should stick to draft4 until most of the users upgraded.
=> Specify JsonValidatorversion explicitly

CONTRIBUTING.md, config_full.json.example, docs/bot-usage.md, docs/configuration.md, docs/developer.md, docs/index.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/freqtradebot.py, freqtrade/pairlist/IPairList.py, freqtrade/pairlist/StaticList.py, freqtrade/pairlist/StaticPairList.py, freqtrade/pairlist/VolumePairList.py, freqtrade/resolvers/__init__.py, freqtrade/resolvers/hyperopt_resolver.py, freqtrade/resolvers/pairlist_resolver.py, freqtrade/rpc/rpc.py, freqtrade/rpc/rpc_manager.py, freqtrade/rpc/telegram.py, freqtrade/tests/pairlist/test_pairlist.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_manager.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_acl_pair.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_freqtradebot.py
Provide a dynamic pairlist-provider, to support different types of dynamic pairlists.
Currently only StaticPairlist (base-class) and VolumePairlist are implemented.
Voluepairlist, configured with  "quoteVolume" will mimic the behaviour of `--dynamic-whitelist`.
Volumepairlist however can sort on many other types as well.
Future additions could include a sorting based on top/bottom coins by marketcap, ... 
This should hopefully facilitate #935 in the future, and open the possibility to select pairs based on a corellation matrics (#325)
not part of this PR:
* Implement further pair selections
=> Dynamic Pairlist provider

freqtrade/persistence.py, freqtrade/tests/test_persistence.py
avoid naming conflicts on recreate (indexes are not renamed, and keeping
them on backup tables does not really make sense).
Solve the issue: #1396
=> Drop indexes on renamed table during migration

docs/bot-usage.md
having the commands to run is nice ... but to understand the results, one needs to read the edge documentation ...
this (partially, at least) fixes #1380.
=> Add link to edge documentation in bot-usage

freqtrade/exchange/__init__.py, freqtrade/exchange/exchange_helpers.py, freqtrade/freqtradebot.py, freqtrade/optimize/backtesting.py, freqtrade/strategy/interface.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/exchange/test_exchange_helpers.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_misc.py, scripts/plot_dataframe.py
Parsing the list of candles each time the bot analyzes the strategy increases increase cpu usage.
We can parse the list to DF once, and store the DF to avoid this step.
There is a slight memory-penalty - (smallish dataframes  (of the size we're dealing with) is slightly bigger than a simple python list) - but we need the dataframe each time - so it's actually twice in memory (for a short amount of time).
- refactor klines to be a method returning a copy of a dataframe (never pass the real dataframe back, otherwise caching could break if users are not carefull).
- move klines to be Dataframe
=> keep DF instead of list

.travis.yml, Dockerfile.develop, docs/installation.md, requirements-dev.txt, requirements.txt, setup.sh
Separate development dependencies in another requirements file and Dockerfile.
Solve the issue: #1356
- Add a requirements-dev.txt file which includes additional deps for development.
- Add a Dockerfile.develop which installs all deps for development and also enables dev commands.
- Change related documentations on how to run/dev the bot.
=> Seperate requirements to run the bot and to develop.

freqtrade/freqtradebot.py
in `check_handle_timedout` remaining amount is converted to ìnt`before comparison leading to cases as described in #1424 
I don't see any reason for it. changing it to float solves the problem.
Solve the issue: #1424
=> Remaining amount in check_handle_timedout should be treated as float not int.

freqtrade/arguments.py, scripts/download_backtest_data.py
allow providing --config to the download script.
This allows flexible configuration of the additional exchange properties (like `ccxt_async_config` - which by default does not work with kraken as it get's you blocked after 3-5 requests.
This way, a configuration working for regular bot operations does also work to download pairs.
Configuration values override `--exchange` - which is also mentioned in the help.
=> Download data config

docs/installation.md
Solve the issue: #1432 
- Add `libffi-dev` as an additional package to install before process installation with `pip`.
- Add recommendation to use (mini)conda and remove package `scipy`, `pandas`, and `numpy` from `requrements.txt`.
Solve error build on Raspbian because it needs additional package `libffi-dev` before installation.
=> Update installation reference for Raspbian

scripts/download_backtest_data.py
Fix problem when using download-script with `--config ` in combination of `--pairlist` with different stake currency.
Stake-currency is not relevant for downloading pairs.
=> Reset stake-currency when using config to download pairs

freqtrade/data/history.py, freqtrade/misc.py, freqtrade/tests/data/test_history.py, freqtrade/tests/test_misc.py, requirements.txt, setup.py
This will replace `ujson` with `rapidjson`.
Writing files to disk does also take a long time with the regular json module (updating 5m historic data (~5m) does take multiple seconds to write to disk (longer than downloading 1 days of data).
Writing with ujson however concerns me (see below for reasons). Rapidjson does offer similar performance, while beeing maintained and supported.
* replace `ujson` with `rapidjson`
* use rapidjson for writing as well (speeds up download script / `backtesting --refresh-pairs-cached`)
* Writing with rapidjson (or ujson) does create files without whitespace, which however is fine for our usecase as it keeps files smaller.
* ujson is unmaintained (last release was 2 years ago)
* github repository abandoned
* unresponsive in their issues 
* no wheel builds …
=> Replace ujson with rapidjson

freqtrade/wallets.py
Wallet named tuple is defined twice - which is not needed and does not make sense.
=> Remove unused and duplicate datastructure

docs/bot-optimization.md, freqtrade/optimize/backtesting.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_interface.py
Sequence of keys in min_roi should matter, if 0:0.1 is first or last should produce the same output.
After failing on this I think this needs fixing.
- add test to verify sequence does not matter
- fix code to actually do this
- clarify documentation (hopefully)
=> minroi sequence of keys should not matter

freqtrade/configuration.py, freqtrade/data/history.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_edge_cli.py, freqtrade/tests/test_configuration.py
* Fix bug when `--refresh-pairs-cached` is used that no data is loaded (it's downloaded but only loaded on the next retry.
* Create datadir if it doesn't exist without (almost silently) failing.
Erroneous log: (data downloaded, but not loaded)
```2019-01-01 13:40:01,786 - freqtrade.data.history - INFO - Download data for all pairs and store them in user_data/bittrex2
2019-01-01 13:40:01,786 - freqtrade.data.history - INFO - Download the pair: "TNT/BTC", Interval: 5m
2019-01-01 13:40:02,643 - freqtrade.exchange - INFO - downloaded TNT/BTC with length 9080.
2019-01-01 13:40:02,644 - freqtrade.misc - INFO - dumping json to "user_data/bittrex2/TNT_BTC-5m.json"
2019-01-01 13:40:02,694 - freqtrade.data.history - WARNING - No data for pair: "TNT/BTC", Interval: 5m. Use --refresh-pairs-cached to …
```
=> Fix bug on --refresh-pairs-cached

freqtrade/strategy/interface.py, freqtrade/tests/test_freqtradebot.py
Fix an issue pointed out on slack, where stoploss does not show the correct stop-loss reason when trailing stoploss is active.
- Do only overwrite stoploss reason when necessary
- Fix test to show positive movement - otherwise it's not a trailnig stoploss.
=> Stop loss should also be shown when trailing is active

freqtrade/data/converter.py, freqtrade/data/history.py, freqtrade/exchange/__init__.py, freqtrade/optimize/backtesting.py, freqtrade/tests/conftest.py, freqtrade/tests/data/test_converter.py, freqtrade/tests/edge/test_edge.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/optimize/test_optimize.py, freqtrade/tests/strategy/test_default_strategy.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_misc.py
Interpolate missing data we get from exchange.
This is not that problematic for many exchanges (binance does fill up unless the exchange is down) - however it's problematic for others (bittrex and potentially all others).
ccxt does return sparse arrays (source: https://github.com/ccxt/ccxt/issues/3254)
Having missing values is dangerous, as TA-lib (and other indicators) do not know about it, and will modify indicators, eventually (probably) against you.
Fixes #39 
* Volume will be 0
* Close price will be forwardfilled (ffill)
* "open", "high", "low" will be populated with close-price of that candle. 
This will result in candles looking as follows (the one below cursor)
workings on a dataframe
=> interpolate missing candles

docs/configuration.md, docs/stoploss.md, freqtrade/resolvers/strategy_resolver.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_strategy.py, user_data/strategies/test_strategy.py
Allow configuration of trailing_stop attributes in strategy
- Allow configuration of trailing_stop attributes in strategy
- output summary of strategy attributes so it's clear which value is used
- simplify code by some refactoring ...
```
2019-01-05 07:25:17,073 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 1}
2019-01-05 07:25:17,073 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2019-01-05 07:25:17,073 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
2019-01-05 07:25:17,073 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2019-01-05 07:25:17,073 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.015
2019-01-05 …
```
=> trailing stoploss configuration in strategy

setup.sh
Fixes install script
Solve the issue: #1451
- show message if neither python3.6 nor 3.7 is found
- don't use `--quiet` on pip install - it's more verbose but shows errors.
- add numpy before `pip install -r requirements.txt` to fix `py_find_1st` installation problems.
- skip installation of ta-lib if ta-lib is already installed.
=> fix and improve installation script

docs/configuration.md, freqtrade/configuration.py, freqtrade/edge/__init__.py, freqtrade/tests/test_configuration.py
Providing `db_url` from config.json is ignored. I also added a test, I don't know if is the right way to test it (it's my first python test) so I'm welcome for suggestions.
Moreover I fixed an error log when Edge is enabled and `max_open_trades=-1`
- removed default setting for db_url 
- fix if condition according to https://github.com/freqtrade/freqtrade/blob/b731973c7af3b705f91477fcc467255f1d1cefdb/freqtrade/configuration.py#L146
=>  Fix custom db_url ignored if provided by conf.json

docs/edge.md
Error in the formula of winRate in edge documentation
- Update the winRate formula in docs/edge.md section WinRate
=> Win rate formula was wrong in edge doc (but not the definition)

.travis.yml, requirements-dev.txt
To fix the issue appeared in #1493 - we should pin the dependencies in requirements-dev.txt.
I'm keeping pytest-random-order intentionally out of this as the requirements-dev.txt is used to install on a dev-pc - and pytest-random-order makes working on new tests sometimes cumbersome, so everyone should choose for themselfs if installing it or not.
Solve the issue: #1493
=> Remove unversioned install of most dev packages

freqtrade/constants.py
from boolean to number
BUGFIX:
Invalid configuration. See config.json.example. Reason: 60 is not of type 'boolean'
Failed validating 'type' in schema['properties']['order_types']['properties']['stoploss_on_exchange_interval']:
{'type': 'boolean'}
On instance['order_types']['stoploss_on_exchange_interval']:
60
=> fix stoploss_on_exchange_interval type

freqtrade/exchange/__init__.py, freqtrade/tests/exchange/test_exchange.py
Prevent crash when unexpected results are returned from an exchange
Solve the issue: #1491
- don't unzip directly - also exceptions can be returned from the async method
- check and log exceptions
=> Fix typeerror when fetching candles

docs/bot-optimization.md
Persisting data in a strategy can be accomplished easily within the strategy itself.
The data will not be persisted across bot restarts, however, the strategy is only instantiated once per bot so storing data in a local dict will work perfectly fine, and is an easy way for users to keep simple information (counters, ...).
Solve the issue: #1192
=> Add information about dataframe

docs/backtesting.md, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py
Address the issue #1497. I've opted to add a column due to number formatting of the tabulate function.
The `tot profit %` column represents the % of `tot profit BTC` relative to `stake_amount * max_open_trades`.
- added total profit % column
=> Added total profit column to backtest result

docs/bot-optimization.md, freqtrade/configuration.py, freqtrade/data/dataprovider.py, freqtrade/dataprovider.py, freqtrade/exchange/__init__.py, freqtrade/freqtradebot.py, freqtrade/main.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/edge_cli.py, freqtrade/optimize/hyperopt.py, freqtrade/resolvers/strategy_resolver.py, freqtrade/state.py, freqtrade/strategy/default_strategy.py, freqtrade/strategy/interface.py, freqtrade/tests/data/test_dataprovider.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_edge_cli.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_freqtradebot.py, scripts/plot_dataframe.py, scripts/plot_profit.py, user_data/strategies/test_strategy.py
This is the dataprovider, which provides strategy (and the bot overall) with data from the exchange.
Solves part of the issue #1335
=> Data Provider

docs/configuration.md, freqtrade/resolvers/strategy_resolver.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_strategy.py, user_data/strategies/test_strategy.py
Add experimental settings to strategy - as it's almost exclusively strategy-dependant if the sell-signal makes sense or not.
* Drop mandatory column in the documentation hoping that this will make this table simpler to read.
=> add more settings to strategy

freqtrade/data/converter.py
Some exchanges (BitMEX) return integer values for Volume field. And sometimes even for OHLC -- same, on BitMEX, since price decrease is 0.5. TA-LIB functions assume floats and fail with exception.
Of course, this can be fixed (converted) in ccxt for particular exchange, but TA-LIB will still fail for exchanges for that such a conversion is not implemented in ccxt code. So let's make perform this conversion here in order to be sure our strategy will not crash on a new exchange.
=> OHLCV should be float for TA-LIB indicators in the strategy

freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
Output stake_amount as it is defined in the config (it may be int) instead of float. In order to avoid unnecessary questions where and why it was converted to float and changed in the last digit while it should be integer for the exchange...
Other small cosmetic improvements to logging in freqtradebot.py
=> Cosmetic: fix logging

freqtrade/freqtradebot.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_interface.py
* "30 seconds" was errorneously hardcoded in the text of the log message, while actually it's RETRY_TIMEOUT which may differ
=> logs: cosmetic changes

freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
This PR corresponds to:
https://github.com/freqtrade/freqtrade/issues/1377#issue-386200394
by @mishaker in understanding that a ticker is mostly a statistical thing, but on the other side, create_trade/execute_buy.
It resolves problem with some exchanges (BitMex) where ticker structure returned by ccxt does not contain bid and ask values.
1. On exchanges like Bitmex, set use_order_book: true for buys. FT won't request ticker and will use data from order book only.
2. On exchanges where order book is not available, set use_order_book: false, ticker data (including ask/last balance logic) will be used.
3. On other exchanges, either approach may be used in the config.
Performance: current implementation fetches ticker every time even if order book data will be later used. With this change …
=> execute_buy, handle_trade: do not use ticker if use_order_book:true is set in config

freqtrade/constants.py, freqtrade/freqtradebot.py
Default value should not be hardcoded somewhere deep in the code.
=> Cosmetic: move default amount_reserve_percent value into constants

.travis.yml
Move coveralls to "after_success" since an external service should not break our builds
based on the idea from the coveralls issue: 
https://github.com/lemurheavy/coveralls-public/issues/1264#issuecomment-465257524
We should also investigate if switching to codecov (https://codecov.io/) is worth the effort, since this is not the first time coveralls has a multi-day problem.
=> Move coveralls to after_success

docs/installation.md
During docker built on windows if in  global git config  core.autocrlf = true then when have this message :
Step 6/12 : RUN cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*
---> Running in c0a626821132
/tmp/install_ta-lib.sh: 4: /tmp/install_ta-lib.sh: Syntax error: "&&" unexpected
this behave is because file is in the wrong line ending format
Has script files run on linux they need to use LF lines ending so we need to ensure they are not converted to CRLF lines ending if global git config is at  core.autocrlf = true.
Fix built of docker image if git global config is core.autocrlf = …
=> prevent convert LF->CRLF line ending on window

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/misc.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_main.py, scripts/download_backtest_data.py
* Support for multiple --config options in the FT command line
* Default config filename value moved to constants
* Cosmetic grammar changes (as always :-) ) in the options help strings
One can use it, for example, for keeping keys and exchange secrets in the separate config files in order to avoid their disclosure by mistake.
For example:
config.json:
```
{
...
"exchange": {
"name": "exchangename",
"key": "",
"secret": "",
...
},
...
}
```
keys-exchangename.json:
```
{
"exchange": {
"name": "exchangename",
"key": "mysecretkeyhere",
"secret": "mysecretesecretehere"
}
}
```
Then running `freqtrade --config=config.json` or simply `freqtrade` (with default config) will launch bot with empty keys while `freqtrade --config=config.json --config=keys-exchangename.json` will fetch keys from the …
=> multiple --config options

freqtrade/exchange/__init__.py, freqtrade/exchange/binance.py, freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py
* Add binance subclass
* Add parametrized tests to make sure subclasses don't break regular behavior
* Add simple "ft_has" dictionary (for now it needs to be copied to all subclasses which need to change something)
It's not perfect yet (i'm not certain if stoploss_on_exchange like this works for other exchanges), but i'm hesitent to move it to the binance-class since it might work for other exchanges as well.
The volume of tests significantly raises with this, since all available subclasses (+ one non-available subclass) are tested with most functions. Mostly the results would not change - but this should allow to easily verify new subclass implementations which do override complete methods.
=> Create binance Subclass and parametrize exchange-tests

Dockerfile
Add libssl-dev to have cryptography compile again.
Solve the issue: #1604
=> Add libssl-dev to fix #1604

README.md, docs/bot-usage.md, docs/hyperopt.md, freqtrade/arguments.py, freqtrade/configuration.py
As pointed out on Slack, the documentation for hyperopt is wrong.
The parameter was never called `--hyperopt` but `--customhyperopt`.
- fix documentation to call hyperopt with custom file
- move parameter from before "hyperopt" to after "hyperopt" - since it's a parameter only used by hyperopt.
=> Update documentation for --customhyperopt

docs/bot-usage.md, docs/configuration.md, docs/deprecated.md, mkdocs.yml
* typo in the main site menu fixed
* description of the deprecated --dynamic-pairlist moved out of bot-usage.md to new deprecated.md in order to make bot-usage.md clear of description of deprecations.
* various improvements to configuration.md (review it carefully; I started with changing the section on PirList method but finally... what you see...)
=> Documentation cleanup

freqtrade.service
Deprecated --dynamic-whitelist is still used in the freqtrade service configuration file.
=> Remove deprecated --dynamic-whitelist from freqtrade.service

freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py
Fixes a bug where bots in dry-run mode are unable to buy/sell, because the order-side is always buy (hardcoded).
Solve the issue: #1637
=> Fix broken dry-mode sells 

freqtrade/rpc/rpc_manager.py
Show more information on telegram - stoploss is an important part and should be verified before running the bot. This should simplify that by screaming it at you ...
- Shows either Stoploss - or Trailing stoploss 
*note to self: change this stoploss, it's way to high*
=> Add stoploss to startup messages

freqtrade/resolvers/iresolver.py
Don't fail but skip if a strategy is present which requires modules that are not installed.
Observed:
```
2019-03-11 19:35:45,187 - freqtrade - ERROR - Fatal exception!
File "/home/xmatt/development/freqtrade/freqtrade/main.py", line 45, in main
freqtrade = FreqtradeBot(config)
File "/home/xmatt/development/freqtrade/freqtrade/freqtradebot.py", line 54, in __init__
self.strategy: IStrategy = StrategyResolver(self.config).strategy
File "/home/xmatt/development/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 40, in __init__
extra_dir=config.get('strategy_path'))
File "/home/xmatt/development/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 150, in _load_strategy
object_name=strategy_name, kwargs={'config': config})
File …
```
=> Catch ModuleNotFoundError when importing external code

freqtrade/freqtradebot.py, freqtrade/persistence.py, freqtrade/rpc/rpc_manager.py, freqtrade/tests/test_freqtradebot.py
Notifications should be sent when stoploss_on_exchange is hit.
Solve the issue: #1653
- create notify_sell (extracted from regular sell function
- Send notification on "stoploss on exchange"
=> send notification when stoploss_on_exchange is hit

config_full.json.example, docs/configuration.md, freqtrade/constants.py, freqtrade/exchange/exchange.py, freqtrade/freqtradebot.py, freqtrade/pairlist/IPairList.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/pairlist/test_pairlist.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py, freqtrade/tests/test_freqtradebot.py
See #1554 and #1614. Basically, the already loaded markets from the api are used, instead of fetching markets each time.
- Change `exchange._api.markets` to `exchange.markets`
- Change `exchange.get_markets` to return `exchange.markets` as list
- Change all functions that call `get_markets` to access `exchange.markets` instead
- Add `exchange.markets` property
- Change markets in `conftest` to return as dict
> That would be enough to implement ccxt.fetchMarket() --> ccxt.loadMarkets() transition everywhere in the bot, that would have similar effect, agree.
Only that instead of loading the markets on each call, the loaded `exchange.markets` property is used. The only thing missing is a regular refreshing mechanism that calls `_api.load_markets`. This could be set in config, as @hroff-1902 …
=> Markets refactor

docs/configuration.md, freqtrade/resolvers/strategy_resolver.py
As raised in #1633, minimal_roi is not really optional, even if that's stated in the documentaiton.
Fixes #1633 
- default to 1000%  `{"0": 10}`
- Document this behaviour
=> Default value for minimal_roi

freqtrade/resolvers/iresolver.py
Solve the issue - raised on slack
- Catch Syntax error
- Use Warn not Info as log level - since this could lead to problems if the strategy to load causes the exception.
``` 
root@vmanager6003:~/freqtrade# source .env/bin/activate; python ./freqtrade/main.py -s APstrat1 backtesting
2019-03-14 21:20:18,133 - freqtrade.configuration - INFO - Verbosity set to 0
2019-03-14 21:20:18,134 - freqtrade.configuration - INFO - Dry run is disabled
2019-03-14 21:20:18,134 - freqtrade.configuration - INFO - Using DB: "sqlite:///tradesv3.prodrun.sqlite"
2019-03-14 21:20:18,134 - freqtrade.configuration - INFO - Using max_open_trades: 3 ...
2019-03-14 21:20:18,134 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2019-03-14 …
```
=> Catch syntaxerror on import

config_full.json.example, docs/configuration.md, docs/stoploss.md, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/exchange/exchange.py, freqtrade/resolvers/strategy_resolver.py, freqtrade/strategy/interface.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_freqtradebot.py
This will permit to activate trailing stoploss only if the offset is reached. So basically only the part of the trailing stoploss after offset will be used.
=> Adding an option for trailing stoploss: "trailing_only_offset_is_reached"

docs/bot-usage.md, docs/configuration.md, docs/installation.md, freqtrade.service.watchdog, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/constants.py, freqtrade/freqtradebot.py, freqtrade/main.py, requirements.txt
This PR contains simple and effective watchdog capability using systemd manager as watchdog for the bot when the bot is run as a systemd service. Implemented via sd_notify protocol.
Works brilliant to me. Respawns the bot if it's killed, does not leave any zombies, even if freqtrade is run as a service with additional shell script wrapper and changes the PID of the process thus...
* New `internals.sd_notify` config parameter and the `--sd-notify` command line option are added. Any of those can be used to enable systemd notifications. Descriptions included in the docs.
* I did not get if the reloading of the configuration is currently implemented in the bot. Appropriate sd_notify message can be added additionaly for reloading of the configuration in a proper place.
* Current bot's state …
=> Support for systemd watchdog

docs/telegram-usage.md, freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
Add `/stopbuy` signal to stop the bot from buying new asseets, but close off open trades gracefully.
Solve the issue: #1607 
- Documentation
- /forcebuy command
- /forcebuy tests
=> Telegram `/stopbuy`

freqtrade/freqtradebot.py, freqtrade/rpc/rpc.py, freqtrade/tests/test_freqtradebot.py
get_ticker is not updating when orderbook is enabled since it's never called.
extacted the get_ticker logic (using [bid] ...) to a separate function which is called from RPC.
Solve the issue: #1658
- Reenable updates when orderbook asks  is on
*note*: before using this, read the outcome of #1667  - I may have discovered a bug in the orderbook ask logic.
=> No telegram rate updates when orderbook is enabled

freqtrade/constants.py, freqtrade/exchange/exchange.py, freqtrade/freqtradebot.py, freqtrade/tests/test_wallets.py, freqtrade/wallets.py
Wallet and Wallets:
* Default amount 999.9 for Dry Run moved to constants.
* New configuration option `dry_run_wallet` added which allows for a user to override this default value for her Dry Run if it's needed for some reasons.
* a string member with exchange name removed from Wallet -- not used.
* _config field added into Wallets, Wallets no longer access corresponding private member from Exchange.
* wallets --> _wallets 'cause it's a private member.
* cosmetic adjustment to the log message (as usual ;-) ).
* tests adjusted accordingly.
Exchange:
* _conf --> _config as in (almost) all other classes in the codebase in order to make grepping for appearances of config more comfortable.
TODO (if the PR is accepted):
* description in the docs for the new configuration option …
=> Minor: Wallet and exchange cleanup

docs/configuration.md
Docs added for the new configuration parameter, `dry_run_wallet`.
=> docs for dry_run_wallet

freqtrade/exchange/exchange.py, freqtrade/pairlist/IPairList.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/pairlist/test_pairlist.py
Loop over whitelist only instead of all market pairs in `ipairlist._validate_whitelist` and (potentially) replace `exchange.validate_pairs`.
Solve the issue: #1622
- change `ipairlist._validate_whitelist` to loop over whitelist instead of markets. Also combine stake currency check with main validation.
- change `exchange.validate_pairs` to check only whether pair is in loaded markets
I've mainly combined the conditions in `_validate_whitelist` which brings a significant performance improvement as can be seen below:
I haven't removed `exchange.validate_pairs` yet, as I'd like to get your input.. As I wrote in #1622, that check is basically unnecessary, since the whitelist gets validated by `ipairlist` anyways.. However, it's only executed once when the exchange is initialised. So not too …
=> validate whitelist vs. validate pairs

docs/bot-optimization.md, docs/hyperopt.md, docs/installation.md, docs/sql_cheatsheet.md, docs/telegram-usage.md
Some of our documentation "boxes" have a syntax-error, causing them to not render:
Sample:
=> Fix Documentation Boxes

.travis.yml, docs/backtesting.md, docs/bot-optimization.md, docs/bot-usage.md, docs/deprecated.md, docs/edge.md, docs/faq.md, docs/hyperopt.md, docs/installation.md, setup.sh
The documentation should reflect the correct way to run freqtrade.
As we've seen in #1521, using `python3 freqtrade/main.py ...` can result in odd behaviours.
Since freqtrade needs to be installed, we can call it by using `python freqtrade`.
This implements this on both the documentation and travis, so we know this way is and keeps working.
Solve the issue: #1521
=> Update documentation with correct way of calling

docs/bot-optimization.md, docs/configuration.md, freqtrade/resolvers/strategy_resolver.py, freqtrade/tests/strategy/test_strategy.py
This allows users to use `self.stake_currency` within the strategy.
It's more convenient than `self.config["stake_currency"]`.
Also fixes a typo / error in the documentation for dataprovider.
=> Add stake_currency to strategy, fix  documentation typo

docs/telegram-usage.md, freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/conftest.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
add `/blacklist` and `/blacklist <pair>` calls to rpc / telegram
Solve the issue: #1625
- `/blacklist` -> outputs current blacklist
- `/blacklist PAIR` -> adds pair to current blacklist
- add documentation for /whitelist and /blacklist.
=> add pairs to blacklist dynamically

freqtrade/rpc/rpc.py
As discussed in #1697 - adding a check if the pair is in stake currency.
Also, we should not blindly add pairs multiple times.
=> Check if added pair has correct stake-currency

docs/bot-optimization.md, freqtrade/optimize/backtesting.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/test_freqtradebot.py
Provide dataprovider also during backtesting.
Final fix for #1669, part of #1335
- Add dataprovider during backtest and hyperopt
- update documentation to state so
- add tests checking dataprovider is actually added to the class
=> Dataprovider during backtesting

config_full.json.example
Fix typos in example_full.json - it serves an example - and should be correct.
=> fix typos in full_json_example

README.md, docs/bot-usage.md, docs/configuration.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/tests/test_configuration.py
Add logging to file as an option.
Also change standard-logging to stdout instead of stderr, to allow easier handling when piping the output to something else.
Solve the issue: multiple questions on Slack
- log to stdout
- additionally log to rotating file (10 files, 1M each).
=> Allow logging to file

docs/bot-usage.md, docs/telegram-usage.md, freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
- Adds percentage in front of stoploss and (if initial stoploss is different from stoploss) in front of initial stoploss: 
- Documentation added for telegram
- Some refactoring on telegram documentation (carriage return) 
- Fixed a broken link to configuration.md in docs
=> Added percentage to telegram messages + documentation

freqtrade/optimize/backtesting.py, freqtrade/tests/edge/test_edge.py, freqtrade/tests/optimize/__init__.py, freqtrade/tests/optimize/test_backtesting.py
This PR should fix the backtest with partial data, that can cause a number of open trades greater than `max_open_trades` and therefore wrong results. It's a proposal to be discussed.
Solve the issue: #1624 (all details present here).
Required for #1559.
- added a dedicated index for every pair
- skipped pairs that have a future start date
=> Fix backtest problem with partial data

docs/telegram-usage.md, docs/webhook-config.md, mkdocs.yml
Improve and fix documentation regarding webhooks.
I also added a subsection for "control the bot". 
I would like this section to be non-collapsible, but didn't find a way to prevent this - i assume it's part of the theme, but maybe it can be disabled? 
@mishaker , would you mind giving me a hand on this?
built documentation for this is here:
https://www.freqtrade.io/en/doc-simplify/
*note*: the readthedocs build for this should be disabled once this is merged.
=> Improve documentation formatting

freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py
rpc_count should not return open trades, but a summary of counts.
- Move calculation to `rpc.py`
=> rpc Count should be in rpc.py

freqtrade/constants.py, freqtrade/data/converter.py, freqtrade/data/history.py, freqtrade/exchange/exchange.py, freqtrade/freqtradebot.py, freqtrade/misc.py, freqtrade/optimize/backtesting.py, freqtrade/strategy/interface.py, freqtrade/tests/optimize/__init__.py, freqtrade/tests/optimize/test_optimize.py, scripts/plot_profit.py
This PR gets rid of TICKER_INTERVAL_MINUTES dict, uses ccxt's parse_timeframe() instead.
Resolves #1137.
Later, in a separate refactoring PR, a single function can be implemented and used, which returns an arrow object, for example.
=> Resolution for #1137

freqtrade/data/dataprovider.py, freqtrade/data/history.py, freqtrade/exchange/exchange.py, freqtrade/tests/data/test_dataprovider.py, freqtrade/tests/data/test_history.py, freqtrade/tests/exchange/test_exchange.py, scripts/download_backtest_data.py, scripts/plot_dataframe.py, scripts/plot_profit.py
As promised, issued in a separate PR.
Renaming of parameters and vars containing timeframe values to be more uniform.
In order to simplify grepping for var with timeframe values.
Single exclusion: I did not rename the `interval` parameter in the strategy interface `get_signal()` to prevent breaking the strategy interfaces for existing custom strategies.
=> cosmetic: rename interval, tick_interval, etc --> ticker_interval

docs/configuration.md, docs/faq.md
in faq.md:
* Titles render wrong both in the docs dir and at freqtrade.io.
* Last list of links renders wrong at freqtrade.io.
* Small cosmetic changes.
in configuration.md:
* Order of items in the table fixed.
=> Docs: wrong rendering at freqtrade.io fixed

scripts/download_backtest_data.py, scripts/get_market_pairs.py
Minor impovements to the argument and exception handling in the scripts/get_market_pairs.py utility script:
* Do not raise IndexError if no exchange was specified in the command line, dump gracefully the usage string and exit with status code = 1.
* Dump traceback in case of exception.
* Exit with status code = 1 in case of exception.
P.S. Did not want to create another branch, committed here, minor changes in scripts/download_backtest_data.py:
* Fixed message (it printed out '%s').
* Cosmetic changes in the code.
=> Minor: impoved argument and exception handling in scripts

freqtrade/resolvers/strategy_resolver.py, freqtrade/tests/strategy/test_strategy.py
Gracefully handle pickle-errors when @staticmethod is used
pointed out in https://github.com/freqtrade/freqtrade-strategies/issues/28
We should handle this error gracefully... crashing is never good.
=> Gracefully handle pickle-errors when @staticmethod is used

config.json.example, config_binance.json.example, config_full.json.example, docs/configuration.md, freqtrade/configuration.py, freqtrade/exchange/exchange.py, freqtrade/tests/test_configuration.py, scripts/download_backtest_data.py
Enable rate-limit by default so new users don't encounter bans and document this behaviour.
Resolves #1764
- Enable rate-limit by default 
- Add documentation for this parameter
- remove deprecated parameter for setting rate-limit.
=> Enable ratelimit

freqtrade/configuration.py, freqtrade/data/converter.py, freqtrade/data/history.py, freqtrade/exchange/__init__.py, freqtrade/exchange/exchange.py, freqtrade/freqtradebot.py, freqtrade/misc.py, freqtrade/optimize/backtesting.py, freqtrade/strategy/__init__.py, freqtrade/strategy/interface.py, freqtrade/tests/optimize/__init__.py, freqtrade/tests/optimize/test_optimize.py, scripts/get_market_pairs.py, scripts/plot_profit.py
This PR limits usage (import) of ccxt to the freqtrade/exchange module only, for better incapsulation and isolation of the features.
=> minor: limit usage of ccxt to freqtrade/exchange only

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/hyperopt.py
This option allows to see all results found by hyperopt, not only the best ones.
May be usefull for developers and for better understanding the hyperopt results and optimization path.
=> --print-all command line option for hyperopt

freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
The wallets is not syncing after LIMIT_SELL is occured, because the order is fullfilled few instances later after sell methods are called.
This PR tries to solve this problem syncing wallets when trade is updated, that occurs when sell order is closed.
- Added command for Wallets Sync after a trade is closed in "update_trade" method in "freqtradebot" class, this will help the Wallets get updated after a trade is sold and closed, specifically LIMIT_SELL trades, then bot can work properly with new trades.
Previously without this fix, the log of bot show this scenario:
```
2019-04-19 21:53:34,307 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=4, pair=EVX/BTC, amount=20.00000000, open_rate=0.00014879, open_since=an hour ago)
2019-04-19 21:53:35,177 - freqtrade.persistence - …
```
=> Wallet Sync fix after any trade is closed

docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/data/history.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/data/test_history.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py
A part of #1775.
Current bahaviour is non-logical: a user who optimizes parameters with hyperopt is asked to run the bot with the --refresh-pairs-cached, but it's not available for the hyperopt command. She needs to run backtesting or edge command just due to this deficiency in the implementation.
Since hyperopt class is inherited from backtesting, it already has an initialized instance of exchange class inside self (not used in hyperopt and later set to None in hyperopt start()). We can use it to download refreshed data before it's set to None.
* --refresh-pairs-cached is now a common option for all optimization bot commands;
* The message changed, now it suggests to run the script in addition to stating this option;
* Tests for hyperopt added. adopted from backtesting;
* …
=> hyperopt: --refresh-pairs-cached added

freqtrade/optimize/hyperopt.py
A part of #1775.
Run the bot with the `-v` command line option to see the data.
Internal optimizer state and the points from the hyperspace ('params' in result dict) are printed in different loops since they have (may have) different order.
=> hyperopt: print optimizer state in debug log messages

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/hyperopt.py
A part of #1775.
This new parameter allows to pass a value for the random_state argument of the skopt optimizer to get reproducible optimization path.
Use it defining any positive integer value, for example:
```
python freqtrade hyperopt --random-state=33
```
Non-integer AND zero are invalid and rejected.
The check_int_positive() method was added to the Arguments class, which validates the parameter value at early stage. Can further be used in freqtrade/arguments.py for validation of other integer parameters where a positive value is expected.
=> hyperopt: --random-state for optimizer to get reproducible results

docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
A part of #1775.
This option allows to control the number of the joblib.parallel worker processes used in the hyperopt.
If set to -1 (default), all CPUs are used (joblib parallel backend determines the number of the worker processes automatically), for -2, all CPUs but one are used, etc. If 1 is given, no parallel computing code is used at all.
Needs to be tested additionally on Windows and on VPS or virtual machines with 1 CPU. Please verify the solution in these conditions before merge.
* Docs adjusted as well. No tests added.
* As an additional minor cosmetics, redundant comments that do not apply any additional useful information but require attention while copying/extending options were removed from freqtrade/configuration.py
=> hyperopt: -j/--job-workers command line option added

requirements-pi.txt, requirements.txt
Fix CI failures (https://travis-ci.org/freqtrade/freqtrade/jobs/523902109).
Upgrading urllib3 is blocked by https://github.com/kennethreitz/requests/pull/5063
- fix version mismatch until requests is upgraded
- cleanup requirements - every requirement should be there only once
=> Downgrade urllib3, cleanup requirements files

freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py
We should catch network-errors from the exchange for regular calls.
Resolves #1789
- Catch errors and log them as exception
- Should prevent the bot from crashing regularily.
=> Catch errors on reload_markets

freqtrade/tests/test_main.py
As promised in #1815,
This should be covered very carefully in tests - and the previous test did not contain a complete flow of this function.
=> Improve test for reload_conf with a "realistic" workflow

freqtrade/optimize/hyperopt.py, requirements-pi.txt
Set and check the lock.
Inspired by #1803.
A universal approach (py-filelock) was choosen because a custom one with fcntl/flock is 1) platform specific, 2) a lock set on the results pickle file can persist in case the app was killed in the middle. Can be problematic for an inexperienced user to remove the lock.
* I tested it with graceful hyperopt exit, `Ctrl+C`, `kill` and `kill -9` (Ubuntu).
* @xmatthias, you can adjust the log messages if you wish.
* Please test it on Windows.
* A test for it should probably be added. Too complicated for me, I'm still not quite familiar with all that mocking stuff...
* Docs should mention it somehow if recently added sentence about multiple Heperopts does not suffice.
* TODO (sep. PR, future): start() for Backtesting, Edge and Hyperopt should return …
=> prevent hyperopt from running multiple instances simultaneously

freqtrade/rpc/rpc.py, freqtrade/rpc/telegram.py, freqtrade/tests/rpc/test_rpc.py
This will return the status of the rpc forcesell call
Currently, when you forcesell, the only feedback you get is once the order is filled.
This may be immediately, but it could also be delayed if the limit-sell order is not filled.
This is dangerous as i tend to make typos on the phone, and having immediate feedback if it worked should improve usability.
=> immediately confirm forcesell

freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
Usage:
freqtrade hyperopt --min-trades=N
This enhancement allows to mark hyperopt evaluations with number of trades less then N as 'bad', i.e. assigns them the maximal loss value. 
It helps optimization process to not descend in the hyperspace to points with 1 successfull trade and to not start optimizing around it as a local minimum of the target (loss) function. 
We don't have to and usually don't wish to optimize 'hodl' strategies indeed. 😃 
Now, in the current develop implementation, only points in the hyperspace (evaluations) that contain no trades are considered as such 'bad' points. With the default hyperopt, it (almost) always starts optimizing around a point with a single successful trade after several hundreds of evals (epochs)...
How to see difference: compare output (notice …
=> hyperopt --min-trades parameter

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
A set of small improvements to hyperopt:
* Calculation of Avg Profit corrected: it no longer is multiplied by 100 so that
SumProfit% = N_trades * Avg Profit%
* The precision and the length of this printed field adjusted correspondingly.
* Number of initial random points (30) made a named constant. Later (diff. PR) should be adjustable (bigger for long optimization runs)
* A special marker sign ('*') is printed at the begining of the line with results for first N initial points. In order to distinguish random points of the rest in the optimization path. Maybe this should be printed only in the print-all mode, now is printed when no --print-all option was specified as well...
* A redundant dot in the output (noisy double dot after 'mins') removed
* A redundant empty line in the output …
=> minor: hyperopt output improvements

.pyup.yml
Only update pyup once per week.
I don't think we care about the weekday, so i've not explicitly configured that - but we could if we don't like the day we get randomly.
Solves #1849
=> Update pyup only weekly

freqtrade/optimize/backtesting.py, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_hyperopt.py
* Verification of the loaded ticker data. Taken and slightly adapted from backtesting part.
* Log time interval (min_date, max_date, duration) used for backtesting.
* New test for no data case added.
Part of #1775.
=> Minor: hyperopt verify ticker data

freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
Getting the balance for some currencies (EUR / USD) needs to invert the pair.
Fixes: #1840
- Add EUR and USD to the inverted pairs
=> Fix #1840 - Support balances other than USDT

freqtrade/__init__.py
https://docs.python.org/3/library/exceptions.html#BaseException:
> exception BaseException ... It is not meant to be directly inherited by user-defined classes (for that, use Exception).
https://docs.python.org/3/library/exceptions.html#built-in-exceptions
> programmers are encouraged to derive new exceptions from the Exception class or one of its subclasses, and not from BaseException.
In one of the next PRs I'll show why this has actually sence for freqtrade codebase.
In RPC module, for example, the RPCException is inherited from Exception, which is correct.
=> minor: inherit freqtrade exceptions from Exception instead of BaseException

freqtrade/data/history.py, freqtrade/tests/data/test_history.py
* the check for empty exchange parameter moved from load_pair_history() to download_pair_history() -- it's more correct place for it since download_pair_history() is called separately in the freqtrade codebase.
* wording in a comment.
* wording in log message ("No data for pair:" --> "No history data for pair:").
* wording in log message ("Download the pair:" --> "Download history data for pair:").
* tests adjusted to reflect changes in the log messages.
* the datadir logging also moved to that log message i.o. being a separate log message in load_pair_history().
* `except BaseException` changed to `except Exception`. That's what I kept in mind stating in #1859 ("...has actually sence for freqtrade codebase.").
Currently, this function catches BaseException, including KeyboardInterrupt. …
=> minor: data/history cleanup

freqtrade/persistence.py
,,,in the persistence module
How to reproduce: run
```
python3 freqtrade -v backtesting
```
The log is filled with noisy message "Adjusting min/max rates", which is printed for every candle for every pair during backtesting and do not provide any useful info.
=> minor: remove noisy useless debug message

freqtrade/edge/__init__.py, freqtrade/optimize/edge_cli.py
When edge calculation produces empty trades list (for instance, if the timerange is too short to contain any trade signals with the strategy used):
* the 'No trades found.' info log message is printed
* the empty edge table is not printed anymore in the edge_cli
How to reproduce:
```
freqtrade --strategy TestStrategy edge -r
```
with `"ticker_interval" : "1d"` in the config (I tested with binance exchange used); clean the exchange datadir before.
Resolves (corrects behaviour) #1869
=> edge: handle properly the 'No trades' case

docs/hyperopt.md, freqtrade/optimize/default_hyperopt.py, user_data/hyperopts/sample_hyperopt.py
Resolves the problem reported in #1872.
If for any reason -- wide hyperoptimization parameters space when it contains many points with no trades, short timerange which does not fit any trades, inactive pairs in the whitelist, unlucky point in the optimization hyperspace or simply a buggy strategy defined in the custom (or even default) hyperopt -- if for any reason the `conditions` list defined in the populate_buy_trend() and in populate_sell_trend() (those inside buy_strategy_generator() and sell_strategy_generator() respectively) is empty, the bot crashes with the following exception:
```
TypeError: reduce() of empty sequence with no initial value
```
This PR fixes it.
TODO (sep. PR): This PR can be considered as first workaround. Further, exceptions from Backtesting.backtest() should …
=> fix TypeError from reduce() in hyperopts

Dockerfile.technical, README.md, docs/docker.md, docs/index.md, docs/installation.md, docs/telegram-usage.md, mkdocs.yml
This should help to clarify some issues around installation by cleaning up the installation document and moving sections to their respective section (telegram, docker).
It should also explain #1860 - which is solved but undocumented (`/etc/timezone` is only needed for users to see the timestamps in their timezone, but not for bot operations (which uses UTC throughout).
- improve documentation 
- create dedicated page to install with docker
=> Cleanup installation documentation

freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py
DEBUG messages in exchange.py improved:
* one_call msecs humanized (prints humanized time duration after msecs)
* the since_ms datetime humanized (the humanized datetime is printed after timestamp)
* "BTC, 1h since _timestamp_" --> "pair BTC, interval 1h, since _timestamp_ (_humanized datetime_)" because current message can be read as "1 hour since _timestamp_" by a user which is not familiar with the bot internals. Same change in other messages where "BTC, 1h" is printed. Maybe some other similar messages can still be found...
* Tests adjusted to reflect changes in the log messages
How to see both variants of message with humanized since_ms:
```
python3 freqtrade -v backtesting -l
```
-- since_ms is None, prints `DEBUG - Fetching pair XMR/BTC, interval 1h, since None ...` -- same as now; …
=> minor: exchange debug logging humanized

scripts/plot_dataframe.py
Fix the plot-dataframe script when running with exported trades (
`python3 scripts/plot_dataframe.py --export trades --export-filename user_data/backtest_data-Strategy.json`
Solve the issue: (From Slack)
Appearing error (before)
``` 
File "/home/xmatt/.pyenv/versions/trade3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
return self._engine.get_loc(key)
File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in …
```
=> Update plot-script to work with exported trades

bin/freqtrade, freqtrade/__main__.py, freqtrade/arguments.py, freqtrade/main.py, setup.py
Remove the "binary" script we had and replace it with the "entrypoint" logic (which automatically generates an executable file in the installation folder).
- Remove bin/freqtrade helper file
- Rely on setuptools "entrypoint" feature
- All methods of execution i'm aware of still work `python -m freqtrade`, `freqtrade --help` `python freqtrade/main.py --help` ...
In the future, this method would allow us to specify more entry points (ft_download) for the download script, for example.
I'm putting this as proposal since it will break existing "linked" installations (installed with `pip install -e .`) with the following error:
```
File ".../bin/freqtrade", line 6, in <module>
with open(__file__) as f:
FileNotFoundError: [Errno 2] No such file or directory: …
```
=> [proposal] Eliminate bin/freqtrade

freqtrade/data/history.py, freqtrade/optimize/backtesting.py, freqtrade/tests/data/test_history.py, freqtrade/tests/optimize/test_backtesting.py, scripts/plot_dataframe.py
Remove duplication of --live parameter,which is used in backtesting and the plot_dataframe script (don't ask me why `plot_profit.py` does not support this)
it's part of a larger plot_script refactoring - so i'll add support for this later.
=> refactor `--live` handling

freqtrade/freqtradebot.py, freqtrade/persistence.py, freqtrade/tests/test_persistence.py, scripts/plot_dataframe.py
This will simplify the call to persistence.init() by not requiring a configuration dict.
It may not make sense now, but it's an extracted part from a larger refactoring of the plot-scripts (which do REALLY need a lot of love!!)
=> persistence.init does not need the config dict

freqtrade/strategy/interface.py, freqtrade/tests/test_freqtradebot.py
In case of `trailing_only_offset_is_reached` trailing is not active till the price goes beyond the offset.
But if stop is hit before price reached that point then the bot considers it a trailing stoploss which is false:
`if trailing_stop and trade.open_rate != trade.max_rate:` 
Better approach to know if the trailing was the reason is simply to compare initial_stop_loss with stop_loss.
=> Trailing stoploss sell reason fixed.

docs/configuration.md, docs/developer.md, freqtrade/data/converter.py, freqtrade/data/history.py, freqtrade/exchange/exchange.py, freqtrade/misc.py, freqtrade/tests/conftest.py, freqtrade/tests/data/test_converter.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/strategy/test_interface.py
Dropping the last candle should be optional per exchange, since not all exchanges return an incomplete candle (#1912 - huobi does not).
Closes #1715 (general about dropping candles)
closes #1912 (huobi)
closes #1889 (bitfinex)
- Make dropping the last candle optional
- parametrize and merge `_ft_has` dictionary
- start Documentation on how to test a new exchange
- parametrize `ohlcv_candle_limit` (solves step3 of #1196)
=> Make dropping the last candle optional (configured per exchange)

docs/backtesting.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/tests/test_arguments.py, scripts/download_backtest_data.py
This script really needs tests. It took so long time because I was manually testing all the cases where command line options override settings from the config...
* script now reads pair whitelist from the config, if config is specified (resolves #1857)
* --logfile, -v (-vv, -vvv) options added, as in the main freqtrade
* --export changed to --datadir (to be consistent with main freqtrade)
TBD:
* <s>maybe it should load default config if not specified (and the --no-config option be added to work without config at all)</s> Cancelled, see comment below.
TODO:
* <s>bunch of tests for this tool. (Tests!) </s> As a result of conversation with @xmatthias on tests for scripts -- this task is postponed till the scripts are refactored to modules. Not achievable now.
=> refactoring download_backtest_data.py

freqtrade/configuration.py, freqtrade/exchange/__init__.py, freqtrade/exchange/exchange.py, freqtrade/tests/test_configuration.py
Check exchange name against:
* list of 'bad' exchanges, known to have critical problems with the bot. Warns user. Set currently to `['bitmex',]`, extend it if you know of other bad exchanges.
* list of officially supported exchanges (`['binance', 'bittrex']`), Warns user to be careful running the bot if exchange is not in this list.
* list of exchanges, supported by ccxt (i.e. 'known' for the bot). Current behaviour is kept (raises exception if misspelled or not supported by ccxt), wording changed ('supported' --> 'known').
The check_for_bad parameter is left for scripts -- if set to False, it will allow to run the download script for 'bad' exchanges and not to warn the user of it.
TODO:
* a couple of more tests for all cases (know but not officially supported exchange, etc.)
=> Enhance check_exchange()

freqtrade/optimize/edge_cli.py, freqtrade/tests/optimize/test_edge_cli.py
When running edge cli if the stake amount is not "unlimited" we have: 
```
ERROR - Edge works only with unlimited stake amount
```
This is not necessary as edge cli is just informative and does nothing in live.
The stake amount should be set to unlimited before running egde cli.
=> Edge cli should override stake_amount

freqtrade/arguments.py, freqtrade/tests/conftest.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_edge_cli.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/test_utils.py, freqtrade/utils.py
In order to get rid of awful `scripts/get_market_pairs.py`. Other scripts can also be moved to main freqtrade subcommands.
Done:
* `list-exchanges` subcommand added; was part of scripts/get_market_pairs.py functionality
```
freqtrade list-exchanges
freqtrade list-exchanges -1
```
Todo:
* `list-pairs` subcommand with `--exchange`, `--quote-currency`, `--base-currency` options.
@xmatthias pls review it. It in principle is a template for moving other scripts to subcommands.
I think there should be an additional directory `utils` created for all this stuff with every subcommand in a diff. file.
Maybe `cli-utils` should be used everywhere in the code to name it instead of `utils`.
=> list-exchanges subcommand added

freqtrade/optimize/__init__.py, freqtrade/tests/test_utils.py, freqtrade/utils.py
* slip in a comment fixed
* setup_configuration() from utils.py renamed to setup_utils_configuration();
* setting `dry_run = True` added to it;
* use it in `optimize/__init__.py` to avoid duplication of the code;
* test adjusted
This function is intended for the use in all other new utility subcommands that require configuration in the dry_run mode without real exchange key and secret (i.e. all besides simple list-exchanges which runs without configuration).
=> minor: setup_configuration() cleanup

docs/bot-usage.md, freqtrade/arguments.py, freqtrade/configuration.py
This allows piping the config. May be useful for advanced techniques, when you need to iterate though a parameter in the config, which cannot be redefined in the command line options. (See Examples below)
Short note added to the help string for the `--config` option. Docs updated.
(I don't know how to create a test for this new feature...)
===
(from Slack #dev; this can later be posted in a docs/advanced-usage.md when it will be created)
1. Iterate through a range of stoploss values, for backtesting or hyperopts:
* Create a config template: `cp config.json config.json.template`, set `"stoploss": @@stoploss@@,` in it.
* Then iterating through a range of stoploss values for the backtesting command can be simply performed in a single-line bash script:
```
$ for i in `seq -0.03 -0.01 -0.10`; …
```
=> allow reading config from stdin

freqtrade/arguments.py, freqtrade/tests/test_arguments.py, scripts/download_backtest_data.py, scripts/plot_dataframe.py, scripts/plot_profit.py
An attempt to improve arguments handling without big redesign,
* interfaces of methods unified -- they all made non-static back and call `parser.add_argument()` in a unified manner;
* names of the methods unified: `common_args_parser()` --> `common_options()`, `optimizer_shared_options()` --> `common_optimize_options()`, `scripts_options()` --> `common_scripts_options()`;
* `plot_dataframe.py` specific arguments moved to `arguments.py` (see `plot_dataframe_options()`);
When this script is ready to become a subcommand, that will be enough to add a subparser parameter to this method and change `parser = self.parser` to `parser = subparser or self.parser` in it.
* duplicated arguments in `download_data_options()` removed; 
The script (and then the subcommand) should call the …
=> arguments cleanup

docs/hyperopt.md, freqtrade/optimize/hyperopt_interface.py, freqtrade/resolvers/hyperopt_resolver.py, freqtrade/tests/optimize/test_hyperopt.py
Make ticker-interval available to hyperopt.
Since Hyperopt does mostly use static methods it needs to be assigned as a class attribute.
It's then available as `HyperoptName.ticker_interval`.
Closes #1900
=> Ticker interval to hyperopt

freqtrade/arguments.py, freqtrade/constants.py
* Help strings for the --config, --db-url (main freqtrade), --exchange, --timeframes (download script) errorneously say the default value is None; this is fixed.
* Minor cosmetics for the strings in arguments.py: format help strings in the same manner.
=> minor: fix help strings shown to the user

freqtrade/freqtradebot.py, freqtrade/optimize/backtesting.py, freqtrade/resolvers/exchange_resolver.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py, scripts/plot_dataframe.py
- Move capitalizing exchange into strategyResolver, it's needed EVERY time and we use it 5+ times.
- remoe get_tickers_history - it's only passing arguments to history.load_data.
This is part of my "asset stripping" project for this script, which should become a subcommand soonish.
=> Plot datafame simplification

freqtrade/data/btanalysis.py, freqtrade/data/history.py, freqtrade/strategy/interface.py, scripts/rest_client.py
minor cosmetics
(typos in ':return:', as grepped out)
=> minor: typos in docstrings fixed

freqtrade/freqtradebot.py, freqtrade/tests/conftest.py, freqtrade/tests/test_freqtradebot.py
We should handle InvalidOrderExceptions gracefully (currently they Fatal-error stop the bot).
Closes #1933 
- Remove some duplicate test inits
- Add tests for the error-cases
- Add exception-handlers and log-output
=> Trailing stoploss cancel orders should be handled gracefully

freqtrade/tests/conftest.py, freqtrade/tests/strategy/test_strategy.py
Allow tests to run on windows (without WSL).
Even though it's not easy to install - tests should work without errors due to windows paths if the bot itself does work just fine!
=> Fix tests on windows

freqtrade/arguments.py
* fix help string for --db-url (diff. default values for Live Run and Dry Run modes) -- this is from the codebase logic.
* diverse cosmetic improvements to the texts of the options help strings.
Pls review, if it's okay, I'll update the docs with resulting `--help` output.
=> minor: fix help strings

docs/backtesting.md, docs/data-analysis.md, docs/plotting.md, freqtrade/arguments.py, freqtrade/configuration.py, freqtrade/data/btanalysis.py, freqtrade/plot/plotting.py, freqtrade/tests/data/test_btanalysis.py, freqtrade/tests/test_plotting.py, mkdocs.yml, scripts/plot_dataframe.py
Fix issue when plotting that trades are not loaded from file since config always has db_url.
- Document on how to load data for analysis (either from DB or from Backtest results)
- add argument  `--trade-source` to be explicit from where the trades are loaded (this has been an issue in the past)
- remove now obsolete method combination method to load trades from file or db
=> Split btanalysis load trades

docs/developer.md
to include a note to keep both branches uptodate while creating a changelog.
Cost me ~5 minutes doing the 2019.6 release, since i had ~twice as many changelog entries than commits ...
=> [minor] Improve developer-document

freqtrade/rpc/rpc.py, freqtrade/tests/rpc/test_rpc_telegram.py
Showing `all balances are zero` during dry-run is confusing. We should be clear that we're in dry-run.
Closes #1542
- Show different message for `/balance` during dry-run
=> Show different message for balance during dry-run

freqtrade/exchange/exchange.py
adding bitstamp to list of bad exchanges.
Address the issue: #1983
- added bitstamp to the list of known bad exchanges
I now see : 
```
2019-06-29 17:18:32,056 - freqtrade.configuration - WARNING - Exchange "bitstamp" is known to not work with the bot yet. Use it only for development and testing purposes.
```
=> adding bitstamp to list of bad exchanges.

freqtrade/freqtradebot.py
minor cleanup attempt for the Freqtradebot class:
* check_sell() renamed to _check_sell_and_execute() since it's 1) non-public, 2) it checks and executes a sell
* notify_sell() --> _notify_sell() since it's non-public
* code in check_sell() simplified a bit and made more pythonic (as I guess)
=> partial freqtradebot cleanup

.travis.yml, docs/installation.md, setup.sh
The install script does not work correctly. 
It checks which python version to use before eventually installing that. 
Also, there are many ways (and even more different systems) to install python to a system, many better than the one we use in the script (pyenv to name one).
We should not install python for users, but instead require python and pip to be there.
We also do some "funny" things to brew on macOS. 
I would appreciate if someone with a Mac could look over that part too, since i think depending on the OS version we may break things.
Resolves #1956
=> Modify handling of pip in setup.sh

freqtrade/exchange/exchange.py, freqtrade/resolvers/exchange_resolver.py, freqtrade/tests/exchange/test_exchange.py
This can happen on exchanges which don't have a "real" fetch_OHLCV method.
The example (bitstamp) has this emulated.
From the [ccxt documentation](https://ccxt.readthedocs.io/en/latest/manual.html?highlight=timeframes)
> timeframes: An associative array of timeframes, supported by the fetchOHLCV method of the exchange. This is only populated when has['fetchOHLCV'] property is true.
Closes #1983
- Check if element is available, fail with explaining the error otherwise.
- Add test for this specific case
=> Gracefully fail on timeframes exception

freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py
* This PR addresses the issue mentioned in #1992 (see https://github.com/freqtrade/freqtrade/issues/1992#issuecomment-507825182): `validate_timeframes()` does not work as intended (it does not issue `OperationalException`) after https://github.com/ccxt/ccxt/commit/2be61d6b80a7e7e9be44ba5fe0f5bcc54997584d made in ccxt.
* The text of the exception message clarified (to cover both cases, when there is no `timeframes` attribute and when it's None), test adjusted with the new exception text.
* Test added for `'timeframes': None` in the markets.
=> fix validate_timeframes()

freqtrade/exchange/exchange.py, freqtrade/rpc/rpc.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/rpc/test_rpc.py, freqtrade/tests/rpc/test_rpc_apiserver.py, freqtrade/tests/rpc/test_rpc_telegram.py
Some pairs are not available as <pair>/BTC - but BTC/<pair>. These pairs are often stake-currencies (like PAX).
we used to have a hardcoded list of these pairs, however using the exchanges "markets" for this is way more flexible, and should eliminate this bug for many other currencies (USDC, ...) too.
Closes #1981
=> Support all types of pairs for /balance

docs/backtesting.md, docs/bot-usage.md, docs/deprecated.md, docs/edge.md, docs/faq.md, docs/hyperopt.md, docs/installation.md, docs/strategy-customization.md, setup.sh
we can either use `python3 -m freqtrade ...` or `freqtrade ...` to run the bot (`python3 freqtrade` requires some ugly hacks with PYTHON_PATH.
- and shorter should be better.
closes #1990 
if `freqtrade` is not available as binary - then the installation did not go well or the virtual Environment has not been activated.
=> Don't run the bot with python3 freqtrade

freqtrade/resolvers/exchange_resolver.py, freqtrade/resolvers/hyperopt_resolver.py, freqtrade/resolvers/iresolver.py, freqtrade/resolvers/pairlist_resolver.py, freqtrade/resolvers/strategy_resolver.py, freqtrade/tests/pairlist/test_pairlist.py, freqtrade/tests/strategy/test_strategy.py
Inspired by https://github.com/freqtrade/freqtrade-strategies/issues/37.
* Improvements to logging.
In the meantime in the logs I can see which non-py files were skipped by freqtrade while resolving strategy or hyperopt, but I cannot see what particular .py file the strategy was loaded from.
People (and me) often copy the strategy and hyperopt files just in order to test new variations and forget to change the name of the class. This change allows to see (at least) what's the filename of the .py file the object was loaded from.
The module_path of the module where the object was found is now returned from the `_search_object()` along with the object and then printed by resolvers in the logging messages.
* ImportError changed to OperationalException in order to avoid printing traceback in …
=> minor: improvements to resolvers

freqtrade/exchange/exchange.py, freqtrade/tests/exchange/test_exchange.py, freqtrade/tests/exchange/test_kraken.py
Some exchanges have market-orders requiring prices (this happens when precision is needed in the "wrong" currency by the exchange).
By using the ccxt attribute used for this, we are covered should this be needed for more exchanges in the future.
Closes #1920
=> Market orders with price

bin/freqtrade
As raised in #2020, the legacy script uses a wrong import.
If the bot was installed / reinstalled recently, this can be tested by running `./bin/freqtrade -c config.json`.
For new installations, this will have no impact (`which freqtrade` links to a automatically generated file).
I guess we should also consider removing this file (or removing the call to main() - so it doesn't crash but force you to reinstall)?
Closes #2020
=> Remove wrong import in legacy startup sript

freqtrade/configuration/__init__.py, freqtrade/configuration/arguments.py, freqtrade/configuration/check_exchange.py, freqtrade/configuration/configuration.py, freqtrade/configuration/create_datadir.py, freqtrade/configuration/json_schema.py, freqtrade/data/history.py, freqtrade/edge/__init__.py, freqtrade/main.py, freqtrade/optimize/backtesting.py, freqtrade/optimize/edge_cli.py, freqtrade/optimize/hyperopt.py, freqtrade/plot/plotting.py, freqtrade/tests/conftest.py, freqtrade/tests/data/test_btanalysis.py, freqtrade/tests/data/test_history.py, freqtrade/tests/optimize/test_backtesting.py, freqtrade/tests/optimize/test_edge_cli.py, freqtrade/tests/optimize/test_hyperopt.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py, freqtrade/tests/test_main.py, freqtrade/tests/test_plotting.py, scripts/download_backtest_data.py, scripts/plot_dataframe.py, scripts/plot_profit.py
The patch is wider than I expected but this mostly is due to the tests.
* configuration is made a sep. module in a sep. directory
* arguments moved also to the new configuration module. Because arguments are also a part of configuration.
* validation of json schema separated from configuration.py
* check_exchange() separated from configuration.py
* tests adjusted and improved (2 common functions made in conftest)
* create_datadir() moved to its own separate file
=> Make configuration a module

.travis.yml, requirements-dev.txt
Randomized tests used to be enabled, but the plugin changed how it works
> From v1.0.0 onwards, this plugin no longer randomises tests by default.
The intend with this is to capture tests which depend on state left from previous tests.
Since this has been disabled for a while, it'll probably create a few flukes (tests which can be fixed after restarting the testing). Please note the random-seed for these tests so we can have a look at them one by one.
=> Randomize tests again

docs/bot-usage.md, freqtrade/configuration/arguments.py
`-V` is frequently used for apps as a shortcut for `--version`.
* bot-usage docs also updated with this change
=> minor: add -V alias for --version

freqtrade/configuration/arguments.py, freqtrade/tests/test_arguments.py, scripts/download_backtest_data.py, scripts/plot_dataframe.py, scripts/plot_profit.py
name non-public class attributes and methods with leading underscore.
Currently, `_parse_args()` is also used in the scripts, but this is only temporary till they moved to the subcommands.
=> minor: cleanup Arguments

freqtrade/configuration/create_datadir.py, freqtrade/resolvers/pairlist_resolver.py, freqtrade/tests/test_configuration.py
* Using the more modern pathlib instead of os.path.
* we should also not assume user_data is in parent.parent.parent but use cwd() instead (this is not fully implemented yet - will need followup pr's for other sections of the code)
=> [minor] Convert create_datadir to Pathlib

docs/bot-usage.md, docs/configuration.md, docs/deprecated.md, docs/edge.md, freqtrade/configuration/arguments.py, freqtrade/configuration/configuration.py, freqtrade/tests/test_arguments.py, freqtrade/tests/test_configuration.py
Removal of the `--dynamic-whitelist` option, which left in the deprecated status for long time.
That was not so easy (many appearances), so verify that I did not forget anything.
=> remove deprecated --dynamic-whitelist option

docs/bot-usage.md, freqtrade/configuration/arguments.py, freqtrade/configuration/configuration.py, freqtrade/resolvers/hyperopt_resolver.py
* The option similar to `--strategy-path`.
* Anything was already ready in `hyperopt_resolver.py`.
* Option works for both `HyperOptResolver` and `HyperOptLossResolver`.
* Docs adjusted.
* Handling of `strategy_path` in `configuration.py` improved (moved to the use of 'standard' `_arg_to_config()` method)
=> add --hyperopt-path option

docs/hyperopt.md, freqtrade/optimize/default_hyperopt_loss.py, freqtrade/optimize/hyperopt_loss_onlyprofit.py, freqtrade/optimize/hyperopt_loss_sharpe.py, freqtrade/tests/optimize/test_hyperopt.py
Minor changes:
* Adds Hyperopt Loss Function that takes only profit into account.
May be useful for users , I use it in practice.
If `freqtrade/optimize` is not a proper place for it, I could move it into `user_data/hyperopts` dir or to the `freqtrade/freqtrade-strategies` project.
* Improves wording in comments in DefaultHyperOptLoss and SharpeHyperOptLoss
=> minor: add OnlyProfitHyperOptLoss

docs/deprecated.md, freqtrade/configuration/configuration.py, freqtrade/tests/test_configuration.py
as mentioned in #2052,  `--live` should be deprecated, since it does not provide any value (too short for realistic backtesting).
Closes #2052
- Add simple method to deprecate cmdline options
- deprecate `--live`
=> Deprecate live bt

freqtrade/exchange/exchange.py, freqtrade/freqtradebot.py, freqtrade/tests/test_freqtradebot.py
get_order errors (invalidOrder)should be cought.
Closes #2054, #2037 
- Catch InvalidOrder error
- Add test for this
- Reraise errors using `raise OperationalError() from e`
This last point needs some more explanation:
the following code: (hell is not defined
```python
try:
print(hello)
except Exception as e:
raise ValueError()
```
produces the following traceback:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-978637addd74> in <module>()
1 try:
----> 2     print(hello)
3 except Exception as e:
NameError: name 'hello' is not defined
During handling of the above exception, another exception occurred:
ValueError                                Traceback (most recent …
```
=> Get order exception

freqtrade/tests/strategy/test_strategy.py
...when testing handling of the deprecated strategy interfaces
Cherry-picked from #2058
=> minor: eliminate warnings in pytest

freqtrade/tests/optimize/test_hyperopt.py
Eliminates warning;
```
freqtrade/tests/optimize/test_hyperopt.py::test_loss_calculation_prefer_shorter_trades
/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/tests/optimize/test_hyperopt.py:300: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```
=> get rid of pandas warning in pytest

docs/bot-usage.md
Issue #2042 noted that the terminal output from `setup.sh` regarding an option use the bot was missing from the documentation. This has been added.
Add note to docs from `setup.sh`.
Solve the issue: #2042
- Added second paragraph to Start the Bot page of documentation.
Just a new line in `docs/bot_usage.md`
=> Resolve issue #2042

freqtrade/worker.py
This was the FIRST change I made into freqtrade when I fetched it...
Without this the logs are too blind -- it helps to navigate in the sheets of logs, especially with verbosity increased.
Now printed at debug level, can also be printed as info.
=> Improve logging: output divider in logs between throttles

docs/developer.md, requirements-dev.txt, setup.py
This pr will allow installation via pip using "extras".
basically, to install the bot for a development installation:
`pip install -e .[all]`.
To only install the base bot + plot features: `pip install -e .[plot]`
This will become more power should we be able to sucessfully isntall through pypi - where a command like `pip install freqtrade[all]` will become possible.
- add extra-install tools
=> Improve setup.py to allow "extras" installations

freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
* modification of the use_sell_signal config setting to True moved to `__init__()` -- it should not be done at every call to `hyperopt_space()`
* minor cleanup in `log_trials_result()` (`params = best_result['params']`)
* detection if roi table should be printed in `log_trials_result()` improved -- this should be done via `has_space()`, because in her custom hyperopt a user may use other names for t1 and other components of the roi table,
* implementation of `has_space()` pythonized
* tests adjusted to not fail with these changes
=> minor: cleanup in hyperopt

docs/hyperopt.md, freqtrade/optimize/hyperopt.py, freqtrade/tests/optimize/test_hyperopt.py
In the printed best result's detailization:
* Params in the 'buy' and 'sell' spaces are printed separately. This will help a user to understand the result.
* ROI table is printed separately as a generated table. Params from the 'roi' space (roi_t1, roi_p1, ...) are not printed because they are internal and useless for the user. (Available in the debug log anyway)
* Stoploss is printed separately (if 'stoploss' space is in the list of spaces).
* Hyperopt docs adjusted accordingly with new output; some minor fixes added to the docs.
P.S. I'm thinking of removal the 'with values:' line from the output now...
=> Improvements to hyperopt output

docs/faq.md, freqtrade/exchange/exchange.py, freqtrade/tests/conftest.py, freqtrade/tests/exchange/test_exchange.py
Freqtrade should warn users if they have restricted pairs in their whitelist.
As noted in https://github.com/ccxt/ccxt/issues/5624, there is currently
no way to detect if a user is impacted by the restriction or not prior to creating (and eventually failing to create) an order.
Closes #2074, 
Closes #1690
- Warn on startup
- document in FAQ about this problem
=> Restricted pairs warning

freqtrade/data/btanalysis.py, freqtrade/tests/data/test_btanalysis.py
We were missing one needed column in the load_trades_db function.
Solve the issue: #2083
- Add multiple columns to have all that backtesting gives, and some more for extendet analysis
=> load_trades_db should give as many columns as possible

freqtrade/plot/plotting.py, freqtrade/strategy/interface.py, freqtrade/tests/strategy/test_interface.py, freqtrade/tests/test_plotting.py, scripts/plot_dataframe.py
This will split analyze_ticker into 2 functions.
* `analyze_ticker()` is the public interface, ONLY running the strategy's functions, without additonal logic. This function should be used for data analysis, and plot-scripts, where `process_only_new_candles` is irrelevant since we always want this analyed. Having the logic for `process_only_new_candles` in place can prevent plots to be correct.
* `_analyze_ticker_int()` handles the logic if the ticket needs to be analyzed or if `process_only_new_candles` kicks in.
As a consequence, `generate_dataframe()` in `scripts/plot_dataframe.py` has beenremoved, since this is now a copy of `analyze_ticker()`.
* Added output to show the plot-location (since i did not refind my plot ...).
This is probably the last sub-PR  before moving the plot-scripts …
=> Split analyze_ticker
