freqtrade/freqtrade

- docs/installation.md
- environment.yml
Enables building app in a conda environment or Docker container using a Makefile
Solve the issue: #2041 
- Added Makefile
- Updated .dockerignore/.gitignore
- Created new logic for generation of startup files
- Added .env file to separate configuration from strategies
- Added support for version control of a repo located at `user_data/user_repo` so users can keep custom strategies, scripts, and jupyter notebooks backed up
This is a proposed alternative to the installation process intended to:
- Streamline the installation options
- Make working with Docker containers less cumbersome and
- Add support for installation in a conda environment. 
The existing `setup.sh` script is untouched and will continue to work as a parallel installation option.
- Overwrite configuration defaults by …
> Conda / makefile

- requirements-common.txt
As pointed out in #2077, requests has been updated to support the latest urllib3 version too, so there is no reason to pin urllib3 to an older version.
closes #2077
- update urllib3 to latest version
> Update urllib to latest version

- docs/backtesting.md
- docs/bot-usage.md
- freqtrade/configuration/cli_options.py
Fix docstring for strategy list (it's space seperated, not comma seperated), add small documentation sample for this option
Closes #2098
> Fix documentation for strategy-list

- .travis.yml
- build_helpers/install_ta-lib.sh
Installing ta-lib on travis takes some time (80+ seconds usually).
Since it's running once per job, it accounts for the most part of our CI cycle.
Travis does support caching, which we had in place for ta-lib, but since it's a system-folder (non-empty) - caching does not work correctly.
This PR will reenable travis to cache ta-lib, improving performance as can be seen here:
https://travis-ci.org/freqtrade/freqtrade/builds/568019204
To see this problem, extend one of the tasks and go to the step `install.1` (on a current and new build).
- Use --prefix /usr/local for install-script too
- improve travis performance greatly
- Cleanup some unused apt installs from `.travis.yml`
before:
after / with caching
> Update install-script to use parameter

- freqtrade/optimize/backtesting.py
- freqtrade/tests/optimize/test_backtest_detail.py
- freqtrade/tests/optimize/test_backtesting.py
During backtesting, we use "open" for both timestamp and rate, so realistic backtesting needs to evaluate the current  candle for ROI / stoploss too, which is also happening during live trading.
Closes #1971 
- Add 3 new testcases to cover this trading scenario (these 3 fail without the 2nd commit).
- Cleanup of some comments - no need to be that verbose, all information is in the initialization too.
> Evaluate current candle during backtesting

- freqtrade/exchange/exchange.py
- freqtrade/tests/exchange/test_exchange.py
Since arguments are in milliseconds integer throughout ccxt.
apparently this is accidentally working for binance / bittrex, but not for kuocoin (i suspect it did return all trades for that pair from binance, too)...
Explained here: https://github.com/ccxt/ccxt/issues/5636
fixes #2093
- Enhanced tests to verify we convert this correctly
> Since arguments are in milliseconds integer throughout ccxt.

- freqtrade/optimize/backtesting.py
- freqtrade/tests/optimize/test_backtesting.py
ticker-interval needs to be set for backtesting to work.
In case of strategy-list, it needs to be defined on either config or cli level, since each strategy could define it's own interval.
Solves #2099
- Fix uncought error
- add test for this behaviour
> Backtest ticker interval unset

- setup.sh
Improve setup.sh to fail less often, and not require additional system configuration
closes #2006, #2087
- detect running in venv (closes #2006)
- ensure ld_library_path (closes #2087)
- check if  venv is realy active (fail otherwise)
- don't require interaction for `apt-get install`
- ask for confirmation before running `git reset --hard` - it'll remove all changes made
- ask for dev-dependency installation before installing (`requirements-dev.txt` includes all dependencies)
> Improve setup.sh

- freqtrade/optimize/hyperopt_loss_sharpe.py
This leads in a high positive result of the loss function, as it is a minimal optimizer
> As -sharp_ratio is returned the value should be nagative.

- freqtrade/rpc/rpc.py
- freqtrade/tests/conftest.py
...cause these are tests, we need to see all errorneous cases.
This change produces an error in the rpc test -- that's its purpose.
I cannot fix that error because I do not understand why `numpy.mean()` is used in that place in rpc.py...
> tests: don't mask numpy errors as warnings in tests

- freqtrade/freqtradebot.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/tests/strategy/test_strategy.py
- freqtrade/tests/test_freqtradebot.py
Stoploss on exchange does not make sense for dry-run scenarios - so we need to disable this option similar to how we handle this for backtesting.
Closes #2106
Using stoploss on exchange with dry-runs causes errors, and will provide no benefit since there is no exchange executing dry orders.
> Disable stoploss on exchange during dry-runs

- docs/bot-usage.md
- docs/data-analysis.md
- freqtrade/configuration/configuration.py
- freqtrade/tests/test_configuration.py
Simplify loading configuration files in "standalone" mode (without arguments).
This can be useful when using methods of freqtrade in interactive environments (jupyter notebooks).
Part of  #2078
- change internal `_load_config_files` to static method `from_files`
- move validation to this method
- move normalization to this method (does not make sense to keep this seperate unless we add more normalizations).
usage (from notebooks / standalone mode):
``` python
from freqtrade.configuration import Configuration
config = Configuration.from_files(["config1.json", "config2.json"])
print(config)
```
> Config standalone loading

- docs/developer.md
- freqtrade/tests/conftest.py
- freqtrade/tests/data/test_converter.py
- freqtrade/tests/data/test_history.py
- freqtrade/tests/edge/test_edge.py
- freqtrade/tests/exchange/test_exchange.py
- freqtrade/tests/optimize/test_backtesting.py
- freqtrade/tests/optimize/test_edge_cli.py
- freqtrade/tests/optimize/test_hyperopt.py
- freqtrade/tests/rpc/test_fiat_convert.py
- freqtrade/tests/rpc/test_rpc_apiserver.py
- freqtrade/tests/rpc/test_rpc_manager.py
- freqtrade/tests/rpc/test_rpc_telegram.py
- freqtrade/tests/rpc/test_rpc_webhook.py
- freqtrade/tests/strategy/test_interface.py
- freqtrade/tests/strategy/test_strategy.py
- freqtrade/tests/test_configuration.py
- freqtrade/tests/test_freqtradebot.py
- freqtrade/tests/test_main.py
- freqtrade/tests/test_persistence.py
- freqtrade/tests/test_plotting.py
we can clean up some tests by passing `caplog` to `log_has()`, instead of `caplog.record_tuples`.
This has the benefit of beeing shorter - and helps reduce a lot of (now) unnecessary linebreaks.
- use caplog instead of caplog.record_tuples in calls to log_has
- Replace all non-standard tests in `test_strategy` with calls to log_has.
- add dev-documentation section about tests
> [minor, tests] - use caplog instead of caplog.record_tuples

- docs/bot-usage.md
- docs/hyperopt.md
- freqtrade/configuration/cli_options.py
Improve documentation of hyperopt loss (allowing copy/paste of builtin loss-functions from `--help`).
If i know i want Sharpe Loss function, i shouldn't need to go to the documentation to look for the correct name.
> [minor] Improve hyperopt-loss docs

- docs/configuration.md
- freqtrade/configuration/check_exchange.py
- freqtrade/configuration/configuration.py
- freqtrade/exchange/__init__.py
- freqtrade/exchange/exchange.py
- freqtrade/tests/test_configuration.py
If we know an exchange is not working with freqtrade, freqtrade should not simply warn users, but fail instead (startup-warnings are easily missed ...).
Also adding the "reason" element we discussed in #1992
Closes #1992
- Fail for bad exchanges
- show reason why this exchange will not work
- skip-fail in experimental flags (`experimental.block_bad_exchanges=False`)
> fail for bad exchanges

- docs/bot-usage.md
- docs/hyperopt.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- freqtrade/misc.py
- freqtrade/optimize/hyperopt.py
- freqtrade/tests/optimize/test_hyperopt.py
- requirements-common.txt
- setup.py
The `--color/--print-colorized` option to print colorized results:
* bad (zero trades or limited by `--min-trades`) are in red;
* current bests -- in green (also when used without `--print-all`)
* epochs with positive total profit -- in bold
This option helps a user recognize visually the performance of hyperopt evaluations, especially when used with `--print-all`.
Brief description added to hyperopt docs (also a description for `--print-all` which was missed).
> Hyperopt print colorized results

- docs/bot-usage.md
- docs/configuration.md
- freqtrade/configuration/load_config.py
- freqtrade/tests/config_test_comments.json
- freqtrade/tests/test_configuration.py
...and trailing commas.
rapidjson allows this, it has corresponding parse_mode values.
A special test config file (`config_test_comments.json`) was added into the tests dir since I found it inappropriate to add those testing comments into `config_full.example.json` from the main dir.
(btw, `config_full.example.json` is the only file which is really loaded by the tests. Should not we also load in the tests the `config.json.example` after modifying it in the same manner as setup.py does?)
If accepted, TODO:
> Allow comments in config files

- freqtrade/freqtradebot.py
- freqtrade/tests/rpc/test_rpc.py
- freqtrade/tests/rpc/test_rpc_apiserver.py
- freqtrade/tests/rpc/test_rpc_telegram.py
- freqtrade/tests/test_freqtradebot.py
- freqtrade/worker.py
Returning from the create_trade function does not make sense - if multiple "trade-slots" are open, and we have buy-signals, we should buy immediately to not loose the opportunity.
This will also implicitly fix #1850, since this will run analysis for all whitelisted pairs while checking for trades. In combination with `process_only_new_candles` and #2131, buys only happen right after the new candles appear.
Closes #1850
- `process()` functions should not return anything (as identified in TODO in worker.py), since it's only used in tests
- `process_maybe_execute_buy()` should not return anything.
- `create_trade()` should check full whitelist (until `"max_open_trades"` is reached) to create as many trades as allowed (and set by the buy-signal).
- Adapt tests (especially `edge` - which did …
> allow create_trade() to create multiple trades per iteration

- freqtrade/configuration/__init__.py
- freqtrade/configuration/arguments.py
- freqtrade/configuration/timerange.py
- freqtrade/edge/__init__.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/optimize/hyperopt.py
- freqtrade/plot/plotting.py
- freqtrade/tests/data/test_btanalysis.py
- freqtrade/tests/test_arguments.py
- freqtrade/tests/test_plotting.py
- freqtrade/tests/test_timerange.py
- scripts/download_backtest_data.py
Refactoring to avoid importing Arguments to get a valid class.
- Move TimeRange to it's own file
- move parse_timerange to TimeRangeClass
- adapt code to use this method.
> [refactor] Move Timerange parsing to it's own class

- freqtrade/data/history.py
- freqtrade/exchange/exchange.py
- freqtrade/tests/data/test_history.py
- freqtrade/tests/exchange/test_exchange.py
Clarify how each method works (async over pair / async over history for one pair)
rename `get_history` to `get_historic_ohlcv` - so it's clear what we're actually downloading.
> [minor] Improve docstring for some downloading methods

- freqtrade/configuration/configuration.py
Someone wrote an fstring without the f
- add f to the fstring to make logging print the variable
Output will print the actual runmode now instead of this:
```
2019-08-15 16:12:19,640 - freqtrade.configuration.configuration - INFO - Runmode set to {self.runmode}.
```
> f the string

- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- freqtrade/optimize/hyperopt.py
- freqtrade/tests/optimize/test_hyperopt.py
This PR adds the `--print-json` option which prints best result details in json format, in one line.
This helps automatization of backtesting, since the details in this format are easily greppable (one line, defined format) and can then be easily parsed and transferred into existing strategy or to the options of the freqtrade backtesting or freqtrade dry-run...
Example of output, spaces='all':
```
*    1/10:     15 trades. Avg profit -0.57%. Total profit -0.00429526 BTC (  -8.57Σ%). Avg duration 1287.0 mins. Objective: 2.28322
*    2/10:     60 trades. Avg profit -0.76%. Total profit -0.02279588 BTC ( -45.48Σ%). Avg duration 1638.4 mins. Objective: 2.39411
*    3/10:      0 trades. Avg profit   nan%. Total profit  0.00000000 BTC (   0.00Σ%). Avg duration   nan mins. Objective: …
```
> Hyperopt: --print-json option

- freqtrade/data/dataprovider.py
- freqtrade/tests/data/test_dataprovider.py
* The `get_pair_dataframe()` method added. This can help dealing with informative pairs in the custom strategies. For example, the `InformativeSample.populate_indicators()` can be simplified to be as easy as:
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)
if self.dp:
data = self.dp.get_pair_dataframe(pair=f"{self.stake_currency}/USDT", ticker_interval=self.ticker_interval)
dataframe = dataframe.merge(data[["date", "close"]], on="date", how="left", suffixes=("", self.config['stake_currency']))
dataframe[f"sma{self.config['stake_currency']}20"] = …
```
> Dataprovider: get_pair_dataframe() helper method, cleanup

- freqtrade/exchange/exchange.py
- freqtrade/tests/exchange/test_exchange.py
Fixes exceptions with keyerror due to dry-run order handling messing up "something".
We reset dry-run orders on startup so ideally this error should not happen.
If it does, its better to handle it gracefully rather than failing with a keyerror.
sample exception
```
2019-08-18 14:50:14,822 - freqtrade - ERROR - Fatal exception!
File "/freqtrade/freqtrade/main.py", line 49, in main
worker.run()
File "/freqtrade/freqtrade/worker.py", line 72, in run
state = self._worker(old_state=state)
File "/freqtrade/freqtrade/worker.py", line 110, in _worker
self._throttle(func=self._process, min_secs=throttle_secs)
File "/freqtrade/freqtrade/worker.py", line 123, in _throttle
result = func(*args, **kwargs)
File "/freqtrade/freqtrade/worker.py", line 133, in _process …
```
> Gracefully handle problems with dry-run orders

- freqtrade/constants.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/resolvers/iresolver.py
VolumePairlist is way too verbose. The whitelist changes once every 1800 seconds, no need to print it with every iteration.
Also, logging did not "know" the volumepairlist's name and used "unknown" since this was passed into the dynamic loader.
Using the class-name seems to make more sense here.
logging before:
```
2019-08-18 14:50:09,710 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...
2019-08-18 14:50:11,842 - unknown - INFO - Searching pairs: ['BNB/ETH', 'XRP/ETH', 'LINK/ETH', 'ENJ/ETH', 'HC/ETH', 'EOS/ETH', 'LTC/ETH', 'TRX/ETH', 'WAVES/ETH', 'XVG/ETH', 'ADA/ETH', 'MTL/ETH', 'HOT/ETH', 'ICX/ETH', 'THETA/ETH', 'QTUM/ETH', 'NPXS/ETH', 'ZEC/ETH', 'LSK/ETH', 'ZIL/ETH']
2019-08-18 14:50:14,819 - freqtrade.freqtradebot - INFO - Found no buy …
```
> Fix pairlist logging

- freqtrade/exchange/exchange.py
- freqtrade/tests/exchange/test_exchange.py
Since price can be `None` in case of market orders, we cannot do calculations within eceptions, otherwise we crash the bot (see #2011 for that case).
Closes #2011 
- Split exception tests to test for both limit and market orders
- fix calculation error by removing calculation from the exception handler
> create market order crash if exchange raises an exception

- freqtrade/configuration/__init__.py
- freqtrade/configuration/config_validation.py
- freqtrade/configuration/configuration.py
- freqtrade/freqtradebot.py
- freqtrade/tests/test_configuration.py
Validate edge_configuration vs. Volume pairlist - the 2 are incompatible (edge will always override volume pairlist - which will cause unnecessary calls to the exchange from the VolumePairList.
Closes #1196 (5th and last point).
- move validation methods out of Configuration
- Check configuration after loading strategy (strategies can set options, especially related trailing stop - so our current approach is inefficient for these cases).
> Config consistency checking improvements

- freqtrade/configuration/configuration.py
- freqtrade/misc.py
- freqtrade/tests/test_configuration.py
This fixes both bugs (both reported in #2133).
Closes #2133
The pairlist part of download-data had 2 bugs
* load_json does expect a file-like object, not a Path
* fallback-path to pairs.json did not include exchange (this was present in the old download-script too)
The 2nd part was not noticed since i accidentally have a `pairs.json` in `user_data/data/` too (while we should load from `user_data/data/<exchange>/pairs.json`.
> Fix downloadscript pair handling

- docs/backtesting.md
- docs/bot-usage.md
- docs/deprecated.md
- docs/edge.md
- docs/plotting.md
- docs/strategy-customization.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- freqtrade/optimize/backtesting.py
- freqtrade/plot/plotting.py
- freqtrade/tests/optimize/test_backtesting.py
- freqtrade/tests/optimize/test_edge_cli.py
- freqtrade/tests/optimize/test_hyperopt.py
- freqtrade/tests/test_arguments.py
- freqtrade/tests/test_configuration.py
- freqtrade/tests/test_main.py
We have --live deprecated now in one release version, so we can remove it as agreed.
This pr will also deprecate -r as discussed in #2148.
This PR shall be merged after  #2146 - and rebased onto develop first (carefully go through the ocs after that).
closes #2148
> Remove deprecated option live  - deprecate -r

- freqtrade/configuration/config_validation.py
- freqtrade/tests/test_configuration.py
Stoploss with 0 is problematic, since that would lead to sells immediately.
This should prevent the bog from starting up - otherwise it results in misleading bug reports (as #2171).
Solve the issue: #2171
- Validate stoploss_positive !=0 (it can be positive or negative, since we use `-1 * abs()` when applying this).
- validate stoploss != 0 (same `-1 * abs()` logic as before
> improve stoploss validation

- freqtrade/optimize/hyperopt.py
- freqtrade/tests/optimize/test_hyperopt.py
Do not inherit Hyperopt from Backtesting. Make an instance of Backtesting an attribute of Hyperopt.
Rationale: because Hyperopt is not a ***kind of*** Backtesting, it ***uses*** Backtesting...
> Hyperopt redesign

- freqtrade/freqtradebot.py
- freqtrade/tests/test_freqtradebot.py
When orders can't be recreated, we need to reset  `stoploss_order_id` - otherwise we'll end up in an endless loop trying to cancel an unexisting order.
Another part to: #2171
- Add test for expected behavior
- reset stoploss_order_id when order can't be created.
- Fix typo ("we could **NOT** create trailing stoploss order" )
> [minor]improvements to stoploss-on-exchange handling

- freqtrade/__init__.py
- freqtrade/exchange/binance.py
- freqtrade/exchange/exchange.py
- freqtrade/tests/exchange/test_binance.py
- freqtrade/tests/exchange/test_exchange.py
- freqtrade/tests/test_freqtradebot.py
Stoploss on exchange is currently only supported by binance, and the code is binance-specific, therefore we should move the implementation to the binance subclass.
We also should not use `self.create_order()` for this case, since we need to handle `InvalidOrder` exceptions differently (in a future PR) - probably by force-selling the pair.
Note: There is no functional change in this PR, so nothing will improve for users, but it enables #1557
- Move implementation to binance subclass
- some minor maintenance in exchange class
- Improve docstring for OperationalException 
- move corresponding tests to newly created `test_binance.py`
> [refactor] Move stoploss on exchange implementation to binance

- freqtrade/freqtradebot.py
- freqtrade/optimize/hyperopt.py
- freqtrade/persistence.py
- freqtrade/tests/optimize/test_hyperopt.py
- freqtrade/tests/test_configuration.py
We shouldn't escape `'` in strings if we can use double-quotes as string-delimiters
> [minor] Don't escape ticks where it's not needed

- freqtrade/data/history.py
- freqtrade/tests/data/test_history.py
- freqtrade/tests/test_utils.py
- freqtrade/utils.py
This will simplify the logic in `utils.py`.
Main reason is preparational work for #2134 (trying to keep that PR as small as possible by extracting some needed refactorings).
- introduce `refresh_backtest_ohlcv_data()` which is used by download-data
- move tests to test_history.py
> [Refactor] Logic for download-data to history

- freqtrade/exchange/exchange.py
- freqtrade/tests/exchange/test_exchange.py
- requirements-common.txt
- setup.py
Since round_timeframe has been added to ccxt, we can rely on that instead of reimplementing the calculation.
> [minor] Use ccxt methods to round timeframe

- freqtrade/optimize/backtesting.py
Small optimization in Backtesting: move initialization of `self.ticker_interval` from `_set_strategy` method to `__init__()`. It's not taken from the strategy attribute and required to be set in the config/options.
> minor: Backtesting cleanup

- docs/backtesting.md
- docs/data-analysis.md
- docs/strategy-customization.md
- freqtrade/tests/optimize/test_backtesting.py
- freqtrade/tests/optimize/test_hyperopt.py
- freqtrade/tests/strategy/legacy_strategy.py
- freqtrade/tests/strategy/test_strategy.py
- freqtrade/tests/test_arguments.py
- user_data/notebooks/strategy_analysis_example.ipynb
- user_data/strategies/sample_strategy.py
Having the name test_strategy can be misleading that this is the strategy which does only test but not use real money.
Also, renaming `TestStrategy` to `SampleStrategy`aligns it with the naming convention used for `Hyperopt`/`HyperoptLoss`.
NB: LInks will fail until merged, since they link to the develop-branch, where the file is not yet renamed.
> Rename testStrategy to sample_strategy

- docs/strategy-customization.md
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/strategy/default_strategy.py
- freqtrade/strategy/interface.py
- freqtrade/tests/strategy/test_strategy.py
- user_data/strategies/test_strategy.py
In order to allow future iterations of the strategy interface, we should version the API (basically allowing the strategy to tell the bot clearly what interface it's going to use without us trying to parse this from available methods or similar).
This will enable / simplify work on #2183.
- Introduce `strategy_version` (current version is 2 - legacy would be 1 and is auto-detected).
> Introduce strategy_version 

- freqtrade/configuration/configuration.py
- freqtrade/tests/test_configuration.py
When running `freqtrade download-data --exchange binance ` - the path needs to point to the final folder (incl. exchange). To accomplish this, `--exchange` needs to be parsed before setting datadir.
This also simplifies detecting the pair-list (wrongly fixed in #2168).
- Change argument resolution sequence to have exchange name available earlier
- test that running the bot with `--exchange binance` sets the correct path.
- Fix test-leakage (MINCONFIG was changed...) by not copying a dict properly.
> Fix datadir init to always include exchange

- freqtrade/rpc/rpc_manager.py
- freqtrade/rpc/webhook.py
- freqtrade/tests/rpc/test_rpc_manager.py
- freqtrade/tests/rpc/test_rpc_webhook.py
Catch `NotImplementedError` (it can be thrown by any rpc provider).
* Handle new message-types in webhook notifications.
Closes #2200
> sending rpc messages should not stop the bot

- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/tests/test_freqtradebot.py
Stoploss on exchange does make (limited) sense in dry-run (and it was also implemented, but had a bug for trailing stoplosses).
stoploss on exchange during dry-run assumes to always sell at stop_price - while regular operations can have a stoploss at 5%, and sell at -7% because there was a sharp drop (so it makes sense to leave this setting on during dry-run).
Solve the issue: #2106, revert #2119
- Add missing attribute for dry-run stoploss orders
- remove setting `stoploss_on_exchange` to false during dry-run operations.
> Reenable stoploss_on_exchange for dry-run

- config_full.json.example
- docs/configuration.md
- docs/strategy-customization.md
- freqtrade/constants.py
- freqtrade/exchange/binance.py
- freqtrade/freqtradebot.py
- freqtrade/strategy/interface.py
- freqtrade/tests/exchange/test_binance.py
- freqtrade/tests/test_freqtradebot.py
Failed stoploss-on-exchange orders should be handled gracefully.
Fixes #1557, Fixes #1918 (part of this was fixed in #2177).
- Extract logic to create a stoploss-order (it was called in 3 places) - (enables easy implementation of #1717  and #1718)
- introduce new sell-type - EmergencySell - to clearly outline sells which were not triggered by the exchange.
- If creating a stoploss-order fails with InvalidOrder (mostly seen as `Order would trigger immediately.`) - we force-sell the pair using a market order (can be changed).
- best review the first 2 commits seperately - they are simply refactoring to enable the remaining work without code duplication in 3 places.
> Improve stoploss on exchange handling

- freqtrade/configuration/arguments.py
- freqtrade/plot/plot_utils.py
- freqtrade/tests/test_configuration.py
- freqtrade/tests/test_plotting.py
We should always default to config.json if it exists (also for plot-scripts).
Closes #2215
- Use `config.json` if it exists
- use None only if it really doesn't exist and for allowed subcommands
- Validate that either --config or --datadir is specified for plot commands (download-data requires exchange, so validation for this is different).
> Always use config.json if it's available

- freqtrade/exchange/exchange.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- freqtrade/tests/rpc/test_rpc.py
- freqtrade/tests/rpc/test_rpc_apiserver.py
- freqtrade/tests/rpc/test_rpc_telegram.py
- freqtrade/tests/test_configuration.py
`/balance`  should not fail if None is reported by ccxt, since this is a valid return value according to their documentation.
In addition to that i discovered that Kraken does not correctly report "free" balances, making detecting of available balances impossible.
Details and a possible fix are documented in the Kraken issue https://github.com/freqtrade/freqtrade/issues/1687#issuecomment-528509266
.
Until we have that fix implemented / developed, we will need to block kraken, since trading on it will not be possible.
Close #2225
* fix /balance failure
* block Kraken trading since it's not working due to wrong return values for `get_balance()` calls
> Fix RPC /balance failure

- freqtrade/data/dataprovider.py
- freqtrade/data/history.py
- freqtrade/edge/__init__.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- freqtrade/tests/conftest.py
- freqtrade/tests/data/test_btanalysis.py
- freqtrade/tests/data/test_converter.py
- freqtrade/tests/data/test_dataprovider.py
- freqtrade/tests/data/test_history.py
- freqtrade/tests/edge/test_edge.py
- freqtrade/tests/optimize/test_backtesting.py
- freqtrade/tests/optimize/test_hyperopt.py
- freqtrade/tests/strategy/test_interface.py
- freqtrade/tests/test_misc.py
- freqtrade/tests/test_plotting.py
Freqtrade should not default to test-data from the tests/datadir.
This data is outdated (early 2018, and not a long timerange) - and is never representative of a realistic backtest used today (which must use more recent data!).
part of #2112 - moving tests out of freqtrade module (which will be the next PR).
- datadir is always required (it's also always added to the configuration, so there should not be a problem).
- remove `make_testdata_path()` - and replace it with a fixture returning the correct path
- Adapt all tests to this new way of working.
> datadir should not default to freqtrade/tests/testdata

- freqtrade/strategy/__init__.py
#2235 caused random test-failures (mainly when running `pytest freqtrade/test/test_freqtrade.py` (without randomization).
This is because DefaultStrategy is imported directly, which causes StrategyResolver to reuse the already imported object (importlib seems to do this implicitly).
Since #2235 fixes hyperopt importing however, there is no need for the artificial import causing all this.
Followup to #2235, fixing random test failures
> [minor, important] Fix random test failures

- tests/test_plotting.py
This test fails if `config.json` exists, since we add `config.json` to the passed arguments whenever we find it in CWD().
Closes #2241
> Fix random failure if config.json exists

- build_helpers/publish_docker.sh
Followup to #2236  - forgot that now the docker-image won't have test-data, so the test does not work correctly as visible [here](https://travis-ci.org/freqtrade/freqtrade/jobs/582373246) 
```
No history data for pair: "ETC/BTC", interval: 5m. Use --refresh-pairs-cached option or `freqtrade download-data` script to download the data
```
Small oversight - since this code only runs when a PR is merged to develop.
> Pass test-data to dockerized backtest

- freqtrade/rpc/fiat_convert.py
- tests/rpc/test_fiat_convert.py
Fiatconvert should always return a float (input values can be numeric strings or float).
closes #2239
> Telegram fiatconvert with identical currencies

- freqtrade/configuration/arguments.py
- freqtrade/configuration/configuration.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/resolvers/iresolver.py
- freqtrade/rpc/fiat_convert.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/rpc_manager.py
- freqtrade/wallets.py
- freqtrade/worker.py
Minor code cleanup: no need to inherit classes from 'object' in python3.
> Cleanup: Don't inherit from object

- tests/conftest.py
- tests/exchange/test_exchange.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
This PR eliminates asyncio and aiohttp DeprecationWarnings while testing with pytest.
I also found the aiohttp-pytest plugin, but seems it's not needed...
I found this recipe, but I actually don't completely understand in all details what I'm doing by introducing this change and how it can influence testing of other functionality in the affected tests. Especially, I do not understand while other tests in those modules, just below and above the changed tests, do not require it...
> Eliminate asyncio warnings in tests

- docs/data-analysis.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/configuration.py
- freqtrade/main.py
- freqtrade/optimize/__init__.py
- freqtrade/plot/plot_utils.py
- freqtrade/utils.py
- freqtrade/worker.py
- tests/test_arguments.py
- tests/test_configuration.py
- tests/test_main.py
- tests/test_plotting.py
Simplify configuration (passing a dict instead of `Namespace` to it).
Where possible, we can use `args.get('argument')` instead of having to check everything first.
This will allow simpler (and correct) initialization of configurations in interactive environments (still using `Configuration.from_files([files...])`).
This should also solve #2078, since a simple (sample) configuration can be passed to `from_files()` and will be correctly initialized (including the correct types for data_dir and user_data_dir) - as pointed out in #2228 .
- Use vars(args) to avoid passing around Namespace objects
- Refactor `from_files()` to correctly initialize configuration 
- Add create-datadir to the commands that don't require config to be set.
> Configuration/Arguments refactoing (don't pass Namespace around).

- freqtrade/optimize/backtesting.py
- freqtrade/persistence.py
- freqtrade/strategy/interface.py
- tests/test_freqtradebot.py
It's impossible before to understand from the debug log what's happening with the signals and other sell reasons during backtesting. When the emulated trades start and what pairs sell reasons were found for.
* non-humanized open_date is printed in persistence __repr__. Because for longer intervals '10 months ago' does not say anything useful.
* is_open is set to True for the Trade created in backtesting. @xmatthias please verify that it does not influence something except logging,
* pair set for the Trade created in backtesting.
* pair is always (almost -- in the logs visible during backtesting) printed in the log messages from backtesting and strategies.
* some cosmetics.
* tests adjusted.
> Improve logs for backtesting

- freqtrade/strategy/default_strategy.py
- tests/optimize/test_backtesting.py
Remove indicators from default-strategy that are not used.
Since we now use SampleStrategy as example for users, the default-strategy should contain only indicators that are really needed by the strategy and by some additional tests (bollinger-bands).
This did speed up tests from 43 to ~30 seconds for me, since the default-strategy is analyzed multiple times.
- Remove unused indicators
The comments and additional indicators were intended as a sample for users, however the SampleStrategy should be used for that and is linked throughout the documentation.
> [minor] Test speedup

- tests/optimize/test_hyperopt.py
unit tests, and is your code PEP8 conformant? 
Yes
Change the dataframe fixtures of hyperopt results to more realistic one.
- b7da02a realistic usecase introduce a losing trade (don't associate a profit_percent postive with SellType.STOP_LOSS for example )
- f3e3a8f remove unused datas
Try to create a more realistic dataset fixtures
Have a nice day
> Hyperopt test use case

- freqtrade/configuration/configuration.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- freqtrade/resolvers/hyperopt_resolver.py
- tests/optimize/test_backtest_detail.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_hyperopt.py
- tests/test_configuration.py
* Get rid of `Backtesting.advise_buy`, `Backtesting.advise_sell` -- they are not actually needed and only increase the complexity of the assignments of the attributes between classes. Use `Backtesting.strategy.advise_*` instead.
* Cosmetics for the log messages in the configuration
* Initialization for `hyperopt.backtesting` moved to be performed after hyperopt class is resolved. This will help later fetch stoploss and roi from the hyperopt if/when this will be implemented.
* Tests adjusted.
> minor: Cleanup in backtesting

- docs/data-analysis.md
- freqtrade/configuration/configuration.py
- tests/test_configuration.py
Allow easy printing of loaded configuration
(beforechanging types and applying defaults)
Solve the issue: https://github.com/freqtrade/freqtrade/issues/36#issuecomment-533356803
- keep originally loaded configuration as part of the configuration, so the combined configuration can be plotted easily.
- will enable the configurator mentioned in #2112 - which will require saving the configuration to disk again.
> Allow easy printing of loaded configuration

- freqtrade/configuration/check_exchange.py
- freqtrade/utils.py
- tests/test_configuration.py
- tests/test_utils.py
Download-data requires both exchange and pairs  to be set either directly or through configuration / pairs-file.
If it's not set, we should fail gracefully, not raising key-errors which is not clear for the usre.
Closes #2229
> Gracefully handle download-data startup errors

- docs/backtesting.md
- docs/bot-usage.md
- docs/deprecated.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- freqtrade/data/dataprovider.py
- freqtrade/data/history.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/optimize/hyperopt.py
- tests/data/test_converter.py
- tests/data/test_dataprovider.py
- tests/data/test_history.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_edge_cli.py
- tests/optimize/test_hyperopt.py
- tests/test_arguments.py
- tests/test_configuration.py
As deprecated in #2156, this will remove -r / --refresh-pairs-cached.
Unfortunately not everything depending could be removed since edge still requires to update the data "during edge" in real operations.
This is explained in a TODO and next steps for this are outlined there.
- remove deprecated option -r / --refresh-pairs-cached
- clarify download-data incremental option
> Remove refresh-pairs-cached

- tests/test_utils.py
Fix tests of download-data when config.json is present (which makes them fluky, depending on the environment).
> [minor] Fix tests that fail when config.json is present

- freqtrade/__init__.py
We should use git commits as version for develop. This ensures that it's always uptodate, and we don't need to adjust the version in develop when we do a new relese.
closes #2166 
- use `git describe` to print version if we're on develop (`__version__` is develop
> Apply dynamic versioning to develop

- freqtrade/optimize/hyperopt.py
Fixed the bug which caused serious deviations between hyperopt results and backtesting in same conditions.
Details: Position stacking in hyperopt has not been switched off (was a tuple instead of False).
This is one of those moments when I hate python. Simply hate. 👿 
Imho, quite critical. If the upcoming master release will use one of the previous commits as a baseline, this should be cherry-picked.
> Fix hyperopt position stacking

- freqtrade/optimize/hyperopt.py
Fixes #2271 , #2296 
For the original fix see: https://github.com/scikit-optimize/scikit-optimize/pull/746
Skopt keeps the list of all optimization models found, 
"We store each fitted surrogate model created during each iteration" for people who "need to/want to inspect each surrogate in detail", see https://github.com/scikit-optimize/scikit-optimize/issues/349#issuecomment-293174547
This list is not actually used by our code. Internally, only current model from the estimator is used by skopt.
Skopt is not actively maintained in the meantime, so the fix is added into our hyperopt code as a workaround.
* As a sidechange, the number of iteration is now passed into `generate_optimizer()`, which would allow to make some actions in the worker periodically (cleanup or print logs/stat).
> Fix skopt memory exhaustion

- Dockerfile.pi
- docs/installation.md
- environment.yml
- freqtrade/optimize/__init__.py
- requirements-common.txt
- requirements-dev.txt
- requirements-hyperopt.txt
- requirements.txt
- setup.py
- tests/conftest.py
- tests/optimize/test_hyperopt.py
We require `scikit-learn`, `scipy`, `scikit-optimize` and `joblib` for all installations, although they are only necessary to run hyperopt.
This bloats installation, since these are quite heavy dependencies.
Since they are not needed for regular operations (backtesting / downloading data / ...) they should only be installed intentionally.
This will also improve build-time for the PI image, as they are not included by default.
Closes #2273
- Improve Dockerfile.pi (does not install hyperopt dependencies anymore!)
- split out hyperopt dependencies into it's own `requirements.txt` file
- require `pip install -e .[hyperopt]` or `pip install -r requirements-hyperopt.txt` to install hyperopt dependencies.
- update install documentation to not install using requirements, but instead use setup.py …
> Optional hyperopt dependency installation

- freqtrade/optimize/hyperopt_interface.py
...to be [-0.35, -0.02]
Fixes: #2259
> Shorten the default hyperopt stoploss space

- freqtrade/optimize/hyperopt_interface.py
- freqtrade/resolvers/hyperopt_resolver.py
- tests/optimize/test_hyperopt.py
This PR passes config into hyperopt interface init method and saves it in the attributes.
This will allow to use values from the config in the custom populate_* methods (for example, compare values against stake_amount, use stake_currency for creation the names of the columns, etc. -- all as in the strategies).
> Allow use of config in custom hyperopt methods

- freqtrade/constants.py
- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
As reported on slack, sometimes the amount does not match if an order is filled in multiple trades, and the sum results in a float rounding error.
This can be easily solved by using `math.isclose()` - however since we can have very small numbers, we should set `rel_tol` to a lower floating point to avoid calculation problems.
part of the issue: #1639 (will probably not cover all of it, since this looks at this specific problem).
- Add tests to verify this problem and make sure this won't break in the future
- introduce `MATH_CLOSE_PREC` constant - to have one place to specify this rounding
- use math.isclose() to compare amounts
> Don't compare floats when updating fees

- docs/installation.md
Don't use main.py as entry point in documentation
we should be consistent and always use `freqtrade ...` as commands to execute.
as pointed out in #2302 
- Removed some odd directory changing in cmd documentation
- don't use main.py
> Don't use main.py as entry point in documentation

- freqtrade/configuration/arguments.py
- tests/test_arguments.py
Don't load `config.json` when it's not needed.
- use a "Not_allowed" list to exclude loading config.json for some utils commands where it could cause problems.
> args - Add config no allowed list to skip loading config.json

- freqtrade/configuration/arguments.py
- freqtrade/configuration/check_exchange.py
- freqtrade/configuration/cli_options.py
- freqtrade/exchange/__init__.py
- freqtrade/exchange/exchange.py
- freqtrade/utils.py
- tests/test_configuration.py
- tests/test_utils.py
* The `--all`/`-a` option is added to the `list-exchanges` subcommand, With this option the subcommand prints the list of all exchanges, known to ccxt, including 'bad' exchanges.
* Without this option the subcommand prints only available for Freqtrade exchanges (bad ones excluded)
* Messages of exceptions produced by `check_exchange()` corrected
* Tests adjusted
```
(.env) $ freqtrade list-exchanges
Exchanges available for Freqtrade: _1btcxe, acx, allcoin, bequant, bibox, binance, binanceje, binanceus, bitbank, bitfinex, bitfinex2, bitkk, bitlish, bitmart, bittrex, bitz, bleutrade, btcalpha, btcmarkets, btcturk, buda, cex, cobinhood, coinbaseprime, coinbasepro, coinex, cointiger, coss, crex24, digifinex, dsx, dx, ethfinex, fcoin, fcoinjp, gateio, gdax, gemini, hitbtc2, huobipro, huobiru, …
```
> Add --all option to list-exchanges

- docs/data-analysis.md
- docs/developer.md
- docs/strategy_analysis_example.md
- mkdocs.yml
- requirements-dev.txt
- setup.py
- user_data/notebooks/strategy_analysis_example.ipynb
Add plotting documentation to notebook
- Add plotting section to jupyter notebook
- Add documentation on how to autogenerate markdown documentation from jupyter 
- Split data-analysis into snippets and auto-generated section.
- Restructure Data analysis section of documentation to have sub-points
> add plotting documentation to jupyter notebook

- freqtrade/data/history.py
- tests/data/test_history.py
(Minor) cleanup in the data.history module:
* align the use of the TimeRange parameter, its default value should better be None, not an atrificially created object.
* _load_cached_data_for_updating is made private, since it's "only used by download_pair_history()" as said in the docstring.
* _validate_pairdata() was separated and created mostly to pass mypy.
> Cleanup in data.history

- docs/backtesting.md
- docs/bot-usage.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- freqtrade/edge/__init__.py
- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_edge_cli.py
- tests/test_configuration.py
Allow specifying fee percentage to be applied during backtesting.
This can be usefull if you'r exchange account has some rabates applied (for high volume, for example), which ccxt does not detect (it'll always show the basic fees for each exchange).
This can also be "abused" to add slippage, by specifying a slightly higher value than what the exchange applies.
It can also be applied to test a "ideal" world, where no fees apply (although that is unrealistic).
closes #2223
Remotely related to #1059, which explains behaviour of different exchanges related to this ... this PR only applies to backtesting, so will not fix this issue.
- Add `--fee` parameter to backtest/hyperopt/edge commands
> Backtest no fees / custom fees

- docs/partials/header.html
- docs/stylesheets/ft.extra.css
- mkdocs.yml
Allow selection of different versions in the documentations
https://www.freqtrade.io/en/latest/
closes #1619
- Include jquery - so ReadTheDocs can load the version window correctly
- Add some basic styling since the whole `div` is added via JS later, there is only soo much we can style with JS.
**Note**: Changes to the css file will be cached for 4 hours - so don't be surprised if it does not change immediately.
switch default branch on RTD back to develop!
> Add versions to doc theme

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
* `process_maybe_execute_buy()` renamed to `process_maybe_execute_buys()` because it executes mutiple buys.
* Same for `process_maybe_execute_sell()`, to be symmetric.
* `process_maybe_execute_sell()` (now `process_maybe_execute_sells()`) accepts now the list of trades and iterate through them internally.
* Code of `process_maybe_execute_sells()` cleaned up, pls review.
* "Whitelist is empty." message should not be a warning.
* 'whitelist' was changed to 'active pair whitelist' in some of the log messages. (so probably this is enough to be applied instead of #2313 )
* Tests adjusted accordingly
> Freqtradebot refactoring

- docs/stylesheets/ft.extra.css
Followup to #2353
The underline looks odd as there are also "spaces" with underlines ...
> remove underline from docs style

- config.json.example
- config_binance.json.example
- config_full.json.example
- config_kraken.json.example
- docs/configuration.md
- freqtrade/configuration/configuration.py
- freqtrade/configuration/deprecated_settings.py
- freqtrade/constants.py
- freqtrade/freqtradebot.py
- freqtrade/optimize/hyperopt.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/strategy/interface.py
- tests/config_test_comments.json
- tests/optimize/test_backtest_detail.py
- tests/optimize/test_backtesting.py
- tests/strategy/test_strategy.py
- tests/test_configuration.py
- tests/test_freqtradebot.py
- user_data/strategies/sample_strategy.py
* Experimental settings moved to `['ask_strategy']`.
* The default value for `ask_strategy.use_sell_signal` changed to True (true in json config)
* Docs adjusted (description of `use_sell_signal` slightly improved)
* Tests adjusted
* An error in json schema fixed (it was using `ignore_roi_if_buy_signal_true` instead of proper `ignore_roi_if_buy_signal`)
Resolves #2233 
TODO:
> Move experimental settings to ask_strategy

- docs/rest-api.md
Rest API Documentation contained a command that no longer was available so I removed it from the Doc.
> Updated Rest API Docs

- freqtrade/data/dataprovider.py
- tests/data/test_dataprovider.py
Add tests and typehints (since these are user-facing functions) for dataprovider methods.
The tests cannot guarantee correct returns from the exchange, however we can make sure that the correct ccxt-method is being called.
> Add tests for orderbook and market in dataprovider

- freqtrade/resolvers/strategy_resolver.py
- freqtrade/strategy/interface.py
We keep these options in both config and strategy. 
By using the values from Strategy, we enable hyperopting these values and speed up the code (no dictionary lookups, but attribute gets).
enables further work on #2363 
- use `strategy.*` instead of `config.get(*)`
> Interface options should not use config

- freqtrade/exchange/__init__.py
- freqtrade/exchange/exchange.py
- freqtrade/resolvers/exchange_resolver.py
- tests/exchange/test_exchange.py
Use Mapping-table to load correct exchange subclass (Binance, BinanceUS and binanceJE are identical as far as is known.
closes #2371
> Load correct exchange class for binanceus

- docs/bot-usage.md
- freqtrade/configuration/arguments.py
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
- tests/test_configuration.py
Allow `freqtrade trade --dry-run` to force dry-run mode.
as discussed in https://github.com/freqtrade/freqtrade/pull/2264#issuecomment-541839416.
I opted for option 2, since this keeps the possibility to have this configured in the configuration.
- Add `--dry-run`
- add test for `--dry-run`
once `args_aftersubcommand2` is merged to the feature branch, we'll merge develop into that branch, and redo the command output documentation since other new features have been added.
> Add --dry-run to trade command

- docs/strategy-customization.md
- tests/strategy/test_strategy.py
- user_data/strategies/sample_strategy.py
The Sample strategy  and documentation should try to guide users in the right direction when developing strategies, therefore it's important to have good samples.
Using crossed() as signal avoids generating "sticking" buy-signals.
e.g. you want to buy whe ADX crosses 30 from the bottom - not whenever it's > 30.
This is especially problematic with limited max_trades - since it could buy when ADX > 90 - and sell immediately afterwards.
closes #1364
- Improve Samplestrategy
- improve and comment strategy-customization documentation
> Use crossed() in sample strategy

- freqtrade/constants.py
- freqtrade/freqtradebot.py
- freqtrade/rpc/rpc_manager.py
- tests/conftest.py
- tests/test_freqtradebot.py
in case of partial buys which are cancelled due to timeout, we need to apply the "fee-fix" calculation to the amount as well, otherwise #2383 will happen.
This will need to use the return-value of the `cancel_order()` call (which is the same result - but with `status=canceled`). This makes sure that we use the latest information (at the time of canceling).
It can fall back to the result of the previous `get_order()` call if the order was cancelled already.
In addition, we should also use the same trade-update logic for orders that are cancelled on the exchange, since we cannot be sure that these orders are not partially filled (fixes #1858).
closes #2383
closes #1858
- don't raise OperationalException - this should only be used to stop the bot completely
- add fee-fix logic to …
> Improve buy timeout handling

- docs/backtesting.md
- docs/edge.md
- freqtrade/configuration/timerange.py
- freqtrade/data/history.py
- tests/data/test_btanalysis.py
- tests/data/test_history.py
- tests/optimize/test_backtesting.py
- tests/strategy/test_interface.py
- tests/test_timerange.py
This will remove non-date based timeframe selection (e.g. `--timeframe -200`).
This has no practical usecase outside of tests, users should select a date-range instead.
There is no deprecation period for this, since the option itself is not removed - and i don't think anyone used this when backtesting.
preparation for work on #2311
- Update tests to use date-based timeranges instead
- remove non-date options from timerange parser
- remove non-date based options from history selection
- enable millisecond epoch timeselections (13 digit dates).
> Remove non-date based timeframe selection

- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
exportfilename should default to the configured user_data_dir / backtest_results - not be hardcoded to `cwd()/user_data_dir/backtest_results/`
part of #2112
> exportfilename should respect configured user_data_dir

- freqtrade/data/btanalysis.py
Duration expects minutes - subtracting timestamps results in seconds - so we need to convert this to minutes.
Otherwise, the hover-element of sell trades shows wrong minutes (2400min instead of 40min).
> [minor][plot] Plotting trades from database should show correct duration

- docs/backtesting.md
- docs/requirements-docs.txt
- mkdocs.yml
Fix backtesting doc formatting since sublist does not render correctly on readthedocs.
https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting
> [minor][doc]Fix backtesting format since sublist does not render correctly

- Dockerfile
- requirements-hyperopt.txt
Update image to python 3.7.5 (intentionally not 3.8.0 - since i think we'll need to do some more testing before defaulting to that - however i don't expect many problems).
Reenable hyperopt dependencies in docker image
closes #2385
> Update python base to 3.7.5 and install hyperopt dependencies in docker image

- freqtrade/exchange/exchange.py
- freqtrade/resolvers/exchange_resolver.py
- freqtrade/utils.py
Utils should not run certain validations for the exchange.
There is no need to add another level of exchange classes - it's a simple "flag" mechanism.
replaces: #2368
Resolves #2367
If needed, this can be extended to allow disabling of single checks - so `download-data` can disable different checks than `list-timeframes`.
> Allow skipping of exchange validation

- freqtrade/freqtradebot.py
...during initialization of Freqtradebot.
It's _not_ a solution for #2413, but a bit related.
RPC runs in separate threads, can start handling external commands just after initialization, even before Freqtradebot has a chance to start its throttling, so anything in the Freqtradebot instance should be ready (initialized), including the initial state of the bot.
Initialization of RPC is moved thus to the end of the Freqtradebot initialization method.
> minor: Fix potential race conditions between RPC and Freqtradebot

- config_full.json.example
- docs/configuration.md
- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
Disable repeated log message from default output (makes reading the logs very difficult).
closes partially #2408 (closes it in combination with #2418).
- Switch log-level to Debug for repeated message.
> Change loglevel of repeated message to debug

- docs/configuration.md
- freqtrade/configuration/config_validation.py
- freqtrade/configuration/configuration.py
- freqtrade/constants.py
- freqtrade/freqtradebot.py
- freqtrade/pairlist/VolumePairList.py
- tests/conftest.py
- tests/data/test_history.py
- tests/exchange/test_exchange.py
- tests/pairlist/test_pairlist.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_telegram.py
- tests/test_configuration.py
- tests/test_freqtradebot.py
- tests/test_utils.py
`pair_whitelist` is not mandatory (it's not used at all) if VolumePairList is used.
Improve dynamic pairlist documentation to mention that pair_whitelist is not used and not needed by VolumePairList.
Closes #2414
closes #2413
- Lift requirement of having pair_whitelist if not using `StaticPairList`
- Update docs
> DynamicPairlist - pair_whitelist

- docs/stoploss.md
Improve the stoploss documentation 
closes #2428 
- by simplifying the documentation by not repeating that everything can be set in configuration or strategy
- changing code-samples to python (all user samples i've seen so far use stoploss in the strategy, not from the configuration) - so i assume this is the primary place to configure this
- split `trailing_only_offset_is_reached` from `trailing_stop_positive` to not create confusion
> [Docs] stoploss documentation improvements

- freqtrade/data/btanalysis.py
- freqtrade/plot/plotting.py
- tests/data/test_btanalysis.py
- tests/test_plotting.py
Plot-profit should accept both a backtest result, or a dry-run / live database.
When using the database, the calculation of cumulative profits had a problem which caused 0 profits throughout the dataframe, unless a trade close time accidentally matches exatly a candle.
Solve the issue: #2432 
- Add test making sure we don't break this (again!)
- Resample trades to to timeframe (ticker_interval)
> Plot-profit does not work with db file

- docs/backtesting.md
- docs/strategy-customization.md
- freqtrade/configuration/timerange.py
- freqtrade/data/history.py
- freqtrade/edge/__init__.py
- freqtrade/exchange/exchange.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/strategy/default_strategy.py
- freqtrade/strategy/interface.py
- tests/data/test_history.py
- tests/edge/test_edge.py
- tests/exchange/test_exchange.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_hyperopt.py
- tests/test_timerange.py
- user_data/strategies/sample_strategy.py
Since most indicators need a startup-period, freqtrade should know about it and handle this accordingly.
This PR adds the `startup_candle_count` attribute to the strategy, which should be set to the maximum any indicator looks back.
Backtesting then tries to load data earlier than the specified date - or moves the date by the specified amount of candles into the future.
closes #2311
- Document this behaviour and attribute
- move date by `startup_candle_count` in backtesting, hyperopt and edge
- Refactor data loading in backtesting / hyperopt to reduce code duplication 
- add validation to make sure strategies can run on an exchange (based on the specified startup candle count - with an offset of 5 candles).
> Add Startup period for strategies

- freqtrade/exchange/__init__.py
- freqtrade/exchange/common.py
- freqtrade/exchange/exchange.py
- tests/exchange/test_exchange.py
Clean up the exchange file by moving constants to a seperate file.
I'm considering to also move all "non-class" functions from the bottom of the file to this file in the future to keep `exchange.py` focused on the exchange class itself.
- move exchange Constants to `exchange/common.py`
- move retrier decorators to new file
> Move exchange-constants and retriers to exchange.common

- .travis.yml
- docs/configuration.md
- docs/data-download.md
- docs/docker.md
- docs/installation.md
- docs/plotting.md
- docs/rest-api.md
- docs/strategy-customization.md
- docs/telegram-usage.md
Update documentation to install freqtrade on a raspberry.
The instruction was overly complex, and without hyperopt "regular" installation works just fine.
Also fixed some "box"-titles which were not rendering correctly.
> [docs] Update Raspberry documentation

- docs/configuration.md
- freqtrade/freqtradebot.py
"stoploss on exchange limit" should be configurable and not default to 1% without an easy way to modify this.
closes #1717
- add option within order_types to configure stoploss-limit
> Allow configuration of stoploss on exchange limit

- docs/strategy-customization.md
- freqtrade/data/btanalysis.py
- freqtrade/freqtradebot.py
- freqtrade/persistence.py
- freqtrade/rpc/rpc.py
- tests/test_persistence.py
`scoped_session` from sqlalchemy is a powerfull construct, allowing thread-safe handling of Sqlalchemy objects **if done correctly**.
freqtrade did not - initializing an explicit session and assigning this to `Trade.session` - breaking the scoped-session thread-safe functionality.
This caused problems like #1986 - which effectively is a race-condition (coincidental flushing of both the main and Telegram thread).
Closes #1986
closes #1753
- Introduce `Trade.get_trades()`
- Fix `scoped_session` handling
- extract SQL handling from rpc module
- Add documentation for the new query methods (#closes 1753)
> Fix scoped_session and add Documentation for strategy

- docs/strategy_analysis_example.md
- freqtrade/data/btanalysis.py
- tests/data/test_btanalysis.py
- tests/optimize/test_backtesting.py
- user_data/notebooks/strategy_analysis_example.ipynb
Expose the algorithm to get max_open_trades at each candle to users.
Closes #2449
- Add `analyze_trade_parallelism()`
- Document `analyze_trade_parallelism()` as part of the juptyer notebook (Export of the notebook is in `strategy_analysis_example.md `).
> Bt analysis maxopen at any time

- freqtrade/configuration/check_exchange.py
- freqtrade/configuration/config_validation.py
- freqtrade/configuration/configuration.py
- freqtrade/state.py
- freqtrade/utils.py
We have 2 types of Utils - the ones that use exchange, and the ones that don't.
This info is relevant for certain configuration validations ... which should (or should not) happen for util commands.
It'll allow us to use `setup_utils_configuration()` for new utils without breaking in certain "config" cases.
While this may seem "random" ... it's extracted from a new cool util i'm working on ... where i faced EXACTLY this problem.
I can also keep this commit there ... but for clarity's sake i guess it's better to have it seperate.
Second part:
Also, certain startup messages don't make sense for utils ...
when running `list-timeframes`, i don't care about dry-run or database url ...
This tries to address this, but is probably by no means complete, so further updates to this may follow …
> [minor] Add new runmodes

- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtest_detail.py
Fix pandas access warning during backtesting.
While it's not a problem in our case, it's still unnecessary output which can be avoided VERY easily.
```
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
pair_data['buy'], pair_data['sell'] = 0, 0  # cleanup from previous run
/home/xmatt/.pyenv/versions/3.7.3/envs/trade3.7.3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```
Solve the issue: (brought up on slack ...)
- use .loc[] to reset dataframe
> Fix pandas access warning

- freqtrade/configuration/check_exchange.py
- tests/test_configuration.py
Other is only used for "custom" commands, probably run from a REPL or interactive environment.
For this, we can omit checking exchange. This will allow loading a base Configuration easily as follows:
``` python
from freqtrade.configuration import Configuration
Configuration.from_files([])
```
closes #2078
- don't check exchange for Runmode Other.
> Don't check exchange for Utils commands

- docs/docker.md
Explain to end user docker is able to have a restart policy for the container and that the 
`unless-stopped` policy could be useful.
Have a nice day.
> Update docker doc (new note about restart policy)

- freqtrade/configuration/__init__.py
- freqtrade/configuration/check_exchange.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/utils.py
- tests/test_configuration.py
- tests/test_utils.py
we should only have one place to remove credentials from the configuration.
This will reduce code duplication, and will allow easy circumvention should this be needed for some tests.
closes #2474 
- have one place to remove credentials (api keys , ...).
> Introduce remove_credentials to remove code duplication

- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
Depending on the system locale settings, we can encounter UnicodeErrors during hyperopt output. This is caused by the Sigma (sum sign) - which cannot be converted to some non-utf8 encodings.
To fix this, we can convert the data to the users configured locale - and back.
On "supported" systems (utf-8 locale) - the output will be as usual 
```
*    1/5:     72 trades. Avg profit  0.29%. Total profit  0.01064443 BTC (  21.24Σ%). Avg duration  69.6 mins. Objective: 1.86128
```
On unsupported systems, the "non-displayable" sign is converted to a questionmark
```
*    1/5:     72 trades. Avg profit  0.29%. Total profit  0.01064443 BTC (  21.24?%). Avg duration  69.6 mins. Objective: 1.86128
```
This is visible [here](https://github.com/xmatthias/freqtrade/commit/e02e970ba0348e88eaa53e83e8d193dac …
> [minor] Fix UnicodeError in hyperopt output

- docs/installation.md
Hi,
- I have try to explain the differences between master and develop.
- I have delete the `git checkout develop` as we are already in this branch when cloning so we tell the end user to do something that has no impact and so confusing.
> Prepare reorg install doc : explain differences between master and develop

- README.md
- docs/advanced-setup.md
- docs/configuration.md
- docs/data-download.md
- docs/exchanges.md
- mkdocs.yml
Add a seperate exchange section in the documentations, where we can combine exchange-specific informations.
Currently this is distributed all around in the documentation - which is a pain if someone has a question and you seem to remember that we have it documented...
- move exchange-specific infos to seperate document
closes #2480
> [docs] Add seperate exchange section in docs

- docs/exchanges.md
- docs/faq.md
add snippet to get restricted pairs from bittrex to exchange.md
more info:
https://github.com/freqtrade/freqtrade/issues/2074#issuecomment-552307926
Solve the issue: #2074
> Add restricted markets snippet to documentation

- docs/faq.md
This was not noticed in terms of #2505
> minor: Fix link in the Faq docs

- tests/rpc/test_rpc_manager.py
Sometimes, this test is fluky (especially in CI).
I think this is related to `thread.start()` - which may not execute the run-mock in time if resources are low. 
Adding a half-second delay to this should help mitigate these random failures.
> [minor] Add sleep to allow thread to start

- freqtrade/rpc/api_server.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc.py
Cleanup of `/status table` and addition of fiat currency.
Closes  #464
- removes need to import DataFrame in rpc areas
- Cleanup of rpc (Decimal conversation is not needed here)
- add fiat-currency output to status_table.
> Add fiat to status table

- freqtrade/exchange/__init__.py
- freqtrade/exchange/bibox.py
- freqtrade/exchange/exchange.py
* Particularly, fixes #2474 
* <s>Adds a generic mechanism to override the ccxt exchange API metadata info (ccxt exchange `has` options). Can be useful/needed for other exchanges in the future.</s>
* Add a generic mechanism to specify exchange-specific part of ccxt_config in the exchange-specific class, which is then merged with custom ccxt_config/ccxt_async_config from user's config.
Command to test:
```
freqtrade list-pairs --exchange bibox
```
> Add fix for bibox exchange

- freqtrade/freqtradebot.py
unfilledtimeout is a mandatory key in config, so checking for it before running the timeout sequence does not make sense.
In addition to that, not running this part would break the "order cancelled on exchange" logic.
Also, the logic is identical for buy and sell orders - so this can be refactored into it's own method, which will simplify the whole logic.
- Extract comparison logic 
- simplify `check_handle_timedout()`
> Improve timedout handling

- freqtrade/data/history.py
- freqtrade/plot/plotting.py
Plot-profit fails if a pair has only one trade and that trade is still open.
we can mitigate this by filtering this out. The trade would not be counted anyway, since the profit is not yet known (and resample on close-time would not work).
Also, trades should be filtered by timerange if one is given.
Solve the issue: From slack ...
- Remove duplicate loading
- filter out open trades
- Filter by timerange
> plot-profit script fails in certain conditions

- freqtrade/main.py
- freqtrade/utils.py
- tests/test_utils.py
since we're now calling `freqtrade trade` - worker does not exist in main anymore, causing bots to "not stop" when used with telegram and trying to sigint the bot.
Solve the issue: from slack ...
- Move keyboardinterrupt and `worker.exit()` to `utils.py` (where it belongs).
> Fix non-terminating bot

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
cancel_order responses are not necessarily full "get_order" calls (kraken only returns a status).
closes #2555 #]
- Handle case where cancel_order response does not have certain keys (falls back to original order - which is a result of a `get_order` call moments before
- add test for this behaviour
> Fix 'remaining' bug when handling buy timeout

- .github/workflows/ci.yml
Slack notifications from Forked repositories don't work and cause CI failures.
reason: secrets are currently not available to forked repositories - so cannot use slack notifications ...
> FIx failure for PR's from forked repositories

- tests/test_plotting.py
This always created the "plots" folder in user_data ... when running tests.
It's not used anywhere other than in this test ...
> [minor] Adjust plotting test to match user_data folder

- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
Add saving epochs at intermediate points:
* after best epoch found
* every 100 epochs
Also,
* fixed handling of Ctrl+C pressed before first epochs were evaluated (and after skopt deprecation messages -- previously this produced an error with a backtrace printed).
Part of #2464
> Hyperopt: Save epochs at intermediate points

- .github/workflows/ci.yml
- freqtrade/configuration/deprecated_settings.py
Followup to #2442 ... we should allow a "smooth" transition from "very old" configs (no explicit pairlist selection) to the new pairlists method.
So if neither pairlists - nor "pairlist" is configured, we add staticpairlist as default for now (this used to be the default in the past, too).
Also trying to fix coveralls (if it comments here, anyway).
closes #2567
> Pairlists transition

- freqtrade/rpc/api_server.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- freqtrade/wallets.py
- tests/conftest.py
- tests/pairlist/test_pairlist.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
`/balance` should not fail if a pair has no bid.
`/balance` also does not need to call each `fetch_ticker()` once - but can use the `fetch_tickers()` method, which will fetch all tickers at once (so it's one call, instead of one per owned currency).
This will also handle "non-bid" situations - where bid is empty as seen in #2515 .
closes #2515 
- `/balance` should not fail if a pair has no bid.
- `/balance` also does not need to call each `fetch_ticker()` once - but can use the `fetch_tickers()` method, which will fetch all tickers at once (so it's one call, instead of one per owned currency).
- Allow "empty" bids - these pairs will be filtered from the output though.
- Use stake_currency instead of hardcoding to BTC (if you trade ETH as your stake - you're probably not interrested in the …
> /Balance rework

- freqtrade/freqtradebot.py
- tests/conftest.py
- tests/test_freqtradebot.py
Fixes #2575 
Markets in the conftest changed, since current limits set there causes many tests to fail -- the orders cannot be created because their amounts are less than those limits in the markets.
The rest of failing test cases should be carefully reviewed and adjusted.
> Fix _get_min_pair_stake_amount

- docs/bot-usage.md
- docs/configuration.md
- freqtrade/configuration/config_validation.py
- freqtrade/configuration/configuration.py
- freqtrade/constants.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/rpc/api_server.py
- tests/pairlist/test_pairlist.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_manager.py
- tests/rpc/test_rpc_telegram.py
- tests/rpc/test_rpc_webhook.py
- tests/test_configuration.py
- tests/test_freqtradebot.py
Since configuration options can come from multiple sources (cli, config file(s), strategy) - we need to validate the configuration after all possible sources have applied.
This will allow to specify mandatory options flexibly in the config validation dict - without manually coding the checks required.
Closes #2531
Closes #2532 (Defaults are now only in the documentation where they apply!) 
Improves visualization of config documentation (one fewer column).
- Validate after strategy is loaded - this can change options so we need to validate after that, not before.
- This needs to be called from backtesting / trade / edgecli seperately
- Reevaluate some minimum values
- Reformat configuration documentation to be 2 columns only (default-values are now specified in the description - and only …
> "fix" config validation

- docs/advanced-hyperopt.md
- docs/hyperopt.md
- mkdocs.yml
The docs on Hyperopt will be better structured and easier for an ordinal user if we move some sophisticated parts that are rarely needed and require higher coding skills and Python knowledge to a new Advanced Hyperopt chapter. (Only one such part for now actually -- the section describing the Creation of a custom loss function)
> Move docs on loss function creation to a separate doc file

- freqtrade/data/history.py
- tests/data/test_history.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_hyperopt.py
`load_pair_history()` should have predictable return values, so returning an empty DataFrame does make more sense than None (it also makes checking easier, as `len(data)` can be applied without type-error risks.
closes #2609
- Return empty dataframe if no data is found.
> Don't return None from load_pair_history

- docs/backtesting.md
- docs/configuration.md
- docs/utils.md
- freqtrade/configuration/arguments.py
- freqtrade/pairlist/PrecisionFilter.py
- freqtrade/utils.py
- tests/test_utils.py
Configuring pairlists can be quite complex, and different sequences of configurations can generate different results. 
To test these quickly, a new subcommand, `freqtrade test-pairlist` will be introduced.
This will also solve #935 (althought through a manual step) to use a dynamically generated pairlist for backtesting. For that, simply use `freqtrade test-pairlist` and insert the output as pair_whitelist into the configuration.
Closes #935
- new subcommand
- Document usage of this command
> Subcommand: test-pairlist

- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
We support loading ticker_interval from the strategy - so i have it in almost none of my configurations.
However it fails with hyperopt - since the strategy is loaded after the hyperopt file.
By simply reversing the order of initialization between the custom hyperopt file and backtesting, we can support this again.
- fix bug
- add test ensuring we're not reintroducing this
> Fix hyperopt with ticker_interval from strategy

- docs/hyperopt.md
Document the "quick" hyperopt mode - without modifying the default hyperopt template.
Works only for ROI / stoploss / trailing stoploss spaces (not for buy / sell).
closes #2231
**Note:** I hope this renders correctly in the docs (codeblock within the "tip"-box), otherwise we'll need to move this as it's own header.
> Document "quick" hyperopt of roi/stoploss and trailing stoploss

- freqtrade/configuration/config_validation.py
- tests/test_configuration.py
We should verify that only correct pairs are in the whitelist.
Otherwise backtesting may have irritating results (#2622) - and it'll result in the static-pairlist outputting "removing pair from whtitelist" once per iteration for all incompatible pairs.
Closes #2622
- Check that pairlist only contains pairs with correct stake-currency
> Validate stake-currency against pairlist

- build_helpers/publish_docker.sh
DOcker image latest has not been pushed anymore.
[dockerhub](https://hub.docker.com/r/freqtradeorg/freqtrade/tags).
We used to push latest along with develop, and we should continue to do that.
(100% correct functioning can only be tested once it's merged, since we only run deploy then) - but i'm confident that it works, since the develop-tag is pushed correctly.
> Docker: Build latest along with develop image

- freqtrade/optimize/hyperopt.py
- freqtrade/optimize/hyperopt_interface.py
- tests/optimize/test_hyperopt.py
Fixes #2617.
Also, limits (boundaries) for dimensions changed:
```
Real(0.01, 0.35, name='trailing_stop_positive'),
```
-- min boundary is 0.02 in develop;
and
```
Real(0.001, 0.1, name='trailing_stop_positive_offset_p1')
```
-- this is the new dimension for the difference between `trailing_stop_positive_offset` and `trailing_stop_positive`. Thus, the `trailing_stop_positive_offset` can be in range '0.011...0.45'. Pls review it.
TODO:
> Fix generation of hyperopt trailing params

- freqtrade/exchange/exchange.py
- tests/test_freqtradebot.py
Round amount to precision also for dry-runs - so it's more realistic.
otherwise we can have amounts with 100ds of decimals - since amount-rounding happens within create_trade - which is never reached in dry-mode.
- apply Amount to precision for dry-run trades.
> Round amount to precision also for dry-runs

- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc_telegram.py
Improve output of /show_config when trailing_stop is on.
We should not just show the stoploss, but also the parameters of the trailing stoploss.
> improve show config when using trailing stop 

- docs/hyperopt.md
- freqtrade/optimize/hyperopt.py
Define random_state explicitly in `start()` if not passed in the cli or config.
Log the value.
To be able to reproduce results in any case.
TODO:
> Seed hyperopt random_state if not passed

- freqtrade/rpc/telegram.py
The output currently contains a trailing tick (') after the strategy. ...
Erroneous output:
> [minor] Fix typo causing a trailing "tic" in /show_config output

- freqtrade/edge/__init__.py
- freqtrade/exchange/exchange.py
- freqtrade/optimize/backtesting.py
- tests/edge/test_edge.py
- tests/exchange/test_exchange.py
get_fee for backtesting and edge should not use ETH/BTC, but the first pair in the pairlist instead.
closes #2653
- Send first pair from pairlist as symbol to `get_fee()`
> Use first pair of pairlist to get fee

- docs/backtesting.md
- docs/configuration.md
- freqtrade/optimize/backtesting.py
- freqtrade/strategy/interface.py
- tests/optimize/test_backtest_detail.py
This adds speific handling for ROI=-1 (using close when the roi-entry falls on a candle open and ROI = -1.
We should document ROI=-1.
Closes #2277 
- document usage of ROI=-1 as forcesell method
- Refactor `_get_close_rate()` out of `_get_sell_trade_entry()`
- use open if the forcesell entry is a candle open, else low (as before).
> handle and document ROI=-1

- freqtrade/optimize/backtesting.py
Fix mypy error after #2624 
How could this happen with all our travis checks?
The problem actually is not the mypy by itself, but the error in the code where can fail when the users run backtesting...
> [critical]: Fix mypy errors in develop

- freqtrade/data/history.py
- freqtrade/utils.py
- tests/data/test_history.py
Small cleanup of code in this module: alignment of download_pair_history/download_trades_history and refresh_backtest_ohlcv_data/refresh_backtest_trades_data.
(Further they could/should be merged together to remove code duplication)
> Minor: improvements in data/history.py

- docs/developer.md
- docs/exchanges.md
Document how to get incomplete candles within a strategy (and warn about the dangers of these).
Closes #2202
- Add docs about `ohlcv_partial_candle`
- improve documentation how to discover incomplete candles from a exchange return value.
> Add documentation about ohlcv_partial_candle

- freqtrade/data/btanalysis.py
- freqtrade/freqtradebot.py
- freqtrade/optimize/backtesting.py
- freqtrade/persistence.py
- freqtrade/rpc/rpc.py
- freqtrade/strategy/interface.py
- tests/rpc/test_rpc_apiserver.py
- tests/strategy/test_interface.py
- tests/test_freqtradebot.py
- tests/test_persistence.py
Based on the initial work of #2650 (but new commits, since the previous commits are no longer accessible somehow due to forcepush...).
Removes ~10% as pointed out in #1016 from backtesting (similar enhancement will apply to hyperopt...
closes #1016
- Calculate open_trade_price (which includes fee) only once per trade and persist this in the database
- removal of unused `fee` argument from `_calc_open_trade_price()`
- Rename `calc_profit_percent()` to `calc_profit_ratio()` - since it does not return a percent value, but a ratio.
> Pre-calculate open_trade_price

- freqtrade/data/history.py
- freqtrade/edge/__init__.py
- tests/data/test_history.py
- tests/edge/test_edge.py
- tests/optimize/test_backtesting.py
... from `load_data()`
New `refresh_data()` function introduced, which is used in Edge (besides tests).
No exchange is to be passed (and checked for None) into `load_data()`
> Dataprovider history: split refresh part

- freqtrade/data/history.py
- freqtrade/edge/__init__.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- tests/data/test_converter.py
- tests/data/test_history.py
- tests/optimize/test_backtest_detail.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_hyperopt.py
Follows #2678 and #2346 
* Removal of Optional in the type of exchange argument; removal of checking for exchange is None.
* `get_timeframe` renamed to `get_timerange` because it calculates and returns boundaries of the common timerange, not a timeframe as we use this term.
* type of the value returned by `load_tickerdata_file` clarified.
> Minor improvements in data.history

- .github/workflows/ci.yml
This will reenable Pull request comments when the PR comes from a foreign repository.
I really really don't like that we have to hardcode the token ... 
but github actions currently do not allow passing secrets to PR's from forked repositories.
on the other hand, this token allows only access to the coveralls repository site - and it's quickly rotated should something go wrong ...
> Try to get comment from forked repos

- freqtrade/optimize/edge_cli.py
timerange is never used within edge-cli - only from within edge - so we can assign it directly.
> [minor] Edge small cleanup

- docs/bot-usage.md
- freqtrade/configuration/cli_options.py
- freqtrade/configuration/configuration.py
Mixing underscores and dashes in the cli options is at least is of bad style.
* `--max_open_trades` --> `--max-open-trades`
* `--stake_amount` --> `--stake-amount`
* Also, description for the options in the helpstrings improved.
P.S. (Not in this PR) I would deprecate and then remove `--stake-amount`. Since all other options that define stake amount for backtesting are defined in the config. Especially after upcoming implementation of relative stake amount (#2458).
First one (`--max_open_trades`) in the cli may theoretically have sense to see quickly differences in the backtesting to define max value of this parameter which may be needed in the example of the backtesting period.
> Minor: Please no underscores in cli options

- docs/configuration.md
- freqtrade/resolvers/strategy_resolver.py
Allow supplying unfilledtimeout from the strategy.
Since it passes the config validation afterwards, no further checks should be required.
Closes #2513
- Allow passing `unfilledtimeout` via strategy (needs to be removed from the configuration first, obviously).
> Add unfilledtimeout to strategy overrides

- docs/strategy-customization.md
- freqtrade/strategy/interface.py
- tests/strategy/test_interface.py
Document usage of custom pairlocks, and slightly improve handling of it. The bot should never be allowed to lower the lock (it's not needed for internal use, and should not override external usage).
Closes #2582 
* Don't allow lowering the time once a lock is in place (use `unlock_pair()` instead)
* Implement an easy way to remove a pair from the lock (`unlock_pair()`).
* Documentation example for this method
> Improve pairlocking mechanism to allow usage from within strategy

- docs/strategy_analysis_example.md
- freqtrade/freqtradebot.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/edge_cli.py
- freqtrade/optimize/hyperopt.py
- freqtrade/pairlist/pairlistmanager.py
- freqtrade/plot/plotting.py
- freqtrade/resolvers/exchange_resolver.py
- freqtrade/resolvers/hyperopt_resolver.py
- freqtrade/resolvers/iresolver.py
- freqtrade/resolvers/pairlist_resolver.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/templates/strategy_analysis_example.ipynb
- freqtrade/utils.py
- tests/conftest.py
- tests/exchange/test_exchange.py
- tests/optimize/test_hyperopt.py
- tests/pairlist/test_pairlist.py
- tests/strategy/test_strategy.py
Creating an instance of the resolvers is not necessary, since we're just calling a few methods in sequence and then return exactly one result.
Also, if the resolver does not move out of scope it'll be kept in memory for the whole run-time of the bot ... which is unnecessary.
- Convert resolvers to static classes, using a `load_*()` method instead of `__init__()`.
> Refactor resolvers to static resolvers

- freqtrade/wallets.py
- tests/test_integration.py
The bug causes closed trade balances to stick around since the balance is never reset (it's not in open trades, and we don't loop closed trades).
When then calling /balance after some time, you'll see more than `max_open_trades +1` assets in the list - and the total amount does not correspond to the real value.
This can simply be mitigated by recreating the whole wallet dict.
- Recreate wallet dict and replace it after calculations
- Update integration test to include testing dry-run wallet (that's what integration tests are for, no?)
> Fix bug in dry-run wallet 

- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc_telegram.py
Align /balance output to show everything in stake currency the conversation to BTC does not make sense
- fix typo
- convert total amount to stake-currency instead of BTC
> /balance should not convert to BTC

- docs/backtesting.md
- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtesting.py
Enhance backtest result with sell-reason profit / loss statistics.
This can be show important details for certain types of sell reasons (mainly trailing stoploss and sell-signal) and will help to determine which area of the strategy can be worked on to be improved.
e.g. if most sell-signals produce losses, and all gains come from ROI, it may be best to try the strategy without sell signal.
- add sell reason counts to output
> backtesting - Sell reason counts

- docs/configuration.md
- docs/edge.md
We should use the same style when documenting a set of configuration options.
Also renamed the Header of the tables to Parameter instead of Command - since these are parameters / configurations, not commands.
##
* convert edge documentation to table
* newline before "Keep it seecret" to improve appearance in the doc pages
> Align Edge documentation to configuration page

- freqtrade/exchange/exchange.py
- tests/exchange/test_exchange.py
Markets.info does not need to be a dict - but contains the raw content from the exchange - in case of gemini, that's a string, so we need to verify the type here first.
closes #2716
- Ensure we're not failing when markets.info is not a dict.
> Check if markets.info is a dict before using it

- freqtrade/configuration/configuration.py
- freqtrade/configuration/directory_operations.py
- freqtrade/data/dataprovider.py
- freqtrade/edge/__init__.py
- freqtrade/optimize/backtesting.py
- freqtrade/plot/plotting.py
- freqtrade/utils.py
- tests/test_configuration.py
Currently, we convert datadir to Path every time we use it.
By converting when config is initialized, we can avoid this 100fold conversation.
It's a real / visible performance improvement - but it's unnecessary and clutters our code with unnecessary Path() calls and imports.
> Convert datadir within config to Path

- docs/utils.md
- freqtrade/configuration/arguments.py
- freqtrade/resolvers/exchange_resolver.py
- freqtrade/resolvers/hyperopt_resolver.py
- freqtrade/resolvers/iresolver.py
- freqtrade/resolvers/pairlist_resolver.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/utils.py
- tests/optimize/test_hyperopt.py
- tests/strategy/test_strategy.py
- tests/test_utils.py
Add list-strategies subcommand allowing to list all strategies in a folder.
Default output is a table, but machine-readable `--one-column` output is available as well.
- Refactor resolvers further to use class-mehods to reduce code duplication
- Combine `_load_*()` methods into a generalized one (apart from load_strategy due to loading from base64)
- Allow `IResolver._get_valid_object()` to work without a name, where it returns all valid objects within that file
- move module instanciation to `_load_object()` to support searching modules without initializing them.
> add list-strategies subcommand

- freqtrade/freqtradebot.py
- freqtrade/rpc/rpc.py
- tests/test_freqtradebot.py
* Cleanup logic in get_trade_stake_amount()
* Introduced new _check_available_stake_amount(), _calculate_unlimited_stake_amount() and get_free_open_trades() methods that encapsulate appropriate parts of business logic.
* This does not (should not) change behavior (business logic), except the change for max open trades in process(). Currently, if max open trades is reached AND some trades are sold before processing buys, the buys will only be processed at the next throttling iteration. New behavior: we have some free open trade slots right after trades sold so we can process buys right at this throttling iteration. This is due to the call to get_free_open_trades() method made again before we proceed to buys instead of comparison of the length of the trades array, which is collected before …
> Minor: code cleanup in freqtradebot

- freqtrade/rpc/rpc.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_telegram.py
If no trade is open we should not show "no active order" - but "no active trade" instead, since it's not about orders, but trades.
Funnily, `/status` shows it correctly now, but `/status table` shows "no active order".
> [minor]Fix misinformation in /status table

- freqtrade/templates/base_strategy.py.j2
- freqtrade/templates/sample_strategy.py
we should have `trailing_stop_positive_offset` in the sample strategy (and template) too - it's an important setting with trailing_stoploss and should be set intentionally to true or false
- add `trailing_stop_positive_offset` to sample and template
> [minor] Add trailing_only_offset to template and sample

- freqtrade/optimize/edge_cli.py
- tests/test_utils.py
Edge-cli should use Exchangeresolver just as everything else.
Also added a small debug-assert trying to find the root-cause for the random test-failures (which are not reproducible with the same random seed).
> [Minor] Edge-cli should use exchangeresolver

- freqtrade/freqtradebot.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
- tests/test_integration.py
This PR refactors the `create_trades()` method of Freqtradebot (continuation of #2718):
* move `for pair` loop to `process_maybe_execute_buys()` from `create_trades()`. This aligns `process_maybe_execute_buys()` to be similar in the structure to `process_maybe_execute_sells()`, it also contains the loop for pairs (trades) and calls `handle_*()` methods that work for single trade (pair).
* `create_trades()` renamed to `create_trade()` accordingly
* tests adjusted
* handing of DependencyException improved. Currently, if this exception happens during creation of a trade for any pair, this terminates the whole `for pair` loop and other trades can only be processed at the next throttling iteration (where same exception can also happen).
The changes are quite simple, but not very visible in the …
> Refactor create trades

- setup.sh
We've forgotten to align the message printed in setup.sh to reflect new cli option rules.
From Slack.
> Minor: Fix message in setup.sh

- freqtrade/data/btanalysis.py
- tests/data/test_btanalysis.py
Align columns between `load_backtest_data()` and `load_trades_from_db()` where content is aligned (profit) - reported on Slack a while ago.
Also removes an obsolete folder in user_data i've accidentally (on purpose) discovered...
> Btanalysis align columns

- freqtrade/plot/plotting.py
- tests/test_plotting.py
Even though the column is called profit_perc - it contains a ratio in both cases (from DB or from backtest result.
- Plotting - fix incorrect visualization showing stoplosses of 0.05% instead of 5%
> show percent in sell hover message.

- freqtrade/freqtradebot.py
* Introduce `_notify_buy()`, which is aligned to existing `_notify_sell`. This simplifies the code in `execute_buy()` a bit, since no configuration params that are needed only for notification should be fetched there.
* Minor cleanup of creation the sell msg
To be discussed/possibly fixed (changed) here, pls review this separately:
* should not the call to `_notify_buy()` be moved in `execute_buy()` to be at the end, right before `return`? Or after `Trade.session.add()` and `Trade.session.flush()` to contain data possibly updated by `self.update_trade_state()`? Now it's left in its place to have same info as in the current implementation...
> Cleanup buy/sell notification in freqtradebot

- docs/backtesting.md
Fix documentation - `--fee` is not a percentage but a ratio.
Also include a note that this parameter is usually gotten from the exchange.
closes #2738
> Update Backtesting fee documentation

- freqtrade/configuration/config_validation.py
- freqtrade/constants.py
- freqtrade/utils.py
- tests/test_configuration.py
Run config validation with a reduced set of required properties for Utils too.
This has the advantage that we can rely on "default" properties in the conf_schema to properly populate the attributes for utils, too.
- Split "required" list in schema into 2
- Run validation for utils
> Config validation split

- freqtrade/optimize/backtest_reports.py
- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtest_reports.py
- tests/optimize/test_backtesting.py
By removing the backtest "output" functions from the backtesting class, this class becomes a lot easier to manage.
It'll improve overview more than anything - there is no other functional benefit at the moment.
> Extract backtest reporting

- freqtrade/configuration/config_validation.py
- freqtrade/constants.py
- freqtrade/exchange/exchange.py
- tests/conftest.py
- tests/exchange/test_exchange.py
We should not hardcode timeframes nor stake-currencies. THey vary by exchange, so we should use what the exchange gives us.
Closes #2757
closes #1861 
- Use timeframes from the exchange
- Use quote-currencies from the exchange
- Limit freqtrade to work on timeframes >1m (lower than that is very risky and does currently produce errors since we assume minute in certain places (for example when resampling). While these could be easily fixed, i don't think trading <1m with freqtrade is something that can be profitable.
- Remove some occurences of empty `MagicMock()` in `mocker.patch()` calls (it defaults to MagicMock() anyway).
> Remove hardcoded exchange parameters

- freqtrade/rpc/rpc.py
- freqtrade/wallets.py
- tests/test_wallets.py
Conditinoally refresh balances on /balance calls.
The configured value of 1h is not configurable (intentionally) as allowing this too often may result in exchange bans. wallets are refreshed before trading (buy / sell) actions to ensure we have the latest balance, so this applies only for `/balance` rpc calls.
Closes #2756
- Add conditinonal update possibility for wallets.update
- Call wallets.update() from /balance.
> refresh wallets on /balance call

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
We MUST compare selling amount to wallet amount with >= (not >) - otherwise regular trades without "dust" are unable to be sold.
supports #2770
- Fix bug
- add test
> Fix bad bug in safe_sell_amount

- freqtrade/freqtradebot.py
- tests/rpc/test_rpc.py
- tests/test_freqtradebot.py
- tests/test_integration.py
When using wallets.get_free() we need to ensure that the wallet is uptodate.
A stoploss on exchange is cancelled milliseconds before executing `_safe_sell_amount()` - so the amount on the exchange will not be free at that time.
This will also revert the log-message to debug - however show the amounts as part of the exception (that's where we really need them - when it fails, not when it works).
closes #2770
> Safe sell amount update wallet

- freqtrade/optimize/optimize_reports.py
FIx a typo in sell_reason table generation that's causing a warning to be shown in the middle of the table.
Closes #2789
> Fix typo in sell-reason table generation

- freqtrade/templates/sample_hyperopt_loss.py
It's just one missing word I added
> added missing word in hyperopt loss example

- freqtrade/freqtradebot.py
- freqtrade/rpc/rpc.py
Since forcesell calls `execute_sell()` we need to update wallets after this to avoid keeping the old wallet status until the next action happens. 
It's not a problem if the order doesn't fill immediately since `update_trade_state()` will update the state too - but it's a problem if the order does fill immediately, as then we close the trade.
In regular operations, wallets are updated after handling all "sellable" trades - but that's not the case with forcesell.
closes #2793
* call wallets.update when /forcesell is completed
* implement threading.lock object to avoid stoploss recreation when /forcesell is being used
> update wallets after forcesell

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- tests/optimize/test_backtest_detail.py
- tests/optimize/test_backtesting.py
Extract the first 2 commits from #2658. 
These do make absolute sense - and i need them "now" for some memory usage testing and optimizations i hope to get ...
- Backtesting should accept kwarguments, not a dictionary
> Backtest arguments instead of dictionary

- tests/test_utils.py
This test is missing a mock - causing a "real" ccxt object to be initialized.
I suspect that's causing the random test failure we see in `test_create_datadir()` - however since these failures seem to only happen in CI we'll have to test to be sure if this will really fix the issue for good.
> Fix missed mock

- docs/installation.md
...because ssh can lead to permission denied error when no public key is installed, which can be frustrating for novices installing the bot following the docs.
> Minor: Advise to use https method for git clone instead of ssh

- freqtrade/worker.py
- tests/test_freqtradebot.py
- tests/test_worker.py
Small cleanup from the overall design point of view.
The `state` attr is currently only used in the tests. Which is probably wrong, because tests should interact with the code in the same way, as other parts.
Actually, `state: State` is not an attribute of worker from the design point of view: 1) worker is always running (throttling), even when the bot is in the stopped state; 2) assume we extend later the worker to operate with a couple or with a list of bots -- then the state of each bot should be handled separately. So it's an attribute of the bot instance, not of the worker itself.
> Remove state attribute from Worker class

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_optimize_reports.py
Backtesting report and sell reasons tables are now more consistent with each other, and sell reasons table gives better info to help you differentiate between your backtest results with a quick glance by providing more info there as well.
> more consistent backtesting and sell reasons tables

- .github/workflows/ci.yml
- Dockerfile
- Update Dockerfile to python3.8.
- Run CI against python 3.8 to ensure everything is working. 
(Note: i've been running with 3.8 since it came out without any issues).
> Python 3.8

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
Combined with the 2nd part of #2796 (Locking) - this will prevent stoploss orders from being recreated if a sell is currently in place (but not yet filled).
There are several protections in place at the moment - however in case of trailing stoploss it can happen that the bot places a regular sell limit order which is not filled immediately.
The next iteration will see that the stoploss is gone and try to recreate a stoploss order.
The other case (the one i hit):
Sell-order limit is placed (obviously, cancelling stoploss_on_exchnage).
The next iteration, the limit-order filling is confirmed (calls `trade.close()` - which sets `is_open=False` and `open_order_id=None`, causing that protection to fail.
is_open is verified in `handle_trade()` - but was missing here.
For me, it created a …
> Fix stoploss recreated

- freqtrade/freqtradebot.py
modified two lines on freqtradebot.py from using _logger.info_ to **logger.debug** instead cause they're too spammy and repetitive, users can still opt-in to see them with -v.
> reduced noise without verbose mode if use_order_book is true

- tests/test_freqtradebot.py
Fix test error introduced in combination of #2799 and #2779 - by having "colliding" but not breaking commit overlaps
- Rename mock to how it should really be called.
> Fix failing stoploss CI test

- .github/workflows/ci.yml
Coveralls should only run once (and only comment once).
> Only run coveralls once

- tests/exchange/test_exchange.py
Another try to fix the random test failure ...
This is the only test where ccxt is not mocked away (which is correct, as that's what's tested).
- ensure that asyncio_loop is not started
> make sure asyncio_loop is not initialized within ccxt code

- freqtrade/exchange/exchange.py
Helps localizing #2774:
```
2020-02-03 17:16:45,439 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history for pair NXT/BTC due to BadSymbol. Message: bittrex {"success":false,"message":"RESTRICTED_MARKET","result":null,"explanation":null}"
```
Without this it's impossible to get which pair is problematic.
> Add pair to exception messages in exchange module

- freqtrade/commands/data_commands.py
- freqtrade/commands/deploy_commands.py
- freqtrade/commands/plot_commands.py
- freqtrade/configuration/check_exchange.py
- freqtrade/configuration/deprecated_settings.py
- freqtrade/configuration/directory_operations.py
- freqtrade/configuration/timerange.py
- freqtrade/data/btanalysis.py
- freqtrade/data/history.py
- freqtrade/edge/edge_positioning.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/misc.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/PrecisionFilter.py
- freqtrade/pairlist/PriceFilter.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/persistence.py
- freqtrade/plot/plotting.py
- freqtrade/resolvers/iresolver.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/rpc_manager.py
- freqtrade/strategy/interface.py
- freqtrade/wallets.py
- freqtrade/worker.py
This helps finding errors like that in `FreqtradeBot.handle_trailing_stoploss_on_exchange()` (`return False` instead of `return`)... And this can emphasize, highlight some design problems as well.
Some notes/questions:
* `cast` in freqtrade/commands/data_commands.py -- is this a good case for using `typing.cast`? From one point of view this looks (well, a bit) like a code smell, from another point of view -- it's more efficient than calling `bool(...)` there. 
From third point of view, mypy may be made happy here by adding `erase: bool = config['erase']` var here. From forth point of view, we'd in this case make this (assigning a local var with the value taken from the config dir) in all other places where config values are passed to the functions with type hints. So probably `cast` here …
> Add some type hints

- freqtrade/vendor/qtpylib/indicators.py
Fixes the implementation of rolling_max to use rolling_max.
Identical to https://github.com/ranaroussi/qtpylib/pull/149
closes #2853
- use `max()` to calculate the maximum ...
> Fix implementation of rolling_max

- .github/workflows/ci.yml
- Dockerfile
- docs/bot-usage.md
- docs/hyperopt.md
- freqtrade/commands/cli_options.py
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- freqtrade/optimize/hyperopt_loss_sharpe_daily.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_hyperopt.py
- tests/optimize/test_optimize_reports.py
Added the sharpe ratio hyperopt loss method which calculates sharpe ratio on a daily basis instead of yearly, as suggested by @djacky [here](https://github.com/freqtrade/freqtrade/issues/2727). On that thread, it was discussed how it can also be modified to work for smaller timeframes by users. 
I believe this hyper optimization loss method may help in eliminating bias due to having certain trades taking place in historical trends, when backtesting for the goal of having a strategy with consistent daily risk.
closes #2727 
~~Note: This requires having [freqtrade/technical](https://github.com/freqtrade/technical) installed in your freqtrade.~~
> added daily sharpe ratio hyperopt loss method, ty @djacky

- docs/backtesting.md
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_optimize_reports.py
Updated Strategy Summary to be consistent with other backtesting tables...
```
=========================================================== STRATEGY SUMMARY ===========================================================
| Strategy    |   Buy Count |   Avg Profit % |   Cum Profit % |   Tot Profit BTC |   Tot Profit % | Avg Duration   |     Wins | Losses |
|:------------|------------:|---------------:|---------------:|-----------------:|---------------:|:---------------|---------:|-------:|
| Strategy1   |         429 |           0.36 |         152.41 |       0.00762792 |          76.20 | 4:12:00        |      186 |    243 |
| Strategy2   |        1487 |          -0.13 |        -197.58 |      -0.00988917 |         -98.79 | 4:43:00        |      662 |    825 |
```
> Enhanced Backtesting Tables

- config.json.example
Resolves #2774 
(NXT on Bittrex is restricted in some regions for unknown reason)
> Minor: Replace NXT with XRP in config.json.example

- freqtrade/optimize/hyperopt_interface.py
- freqtrade/templates/sample_hyperopt_advanced.py
Resolves #2859
* Align code of the trailing_space() method in advanced hyperopt sample to changes in dimensions made into hyperopt_interface
* Adjust the range of stoploss dimension to be same with default from hyperopt_interface
* Fix typo in the comment in hyperopt_interface
> Update advanced hyperopt template

- docs/advanced-hyperopt.md
- docs/strategy-customization.md
- freqtrade/resolvers/iresolver.py
...like this:
```
class SampleStrategy2(SampleStrategy):
trailing_stop = True
```
`list-strategies` also works:
```
$ freqtrade list-strategies
...
| name               | location                |
|:-------------------|:------------------------|
| SampleStrategy     | sample_strategy.py      |
| SampleStrategy2    | sample_strategy.py      |
```
P.S. Same should work for hyperopt classes. Can be very useful, since you can simply redefine the `indicator_space()` method(s), for example with different range for dimension(s), leaving the rest intact.
> Allow derived strategies

- freqtrade/commands/data_commands.py
download-data does not need exchange validation - as none of the validated fields are relevant for data-download.
Closes #2883
closes #2679
> fix download-data validation problems

- freqtrade/optimize/hyperopt_loss_sharpe_daily.py
Calculations of SharpeHyperOptLossDaily fails in some conditions due to non-normalized index.
Reindex then (I wonder why it fails on non-normalized index!..) fills the aggregated column with NaNs and loss function therefore returns the '-20' bad value for all epochs.
The behavior depends on current local time and on the timerange passed to hyperopt.
Thanks to @yazeed for pointing out on the conditions when this happens.
(data with --days 500, 1h timeframe, local time is not about midnight, timerange is omitted or just before the date of first downloaded candle)
> Fix SharpeHyperOptLossDaily

- docs/exchanges.md
- docs/faq.md
"Fixes" running SampleStrategy on Bittrex (market order types) by adding a note in the FAQ.
> Add tip on running order types for Bittrex

- tests/data/test_history.py
- tests/optimize/__init__.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_edge_cli.py
- tests/optimize/test_hyperopt.py
As pointed out in #2894 - mypy for tests is not running correctly.
This does fix about half of the errors (reducing the errors from >200 to 95).
Now the problem with many of the remaining errors is that it's "cannot assign to a method".
For tests however, that's a perfectly valid scenario - where we want to monkey-patch a method for a 
specific run (that's why this was disabled in the first place).
To test this, remove the whole section of `[mypy-tests.*] ` in `setup.cfg`.
- Fix a few code type errors in tests
> Fix mypy type errors in tests

- bin/freqtrade
Break the old binary file so users are forced to reinstall.
We could also remove it assuming everyone did perform a "pip install ." again since July - however i'd like to leave it with the new message for one release - so really everyone is aware and is not hit by "could not find file".
This should not be relevant anymore - this binary has been deprecated
and is not being used by new installations since July 2019.
> Break the old binary file so users are forced to reinstall

- tests/optimize/test_hyperopt.py
Fixes several mypy errors in test_hyperopt.py
(min_date and max_date params were not passed into the loss function)
The dates were copied from another unittest, where they were used this way.
> Minor: Fix tests for hyperopt_loss

- docker-compose.yml
- docs/docker.md
Improve docker-documentation to recommend using docker-compose. 
It's a lot simpler to use and provides a way to persist default settins / parameters without using ever-long docker-command strings.
Inspired by the problems seen in #2868.
Requires #2831 to be merged first - therefore this is "don't merge".
- Improve docker-compose file 
- by storing the configuration + database within the user_data directory, we avoid having empty directories created.
- Enables logging to file by default
- enables restart: unless-stopped to restart if the docker-host is restarted
- Add docker-compose quickstart guide - marking the "old" docker documentation "advanced".
> Docker docs

- docs/utils.md
- freqtrade/commands/arguments.py
- freqtrade/commands/cli_options.py
- freqtrade/commands/hyperopt_commands.py
- freqtrade/configuration/configuration.py
- tests/commands/test_commands.py
Adding more filter options for hyperopt-list to easier find what your looking for in larger runs
PEP8 = Yes
Adding two more filter options that can be used in combination to the other options in order to filter and search thru larger hyperopt runs.
- Adding filter options --max-trades and --min-trades
- Adding missing filter options --max-avg-profit and --max-total-profit
- Added additional tests for the new options
```
freqtrade hyperopt-list --max-avg-time 200 --min-trades 20 --max-avg-profit 0.29 --min-avg-profit 0.20 --max-total-profit 8
2020-02-11 21:01:47,383 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-11 21:01:47,383 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 20
2020-02-11 21:01:47,383 - freqtrade.configuration.configuration - INFO …
```
> Adding --min-trades and --max-trades for hyperopt-list

- tests/data/test_history.py
- tests/optimize/test_backtesting.py
- tests/strategy/test_interface.py
- tests/test_plotting.py
...use `load_strategy()` instead, as in other places/tests. 
* This removes a few mypy errors in tests
* Can simplify removal of DefaultStrategy in the future, when (and if) this will be performed
* Not all appearances of `DefaultStrategy()` removed here -- some (with empty config dict) left to be managed separately
* Cosmetics in one of the tests: `strat` --> `strategy`, to have it aligned with the others
> Do not instantiate directly DefaultStrategy in tests

- docs/configuration.md
Fix rendering issue in configuration table.
I think RTD has problems with the combination of Italic and bold (and i'm not sure that's needed).
For now i've fixed it for `max_open_trades` (and relinked https://www.freqtrade.io/en/latest/configuration/ to this branch) - if you think that's ok i'll fix it for the remaining table, too.
> fix configuration table

- freqtrade/freqtradebot.py
It's only used once and is not really needed after #2887 
In the notebooks, the user should use the method from Trade class directly.
> Get rid of delete_trade method in Freqtradebot

- freqtrade/freqtradebot.py
If telegram networking is blocked, then rpc send may hang for timeout. If the user then closes the bot, it may happen that the trade object has not been flushed to persistence properly.
It's better to have rpc call after session add/flush, just to be sure add/flush is made before blocking rpc call.
> Move rpc send to be after db session add/flash

- CONTRIBUTING.md
- docs/bot-usage.md
- docs/configuration.md
- docs/developer.md
- docs/hyperopt.md
- docs/rest-api.md
- freqtrade/commands/arguments.py
- freqtrade/commands/cli_options.py
- tests/test_arguments.py
- tests/test_main.py
This will change the default behaviour for loading config.json, defaulting to `user_data/config.json` if it exists - followed by `config.json`.
This will simplify docker-usage (we can mount just one folder and it loads everything from user_data.
It'll also simplify usage for installations from pypi, where cwd can be the user_data directory - and therewith closes one point in #2112 
- Lowercase all FreqTrade usages in documentation
- change defaulting of config.json to use `user_data/config.json` - then `config.json`
- when using `--userdir asdf/` - the code will try to use `asdf/config.json` before `cwd/config.json`
> default to loading config.json from userdir if it exists

- docs/utils.md
- freqtrade/commands/arguments.py
- freqtrade/commands/list_commands.py
- freqtrade/resolvers/iresolver.py
- tests/strategy/failing_strategy.py
- tests/strategy/test_strategy.py
for both `list-strategies` and `list-hyperopts` subcommands:
`OK`, `LOAD FAILED` in red, `DUPLICATE NAME` in yellow,
`--no-color` option added
example:
```
| name                   | location                   | status          |
|:-----------------------|:---------------------------|:----------------|
| --                     | aaaw.py                    | LOAD FAILED     |
| --                     | test_Resampling_NNNNNN2.py | LOAD FAILED     |
| --                     | test_Resampling_NNNNNN3.py | LOAD FAILED     |
| --                     | strategy-FFFFFFF.py        | LOAD FAILED     |
| InformativeSample      | aaa.py                     | OK              |
| MA                     | JJJ.py                     | OK              |
| NewSampleStrategy      | NewSampleStrategy.py …
```
> Add printing statuses for enlisted strategies and hyperopts

- freqtrade/rpc/rpc.py
So, after testing develop branch for a bit, I noticed /status table wasn't returning pairs as expected:
So, I looked into the code merged from #2887 and apparently the problem lied here:
```
trade.pair + '*' if (trade.open_order_id is not None
and trade.close_rate_requested is None) else ''
+ '**' if (trade.close_rate_requested is not None) else '',
```
However, trying the previous code format I had actually works, no idea why though.
```
trade.pair + ['', '*'][trade.open_order_id is not None
and trade.close_rate_requested is None]
+ ['', '**'][trade.close_rate_requested is not None],
```
This is a PR to propose a right fix for it (if you still don't want to use my code as it doesn't have great at readability), though, it starts with proposing my code format as a quick fix for it.
Thanks.
> /status table quick fix

- freqtrade/exchange/__init__.py
- freqtrade/exchange/ftx.py
since ftx returns 1500 candles by default, we should adjust to this to avoid downloading the same data twice.
In combination with #2719 this would not be a problem for the final data (duplicate candles are dropped) - however the data is still downloaded 3 times - which is absolutely unnecessary.
Closes #2916
- Create FTX subclass to change setting of default candle return value
> increment limit to adjust to FTX defaults (1500 candles)

- README.md
- docs/index.md
With most of our CI running on github actions now, i think the CI badge should correspond to that.
> Add github actions badge

- .github/workflows/ci.yml
- freqtrade/__init__.py
this will add PyPi builds / uploads to the CI pipeline.
Solve part of the issue: #2112 
An successful workflow is available [here](https://github.com/freqtrade/freqtrade/runs/449795378?check_suite_focus=true) - i've since rebased this branch as i needed about 20 retries to get to that point.
- Run on release (hopefully - can only really test this when releasing)
- build pypi package
- upload pypi package
Our current versioning scheme for develop versions of develop-commit-hash (`develop-1172c95` is not [PEP440](https://www.python.org/dev/peps/pep-0440/#dvcs-based-version-labels) compliant as ordering is not reliably possible - and such releases can therefore not be uploaded to pypi.
This commit attempts itself on an alternative Versioning scheme (visible on both test.pypi.org - as well as …
> GitHub actions tests

- freqtrade/persistence.py
When kraken stoploss orders are hit they are not properly updated at the moment.
This will fix that.
- Handle stop-loss ordertype as well.
> Kraken stoploss bugfix

- freqtrade/data/history/jsondatahandler.py
This replicates behaviour from `parse_ticker_dataframe()` - which however is not called for backtesting data since #2719, as we load the data directly as pandas dataframe, skipping the step of loading it as list, and then converting to dataframe.
closes #2948
> Load ohlcv data as float

- freqtrade/freqtradebot.py
- freqtrade/worker.py
- tests/test_freqtradebot.py
- tests/test_worker.py
Preparation for (part of) #2885 
Split from the upcoming rest to have it observable, for easy review.
* Worker now throttles (with an empty function) in the STOPPED state as well, instead of explicit sleep, this allows to print same diagnostics messages in the stopped state as well.
* Better throttling: the "====..." divider (at debug level) is printed before the working function, to efficiently separate startup messages in the log from the messages of the first throttling iteration
* The heartbeat message moved from FreqtradeBot into Worker and issued at the stopped state as well.
* The heartbeat message now contains the state, to see something when the bot was stopped.
* The heartbeat message now contains the version of the bot. I added this for us to see the version from the logs …
> Better throttling

- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- tests/exchange/test_exchange.py
- tests/rpc/test_rpc.py
- tests/test_freqtradebot.py
Buy / sell rate caching is broken as we discovered in #2887 
Caching did not work when orderbook was enabled, making a call to the exchange for every RPC call.
This now implements caching in a slightly different manner:
It caches the result calls for 5 seconds - so notifications sent within 5 seconds will reuse the present value - otherwise a query to the exchange is sent.
If a fresh value is requested (only applies for calls right before creating an order) - then refresh is set to True, forcing a exchange query.
- Implement caching for `get_buy_rate()`
- implement caching for `get_sell_rate()`
- remove caching from `exchange.fetch_ticker()`
> Improve and fix buy / sell Rate caching

- docs/configuration.md
- docs/installation.md
- mkdocs.yml
This should simplify the installation documentation.
Docker should be the first option for new users (i think that's the easiest to get started with).
Also, Exchange keys are NOT part of the installation - users won't need them until the strategy is ready and backtested.
Closes #2498
- adjust easy-install script (i'll honestly not put too much work into this, as i see this method disappear hopefully soon)
- Reorder points to have docker installation come first on the documentation page
- api-keys should be part of the configuration - not part of the installation.
> simplify installation documentation

- freqtrade/configuration/config_validation.py
- freqtrade/constants.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/rpc/rpc.py
- freqtrade/wallets.py
- tests/commands/test_commands.py
- tests/conftest.py
- tests/exchange/test_exchange.py
- tests/rpc/test_rpc.py
- tests/test_configuration.py
- tests/test_freqtradebot.py
Certain markets are not in the format of quote/base.
This PR allows to extract either side from the markets dict for each pair.
Closes #268
Closes #1107 (the bot should now support inversed pairs too)
most likely will close #2969 (still needs validation / confirmation)
- move pairlist validation for correct stake currency to exchange (it requires markets now)
- remove all usages of `pair.startswith()`, `pair.endswith()` and `pair.split('/')` and replace them with the methods `get_pair_quote_currency()` and `get_pair_base_currency()`
- Remove config validation to make sure pairs are `base/quote` formatted.
> Support non pairs

- freqtrade/configuration/configuration.py
While working on recreating #2980, i noticed that runmode should be shown in the logs but it's not because logging is initialized too late.
I think logging should be initialized first within config - so all log-messages are shown/logged correctly
- Change calling sequence within configuration for logging
- Fix output to be "nice"
> Logging should be initialized first

- docs/strategy-customization.md
sometimes using ROI based on candle can be useful (especially during strategy development when experimenting with different timeframes).
While easily possible, it's so far only been documented in a issue, but not in the documentation.
Closes #2463
- add sample for candle based ROI
> Add timeframe_to_minutes to ROI documentation

- freqtrade/configuration/configuration.py
- tests/test_configuration.py
run-mode not correctly set when using --dry-run
closes #2980
- Test reproducing this behaviour
- fix by reordering config parsing.
> run-mode not correctly set when using --dry-run

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_optimize_reports.py
Changed table style of backtesting to be same as for hyperopt-list
Aligned table headers so they match table size.
PEP8 = Yes
- Changed table style
- Alignment of headers
Current:
```
========================================================= BACKTESTING REPORT ========================================================
| Pair     |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit BTC |   Tot Profit % | Avg Duration   |   Wins |   Draws |   Losses |
|:---------|-------:|---------------:|---------------:|-----------------:|---------------:|:---------------|-------:|--------:|---------:|
| ETH/BTC  |     32 |           0.42 |          13.56 |       0.00081463 |           4.52 | 5:50:00        |     32 |       0 |        0 |
| XRP/BTC  |      5 |           0.35 |           1.75 | …
```
> Changed table style of backtesting and alignment of headers

- tests/commands/test_commands.py
Yet another another try to fix the random test failure we're seeing while checking caplog length.
> Try fix random testfailure

- README.md
- docs/configuration.md
- freqtrade/exchange/exchange.py
Secretly, kraken has been supported a while now.
We'll now 
- Add kraken to list of supported exchanges
- Fix link to binance BNB blacklist note
> Add official support for Kraken

- docs/strategy_analysis_example.md
- freqtrade/templates/strategy_analysis_example.ipynb
`generate_candlestick_graph()` needs a filtered pairlist, not a list
containing all pairs
Solve the issue: Posted on slack 
- Filter trades on pair before calling `generate_candlestick_graph()` in documentation and jupyter example.
**edit**
:tada: pr/issue #3000 ... can't say we've not been active anymore :laughing:
> [minor] Fix jupyter notebook example

- freqtrade/exchange/exchange.py
- tests/exchange/test_exchange.py
Fixes a bug mentioned on slack, where running download-data without stake-currency did fail again (reintroduced in #2973).
- Test + fix allowing empty stake-currency
> Allow Stake currency empty when using download-data

- freqtrade/optimize/hyperopt.py
Hyperopt fix when specifying total epochs less than amount of CPU cores.
PEP8 = yes
- Hyperopt.py, aligning total epochs and cpu core config
Aligning the parameters when less epochs are specified will avoid the situation below:
```
Parameter --epochs detected ... Will run Hyperopt with for 1 epochs ...
Parameter -j/--job-workers detected: -1
- INFO - Effective number of parallel workers used: 8
+--------+---------+----------+--------------+----------------+----------+----------------+-------------+
|   Best |   Epoch |   Trades |   Avg profit |   Total profit |   Profit |   Avg duration |   Objective |
|--------+---------+----------+--------------+----------------+----------+----------------+-------------|
|      * |     1/1 |        0 |          nan | 0.00000000 BTC |    0.00% | …
```
> Hyperopt: fix number of CPU cores, jobs and total epochs

- docs/plotting.md
- freqtrade/data/btanalysis.py
- freqtrade/plot/plotting.py
- tests/data/test_btanalysis.py
- tests/test_plotting.py
Adds additional markets for max drawdown period in the profit plot.
The function (`calculate_max_drawdown()`) is intended to be reused for other areas of the bot as well (backtesting -> #1908, Risk management -> #2968).
- Add new markets showing max-drawdown period
- New function calculationg max drawdown (including start and end dates).
Max drawdown visualized
> Max drawdown in plot-profit

- freqtrade/commands/hyperopt_commands.py
- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
Change print output of hyperopt to table style. More space efficient.
WIP
Part of issue: #2913 
Part of issue: #2837 
Part of issue: #1775 
- Changed default output to table style
- Small modifications to print table function
New output example:
```
2020-02-29 23:16:56,838 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8
+--------+---------+----------+--------------+-----------------------------+----------------+-------------+
|   Best |   Epoch |   Trades |   Avg profit |                      Profit |   Avg duration |   Objective |
|--------+---------+----------+--------------+-----------------------------+----------------+-------------|
|      * |    1/10 |        0 |           -- |                          -- |             -- |         N/A |
|      * …
```
> Added dynamic print table function to hyperopt

- tests/test_worker.py
Throttle may take longer than .10s on slow machines
This made this test fluky on windows CI ...
Use proper regex to allow slightly different values (in case of windows CI, the output was 0.08 instad of 0.10.
> Fix random CI failure 

- .travis.yml
Not sure why it was working for the last 1.5 years ... the path to the include has been wrong since "quite some time".
Oddly enough, it's correct in github actions ...
> Fix travis build failure

- freqtrade/freqtradebot.py
Simple PR to bring consistency to logger messages and variable names between get_buy_rate and get_sell_rate.
> consistency between get_sell_rate with get_buy_rate

- freqtrade/freqtradebot.py
Found a single instance of config get for **ignore_roi_if_buy_signal** without its default fallback.
> default for ignore_roi_if_buy_signal in freqtradebot.py

- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/pairlist/pairlistmanager.py
- tests/pairlist/test_pairlist.py
Blacklisted pair mesages should not appear as Warning when using volumepairlist
Now this intentionally leaves the repeated logging in case of staticpairlist, which collides with blacklisted pairs - as in that case, the pairlist should be fixed instead.
Closes #2992
- conditionally log blacklisted message
- Don't check pair blacklist 3 times in a row ...
> reduce Pairlist message warning level

- docs/utils.md
- freqtrade/commands/arguments.py
- freqtrade/commands/cli_options.py
- freqtrade/commands/hyperopt_commands.py
- freqtrade/configuration/configuration.py
- freqtrade/optimize/hyperopt.py
- tests/commands/test_commands.py
Add options for exporting CSV-file from hyperopt
Work in progress.
Tests are missing at the moment.
- New command to hyperopt-list: --export-csv FILE
freqtrade hyperopt-list --export-csv /tmp/test.csv
or
<s>freqtrade hyperopt-list --export-csv +/tmp/test.csv</s> (this functionality refused; edited by @hroff-1902)
> Hyperopt: Add export CSV-file option

- config.json.example
- config_binance.json.example
- config_full.json.example
- config_kraken.json.example
- docs/configuration.md
- freqtrade/templates/base_config.json.j2
order_book_max should be set to 1 in almost all cases, otherwise it can lead to misleading results in dry-runs - and may lead to missed stoplosses in real runs.
closes #3043
- Change default settings to 1
- update documentation with more clarity
> order_book_max - change example setting

- docs/hyperopt.md
- freqtrade/templates/base_hyperopt.py.j2
- freqtrade/templates/sample_hyperopt.py
- freqtrade/templates/sample_hyperopt_advanced.py
To have hyperopt aligned to regular strategy recommandations, hyperopt should include a condition to only use candles with volume.
If that's not done and the strategy is written according to specs, a volume>0 condition is included, leading to slightly different results between backtesting and hyperopt.
- Add condition to check for volume to all hyperopt condition samples.
> Hyperopt - add default volume > 0 filter

- freqtrade/edge/edge_positioning.py
- tests/edge/test_edge.py
Fix deprecation warnings when running tests for edge (proactive, before it breaks with the next numpy update ...).
- use correct indexing of columns (2 columns = list)
- use different method to compare result times in test.
> Edge test warning

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_optimize_reports.py
Refactor backtest result reporting out of backtesting class.
This also seperates the storing of the backtesting file from the actual plotting - so the result is stored even if the output is interrupted while the printing is still going on.
- Refactor `store_backtest_results()` to take a list of results
- refactor `backtesting.start()` to call `show_backtest_results()` instead of containing all logic itself. This greatly simplifies the backtesting class, as it's reduced to what's really needed for backtesting.
> Backtest small improvements

- MANIFEST.in
Non-python  files need to be included explicitly into a release distribution.
Closes #3078
- Add *.j2 and *.ipynb files from the templates directory.
> Add template and jupyter files to release

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
Apparently ccxt's `cancel_order()` function does not guarantee to return a dictionary, and in FTX's case returns `'Order queued for cancellation'`.
Therefore, we need to verify if the return-value is a dict, and eventually use an empty dict instead.
closes #3085
> Ftx cancel order

- .gitignore
Since the example notebooks have been moved to the templates folder, running `freqtrade new-datadir --userdir user_data` did result in a unclean git environment, showing `user_data/notebooks/strategy_analysis_example.ipynb` as uncommited file.
> [minor] Add example notebook to gitignore again

- freqtrade/configuration/load_config.py
- tests/test_configuration.py
Improve config error handling by
* not showing stacktrace
* showing the relevant section of the error based on the load-error character
```
Parse error at offset 77: Invalid value.
Please verify the following segment of your configuration:
"max_open_trades": 3,
"stake_currency": "ETH",
"stake_amount": .10,
"fiat_display_currency": "USD",
"tradable_balance_ratio": 0.99,
```
> Improve config parse error handling

- tests/test_configuration.py
Fix random test failure by always enabling warnings - otherwise it'll sometimes be disabled depending on the environment.
> [minor] Test warnings with filter always on

- freqtrade/freqtradebot.py
- freqtrade/persistence.py
- freqtrade/rpc/rpc.py
- tests/test_persistence.py
Add column `close_profit_abs` to the database, to simplify analysis afterwards (aligned to close_profit - which represents the ratio.
closes #3010
- Add new column close_profit_abs
- add migration test case for closed trade
- Simplify rpc calls where possible
> Add close_profit_abs column

- docs/exchanges.md
The partial candle method  was never fully tested - and does not work correctly since we're not fetching candles on every iteration - but only when new candles are actually expected.
closes #2993
- Remove wrong documentation part - suggesting alternatively using the dataprovider to fetch the latest price.
> Remove partial candle documentation

- docs/bot-usage.md
remove last occurance of default_strategy from the docs and replace it with SampleStrategy - as pointed out in #3120
> [minor] Remove defaultstrategy occurance from docs

- freqtrade/plot/plotting.py
Max drawdown is a ratio - to show it in the graph we should multiply it with 100 to show it as % (especially as there is a % sign after the number).
> [minor] Plot percent correctly

- freqtrade/strategy/interface.py
- tests/strategy/test_interface.py
Save a few dataframe elements before calling the signals, to make sure they are
still there afterwards.
Also fetch the correct signals by date.
related to #2696 
- functions `preserve_df` and `assert_df` used around strategy calls to gauge dataframe validity
- locate the correct signals row by date instead of by index (which is kinda reduntant since with those checks it will raise an exception if the index does not match...
...the failing tests are...broken because they indeed pass a non matching dataframe..
these checks are done on each call...they are not heavy so...doesn't seem to hurt
> check that the strategy dataframe matches the one given by the bot

- freqtrade/data/btanalysis.py
- freqtrade/plot/plotting.py
without the equality operator which losely checks within a range, the lookup will throw an index error when plotting against the trades on a database, because trades in a database have real dates, compared to backtesting that are fixed to the precision of the timeframe
> use equality instead of index for row lookups

- freqtrade/optimize/backtesting.py
- freqtrade/strategy/interface.py
- tests/strategy/test_interface.py
After thinking about this for a long time  (since November) - i'm finally ready with this.
It'll be a small change - but memory_profiling shows positive effects on memory usage, especially when using multiple strategies, but also for single strategy backtesting.
This will also remove the risk of having a strategy overwrite certain columns when using `--strategy-list` - which could happen if for example 'close' would be overwritten.
Now this change also applies to "single-strategy" backtesting - and i've been thinking about that for a long time, and making this optional (only apply to multi-strategy mode) would not be a problem, but memory-profiler shows that memory-consumption is reduced also in that case.
closes #3132
- Provide a fresh copy of the dataframe to each strategy
Current …
> Backtesting memory and dataframe

- freqtrade/data/btanalysis.py
- tests/data/test_btanalysis.py
- tests/test_plotting.py
Max drawdown must always have high first, then low.
This was incorrectly done in our previous implementation, resulting in plots as the following:
Correct version would be: 
- add test showing this is broken
- fix broken max-drawdown implementation
> [minor] Fix maxdrawdown

- freqtrade/__init__.py
have version-detection fall back to `freqtrade_commit` - the file created in docker-ci.
this allows `freqtrade --version` to work for develop images in docker too.
to test: 
- create a file freqtrade_commit containing the current hash
- modify docker-compose.yml to include `- ".:/freqtrade/"` as volume (mounting the current directory into the container)
- run `docker-compose run --rm freqtrade --version`
> [minor] have version-detection fall back to freqtrade_commit

- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_optimize_reports.py
Filenames for exported fiels should not be increasing in length - but should be `filename-<strategy>.json` for all strategies, independently if it's the first or last strategy.
As reported on slack.
> [minor] Fix filename handling with --strategy-list

- freqtrade/exchange/exchange.py
- freqtrade/pairlist/PriceFilter.py
- tests/exchange/test_exchange.py
pricefilter must calculate the price difference depending on the precision type to be correct.
If the type is "Tick" - then the precision is already what we need.
Otherwise we need to calculate it as before.
Fixes bugs with FTX showing over 100% pricechange for one asset.
closes #3170
> Fix pricefilter

- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/persistence.py
- freqtrade/rpc/telegram.py
- tests/conftest.py
- tests/exchange/test_exchange.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
Revise/revisit handling of orders which are closed on the exchange.
When using limit orders, an order can remain on the exchange until it's timed out.
However, users can also manually go to the exchange and cancel an order - which did act differently depending at what point in the bot-cycle the order was cancelled.
This acts also as a preperation for #2646 - and may eventually solve part 3 of #3103 (unverified, as i'm not 100% clear on the problem there).
This PR 
* Combines methods for handling trade-updates to fees
* Moves the checking for closed orders into the timeout section (so cancelled orders are handled properly)
* moves checking for timedout orders to the start of the cycle 
* adjusts handling of cancelled orders (FTX returns the orderstatus as closed, with filled == 0.0).
* …
> Trade state updates

- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/PrecisionFilter.py
- freqtrade/pairlist/PriceFilter.py
- freqtrade/pairlist/SpreadFilter.py
- freqtrade/pairlist/VolumePairList.py
- tests/pairlist/test_pairlist.py
Fix bug from #3166, where Volumepairlist doesn't filter correctly when StaticPairlist is first.
Also, implements "log-caching" to avoid log spamming.
Currently, the same logmessages from PairlistFilter are printed every few seconds in certain constellations (when using StaticPairlist first, for example).
closes #3166
- Don't log so frequently by using a TTL cache (only logs messages every 1800s - avoiding log spamming).
- Fix bug where Volumepairlist doesn't correctly filter pairs
> Fix pairlist caching

- freqtrade/freqtradebot.py
- freqtrade/misc.py
- tests/test_freqtradebot.py
- tests/test_misc.py
Improve logging to enable checking (via logs) which branch is taken when cancelling a buy order.
Also fixes #3130 - an exception caused by the cancel-order ['remaining'] field to be None (instead of not being present).
- Add logging statement for full buy order cancel
- Logging for the "partial" branch is available.
- Add `safe_value_fallback()` - a function to safely get a value out of 2 dictionaries where keys could exist, or be empty
- use safe_value_fallback to get remaining - the failing key
- Correctly catch InvalidOrderException should it occur from cancel_order (could happen if the order is filled that moment).
> Improve handling for buy order cancels

- freqtrade/optimize/hyperopt.py
This fixes random test failures by not initializing stdout capturing twice.
Now i'm not certain why the failures only occur in windows CI - as with the same random number, i can get them to fail on linux just fine ... 
Visually i did not observe any difference between the 2 modes ... (probably because stdout/stderr is already captured).
progresbar however seems to have a problem with this double-capturing if it's initialized twice and raises an error.
https://github.com/WoLpH/python-progressbar/issues/225
- Fix random test failures
one of the random test-seeds:
(does not matter if it's running just for this file or for the whole testsuite).
```bash
pytest tests/optimize/test_hyperopt.py -v --random-order-seed=541257
```
> Fix random test failure in hyperopt

- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- tests/exchange/test_exchange.py
- tests/test_freqtradebot.py
Better handle the "different" return-values `cancel_order()` calls can have.
This combines the to support "non-dict" return-values and "incomplete" return values.
closes #3128 
closes #2893 
most likely closes #3175 (problem is not clear since the logs are incomplete)
- Test if cancel-order is suitable for processing
- if it's not, run a `fetch_order()` call to get the results
- If the exchange doesn't return cancelled orders - mock a result we can use.
> Fix several cancel order problems

- docker-compose.yml
- docs/advanced-setup.md
- docs/faq.md
- freqtrade/configuration/directory_operations.py
- tests/test_directory_operations.py
Default to creating a log folder in `user_data` - and have `docker-compose.yml` log there.
closes #3185
- fix typo in advanced logging documentation
- Log to user_data/logs/
Default to log to a file in `user_data/logs` also for non-docker setups.
This is still in development / testing as it's not trivial to get this right without introducing a Memory leak.
> Docker log location

- docs/sql_cheatsheet.md
Update SQL cheatsheet with last required column
closes #3201
- fill close_profit_abs column
- slightly reformat sql queries to render better in docs (and to make them easier to read)
- remove outdated reference to updating fees (this was necessary sometime mid-2017 ...).
> Update sql cheatsheet to allow manual closing trades correctly

- docs/edge.md
This PR aims to improve the documentation of the Edge module by using more precise wording when describing expectancy.
-  Fix return rate in expectancy docs
-  Add example to make it more clear
The docs state that a strategy which returns .68 times as much as it loses is positive. But, if a strategy returns .68 times as much as it loses, then that means it loses 1.47 times as much as it returns and it is NOT a good strategy. 
One (off-topic) question, have you guys ever considered using the kelly criterion in order to determine stake size? The math is very similar to what already exists in this module. I believe that ideal position size according to the kelly criterion would be given by:
(expectancy * available capital) / (risk reward ratio)
I think this could be normalized to avoid …
> Update wording in expectancy docs and add example

- freqtrade/pairlist/PriceFilter.py
- tests/conftest.py
- tests/pairlist/test_pairlist.py
Pricefilter will reject this pair as it doesn't have any information - and the whole get_ticker call is empty
closes #3117
- Fix crash
- add test ensuring we're not regressing this.
> fix crash with Dynamic whitelist with pairfilter on FTX 

- docs/hyperopt.md
- freqtrade/optimize/hyperopt.py
* Fixes printing of asterisk (`*`) for initial random points (currently it's not printed for epochs marked as Best)
* The docs is slightly adjusted to document it, fixes #3065 
Current output:
```
+--------+---------+----------+--------------+------------------------------+----------------+-------------+
|   Best |   Epoch |   Trades |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+---------+----------+--------------+------------------------------+----------------+-------------|
|   Best |    1/50 |       63 |       -3.75% | -472.35727170 BTC (-235.94%) |     12,617.1 m |     2.44816 |
|   Best |    2/50 |      114 |       -1.20% | -274.30359399 BTC (-137.01%) |      5,760.0 m |      2.2858 |                                 
|   Best |    3/50 | …
```
> Better handling and description of asterisk in Hyperopt output

- setup.sh
setup.sh is showing a invalid command.
We should not pin users to `freqtrade trade` - but instead suggest that multiple commands are available.
Also - it'll show how to print the version.
closes #2773
> [minor] Update "final" message in setup.sh

- docs/hyperopt.md
Add small section noting that a strategy file is always necessary for hyperopt
closes  #3047
> Hyperopt should mention that a strategy is mandatory.

- docs/backtesting.md
- docs/configuration.md
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
- tests/optimize/test_backtesting.py
Use pairlists for backtesting.
While i'm skeptical on using Volumepairlist for backtesting  since it will use the current 24h volume to select pairs (so pairs during dry-run would have been different), using the filters can make sense (especially once #2956 is in).
This also now respects the blacklist correctly - which was previously ignored by backtesting.
enables  #2956 (random pairlist) for backtesting
- Use pairlists for backtesting to respect blacklist.
> Backtest use pairlists

- freqtrade/optimize/hyperopt.py
- setup.py
* Use optimizer's model_queue_size param (was introduced with model queue management PR in skopt v0.7.2, IIRC)
* Remove my custom hack I implemented before to do same (in a bit different approach) things
> Use skopt model_queue_size instead of custom hack

- freqtrade/optimize/hyperopt.py
Fix  deprecation message
```
.../python3.8/site-packages/progressbar/bar.py:295: DeprecationWarning:
The usage of `maxval` is deprecated, please use `max_value` instead
```
> Use non-deprectated parameter for progressbar

- freqtrade/freqtradebot.py
- tests/conftest.py
Helps when calling `/status` or `/status table` frequently on slowish exchanges (kraken, i'm looking at you), and returns a result faster.
Has no practical impact on trading operations, as that will always refresh the rate - but for rpc methods, this has a huge impact on roundtrip time (and avoids unnecessary calls to the exchange, which can get us blocked on some exchanges).
> [minor] Increase cache for rate limit to avoid delays

- docs/utils.md
- freqtrade/commands/__init__.py
- freqtrade/commands/arguments.py
- freqtrade/commands/cli_options.py
- freqtrade/commands/list_commands.py
- freqtrade/configuration/configuration.py
- tests/commands/test_commands.py
Add subcommand `show-trades` - which can be used to print one or more trades to screen.
This can be very helpful for analysis and issue triage - as we'll not have to ask for "open the database and ... " - but we can say "run `freqtrade show-trades --dburl <sqlite... > --print-json` - and get a nicely formatted result back.
- New command show-trades
> New subcommand show-trades

- freqtrade/commands/list_commands.py
- tests/commands/test_commands.py
Humanize show-trades error when no database is specified
database url (db_url) can be specified in either configuration or explicitly.
Fallback to Default url's is intentionally NOT supported - as it would create the database if it doesn't exist - and just from this command it's not clear if it's a dry-run database or a production database.
Closes #3261
> Humanize show-trades error when no database is specified

- freqtrade/freqtradebot.py
- tests/conftest.py
- tests/test_freqtradebot.py
Cancelled orders may have the status of canceled or closed (ftx).
Also, Remaining is not filled properly by all exchanges (ftx) - however the definition of "remaining" is unclear. 
Ftx is not incorrect in saying that 0.0 amount is remaining if the order has been cancelled.
Either way - we should use filled for this - which contains the really filled value reliably (tested with real (!!) orders from binance, kraken and ftx).
closes #3247
- Add test with different "flavors" of returns per exchange 
- use filled instead of `amount - remaining`.
- check for canceled and closed status type before cancelling orders on the exchange.
> Fix handling of partially or non-filled timedout orders

- freqtrade/commands/trade_commands.py
- tests/commands/test_commands.py
- tests/test_main.py
As identified in #3268, logging does not properly print the stacktrace for certain errors.
This happens because the except / finally handler "swallows" the exception and does not bubble it further.
Catching all errors in the trade_command module will solve this issue (no other command uses a finally handler).
> [minor] Improve exception handling on critical errors

- freqtrade/exchange/exchange.py
Handle retriable errors in get_trades_for_order() in the same way as in other retriers.
> Minor: improve exception handling in exchange

- freqtrade/edge/edge_positioning.py
- tests/edge/test_edge.py
Edge should apply the value of fee twice, not a half of it for buy and sell.
As it's used in backtesting and as defined in the description of the `--fee` cli option:
"Specify fee ratio. Will be applied twice (on trade entry and exit)".
`Exchange.get_fee()`, which is used by Edge, also returns 0.001 for Binance, so it should be applied twice, not halved.
Expectancy and risk reward ratio decreased in the test, as it should be when we apply a higher fee.
Old data kept in the tests, but with halved fee value.
> Fix fee usage in Edge

- freqtrade/rpc/telegram.py
Fix typo in telegram /help respond
enabled is misspelled as "enabeld"
> Fix Typo in telegram Plugin

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
Seems like one case of "cancel_order" exception was forgotten.
There is only one case where this can happen - which is if the order is fully filled between the `fetch_order()` call, and the `cancel_order()` call.
If this happens, then the next iteration will correctly close the trade.
Either way, this (in combination with #3269) will ensure that we're able to track errors correctly in the future should they arrise again (which i don't expect in this case though).
closes #3268
- Catch exception from cancel_order.
> Sell order cancel exception

- config_full.json.example
- docs/rest-api.md
- freqtrade/rpc/api_server.py
- requirements-common.txt
- setup.py
- tests/rpc/test_rpc_apiserver.py
In order to allow an UI to be more secure, the api server should support JWT (JSON Web Tokens), so the password isn't sent around in plaintext all the time.
- Support JWT 
- Support JWT refresh tokesn
- use `safe_str_cmp` to compare username/password.
> API server - support JWT

- tests/optimize/test_backtesting.py
Suppress DeprecationWarning from a test unit which uses LegacyStrategy.
> Minor: Add filterwarning for DeprecationWarning in test

- freqtrade/optimize/hyperopt.py
New Feature: add hyperopt params to the hyperopt CSV export
This appends a column for each parameter setting of the hyperopt space indicators. This can be very useful for further analysis. Such as a cluster analysis.
> hyperopt csv export - add params

- freqtrade/rpc/rpc.py
Show forcebuy status so it's visible before calling forcebuy.
Otherwise we need to call /forcebuy to know if it's available (via API...).
> [minor] Show forcebuy status so it's visible before calling forcebuy.

- freqtrade/rpc/api_server.py
- requirements-common.txt
- setup.py
- tests/rpc/test_rpc_apiserver.py
Without this, cross origin requests are not possible as the CORS header is missing, limiting any UI to proxy requests through itself.
> Add cors support - needed for UI

- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
rpc should not format the output - but each RPC handler should do do this himself.
Telegram output is not changed (no change to test_telegram ...) - but the API now returns a list of objects, instead of a list of lists (where you need to guess which field means what).
This implicitly cleans up the return values for the API.
> Improve daily API format

- freqtrade/exchange/common.py
It (throttling with DependencyException in the Exchange retrier) does not have sense due to its semantics and how (when) we raise it: it will also give same DependencyException.
Part of #3273
> Do not throttle with DependencyException in Exchange retrier

- docs/configuration.md
- freqtrade/constants.py
- freqtrade/pairlist/ShuffleFilter.py
- tests/pairlist/test_pairlist.py
Adds Shuffling pairlist filter.
Replaces #2956 
Usage:
```
{"method": "ShuffleFilter"}
```
for reproducible results:
```
{"method": "ShuffleFilter", "seed": 42}
```
Also, some tests for other pairlists added/adjusted.
TODO: docs
> Add ShuffleFilter

- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/pairlistmanager.py
- tests/pairlist/test_pairlist.py
...and partly in IPairList.
Just to make it clear, where pairlists (instances if IPairList) and pairlists (lists of pairs) are used. 😉 
The term Pairlist Handler is used for instances of IPairList, as in the updated part of the documentation.
Neither the name of IPairList class, nor the name of the parameters of the methods of this class were touched at this attempt, to keep the PR light.
> Cleanup in pairlistmanager

- freqtrade/strategy/interface.py
`signal_date` is absolutely equal to `latest_date` when they are calculated as it is now, so redundant
plus, it's not the "signal date" by its semantics and usage below in the code, but actually the "latest date"
(I wonder it works without `arrow.get()`...)
> Minor: cleanup in get_signal()

- freqtrade/data/btanalysis.py
- freqtrade/plot/plotting.py
- tests/data/test_btanalysis.py
- tests/test_plotting.py
Freqtrade should not crash - but instead show a "nice" warning about why it did not work.
closes #3342
- Check if trades are empty and don't run plot_profit
- Also verify the trade-dict within `create_cum_profit()`. This is not reachable from plot_profit anymore - but ensures we're not reintroduce this bug in other areas should create_cum_profit be reused someplace else.
> [minor] Fix crash when no trades are found in plot-profit

- freqtrade/pairlist/VolumePairList.py
- tests/pairlist/test_pairlist.py
* New unit test test_refresh_pairlist_dynamic_2 added -- it emulates expiring the cache, I thought there is a bug here (but it's actually okay)
* Exception text in VolumePairList corrected (missing space)
* The test_gen_pair_whitelist_not_supported (it catched and verified wrong exception)
> Improve pairlist tests

- README.md
- freqtrade/commands/arguments.py
Reorder subcommands so they have "some" sense when running `freqtrade --help`.
Now i've tried to
a) combine them how they belong together (backtesting/optimize commands, new commands)
b) order them alphabetically where the above doesn't make sense
now we can argue about the trade command. I've left it in "first place" for now as the "important" commmand - but maybe the sequence should be by workflow?
(optimize - then trade) ... 
*note* i only reordered the commands - didn't type one character (might simplify reviews ...)
Old:
```
usage: freqtrade [-h] [-V]
{trade,backtesting,edge,hyperopt,create-userdir,new-config,new-strategy,new-hyperopt,list-strategies,list-hyperopts,list-exchanges,list-timeframes,list-markets,list-pairs,test-pairlist,download-data,convert-data,convert-trade-data,plot-d …
```
> Reorder subcommands

- freqtrade/constants.py
- freqtrade/data/dataprovider.py
- freqtrade/exchange/exchange.py
- freqtrade/pairlist/pairlistmanager.py
- freqtrade/strategy/interface.py
- freqtrade/typing.py
As reported on slack (and anoyed myself just now)
we can't use a file called typing if we import from typing within it.
I've moved this to `constants.py` now ... in the end, that's what it is - a constant.
> Fix typing circular dependency

- freqtrade/data/dataprovider.py
- freqtrade/exceptions.py
- freqtrade/exchange/binance.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- tests/exchange/test_exchange.py
- tests/test_freqtradebot.py
In certain circumstances, orderbooks can be empty (for example RIGHT after an exchange outage - or on very shitty pairs where one side is empty).
currently, freqtrade is crashing hard on these with either KeyError or ExceptionError.
This PR adds handling for cases where the orderbook is empty on one (or both) sides.
It'll obviously only take effect when use_order_book is set to true.
Closes #3367 
- Introduce new errortype - `PricingError` to be clear what the cause for this error is.
- Handle key/IndexErrors when dealing with the orderbook.
- rename get_order_book to fetch_l2_order_book (to be aligned to ccxt).
> Fix orderbook keyerror

- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_optimize_reports.py
First step in refactoring backtest report.
The final result will generate one large dict containing all metrics calculated and shown during backtesting - which can also be stored alongside with the backtest results.
Nothing in the output does change - just the way how backtest-methods are called.
- seperate metric generation from metric visualization (currently still artificially, but will be moved out of this function in the next PR)
- use dicts instead of lists of lists - to make it clear that list[5] contains profit_pct - and not something random.
- Add a bit more detail to certain tests.
> Refactor BTReport

- docs/developer.md
- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/StaticPairList.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/pairlist/pairlistmanager.py
- tests/pairlist/test_pairlist.py
Split the pairlist generation logic and filtering.
Also addresses #3353 and supersedes it (same tests. with exemption of the empty `pairlists`, added)
TODO: Need to find a better place for a call to `self._prepare_whitelist()`. there is definitely no need to duplicate this logic in every filter, but this will be refactored later, to keep this PR small. Now I wonder why the test for ShuffleFilter after StaticPairList does not fail, so Don't merge for a while.
> Split the pairlist generation logic and filtering

- freqtrade/persistence.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/test_persistence.py
There were several database fields not in the to_json() method, basically hiding the information from show_trades (and other users of this method like RPC methods).
> [minor] Add missing fields to to_json output of trade

- freqtrade/resolvers/strategy_resolver.py
Followup to #3394 - removing the internals reference.
Internals contains only timing related things so far. This is closer to `process_only_new_candles` - which is at the top level of the config as well.
> Disabledataframecheck is not in internals and does not belong there

- freqtrade/persistence.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
/Profit should not return 502 just because no trade has been closed.
Instead, it should return the profit for open trades (or no profit, if no trade exists).
- Improve telegram output for just started bots (when calling /profit)
- improve output for API (no 502 - but results instead)
No change to /profit when closed trades exist
shows "No trades yet." if no trade was yet opened.
> improve /profit to not raise an exception if no trade is closed

- docs/configuration.md
- docs/edge.md
- docs/stoploss.md
- freqtrade/configuration/deprecated_settings.py
- freqtrade/constants.py
- freqtrade/edge/edge_positioning.py
- tests/config_test_comments.json
- tests/test_configuration.py
Remove deprecated edge-config `capital_available_percentage` and raise an exception instead.
Part of #2971 (although i'm not sure what would be needed to completely suffice that issue)
- remove `capital_available_percentage` and raise error when it's used in combination with edge
- remove some occurances of percent where we mean ratio in the documentation
> Remove deprecated setting

- freqtrade/freqtradebot.py
- tests/test_freqtradebot.py
Verify sell-rate got a value - otherwise downstream code does not work.
Using PricingException here will cease operation for this pair for this
iteration - postponing handling to the next iteration - where hopefully
a price is again present.
Closes #3347
- Verify if price is None, in which case, we raise PricingException and continue with the next pair.
> Verify sell-rate returns a value.

- freqtrade/freqtradebot.py
Sell rate caching works by saving the latest sell rate to the cache dict.
However, when orderbook is on on the sell side, get_sell_rate is never called, preventing the cache from updating.
The result is that telegram / rpc get's old / outdated rates - while the bot itself works on updated rates.
This can easily be fixed by assigning the latest used rate to the cache in handle_trade (where the sell-rate looping is done).
> [minor] Fix sell rate caching

- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
Adding a pair to pairlists should provide feedback (errormessages) if wrong input was given.
This applies to both telegram and the rest api.
- Add feedback message to blacklist addition
- Use error_msg to eventually add additional error informations at a later point
> Improve RPC Blacklist by adding feedback

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_backtesting.py
Next step in btresult refactoring.
This extracts the generation of the backtest results into a seperate function and passes this to the "visualize" method (`show_backtest_results()`).
Again, no change in the output - just where and how the results are generated.
Next steps will most likely revisit the backtesting export format and store metrics alongside that.
> Refactor result store metrics

- config.json.example
- config_binance.json.example
- config_full.json.example
- config_kraken.json.example
- docs/configuration.md
- docs/rest-api.md
- freqtrade/constants.py
- freqtrade/loggers.py
- freqtrade/rpc/api_server.py
- freqtrade/templates/base_config.json.j2
- tests/test_configuration.py
Allow reducing log verbosity for api-server explicitly.
This will allow to hide the "GET /api/v1/..." calls by setting verbosity within the api_server config section to error.
I think this is important for the UI - as that tends to call the API quite often - clogging up the log with rest messages (and therefore potentially hiding other important messages).
This also addes the api_server to all default configuration templates - so it's easier for people to enable this later on.
> Apiserver logging

- freqtrade/data/converter.py
Fixes crashing `data-download --dl-trades` on empty trades data, which is reported in #3404
> Fix crash in #3404

- freqtrade/exchange/exchange.py
Log exchange milliseconds (as debug) to see where downloading trades for each pairs should stop
(now only "since" miliseconds are printed in the log, and "until" is not shown)
> Minor: Better exchange debug logging

- freqtrade/exchange/exchange.py
- tests/conftest.py
- tests/exchange/test_exchange.py
fix Division by Zero exception in fee calculation due to the trade incurring no cost (not filled enough - so costs fall most likely through API rounding 
fix #3431
- Explicitly check for availability of cost before dividing.
> Free trades should not crash the bot

- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc_telegram.py
Adding some readability to the Telegram messages, depending on whether you make a profit or loss.
Closes #2502
Nothing
Added emoji's to the Telegram messages, (all emoji's are unicoded so that they can work on all platforms, as request by Matthias):
* Blue circle (neutral color) for buying pairs.
* Green star emoji when the user made a profitable sell.
* Rocket emoji when the user made a profit >5.0%, to the moooon! (remove this if you don't like this one, or want to keep it more simplistic).
* Red cross emoji when the user made a loss.
* Warning emoji when the user hit a stoploss, warning messages or buy/sell cancels.
> Added emoji's to the Telegram RPC

- docs/advanced-hyperopt.md
- freqtrade/data/btanalysis.py
- freqtrade/optimize/default_hyperopt_loss.py
- freqtrade/optimize/hyperopt_loss_onlyprofit.py
- freqtrade/optimize/optimize_reports.py
- freqtrade/plot/plotting.py
- tests/data/test_btanalysis.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_optimize_reports.py
- tests/test_persistence.py
- tests/test_plotting.py
The column names for loading backtest data and for backtest reports should be aligned.
CUrrently, we've had profitperc from loading data, and profit_percent from backtesting itself.
(part of a multipart series of PR's).
- Use bracket notation in optimize_reports and hyperoptloss functions
- rename column returned from `load_trades_from_db()` and `load_backtest_data()`
- Reorder and rename optimize_report methods so all "text-generation" methods are in one place, and the stats-generation methods are at the top.
> Optimize sorting, rename column when loading backtest data

- docs/configuration.md
This should help with copy pasting the pairlists code block.
Also fixed minor typo on line 594 (was: "I selects" and is now: "It selects")
Solve the issue: n/a
- Fixed typo on line 594
- Added closing } for volume pair lists code block
see above
> Fixed typo and missing {

- docs/configuration.md
Add documentation about pricing related to market orders
closes #3160
- Add documentation section explaining how pricing should be configured for market orders.
> Add documentation about pricing related to market orders

- freqtrade/pairlist/IPairList.py
- tests/pairlist/test_pairlist.py
Explicitly raise  exception when markets is not loaded correctly.
Should only occur during test-pairlist, or if the exchange never successfully started
closes #3465
> Fix exception with stacktrace in test-pairlist

- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- tests/exchange/test_exchange.py
First part of market handling cleanup (split up to make the PRs small and clean):
* Remove async markets -- they are not used in the bot, neither required by other async ccxt methods we use. And it's not async fetching of market info -- it's same with `_load_market()`, but for async instance of the ccxt, should be equal to sync market data and also fetched synchronously...
* Rename `_reload_markets()` to `reload_markets()`, to make it public (used in freqtradebot.py)
* Change level for "Markets were not loaded. Loading them now.." message. It's a normal situation during markets data initialization, there is nothing wrong to warn the user about with a warning message.
> Cleanup async markets

- docs/configuration.md
- docs/exchanges.md
- docs/stoploss.md
- freqtrade/exchange/exchange.py
- freqtrade/exchange/ftx.py
- freqtrade/freqtradebot.py
- freqtrade/persistence.py
- setup.py
- tests/exchange/test_exchange.py
- tests/exchange/test_ftx.py
- tests/exchange/test_kraken.py
- tests/test_freqtradebot.py
- tests/test_integration.py
Introduce stoploss on exchange for FTX.
closes #3103 (only stoploss is remaining).
- Add methods to support stoploss on exchange
- FTX supports both stoploss-limit and stoploss-market (controlled via `order_types.stoploss` key).
- use `cancel_stoploss_order` and `get_stoploss_order` to determine which type of order we're querying. This defaults to `cancel_order` and `get_order` by default, but can be overwritten by exchange subclasses (as does FTX).
> Ftx stoploss

- freqtrade/optimize/hyperopt.py
format the roi, in order to facilitate the copy, in the return of the hyperoptmize
changed to python output to easy use in strategy file without mistakes
- New Format in hyperopt output
Actual return 
``` Buy hyperspace params:
{   'bb_width-value': 22.07556,
'bbwidth-enabled': True,
'direction': 'sma-enabled',
'ema-value': 65,
'rsi-enabled': True,
'rsi-value': 38,
'sma-value': 76,
'trigger': 'bb_lower3',
'width': 'bb_width1'}
Sell hyperspace params:
{   'sell-rsi-enabled': True,
'sell-rsi-value': 98,
'sell-trigger': 'sell-bb_lower1'}
ROI table:
{0: 0.16532, 14: 0.05331, 31: 0.02645, 57: 0}
``` 
changed to 
``` python
buy_params = {
'bb_width-value': 4.66539,
'bbwidth-enabled': True,
'direction': 'ema-enabled',
'ema-value': 32,
'rsi-enabled': False,
'rsi-value': 31,
'sma-value': 27, …
```
> change hyperopt output to print ready to copy to strategy

- freqtrade/configuration/deprecated_settings.py
- tests/test_configuration.py
Fail if both ticker_interval and timeframe are present in a configuration
Otherwise the wrong might be used, as it's unclear which one corresponds to the current user desire.
closes #3488
- fail if both ticker_interval and timeframe are detected
> Fix bug in timeframe deprecation

- freqtrade/exchange/exchange.py
- tests/conftest.py
- tests/exchange/test_exchange.py
Also reload async markets, otherwise the async exchange version does not have the new pairs - causing volumePairlist to cause errors when downloading data on newly listed pairs.
fixes #2876 - Logs and Empty ticker history  for new pair
> Also reload async markets

- config_full.json.example
- docs/configuration.md
- freqtrade/constants.py
- freqtrade/pairlist/AgeFilter.py
- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/PrecisionFilter.py
- freqtrade/pairlist/PriceFilter.py
- freqtrade/pairlist/ShuffleFilter.py
- freqtrade/pairlist/SpreadFilter.py
- freqtrade/pairlist/StaticPairList.py
- freqtrade/pairlist/VolumePairList.py
- tests/pairlist/test_pairlist.py
Adds a new pairslist filter called AgeFilter.
- Fixed a few typos in comments
- Added AgeFilter (with tests)
AgeFilter checks that each pair has been listed on the exchange for a minimum number of days. It does this by requesting daily candles, once a pair has passed this check it is cached, so no further candle requests will be made. Pairs under the required age will still be checked until they also eventually pass the required age threshold.
> AgeFilter for filtering out newly listed pairs

- config.json.example
- config_binance.json.example
- config_full.json.example
- config_kraken.json.example
- docs/rest-api.md
- freqtrade/constants.py
- freqtrade/rpc/api_server.py
- freqtrade/templates/base_config.json.j2
- tests/rpc/test_rpc_apiserver.py
When making authenticated calls to the rest API from a different ressource (and be that only a different localhost port), then a valid CORS policy is a must to allow the requests to not be blocked by the browser.
This PR will enable this by adding a setting, where users can define their source themselfs.
Regular users won't need to change this - but developers and people working on FreqUI might to allow cross-origin testing (without routing everything throught the webpack server).
- add `CORS_origins`  setting to api_server
> Fix RPC Cors

- docs/faq.md
Since this seems to be a common point of confusion - the FAQ now contains a "missing data fillup" section.
> Add missing data fillup to FAQ

- freqtrade/optimize/backtesting.py
- freqtrade/pairlist/PrecisionFilter.py
- tests/optimize/test_backtesting.py
- tests/pairlist/test_pairlist.py
Backtesting should load pairlists after the strategy to avoid running into problems if attributes needed in the pairlist are loaded from the strategy.
closes #3363 
closes #3463
- Load pairlist after strategy
- Explicitly fail if strategy-list is used in combination with PrecisionFilter.
- Explicitly fail loading PrecisionFilter if stoploss is not available (for test-pairlist ...)
> Backtesting should load pairlists after the strategy

- freqtrade/data/dataprovider.py
- freqtrade/exceptions.py
- freqtrade/exchange/binance.py
- freqtrade/exchange/common.py
- freqtrade/exchange/exchange.py
- freqtrade/exchange/ftx.py
- freqtrade/exchange/kraken.py
- freqtrade/freqtradebot.py
- freqtrade/persistence.py
- freqtrade/rpc/rpc.py
- tests/data/test_dataprovider.py
- tests/exchange/test_binance.py
- tests/exchange/test_exchange.py
- tests/exchange/test_ftx.py
- tests/exchange/test_kraken.py
- tests/rpc/test_rpc.py
- tests/test_freqtradebot.py
- tests/test_integration.py
This PR will introduce several new Errors used by the exchange class, as well as implement DDos protection backoffs.
It will also (and this is the main purpose) fix the bugs where a stoploss order is placed, and the api (binance) does not return the error immediately.
For a detailed explanation of the bug: https://github.com/freqtrade/freqtrade/issues/3499#issuecomment-650801197
closes #3273
closes #3513
closes #3116 
closes #3499
- Introduce `ExchangeError` as child-exception of DependencyException (as discussed in #3273)
- Change `TemporaryError` to be of a child of `ExchangeError` - this way we can catch all errors at once - and don't have to look out for TemporaryError specifically). It's not used anywhere outside of Exchange anyway.
- Introduce `DDosProtection` error - as Child of …
> Improve exchange errorhandling and API backoff

- freqtrade/freqtradebot.py
- freqtrade/worker.py
- tests/test_freqtradebot.py
When the bot is stopped while there are still open trades, the user gets a notification about this. Just to make sure he's aware of this.
- Added the warning message  
When the bots state changes to `stopped` and there are open trades, the user will get a notification on Telegram with how many open trades there are, and instructions on what to do if he didn't know this or didn't want this (the /stopbuy). See screenshot below.
> Warning message bot is stopped and left open trades

- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc_apiserver.py
Show winning vs. Losing trades in `/profit` calls.
This will allow to easily determine if a strategy made profit on most trades, or only had a few big winners.
- add Win / Loss to profit output.
> Show winning vs. losing trades

- docs/configuration.md
removed duplicate word using using
Word using is typed twice... Visual aesthetic correction.
Solve the issue: # none
- <change log #1> Removed duplicate wording
Remove duplicate wording in the documentation
> removed duplicate

- freqtrade/rpc/rpc.py
- tests/rpc/test_rpc_apiserver.py
Api response for /show_config will now contain timeframe_ms and timeframe_min.
Usefull for a UI (if calculations based on timeframes are necessary).
- add new fields timeframe_ms and timeframe_min to show_config response. (no change to telegram).
> [minor] Send timeframe min and ms in show_config response

- docs/data-download.md
- freqtrade/commands/__init__.py
- freqtrade/commands/arguments.py
- freqtrade/commands/data_commands.py
- freqtrade/data/history/idatahandler.py
- freqtrade/data/history/jsondatahandler.py
- tests/commands/test_commands.py
- tests/data/test_history.py
A simple new subcommand to list available data.
Can be usefull to determine which data is available.
Currently, for json data, this has limited use, as the same information can be gathered via `ls` - but usages in different future formats which store everything in one file will need to make use of this.
- add `list-data` command
> List available backtesting data

- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtesting.py
Fees of 0.0 (or 0) sholuld also be allowed, since some exchanges allow free trades (and it can be useful for testing, eventually).
closes #3594
> Allow 0 fee value by correctly checking for None

- config_full.json.example
- docs/configuration.md
- freqtrade/exchange/exchange.py
- freqtrade/pairlist/AgeFilter.py
- freqtrade/pairlist/PriceFilter.py
- tests/pairlist/test_pairlist.py
Adds range checks to min_days_listed in AgeFilter, logs messages if too low/high.
- Added range checks to min_days_listed in AgeFilter.
- Added tests for above.
Using min_days_listed < 1 will cause AgeFilter to be ignored.
Using min_days_listed > exchange's ohlcv_candle_limit will cap min_days_listed to this value.
> Added range checks to min_days_listed in AgeFilter

- freqtrade/rpc/rpc.py
Fix rpc_forcebuy SQL syntax error when compare pair strings. First happens in Postgres
- Using  == to compare instead of is_
> Fix SQL syntax error when compare pair strings in rpc_forcebuy

- docs/webhook-config.md
- freqtrade/freqtradebot.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
Add `trade_id` field to possible fields for webhooks.
closes #3578
> Add trade_id to webhooks

- freqtrade/resolvers/hyperopt_resolver.py
Reduce severity of hyperopt "does not provide" messages
They're not really warnings, as it's most of the time preferred to have the populate* methods in the strategy, not in the hyeropt file.
We do however need the message to help debug problems with this - as otherwise typos can become undebuggable.
closes #3371
> [minor] Reduce severity of hyperopt "does not provide" messages

- freqtrade/plot/plotting.py
- tests/test_plotting.py
Fixes #3544 
- adding a DataProvider before plotting the strategy
*We can now plot dataframes that makes use historical data coming from other pairs or other interval*
> Adding a dataprovider to the strategy before plotting

- docs/telegram-usage.md
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/commands/test_commands.py
- tests/conftest.py
- tests/data/test_btanalysis.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
- tests/test_persistence.py
Add telegram trades command to list recent trades. Using existed _rpc_trade_history
- Add command /trades <n> with n (default 10) is the number of trades history
> Add telegram /trades command

- freqtrade/edge/edge_positioning.py
- tests/edge/test_edge.py
Edge currently fails due to an error in a (uncovered) line when removebumps is enabled.
it seems like this is the first case this option has been used - or other users did not report this problem previously.
closes #3637 
- add test covering this scenario (fails without 2nd commit)
- add fix for this case
> Fix edge with removebumps enabled

- freqtrade/exchange/common.py
- freqtrade/exchange/exchange.py
- freqtrade/exchange/ftx.py
- freqtrade/freqtradebot.py
- tests/exchange/test_exchange.py
- tests/exchange/test_ftx.py
- tests/test_freqtradebot.py
When cancelling of a buy fails - we MUST reevaluate the returning of the order status.
Especially binance has a tendency to show updates to trades "late" via their api - so if the order fails to cancel - but is still reporting as open (as not canceled / closed) - then we should just do nothing and come back to this order later.
While this can lead to orders beeing on the exchange slightly longer - it's usually because the order was filled "right at that moment" - or a few ms before.
Fixes #3647
fixes #3638
- Improve logging
- Don't close orders assuming they are unfilled if cancelling fails!
- Increase fetch_order to retry another time (closes #3638). (even though binance claims the delay is 10s max - we've seen delays of 20s and more ...).
> Better handle cancelled buy orders

- docs/developer.md
- freqtrade/exceptions.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/rpc/rpc.py
- tests/test_freqtradebot.py
Some minor cleanup things 
- Document Exception hierarchy
- remove unused argument from `create_stoploss_order`
> [minor] Cleanup and exception hierarchy documentation

- docs/strategy-advanced.md
- docs/strategy-customization.md
- freqtrade/optimize/backtesting.py
- freqtrade/optimize/hyperopt.py
Dataprovider can be enabled in hyperopt mode, but only for the `populate_indicator()` section.
We then need to remove dataprovider before sending the data to the single workers.
closes #2608
- allow Dataprovider mode
- improve strategy documentation formatting (less nesting in the headers)
- provide one extensive sample that covers multiple dataprovider (and informative_pair) sections for simplicity
> Hyperopt enable dataprovider

- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc.py
Change daily return values for API to be numbers, not formatted strings.
Formatting should be left to the handler.
> Fix daily rpc for webservice

- docs/sandbox-testing.md
The sandbox documentation should not be focused on one sandbox, but should instead be generalized to work for 
closes #1630
- Remove custom instructions for gdax (gdax is not an exchange anymore ... and steps may change over time).
- List potential candidates that have a testnet / sandbox
> Update sandbox documentation

- freqtrade/exchange/common.py
added phemex to bad exchanges
reason: `"Could not fetch historical candle (OHLCV) data for pair BTC/EUR due to ArgumentsRequired. Message: phemex fetchOHLCV requires a since argument, or a limit argument, or both"`
> update bad exchanges

- freqtrade/vendor/qtpylib/indicators.py
- tests/test_indicators.py
- tests/test_talib.py
Counterpart to https://github.com/ranaroussi/qtpylib/pull/160 - adding numpy scalar types to the supported list for `crossed()` methods
Fixes bad behaviour when passing in a numpy type instead of a regular integer
crossed_above(series, 25) does work, while crossed_above(series, np.int64(25)) does not work.
On it's own, this is not a problem as you can pick how to create the integer, however, it can become a problem depending where the 2nd variable came from, for example if it comes from a ml library like scikit-optimize.
closes #3718 
- add np.integer and np.floating as "to convert" types.
> Allow numpy numbers as comparisons, too

- docs/rest-api.md
- docs/telegram-usage.md
- freqtrade/loggers.py
- freqtrade/main.py
- freqtrade/rpc/api_server.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- scripts/rest_client.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
- tests/test_configuration.py
Add logging endpoints (`/log` in telegram, `api/log` endpoint in the rest api).
Basically replicates the idea of #3308 - but in a proper way (without assuming a file is there, and reading from file).
- Use `BufferHandler` to keep the last 1000 logmessages in memory for easy query
- Expose last logs via RPC methods 
- Add "early-logging" - so also the first messages out of worker (before initialization) are logged correctly unless they are < INFO log level.
> Logging endpoints

- freqtrade/data/dataprovider.py
- freqtrade/optimize/backtesting.py
- tests/optimize/test_backtesting.py
Allow pairlists through dataprovider in backtesting / hyperopt modes.
closes: #3726
> [minor] Allow pairlists in backtesting

- docs/bot-usage.md
- docs/docker.md
- docs/index.md
- docs/installation.md
Move warnings related to clock sync to the installation sections - it's not really well suited for a "welcome" page.
closes #2491
> Move clock warning to installation pages

- freqtrade/constants.py
- freqtrade/exchange/exchange.py
- freqtrade/freqtradebot.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/telegram.py
- tests/exchange/test_exchange.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_telegram.py
- tests/test_freqtradebot.py
Currently, forcesell handles states of cancelled orders seperately, and out of line with regular cancels.
This leads to a disconnect, and to odd behavior if a trade is force/sold while an order is still open.
Closes #3084
- Disable double-notification in case of partial buy cancels
- have forcesell call the available methods from freqtrade to cancel orders.
> Forcesell should use the available methods for handling a trade correctly

- config.json.example
- config_binance.json.example
- config_kraken.json.example
Trailing stop should not be in the default config.
It'll be confusing and throw people off trying to match hyperopt results with backtests.
> Remove trailing_stop from default config example - it'll be misleading

- docs/strategy-customization.md
- freqtrade/strategy/__init__.py
- freqtrade/strategy/strategy_helper.py
- tests/strategy/test_strategy_helpers.py
Fix informative sample documentation, which had a lookahead bias
- Expose some helpers through freqtrade.strategy
- Move date by one timeunit to account for all dates beeing candle open dates
> fix Informative pair documentation

- freqtrade/rpc/api_server.py
- tests/rpc/test_rpc_apiserver.py
Fix a bug where the API could get "stuck" with some outdated information (not updating correctly anymore).
- remove scoped session on app_teardown in flask as recommended by the documentation
> scoped sessions should be closed after requests

- docs/data-download.md
- freqtrade/commands/arguments.py
- freqtrade/commands/data_commands.py
- tests/commands/test_commands.py
Download-data should support an absolute starting point.
This will be usefull for "initial" data downloads, as it does the "days back" calculation for the user.
For incremental downloads, the `--days` method should be preferred, as it can download the last 14 days of data for all pairs.
closes #3022
- Add support for --timerange in download-data.
> Download data should support absolute starting point

- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
zero pad wins/draws/losses (W/D/L) column to preserve alignment in console pretty print
- zero pad wins/draws/losses (W/D/L) column to preserve alignment in console pretty print
zero pad wins/draws/losses (W/D/L) column to preserve alignment in console pretty print
> prettify hyperopt console output

- config_full.json.example
- docs/telegram-usage.md
- freqtrade/constants.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/rpc_manager.py
- freqtrade/rpc/telegram.py
- freqtrade/rpc/webhook.py
- tests/rpc/test_rpc_manager.py
- tests/rpc/test_rpc_telegram.py
- tests/rpc/test_rpc_webhook.py
Allow finetuning of telegram notifications.
Possible settings are 
* "on" (sending all notifications
* "off" - Don't send this notification type
* "silent" - send notification, but without notification sound (There will be a notification, but the phone will not vibrate / ring).
- Allow finetuning of Notification types to reduce notification noise generated by the bot
This will mainly come in handy iwth later enhancements which will introduce additional notification types (like fill confirmations).
> Allow Notification finetuning for telegram messages

- freqtrade/wallets.py
- tests/test_wallets.py
Fix error of non-resetting balances.
Appeared on bittrex first, which seems to not return all balances anymore, but only the balances that a user actually owns (this was different before - i suspect it changed with the API switch to v3 in ccxt).
Closes #3797
> Fix wallets dont reset

- freqtrade/optimize/backtesting.py
- freqtrade/optimize/optimize_reports.py
- tests/optimize/test_backtesting.py
- tests/optimize/test_optimize_reports.py
parameters that can be overriden in the strategy are not in the global backtesting config object.
Therefore, we need to keep the strategy-specific configs around - and use the correct values in backtesting outputs.
> Backtesting - handle mdifferent max_open_trades per strategy

- freqtrade/optimize/hyperopt.py
- tests/optimize/test_hyperopt.py
Output for hyperopt for trailing space should be copy/pasteable to the strategy to avoid confusion.
closes #3781 
Old results:
```
trailing_params = {
'trailing_only_offset_is_reached': True,
'trailing_stop': True,
'trailing_stop_positive': 0.2299,
'trailing_stop_positive_offset': 0.25083
}
```
New results:
```
trailing_stop = True
trailing_stop_positive = 0.2299
trailing_stop_positive_offset = 0.25083
trailing_only_offset_is_reached = True
```
> Fix Hyperopt trailing output

- freqtrade/edge/edge_positioning.py
- tests/edge/test_edge.py
Edge should not filter out pairs that only produce wins.
closes #3839
- add test for win only scenario
- fix bug of 0 division as there are no losses.
> Implement division/0 checks for win and loss columns in edge

- docs/edge.md
Fix example R calculation in edge documentation (as pointed out on slack, the old calculation has at least one typo in the "number example")
We should not calculate with 100% loss. However, the old formulae seems incorrect in total.
@silvavn i would appreciate if you could have a look at this.
Adding this example was your work initially (#3745) - so maybe i'm completely wrong on this and did not understand something...
The formulas used now are from [this page](https://analyzingalpha.com/risk-reward-ratio-for-stocks#:~:text=The%20risk%2Dreward%20ratio%20measures,risking%20%241%20to%20make%20%242.) - but other pages seem to use the same formula.
To have a reference on the changes (since this is hard to read in diffs, and needs rendering):
Old version:
> Fix example R calculation in edge documentation

- config.json.example
- config_full.json.example
- config_kraken.json.example
- freqtrade/exchange/__init__.py
- freqtrade/exchange/binance.py
- freqtrade/exchange/bittrex.py
- freqtrade/exchange/exchange.py
- tests/data/test_dataprovider.py
- tests/exchange/test_exchange.py
Fix bug after API update by bittrex that breaks fetch-orderbooks as they removed the option to get custom levels of orderbook amounts, and now only support 1, 25 and 500 (removing the previous 1000 that was used). 
closes #3865
- Implement generic way for exchanges that only support a limited number of "limit" for orderbooks
- Add supported orderbook values for bittrex (subclassing Bittrex)
- Align sample configs (all should use dry-run by default ... )
> bittrex fetch_orderbook API change.

- freqtrade/commands/list_commands.py
- freqtrade/data/btanalysis.py
- freqtrade/freqtradebot.py
- freqtrade/persistence/__init__.py
- freqtrade/persistence/models.py
- tests/commands/test_commands.py
- tests/conftest.py
- tests/data/test_btanalysis.py
- tests/test_freqtradebot.py
- tests/test_main.py
- tests/test_persistence.py
Rename persistence.init to init_db to avoid importing the whole module and make the name clear.
- rename `init` to `init_db`
- rename `cleanup` to `cleanup_db`
> Rename persistence.init to init_db

- freqtrade/exchange/exchange.py
- tests/exchange/test_exchange.py
Test if return value is an exception when downloading historic data
closes #3883
- Verify if the return-value is an exception or a tuple (as expected) and handle that case accordingly.
> Test if return value is an exception when downloading historic data

- docs/strategy-customization.md
- freqtrade/freqtradebot.py
- freqtrade/persistence/__init__.py
- freqtrade/persistence/models.py
- freqtrade/persistence/pairlock_middleware.py
- freqtrade/rpc/rpc.py
- freqtrade/strategy/interface.py
- tests/exchange/test_exchange.py
- tests/pairlist/test_pairlocks.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
- tests/strategy/test_interface.py
- tests/test_freqtradebot.py
- tests/test_persistence.py
Round locked pairs to the candle-date they are really locked for.
This ensures that results from /locks are consistent with the real locking state without doing odd roundings.
Also, adds a pairlock middleware to handle pairlocks. This will enable supporting pair-locks in backtesting in the future.
Enhances #3879
- Round lock timestamp before inserting to the database
- implement pairlock middleware to have the possibility to skip database calls
> Pairlock middleware

- freqtrade/commands/cli_options.py
- freqtrade/constants.py
- freqtrade/resolvers/hyperopt_resolver.py
Improve message of missing hyperopt-loss function by providing a list of builtin loss functions.
- Improved exception message
> Improve error when hyperopt-loss-function is missing

- freqtrade/commands/data_commands.py
- freqtrade/commands/deploy_commands.py
- tests/commands/test_commands.py
`freqtrade download-data` does not require stake-currency - and it can lead to failures when it's set to something not matching the pairs downloaded.
It's therefore sensible to set it to empty for that run to avoid these problems.
closes #3901
- set stake-currency to "" for download-data
- Improve some tests
> Download data remove stake_currency

- .devcontainer/docker-compose.yml
- freqtrade/data/dataprovider.py
- tests/data/test_dataprovider.py
Use the value of `dataformat_ohlcv` when using `DataProvider.get_pair_dataframe`
Solve the issue: #3909
- Passing value of `dataformat_ohlcv` to `load_pair_history`
- Add unittest
Solves #3909
> Dataformat informative pair

- freqtrade/exchange/exchange.py
Catch asyncio timeout exception when reloading async markets
Closes #3941
> Catch asyncio.TimeoutError when reloading async markets

- freqtrade/plot/plotting.py
- freqtrade/templates/base_strategy.py.j2
- freqtrade/templates/sample_strategy.py
- tests/test_plotting.py
Plotting should support startup candles
Closes #3943
- support startup-candles for plotting, to allow plotting with correct startup period.
- increase startup_candle_count for sample-strategy since TEMA(9) requires 24 startup candles, not 9.
> Plot startup candles

- docs/windows_installation.md
- Fixed a typo
- Replaced the hyphens U+2011 with U+002D because otherwise pip will throw an error saying ```ERROR: TA_Lib‑0.4.19‑cp38‑cp38‑win_amd64.whl is not a valid wheel filename.```
> Fix typo in windows installation docs

- freqtrade/data/history/hdf5datahandler.py
- tests/data/test_history.py
Convert np to None when loading hdf5 trades to allow duplicate detection
closes #3961 
- add test and fix for wrong duplicate detection when using hdf5 with trades
> Convert np to None when loading hdf5 trades to allow duplicate detection

- docs/exchanges.md
- docs/stoploss.md
- freqtrade/exchange/kraken.py
- mkdocs.yml
- tests/exchange/test_kraken.py
Implement kraken stoploss-limit
replaces #3954 - which unfortunately has the repository deleted, so updating that branch is no longer possible.
I did however use the existing commits to update the documentation.
- Implement stoploss-limit for kraken, which is now [supported again](https://blog.kraken.com/post/5282/stop-loss-limit-take-profit-limit-two-new-advanced-orders-go-live-on-kraken/).
> Kraken stoploss-limit

- config_full.json.example
- docs/includes/pairlists.md
- freqtrade/constants.py
- freqtrade/exchange/exchange.py
- freqtrade/pairlist/AgeFilter.py
- freqtrade/pairlist/VolumePairList.py
- freqtrade/pairlist/rangestabilityfilter.py
- freqtrade/pairlist/volatilityfilter.py
- tests/exchange/test_exchange.py
- tests/pairlist/test_pairlist.py
This PR will introduce the RangeStabilityFilter
It's calculated over the last 10 days (by default)- using the % change between highest high and lowest low in this time interval.
If this Range % is below the specified threshold (1% by default) the pair is rejected from the pairlist.
This can be useful to remove stable-coins from the pairlist without explicitly blacklisting them, as stable-coins usually move within a very tight range, which makes trading them profitable very difficult.
- Introduce RangeStabilityFilter Filter
- Added tests for this new filter
> RangeStabilityFilter filter - filter for pairs without much movement

- docs/configuration.md
Correct which parameter name was referred to within the 2nd Note under "Amend last stake amount"
Make sure someone seeking to adjust the last stake amount min ratio knows to use `last_stake_amount_min_ratio` instead of `last_stake_amount_min_ratio`.
- Fix parameter in documentation.
> [Documentation] Fix parameter name

- docs/stoploss.md
Attempt to fix unintended LaTeX rendering between to `$` symbols by applying [MathJaX's ignore class](https://docs.mathjax.org/en/latest/options/document.html?highlight=mathjax_ignore#option-descriptions).
Before this fix, as displayed below, there is awkward rendering. After this fix, the portion of text should now display: `101$, the stop loss will be 91.8$`.
> [Documentation] Prevent unintended LaTeX rendering

- freqtrade/configuration/deprecated_settings.py
- freqtrade/constants.py
- tests/test_configuration.py
Remove long deprecated settings, which moved from experimental to ask_strategy.
From now on, freqtrade will fail to start if these settings are still in experimental
- Fail if `use_sell_signal`, `sell_profit_only` or  `ignore_roi_if_buy_signal`  are still configured in the experimental section
> Remove deprecated experimental settings

- docs/backtesting.md
- freqtrade/strategy/interface.py
- tests/optimize/test_backtest_detail.py
- tests/test_freqtradebot.py
Changed the `should_sell()` method, to handle the case where both ROI and trailing stoploss are reached in backtest. In that case, the sell reason should be ROI, and not stoploss.
When backtesting some strategies in long timeframes (1h, 2h, 4h..), I noticed that trailing stop loss made profits superior to the strategy's ROI.
I'm not sure if this behavior is intended, but it distorts backtest and hyperopt results significantly.
When reading the documentation, I understood that ROI is always tested first, in order to protect capital. But in this case, capital isn't protected, and profits are …
> change backtesting behaviour if roi and trailing-stop happen at the same time

- freqtrade/freqtradebot.py
- freqtrade/resolvers/strategy_resolver.py
- freqtrade/strategy/interface.py
Ensure non-defined attributes fail correctly, and not implicitly with an attribute error.
Remove unnecessary check, as stoploss cannot be none (it's mandatory and
a number)
- remove None checks on strategy.stoploss as it's required and guaranteed to be a float (by strategy resolver)
> Ensure non-defined attributes fail correctly

- Dockerfile.armhf
Align Raspberry build to regular build using staged dockerfiles.
Replicates #4046 for the arm build.
The image builds correctly ase can be seen [here](https://github.com/freqtrade/freqtrade/actions/runs/422600036), and it's running just fine, reducing the image sice by ~200 MB.
- use multistage docker build.
> Docker stage pi

- freqtrade/commands/arguments.py
- freqtrade/exchange/exchange.py
- freqtrade/pairlist/AgeFilter.py
- freqtrade/pairlist/IPairList.py
- freqtrade/pairlist/PrecisionFilter.py
- freqtrade/pairlist/PriceFilter.py
- freqtrade/pairlist/SpreadFilter.py
- freqtrade/pairlist/pairlistmanager.py
- freqtrade/pairlist/rangestabilityfilter.py
- tests/conftest.py
- tests/exchange/test_exchange.py
- tests/plugins/test_pairlist.py
- tests/rpc/test_rpc_apiserver.py
- tests/strategy/test_interface.py
Refactor pairlist ohlcv download to use async
THis will speed up usage of AgePairlist and RangeFilterpairlist (by a huge amount  ...)
- allow `-v` for test-pairlist
- use async download method for pairlists
- slightly change refresh_pairlist to support non-caching downloads
> Refactor pairlist ohlcv download to use async

- freqtrade/exchange/__init__.py
- freqtrade/exchange/binance.py
- freqtrade/exchange/bybit.py
- freqtrade/exchange/exchange.py
- freqtrade/exchange/kraken.py
- freqtrade/pairlist/AgeFilter.py
- tests/exchange/test_exchange.py
Use limit parameter for fetch_ohlcv to avoid failures for some exchanges which requrire this parameter.
By setting `ohlcv_candle_limit` to the correct value, there is no downside (by increasing this to 1000 for binance, data-download will even be sped up). 
There are no "holes" left in the data due to this change (explicitly tested against this).
closes #3993
- Add limit parameter to `fetch_ohlcv()` call
- set "ohclv_candle_limit" correctly for supported exchanges
- subclass exchange for ByBit - as it allows only 200 candles per call
> set ohlcv limit on ccxt calls

- docs/telegram-usage.md
- freqtrade/rpc/telegram.py
- tests/rpc/test_rpc_telegram.py
Telegram: specify custom keyboard in config.
See docs/telegram-usage.md
closes #3942
closes #4081
> Telegram: specify custom keyboard in config

- freqtrade/rpc/__init__.py
- freqtrade/rpc/api_server.py
- freqtrade/rpc/rpc.py
- freqtrade/rpc/rpc_manager.py
- freqtrade/rpc/telegram.py
- freqtrade/rpc/webhook.py
- tests/rpc/test_rpc.py
- tests/rpc/test_rpc_apiserver.py
- tests/rpc/test_rpc_telegram.py
- tests/rpc/test_rpc_webhook.py
Deconstruct RPC dependencies, so handlers (Telegram, api, webhook) don't inherit RPC, but are passed an instance of RPC.
This way, we'll not have the a child of the same instance around 2-3 times, but can use the same RPC instance.
- Change inheritance of RPC methods
> Refactor RPC dependency tree

- .github/workflows/ci.yml
- docs/developer.md
- tests/conftest.py
- tests/exchange/test_ccxt_compat.py
This will prevent verision incomatibilities.
The tests will only run when explicitly enabled (via `pytest --longrun`) - and run in ci only once.
This can also serve as a quick method to verify a unsupported exchange's public methods.
- Add compatibility tests with ccxt
- Allow quick testing of new exchanges
> add tests to verify exchange compatibility with ccxt
