freqtrade/freqtrade

requirements.txt

Upgrade to latest `python-telegram-bot`, `requests` and `urllib3` dependencies.

Upgrade several dependencies

---

analyze.py
test/test_analyze.py

Initial refactoring and tests for `analyze.py`.
- Separated pulling data from bittrex, parsing it and populating indicators and trends each to their own methods
- Changed parsing to use DataFrames own functions to sort, rename and drop data

Refactor analyze.py

---

analyze.py

Here's a new buying strategy:
- Uses ADX to see if there's enough momentum for a real price change, not just back and forth movement
- Uses parabolic SAR to only buy when market turns bullish
- Uses EMA to double check that the price seems to be swinging up
- Switches to five minute ticker because most indicators are pretty useless in the one minute volatility
Now this strategy seems clearly better than the previous one, but this is just my feeling based on manual verification with many coins. We really need a way to back test different strategies with historical data. @shusso is working on creating such a back testing for us.

New buy strategy

---

freqtrade/main.py
freqtrade/tests/test_main.py

This PR should fix the whitelist vanishing problem

fix whitelist vanishing

---

freqtrade/exchange/bittrex.py

remove redundant 'name' property and pair validation call

Bittrex provider

---

freqtrade/analyze.py

set exchange in analyze.__main__ to fix plotting

---

freqtrade/tests/test_backtesting.py
freqtrade/tests/test_hyperopt.py

Get remove of duplicated backtest functionality for backtesting and hyperopt

Refactor backtest functionality

---

freqtrade/tests/testdata/download_backtest_data.py

When running from project root download the files to the testdata folder instead of cwd

download testdata to correct folder when running from project root

---

freqtrade/analyze.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_hyperopt.py
qtpylib/indicators.py

- pulls in the indicators from qtpylib
- uses one of them (Awesome Oscillator) for testing that integration to our bot works

Include new indicators from qtpylib

---

freqtrade/main.py
freqtrade/persistence.py
freqtrade/rpc/telegram.py

Handles SIGINT, SIGTERM and SIGABRT proces signals and does a proper cleanup for `persistence` and `telegram` modules.

handle SIGINT, SIGTERM and SIGABRT process signals

---

freqtrade/analyze.py
freqtrade/tests/test_hyperopt.py

Started adding different indicators and buy strategies in search of the awesome buy strategy. I don't want to be the only one researching and adding these, others should feel welcome to add more.

More triggers and guards to hyperopt

---

freqtrade/analyze.py
freqtrade/main.py
freqtrade/misc.py
freqtrade/persistence.py

Adds basic argparse functionality and an option for a custom configuration path
```
$ bin/freqtrade --help
usage: freqtrade [-h] [-c PATH] [-v] [--version]
Simple High Frequency Trading Bot for crypto currencies
optional arguments:
-h, --help            show this help message and exit
-c PATH, --config PATH
specify configuration file (default: config.json)
-v, --verbose         be verbose
--version             show program's version number and exit
```

add argparse and implement basic arguments

---

freqtrade/analyze.py
freqtrade/main.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_backtesting.py
freqtrade/tests/test_main.py
freqtrade/tests/test_telegram.py

Point of the PR is to give a starting point for testing sell strategies. It contains very simple RSI based exit strategy and it's plugged to the backtesting so we can start testing more advanced strats.

Sell signal

---

freqtrade/__init__.py
freqtrade/analyze.py
freqtrade/exchange/__init__.py
freqtrade/exchange/bittrex.py
freqtrade/main.py
freqtrade/misc.py
freqtrade/rpc/telegram.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_exchange.py
freqtrade/tests/test_main.py
freqtrade/tests/test_rpc.py
freqtrade/vendor/qtpylib/indicators.py

This PR switches from using dedicated signal handler to use pythonic exception handling, this way it won't freeze while hitting CTRL-C multiple times.
It also no longer uses the built-in `RuntimeError` but an `OperationalException` if an error is raised which requires manual intervention.
Fixes #109

fix signal handling

---

freqtrade/analyze.py

Added Plus and Minus Directional Indicator and Directional Movement into dataframe.
Buy if at the low end of normal range and the price is increasing.
Buy into extreme gains regardless of if it's on the low part of the range.
Avoid buying when the price is on a long decrease even if it's low.
Sell anytime the price is above the top end of normal range and the momentum slows.
Sell on an extreme drop.

Better buy and sell strategy

---

freqtrade/rpc/telegram.py

Add keyboard markup for telegram bot

keyboard markup for telegram bot

---

config.json.example

as it will be removed from bittrex Dec 8th

remove BTC_TIME

---

README.md
freqtrade/rpc/telegram.py
freqtrade/tests/test_rpc_telegram.py

Add a Telegram command that shows the user their per-day profit/loss (in BTC)

Added daily profit telegram command

---

freqtrade/exchange/bittrex.py

This PR handles NO_API_RESPONSE so that it no longer requires human intervention (fixes #161).

Handle NO_API_RESPONSE as temporary error

---

README.md
freqtrade.service

This PR adds a systemd service file to run freqtrade as user daemon in the background.

add systemd service file

---

freqtrade/misc.py

fix hyperopt not getting default ticker_interval

---

scripts/plot_dataframe.py

`scripts/plot_dataframe.py` was broken after refactoring of exchange handling in the bot.

Fix plotting broken by refactoring

---

.travis.yml

As the test coverage is small, added smoke tests for travis to catch that the basic usage works (as hyperopt is currently broken). Will fix hyperopt in another PR and after we can merge this.
I guess merging #196 first will make Travis pass in this PR

add smoke tests to run a round of hyperopt and backtesting

---

.travis.yml
install_ta-lib.sh

Caches TA-lib build results. Skips building of TA-lib if the cache is available.
Build time without cache:
Build time with cache:

Cache TAlib

---

install_ta-lib.sh

See [travis-ci](https://github.com/travis-ci/travis-ci/issues/5059)

use curl instead of wget (see travis-ci/issues/5059)

---

CONTRIBUTING.md
README.md

Moved contribution guide to it's own file and expanded with text from @glonlas

Create contribution guideline

---

freqtrade/optimize/hyperopt.py

filter nan values from total_profit and avg_profit

---

freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py
freqtrade/tests/test_optimize_backtesting.py

This PR is main purpose is to balance the Hyperopt objective function after the changes in #200 to profit calculations. That is done in a0a0a85. Rest of the commits are misc cleanups done to the hyperopting.

Tweak Hyperopt

---

freqtrade/analyze.py
freqtrade/exchange/__init__.py
freqtrade/main.py

This should speed up the check and analyze signals phase.

Run get_signals async.

---

freqtrade/main.py
freqtrade/optimize/__init__.py
freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py
freqtrade/tests/test_optimize_backtesting.py

Fixes one unit test that fails on Windows due to path parsing.
Fixes miscellaneous linter warnings.

Lint fixes

---

freqtrade/rpc/telegram.py

Daily profit was miscalculated, the time part of the time should not be taken to get the previous day and the next day, this commit remove this. Profit and Daily commands are now very close when summing the results of every day profit.

Fixing daily profit,

---

freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/test_acl_pair.py
freqtrade/tests/test_dataframe.py

Backported test from my branch, that are relevant to original branch.
Please see if any of value.

tests for dataframe, whitelist and backtesting

---

freqtrade/main.py
freqtrade/tests/test_misc.py

Fixing the positional parameter naming + unit tests updated to fix issue #262

Fixing bug #262

---

freqtrade/analyze.py
freqtrade/exchange/__init__.py
freqtrade/main.py

Reverts #223 See the discussion in #266 and the issue #255

Revert "Make get_signals async."

---

freqtrade/main.py

Adding more info in the Buy Message sent to telegram (stake amount and amount using fiat converter)

Add fiat display in sell msg

---

freqtrade/main.py
freqtrade/tests/test_acl_pair.py

Fixing issue #283 
- Modify function `refresh_white_list` to preserve sorting order
- Modify function `refresh_white_list`  to remove unknown pairs
- Modify function `refresh_white_list`  to remove pairs that are not active 
- Modify Unit test to handle BaseVolume sorting order checking when using dynamic-whitelist

fixing the sorting issue in MarketSummary when using --dynamic-whitelist (issue #283)

---

freqtrade/main.py
freqtrade/tests/test_acl_pair.py

Reading coverage reports, I've found a path that was not tested, and contained a bug while filtering pairs that are in the blacklist

Bug in blacklist pair handling

---

freqtrade/analyze.py
freqtrade/misc.py
freqtrade/tests/test_analyze.py

Log exceptions to get better backtrace. Also catch all exceptions for analyzing the ticker

Log exceptions

---

freqtrade/analyze.py
freqtrade/optimize/hyperopt.py

This PR adds 28 optional indicators `populate_indicators()` to help users building strategies. In order to save memory and cpu, only indicators used by the buy, sell strategy and hyperopt in `develop`branch are enabled.
- Add 28 indicators with the value they can take
- Reorder indicators per categories
- Add a warning message about memory and CPU usage when enabling unused indicators in `populate_indicators()`
- Add `qtpylib.bollinger_bands()` in addition of the `ta.BBANDS()`
- `crossed_above` and `crossed_below` in `analyse.py` are accessible via `qtpylib.crossed_above` and `qtpylib.crossed_below`
To follow the idea of @seansan in the PR #313 that some indicator are not present in `populate_indicators()`, this PR aims to add optional Indicator (commented) to help users building better …

Add 28 optional indicators populate_indicators()

---

docs/installation.md

Replace private git URL with public https git URL
Small tweak to installation docs.

public git URL

---

.gitignore
freqtrade/optimize/hyperopt.py
freqtrade/tests/optimize/test_hyperopt.py

Resume hyperopt based on previous hyperopt run 
Hyperopt will now handle SIGINT and upon receiving it, it'll pickle the current trials file. When hyperopt is ran the next time, it'll un-pickle the trials file and continue from previous run.

resume hyperopt run

---

.pylintrc
freqtrade/analyze.py
freqtrade/exchange/bittrex.py
freqtrade/exchange/interface.py
freqtrade/fiat_convert.py
freqtrade/main.py
freqtrade/misc.py
freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py
freqtrade/optimize/hyperopt_conf.py
freqtrade/persistence.py
freqtrade/rpc/telegram.py
freqtrade/tests/conftest.py
freqtrade/tests/exchange/test_exchange_bittrex.py
freqtrade/tests/optimize/test_optimize.py
freqtrade/tests/test_acl_pair.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_dataframe.py
freqtrade/tests/test_fiat_convert.py
freqtrade/tests/test_main.py
freqtrade/tests/test_misc.py
freqtrade/tests/test_persistence.py
scripts/plot_dataframe.py

This PR contains a bunch of misc PyLint fixes.
```
Your code has been rated at 9.30/10 (previous run: 8.37/10, +0.93)
```

Linter fixes

---

freqtrade/misc.py

Testdata path broken on Windows per #359

testdata path to use os.path.join

---

scripts/plot_dataframe.py

Fix `plot_dataframe.py` that does not work anymore since the refactoring of the parameters (PR #324)
Solve the issue: #363
- Fix fatal with `plot_dataframe.py`

Fix plot_dataframe.py

---

freqtrade/__init__.py

Update freqtrade version for the incoming tag and master branch rebase.
- freqtrade version update from 0.14.3 to 0.15.1

Update freqtrade version

---

docs/installation.md

Updated, cleaned up installation docs...

New Installation Docs

---

freqtrade/optimize/hyperopt.py

Another PR to balance the Hyperopt objective function and default parameters
- Adjusted objective function to reduce the effect number of trades and trade duration have to the result
- Adjusted default trade and profit targets to more realistic values
- Added a little more debug output to help in using Hyperopt

Balancing hyperopt objective

---

docs/backtesting.md
freqtrade/misc.py
freqtrade/optimize/__init__.py
freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/test_misc.py
freqtrade/tests/testdata/download_backtest_data.py

Export trades made by backtest into a file.

Backtest export

---

docs/plotting.md
freqtrade/misc.py
scripts/plot_dataframe.py
scripts/plot_profit.py

Please atleast cherrypick the first commit. It contains a bugfix and docs.

Plot profit from exported backtesting results

---

config.json.example
docs/configuration.md
freqtrade/main.py
freqtrade/misc.py
freqtrade/tests/conftest.py

ticker_interval as int (instead of string)

---

freqtrade/tests/optimize/test_backtesting.py

Needed for running testcases individually like:
pytest -s file::case

tests: run backtest single

---

docs/configuration.md

[DOC] Correct typos about telegram.

[DOC] Correct typos about telegram.

---

freqtrade/main.py
freqtrade/optimize/__init__.py
freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/optimize/test_optimize.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_main.py
freqtrade/tests/test_misc.py

Another set of random PyLint warnings fixed

Pylint fixes

---

docs/backtesting.md

Update the documentation on backtesting with custom strategies.
Updated file `backtesting.md`

Backtest with **With a (custom) strategy file**

---

freqtrade/rpc/telegram.py
freqtrade/tests/conftest.py
freqtrade/tests/rpc/test_rpc_telegram.py

Fix error when USDT on balance
Solve the issue: #402
Fix exception in /balance command, convert tethers to BTC

Fix usdt balance

---

.gitignore

Simple PR to ignore `freqtrade-plot.html`. So users will not commit it.
- Add `freqtrade-plot.html` into `.gitignore`

Ignore freqtrade-plot.html

---

docs/bot-usage.md

Fixed typo in 'bot-usage.md' documentation.

Fixed typo. Update bot-usage.md

---

freqtrade/main.py

**Summary**
This PR aims is to prioritize selling over buying in poor network conditions.
**Quick changelog**
- refactoring _process to start first by closing open trades then looking for buy opportunities
Fixes issue #480

Fixing buy and sell order

---

scripts/plot_dataframe.py

Changes the buy and sell markers in `plot_dataframe.py` graphs to:

Change buy and sell markers in plot_dataframe

---

scripts/plot_dataframe.py

Just an parameter to control vertical spacing

add an option to control vertical spacing

---

freqtrade/main.py
freqtrade/optimize/backtesting.py
freqtrade/persistence.py
freqtrade/strategy/strategy.py
freqtrade/tests/test_persistence.py

Another 48% faster backtesting. Because all savings were in the backtesting core loop, they will have the same improvement to hypeopt speed.

Faster backtesting

---

scripts/plot_dataframe.py
scripts/plot_profit.py

Cleanup plot scripts

---

freqtrade/optimize/__init__.py

Fixes yet another use of hardcoded path separator.

Correctly join paths in ticker loading

---

freqtrade/analyze.py
freqtrade/exchange/bittrex.py
freqtrade/main.py
freqtrade/rpc/telegram.py
freqtrade/tests/exchange/test_exchange.py
freqtrade/tests/exchange/test_exchange_bittrex.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/optimize/test_optimize.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_main.py

- Remove the word "Got" from like 100 places. And few instances of "Got Got".
- Cleanup logging based tests
- Shorten and/or improve many logging messages
- In case of old dataframe, print out how many minutes it is delayed with

Improve log messages

---

docs/pre-requisite.md

Simple word replacement in docs.

Should be Telegram, not Instagram

---

freqtrade/main.py

Fixes a reference before assignment error during shutdown and sets correct return codes on exit.
- Fixes a reference before assignment issue
- Set correct return codes

fix reference before assignment error during shutdown

---

freqtrade/arguments.py
freqtrade/configuration.py
freqtrade/constants.py
freqtrade/freqtradebot.py
freqtrade/strategy/resolver.py
freqtrade/tests/conftest.py
freqtrade/tests/test_constants.py

Define constants on module level and remove static class as discussed in objective PR.
- Define constants on module level and remove static class

define constants on module level

---

freqtrade/tests/test_misc.py

Add tests for format_ms_time 
- Adds tests for format_ms_time conversation function
*note* most tests will not pass - but this one should.

Add test for format_ms_time

---

setup.sh

Fix a typo in setup.sh

---

docs/telegram-usage.md

Based on the recent "telegram takedown attempts" by our lovely neighbouring bear add a note about using proxy per #609

docs: Add note about using telegram proxy

---

scripts/plot_dataframe.py
scripts/plot_profit.py

some issues were left behind after taking `ccxt` branch into use

Scripts: fix syntax errors and flake8ify

---

README.md
docs/bot-usage.md
docs/configuration.md

Update the README and documentation with the exchanges supported, and refresh the bot usage section

Update Readme and documentation

---

freqtrade/constants.py
freqtrade/fiat_convert.py

Reduce duplicatd list of FIAT currencies (the list was actually identical - but present in 2 places in the code).
- improve code quality by reducing duplicate stuff

Refactor fiat-list to constants

---

CONTRIBUTING.md

Add documentation on how to run mypy.
Necessary as #808 added mypy-checking as part of travis.ci
- updated Contributing documentation

update contributing document to include mypy

---

docs/configuration.md

this PR adds documentation about the **process_throttle_sec** parameter

Update doc process throttle

---

docs/plotting.md

include an example or plotting a strategy buy/sell output.

plotting.md update.

---

freqtrade/tests/test_main.py

This PR adds and fixes some tests for `main.py`. Some of them had `has_log` calls which were never asserted and failed silently.

add and fix tests for main.py

---

docs/bot-optimization.md

Add reference to strategy repository and improve some markdown formatting
- add reference to strategy repository
- fix markdown to have markdownlint not complain that much

add reference to strategy repository

---

freqtrade/arguments.py
freqtrade/fiat_convert.py
freqtrade/tests/test_arguments.py
freqtrade/tests/test_fiat_convert.py
freqtrade/tests/test_freqtradebot.py
setup.cfg

We cannot stay at only 96% of code coverage and be having a Pylint score going down.
This PR is to cover part of the code not tested but unit tests and cleaning code by improving Pylint score.

Increase code coverage and improve Pylint

---

freqtrade/arguments.py
freqtrade/optimize/__init__.py

Fix crash on windows upon startup
fixes issue: slack #general
- Initialize TimeRange with arguments

fix windows-specific init issue with named tuple

---

freqtrade/tests/optimize/test_backtesting.py

Fixes a non-firing test (assert was missing).
Also fixed the test as part of this - as it would have failed in develop.

fix backtest tests

---

scripts/download_backtest_data.py

Currently, the download-script is failing if one pair in pairs.json is not available on that exchange.
The changes proposed here will check for pair availability, and warn (but not fail).
It will also fix a (very ungraceful) exception of 3-4 consequent stacktraces.
* check for pair availability
* sort pair list to have a reliable download sequence
add `VTC/BTC` as well as an available pair `ETH/BTC` to your `pairs.json` and try to download before / after.
The scipt will now skip the pair - and show a warning at the end of pairs that failed to download.
Test-line:
`/scripts/download_backtest_data.py --exchange binance --timeframe 1m --days 1`

fix downloadscript crash if a pair is not available

---

freqtrade/vendor/qtpylib/indicators.py

We pulled qtpylib on 25.10.2017, since then a few things changed upstream: https://github.com/ranaroussi/qtpylib/commits/master/qtpylib/indicators.py
This PR contains the cherry-picked commits since 25.10.2017 for `vendor/qtpylib/indicators.py`.

Apply qtpylib upstream changes

---

freqtrade/optimize/hyperopt.py
freqtrade/strategy/__init__.py
freqtrade/strategy/resolver.py
freqtrade/tests/strategy/test_strategy.py

Implements logic to properly import a given strategy in global freqtrade.strategy scope. The main focus of this PR is to fix the issue mentioned in #930
This work is based on cherry-pick of 8ddd87beaeb5a00ca132987b6b62076eba5f7a54

Improve strategy handling

---

README.md
docs/installation.md

Change the README structure to bring to the top the essential information for new visitors.
This new README is available here: https://github.com/freqtrade/freqtrade/blob/feature/revamp_readme/README.md
- Update README page

Update the README structure

---

freqtrade/__init__.py

will do a `0.17.0` release so bumping version on develop

bump develop to 0.17.1

---

freqtrade/tests/test_freqtradebot.py

Fix missing mocks where tests which fail / take forever when no network connection is available.

Add get_markets mock to new tests

---

freqtrade/__main__.py
freqtrade/analyze.py
freqtrade/arguments.py
freqtrade/configuration.py
freqtrade/fiat_convert.py
freqtrade/freqtradebot.py
freqtrade/indicator_helpers.py
freqtrade/misc.py
freqtrade/optimize/backtesting.py
freqtrade/persistence.py
freqtrade/rpc/rpc.py
freqtrade/strategy/interface.py
freqtrade/strategy/resolver.py
freqtrade/tests/conftest.py
freqtrade/tests/exchange/test_exchange.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/optimize/test_optimize.py
freqtrade/tests/rpc/test_rpc.py
freqtrade/tests/rpc/test_rpc_manager.py
freqtrade/tests/rpc/test_rpc_telegram.py
freqtrade/tests/test_acl_pair.py
freqtrade/tests/test_analyze.py
freqtrade/tests/test_configuration.py
freqtrade/tests/test_fiat_convert.py
freqtrade/tests/test_freqtradebot.py
freqtrade/tests/test_indicator_helpers.py
freqtrade/tests/test_main.py
freqtrade/tests/test_misc.py
freqtrade/tests/test_persistence.py

Yay for pointless PR's. From one comment from @gcarq , I wanted to have our imports sorted to conform with PEP8.

sort imports

---

freqtrade/configuration.py
freqtrade/freqtradebot.py
freqtrade/main.py
freqtrade/optimize/__init__.py
freqtrade/optimize/hyperopt.py
freqtrade/persistence.py
freqtrade/rpc/rpc.py
freqtrade/rpc/telegram.py
scripts/convert_backtestdata.py

another set of replacing `format` with fstrings. Will do a minor refactoring to `rpc.py` and `telegram.py` to make it a bit more easily "fstringifying"

Fstrings in use

---

Dockerfile

keeping dockerfile uptodate by updating the dockerfile to 3.6.6

Update Dockerfile to 3.6.6

---

docs/sql_cheatsheet.md

The profit should be close_rate/open_rate-1   not close_rate/open_rate

Update doc for manually fix trade

---

scripts/plot_dataframe.py

1. if database is defined in config file, it currently tosses an exception that only export file or db is defined
2. if trades are loaded from databases, plot crashes with an exception 'cannot compare tz-naive and tz-aware datetime-like objects'
3. if Trade is not closed, crashes with exception that NoneType has no field timestamp
all should be fixed

Fixing database issues

---

freqtrade/optimize/backtesting.py

Add missing "s" in backtest total results
Solve the issue: #1013
fixing my stupid copy/paste error

add missing s to Backtest cum results

---

freqtrade/freqtradebot.py

Add docs to get_trade_stake_amount function

Add docs to get_trade_stake_amount function

---

freqtrade/arguments.py
freqtrade/configuration.py
freqtrade/main.py
freqtrade/tests/test_arguments.py
freqtrade/tests/test_configuration.py
freqtrade/tests/test_main.py

Reverts freqtrade/freqtrade#1045
This introduces a bug which lowers the log-level to 0 (basically logging only errors).
will reinvestigate - reverting for now .

Revert "Add more verbosity levels"

---

freqtrade/exchange/__init__.py
freqtrade/tests/exchange/test_exchange.py

This is #1083 in a clean commit/PR

Enable GDAX support by rounding amount/rate (with unit tests)

---

Dockerfile
docs/installation.md
freqtrade/tests/test_talib.py
install_ta-lib.sh

Fix Talib Bollinger Bands bug when working on small values.
Solve the issue: https://github.com/mrjbq7/ta-lib/issues/151
Talib was considering small values like 0.00000001 as 0. So the calculation of indicators like Bollinger Bands was broken. All band had the same value. I rised the talib prescision to 0.000000000000000001 at the installation to fix that problem.
Now the Bollinger Bands is working as expected on all assets.
Regards,
Axel

fix talib bug on bollinger bands and other indicators

---

freqtrade/persistence.py
freqtrade/tests/test_persistence.py

Fix broken database migration after the last DB update
Solve the issue: #1121 
- improve test for this case
- fix migration

Fix db migration

---

docs/installation.md

Updated and cleaned up the installation documentation
solve issues: #1169, fill documentation need #939
* refactor documentation (some parts are identical between mac and linux)
* improve windows section with explanation about a commonly seen error
* add section explaining how to install on a raspberry pi
it's best to view the whole document, not just changes as a lot of duplicates between Mac and linux have been removed.

installation documentation update

---

docs/configuration.md

Add documentation for `ccxt_rate_limit`

Document ccxt_rate_limit

---

README.md

I fixed a typo.
Solve the issue: no known issue
- fixed a typo

fixed being

---

docs/installation.md

update documentation to work for raspberry as proven in #1236

update documentation for raspberry

---

docs/stoploss.md

Fix logic error in stoploss.md  as found out in https://github.com/freqtrade/freqtrade/commit/6a3c8e3933a911ba7df6d9694be235a78579a78a

Fix spelling in stoploss.md

---

freqtrade/rpc/telegram.py

add missing option from help (so i don't have to look it up in the code each time i need it).

Add reload_conf to telegram help

---

docs/hyperopt.md

improve documentation on hyperopt, as it seems to raise a lot of questions on how to implement ROI 
* a new section about ROI space interpretation added
* a new part on how to validate hyperopt results through backtest was added.

Add hyperopt ROI documentation, add note on methology for hyperopt

---

freqtrade/exchange/__init__.py
freqtrade/rpc/rpc.py
freqtrade/tests/exchange/test_exchange.py
freqtrade/tests/rpc/test_rpc.py
freqtrade/tests/rpc/test_rpc_telegram.py

Don't crash on telegram if ticker for pair is not available (especially problematic with `/balance`.
Solve the issue: #1272

solve /balance crashes

---

scripts/plot_dataframe.py

Partially reverts #1287 - which inadvertantly removed the plot_dataframe script

Reinstate df - which was removed in #1287

---

CONTRIBUTING.md
README.md

point out good first issue label - some minor header fixes
Extending on issue #1180

point out "good first issue" label

---

freqtrade/wallets.py

Use dot to access attribute in NamedTuple
Solve the issue: #1359

Use dot to access attribute in NamedTuple

---

freqtrade/tests/test_wallets.py

Cover wallets.get_free in live mode 
add test-case for #1359

Test live mode of get_free

---

config_binance.json.example
freqtrade/exchange/__init__.py

Add configuration sample for binance (with valid pairs!)
Improve message shown when an invalid pair is used
Solve the issue: #1366

Add binance config sample, improve invalid pair message

---

freqtrade/freqtradebot.py

"checking sell" INFO log message pollutes logs unnecessarily.

---

freqtrade/freqtradebot.py

`logger.debug('Found no sell signal for %s.', trade)`
instead of 
`logger.info('Found no sell signal for whitelisted currencies. Trying again..')`

log "Found no sell signal for whitelisted ..." changed

---

freqtrade/optimize/edge_cli.py

Fix some comments in edge-cli noticed while "passing by" ...

Fix edge-cli comments

---

docs/index.md

Doc link was broken for some reason ...

fix edge doc broken link

---

README.md

Also adds edge to index.md
fixes one point in #1319 (adding oneliner)
Requested @mishaker for review because edge is his baby and he can probably describe it better

Add link to contributing for "wanna help"

---

freqtrade/exchange/__init__.py
freqtrade/tests/exchange/test_exchange.py

Will be useful for logs and slippage calculation between TA and real price at buy moment. more efficient than returning the whole DF.

Adding "copy" as a parameter to klines. default to True

---

docs/bot-optimization.md

Improved strategy explanation
Solve the issue: #818
- added correct TOC
- added some of the new options

Enhance strategy explanation

---

freqtrade/__init__.py

Version bump to 0.18.1-dev, merge master to develop (to avoid merge-conflicts for future version updates)

After release

---

docs/developer.md

Instructions on how to create a Release
For self-reference as well as for other maintainers.

Add release documentation

---

.pyup.yml
requirements-plot.txt

Add `requirements-plot.txt` and have `plotly` (used in our plotting scripts) update via pyup.
Intentionally used 1 version below current, to verify pyup works for this file.

Add plotly requirements file

---

setup.sh

cd build_helpers added before extracting Tar

---

mkdocs.yml

- Improve structure of the docs, combining what goes together (telegram, webhooks) ...
- move developer docs to the bottom ...
- fix typo in layout

fix typo, improve doc sequence

---

Dockerfile

Upgrade dockerfile base to latest python version 3.7.2

Update dockerfile to python 3.7.2

---

setup.sh

- Only default value while asking questions should be in capital.
- Changed the tense of sentences (ex. "Update your virtual env" => " Updating your virtual env".

fixes few wordings

---

.travis.yml
build_helpers/install_ta-lib.sh
build_helpers/publish_docker.sh

* Update travis image from trusty to xenial
* fix ta-lib installation in .travis.yml
* cache installed ta-lib to speed up travis runs

Fix travis failures 

---

freqtrade/optimize/backtesting.py
freqtrade/optimize/edge_cli.py
freqtrade/rpc/telegram.py
requirements-dev.txt

Add type-ignores to floatfmt
tabulate supports this so mypy is wrong.
https://bitbucket.org/astanin/python-tabulate/src/30554300d76f673377956f7980ba4fd2f892c671/tabulate.py?at=master&fileviewer=file-view-default#tabulate.py-1291:1294
Also upgrading myp to lastest version (otherwise pyup does it tomorrow ...)

Fix mypy issue 2

---

CONTRIBUTING.md
docs/developer.md

Improve documentation for new developers to get started
* add link to readthedocs.com style so i find it again myself

Improve developer docs

---

freqtrade/freqtradebot.py
freqtrade/optimize/backtesting.py
requirements-dev.txt

Add 2 flake8 plugins to help with development and code cleanness.
A fullish list can be found [here](https://github.com/DmytroLitvinov/awesome-flake8-extensions#testing)

Add flake8 plugins 

---

freqtrade/edge/__init__.py

The question as asked in #1523 is recurrent. 
I enriched Edge messages so hopefully it is a bit more understandable.

Edge messages enriched

---

freqtrade/strategy/interface.py

Wrong logger name (root) in the log

Cosmetic: fix logging in strategy/interface.py

---

config_full.json.example
docs/configuration.md
freqtrade/freqtradebot.py

fetch amount_reserve_percent from the configuration file

---

user_data/strategies/test_strategy.py

improve sample strategy for users
* Fix typo in test-strategy
* add volume since in #1364 it was pointed out that a check for volume should always be there
Solve the issue: part of #1364

Fix typo in test-strategy, add volume > 0 check to buy/sell check

---

freqtrade/constants.py

Forgotten/or did not know yet of this json validation schema existence when previous PR which added this option was proposed...

Minor: added amount_reserve_percent into config json-schema

---

freqtrade/exchange/__init__.py

* a wrong comment deleted. Cause it's wrong.
* a couple of typos in the comments fixed
* new method _now_is_time_to_refresh() added. May be useful when the condition in it becomes more complex. (And it *will become* more complex soon, it's preparation for upcoming enhancement...)

Minor changes to exchange

---

freqtrade/__init__.py

Version bump so the version is newer than the latest release 0.18.1 
merge after #1578

Version bump develop to 0.18.2-dev

---

docs/faq.md

FAQ updated with question on Edge

---

docs/faq.md

minor: formatting math expression in FAQ

---

docs/edge.md

Went through the text of the doc page...

Edge doc file minor improvements, typos, formatting

---

freqtrade/freqtradebot.py
freqtrade/persistence.py
freqtrade/rpc/rpc.py
freqtrade/tests/test_persistence.py

* Pythonic stuff moved to separate methods in order to make _process() more straight so that the sequence of actions in _process() will be more readable.
* Fixed typo in a comment

Minor: code cleanup in _process()

---

freqtrade/edge/__init__.py

eliminate recursion in Edge

---

freqtrade/edge/__init__.py

In addition to #1601 (already accepted and merged)

[Minor] comments: removed mentioning recursion, typos, etc.

---

docs/bot-usage.md

Description of multiple config command line options added.
Concrete examples to the bot-configuration page (something like "Hiding your key and exchange secret") will follow.
Please review grammar, wording etc.

How to use multiple configuration files

---

docs/index.md

index.md reviewed, minor improvements

minor: doc update index.md

---

freqtrade/optimize/backtesting.py
freqtrade/tests/optimize/test_backtesting.py

The way stoploss on exchange works is currently incompatible with Backtesting.
However, backtesting assumes a perfect stoploss at all times (which basically equals stoposs-on-exchange), therefore we can safely deactivate that during backtesting.
Fixes issue: Raised on Slack.

Fix issue that backtest is broken when stoploss_on_exchange is on

---

docs/edge.md

Minor: typo in doc

---

docs/configuration.md

Desciption added to configuration.md.

Minor: exchange.sandbox parameter was missing in the docs

---

.travis.yml

New Pr testing if coveralls now behaves better than in #1636

Update travis for coveralls

---

freqtrade/pairlist/VolumePairList.py

Solve the issue: #1662 
- add check to `_gen_pair_whitelist`

Fix sort key not populated

---

docs/telegram-usage.md
freqtrade/rpc/telegram.py

Add `/forcebuy` to telegram /help command - if it's enabled.

Telegram help

---

docs/configuration.md

Improve documentation, fix broken link

Add 15min to documentation, fix link to "parameters in THE strategy"

---

docs/backtesting.md

remove duplicate section explaining how to load backtest results.

Remove duplicate backtest-result-analysis documentation

---

.travis.yml
docs/plotting.md
scripts/get_market_pairs.py
scripts/plot_dataframe.py
scripts/plot_profit.py

the scripts-folder should be checked for style and correctness as well.
Loading mypy also ensures syntactical correctness, even if we don't run the scripts as part of CI.

run flake8 and mypy against scripts folder as well.

---

freqtrade/rpc/rpc.py
freqtrade/rpc/telegram.py
freqtrade/tests/rpc/test_rpc.py
freqtrade/tests/rpc/test_rpc_telegram.py

Telegram status message refactoring

---

freqtrade/persistence.py
freqtrade/strategy/interface.py
freqtrade/tests/optimize/__init__.py
freqtrade/tests/optimize/test_backtest_detail.py
freqtrade/tests/test_freqtradebot.py
freqtrade/tests/test_persistence.py

Solve the issue: #1575
- max_rate should always be updated, so extract this to a seperate function
- Add min_rate so post-analysis is simplified
- add Test to check if trailing-stop is updated correctly and selling correctly during stoploss (hint: it was not)
- this is based on the logic outlined by @gianlup inhttps://github.com/freqtrade/freqtrade/issues/1575#issuecomment-469878803 multiplied by 50 to have it aligned to the other tests.
- added a docstring to let me know if stoploss is absolute or a factor without digging through code
- added some docstrings for clarity
- fixed test-numbering in detailed-tests
Fixing problem2 is (in theory) simple as copy/pasting all of the following code to line 304 in the same file. A few cleanups will be necessary in that case however. …

trailing stop backtest problems

---

freqtrade/tests/conftest.py
freqtrade/tests/rpc/test_fiat_convert.py
freqtrade/tests/rpc/test_rpc.py
freqtrade/tests/rpc/test_rpc_telegram.py

We patch coinmarketcap a few hundred times.
we can also autopatch it every time...
I'm investigating if this makes sense in other patches too - but it's difficult as it doesn't allow exceptions...

Cleanup tests a bit

---

freqtrade/rpc/telegram.py
freqtrade/tests/rpc/test_rpc_telegram.py

Split up /balance telegram-messages into multiple calls if necessary.
Resolves #1745

Telegram long /balance message

---

freqtrade/rpc/telegram.py
scripts/get_market_pairs.py

Add missing header for /daily
Add source-link for copy/pasted script from ccxt
Old:
New:

Missing /daily header

---

freqtrade/arguments.py
freqtrade/configuration.py

With this PR we can override config options "max_open_trades" and "stake_amount" with the command line.

Added command line options to override max_open_trades and stake_amount

---

docs/installation.md

we now have a requirements-pi.txt file - so we should point to that instead of having users remove it from the "real" file.

Update documentation for Raspberry 

---

Dockerfile

Update docker image to new python version

Version bump to 3.7.3 in docker file

---

docs/developer.md

Better explain some steps when creating new releases

Improve developer documentation

---

freqtrade/configuration.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/optimize/test_edge_cli.py
freqtrade/tests/optimize/test_hyperopt.py
freqtrade/tests/test_configuration.py

Simplify configuration class complexity by extracting repeated logic of "check if key is in namespace", "copy it to config", "print log" to a separate function.
- simplify configuration class
- combine all optimize logics (they are all called anyway, so it does not matter where it applies).
- removed duplicate entries (--timerange, --refresh_pairs, ...) since all where always called anyway.

Refactor config

---

freqtrade/worker.py

Fixes #1810 
Incorrect assignment to the Worker.freqtrade attribute upon reconfiguration.

Fix for #1810

---

docs/installation.md

Improve docker documentation to better outline how to run additional command line arguments
Fixes #1824

Improve docker documentation

---

docs/bot-optimization.md

Document how to inspect a generated dataframe using Print statements
Resolves #1833

Add printing dataframe to documentation

---

config_binance.json.example
config_full.json.example
config_kraken.json.example
docs/configuration.md

* Align configuration samples 
* add sample for order_types in the configuration which requires a slightly different syntax).

Small fixes

---

freqtrade/data/history.py
freqtrade/tests/data/test_btanalysis.py
freqtrade/tests/data/test_history.py
freqtrade/tests/test_misc.py

* Error description added into log message in except.
* <s>Renamed make_testdata_path() --> make_datadir_path(). Because it's not testdata dir.</s> 
* Common code transferred to new pair_data_filename() function to avoid code duplication.
* Tests adjusted.

minor: data/history slight cleanup/imrovement

---

freqtrade/arguments.py
freqtrade/tests/edge/test_edge.py
freqtrade/tests/test_arguments.py

Adding some missing tests for edge (and arguments.py) i noticed while reviewing #1871 (not related to that really ... but i saw them then).

Add some tests

---

docs/plotting.md

Slightly improve the plotting documentation (add a missing - but important sample), standardize how to call the scripts (`python3 script/<scripname.py`).

[minor] Improve plotting documentation

---

freqtrade/main.py

fix handling of SystemExit

---

freqtrade/tests/conftest.py

Fix test-failure introduced in #1891
https://travis-ci.org/freqtrade/freqtrade/builds/540374672

Fix test-failure introduced in #1891

---

freqtrade/edge/__init__.py
freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py

Minor cleanup in optimize modules.

minor optimize cleanup

---

docs/strategy-customization.md
freqtrade/data/dataprovider.py
user_data/strategies/test_strategy.py

Orderbook available in the strategy.
Solve the issue: #1874
1. Implemented freqtrade/data/dataprovider.py ordebook() method.
2. Added commented example how to use it to retrieve best bid and ask in user_data/strategies/test_strategy.py.

Bid ask strategy

---

freqtrade/optimize/backtesting.py

Small cleanup to reduce passing around and looking up dictionary keys where it's not necessary.

[minor] Small cleanup to reduce dict lookups during backtesting/hyperopt

---

freqtrade/strategy/interface.py
freqtrade/tests/strategy/test_strategy.py

...for better tracking of freqtrade actions.

debug logging for IStrategy.advise_*()

---

CONTRIBUTING.md
README.md
docs/developer.md
docs/index.md
docs/strategy-customization.md

Update slack link since the old one expired

---

freqtrade/freqtradebot.py

... in the name of a var in freqtradebot.py.

minor: fix typo

---

freqtrade/configuration.py

In the future, our custom validator may contain type checkers and other stuff, so let's make its name more neutral. Comment with description added.

minor: json validator cosmetics

---

docs/installation.md

minor: typo fixed in docs

---

freqtrade/__init__.py

Version bump dev-version after release #1957.
Should be merged after #1957

Version bump develop

---

freqtrade/vendor/qtpylib/indicators.py

Upgrade qtpylib to incorporate the change done by @hroff-1902 to fix ATR.

Update qtpylib from source

---

freqtrade/resolvers/strategy_resolver.py
freqtrade/tests/strategy/test_strategy.py

...found while reviewing base64-related code.

minor: couple of typos fixed

---

freqtrade/arguments.py

We don't need the "dest" kwargument, it's already the key of the dict.
part of  #1945 
- Remove duplicate entry

Remove duplicate keyword from arguments

---

config_full.json.example
docs/backtesting.md
docs/bot-usage.md
docs/configuration.md
docs/docker.md
docs/hyperopt.md
docs/strategy-customization.md
freqtrade/configuration.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/optimize/test_edge_cli.py
freqtrade/tests/optimize/test_hyperopt.py
freqtrade/tests/test_arguments.py
freqtrade/tests/test_configuration.py

Our wording is off as noticed in #1997.
Solve the issue: #1997

minor - Folders are not Directories

---

freqtrade/arguments.py
freqtrade/configuration.py
freqtrade/loggers.py
freqtrade/main.py
freqtrade/tests/conftest.py
freqtrade/tests/test_arguments.py
freqtrade/tests/test_configuration.py
freqtrade/tests/test_main.py

First part of refactoring, consists of a set of mostly minor improvements. See the list of commits.
I decided to split my current large set of changes so that the main idea will be more clear and readable for review at the end.
Next part of changes will follow.

minor: refactoring arguments and configuration

---

docs/rest-api.md

Currently some of the danger boxes don't render, this is trying to fix that.

Fix non-rendering docs

---

freqtrade/data/dataprovider.py
freqtrade/rpc/telegram.py
freqtrade/tests/strategy/test_strategy.py
freqtrade/tests/test_freqtradebot.py
freqtrade/tests/test_plotting.py
freqtrade/tests/test_talib.py

Some small code cleanups found after analyzing the codebase with deepcode.ai (a company sponsoring Europython this year).
- Replace usage of `filter` with comprehensions
- don't overwrite `max` argument

[Minor] Small code cleanups

---

freqtrade/configuration/configuration.py
scripts/download_backtest_data.py

Further configuration code cleanup, no changes to public interfaces or behavior...

minor: configuration cleanup

---

docs/bot-usage.md
docs/installation.md

* Rendering for a Note box fixed. (I hope)
* Non-working old link to misc.py removed.

Docs minor fixes

---

freqtrade/tests/optimize/test_hyperopt.py

Tests should test what they say they test (hyperoptloss...?).
- added tests for wrong names for both hyperopt and hyperopt-loss.

Fix some hyperopt tests

---

docs/developer.md

Add minor thing that is not very clear from the documentation.

Improve release documentation

---

freqtrade/__init__.py

Version bump for develop version.
should be merged after #2070

New develop version 2019.7-dev

---

freqtrade/optimize/hyperopt.py
freqtrade/tests/optimize/test_hyperopt.py

* Some minor code cleanups, aligning the use of terms in the names of the vars and dict keys.
Changes visible to the users:
* the number of epoch ("52/100") is now printed to the best results string. It can help localize it in the list of results dumped to the file.
* the value of the objective is now printed in the string with best results as well.
* the "ROI table" and "Best result: ..." is NOW printed to stdout instead of logging. Because details are also printed to stdout.

minor: hyperopt cleanups and output improvements

---

docs/data-analysis.md

Improving the documentation about how to analyze problems with a strategy.
Once completed, this shall be followed up with a section about plotting the above data.

docs: Create detailed section about strategy problem analysis

---

freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/test_configuration.py

a replacement for closed #2068

tests: hide deprecation warning due to use of --live

---

.github/ISSUE_TEMPLATE.md

Add operating sytem to the questions we ask in the issue template.
This is important for installation problems.

add Operating system to issue template

---

.gitignore
docs/data-analysis.md
environment.yml
setup.py
user_data/notebooks/analysis_example.ipynb

Adds a sample jupyter notebook and documentation for use.
- Edited docs/data-analysis.md for clarity and conformity with example
- Added sample notebook
- Included jupyter in setup.py and environment.yml

Added jupyter notebook example and doc edits

---

freqtrade/configuration/configuration.py
freqtrade/configuration/load_config.py
freqtrade/tests/conftest.py
freqtrade/tests/test_configuration.py
scripts/download_backtest_data.py

* `load_config_file()` moved to a separate module

Minor configuration cleanup

---

freqtrade/optimize/default_hyperopt.py
user_data/hyperopts/sample_hyperopt.py

A few minor cleanup changes in the code, comments and helpstrings.

Minor: cosmetics in sample_hyperopt and default_hyperopt

---

docs/strategy-customization.md

Fix wrongly rendering warning box

Fix wrong warning box

---

Dockerfile

Use python 3.7.4 instead of 3.7.3 as base image

Update dockerfile python version

---

docs/docker.md

As mentioned on slack - we should be clear on when the official images are rebuild.

[minor] Explain docker image rebuilding

---

docs/strategy-customization.md

...missed in the prev. PR.
Addendum to merged #2149

get_pair_dataframe(): example in the docs changed

---

freqtrade/data/history.py
freqtrade/misc.py
freqtrade/optimize/backtesting.py
freqtrade/tests/data/test_history.py
freqtrade/tests/optimize/test_backtesting.py
freqtrade/tests/test_misc.py

Abstract storage layer a bit better so we have one method to store / load data.
- new store_tickerdata_file method
- use load_tickerdata_file also to load cached data.

Refactorings to history

---

docs/backtesting.md

Fix grammar error 
Solve the issue: https://github.com/freqtrade/freqtrade/pull/2146#discussion_r315539700

Fix grammar error in documentation

---

scripts/download_backtest_data.py

Minor fixes:
* typo fixed in the printed message
* hash-bang added since it has exec. permissions

minor: fix download replacement script

---

.travis.yml
docs/bot-usage.md
docs/installation.md

Fix documentation boxes (and add a CI job checking they don't break again).
- Add job to fail when this syntax error appears (sample job: https://travis-ci.org/freqtrade/freqtrade/builds/575173244)
- Fix boxes

Fix documentation boxes

---

freqtrade/exchange/exchange.py

exchange --> exchange_name
To be separate from the bigger upcoming refactoring PR, to keep its clearness...

exchange cosmetics

---

docs/configuration.md

* The `exchange.password` setting added to the table of settings
* Warning 'Keep it in secrete, do not disclose publicly.' added for `exchange.key/secrete/password` and for `telegram.token/chat_id`

minor: improvements in confuguration.md

---

freqtrade/__init__.py
freqtrade/configuration/configuration.py
freqtrade/tests/test_configuration.py

Same as #2199 - but against the master branch.
The only change is this fix.

Release 2019.8-1 - hotfix data-dir not including exchange

---

freqtrade/configuration/arguments.py
freqtrade/main.py
freqtrade/tests/conftest.py
freqtrade/tests/test_arguments.py
freqtrade/tests/test_configuration.py
freqtrade/tests/test_main.py

Remove arguments which are not used anywhere to simplify tests and instantiation.
- Remove description (it's only used once)
- remove `no_default_config` - it's never passed in (not even in tests anymore).

Arguments - remove unused arguments

---

setup.py

Adding `long_description` and `long_description_content_type` to setup.py, so once we publish to pypi it has the correct description. 
part of issue: #2112 
- Add long description (copy Readme.md if available).

Enhance setup.py to include long_description

---

.gitignore
tests/edge/test_edge.py
tests/exchange/test_exchange.py
tests/optimize/test_backtest_detail.py
tests/optimize/test_backtesting.py
tests/optimize/test_hyperopt.py
tests/test_configuration.py
tests/test_freqtradebot.py
tests/test_persistence.py

* SampleStrategy should not be excluded
* we should not print in tests (this is not visible unless the test fails anyway).

[minor] cleanup tests and fix excluded samplestrategy

---

requirements-common.txt

Manual bump to ccxt 1.18.1159

---

docs/configuration.md

Remove some wrong statements (stake_currency and stake_amount need to be in the configuration!).
Add prevelance documentation - so it's clear what overrides what other setting.

Improve configuration documentation

---

freqtrade/data/__init__.py

Minor: fix typo in comment

---

docs/backtesting.md
docs/data-download.md
docs/hyperopt.md
mkdocs.yml

Explain problems raised in #2277 
- Seperate download-data documentation into it's own file
- explain assumptions backtesting makes
- improve wording in backtesting documentation
- link to download-data from hyperopt

Improve backtesting documentation

---

CONTRIBUTING.md
README.md
docs/developer.md
docs/index.md
docs/strategy-customization.md

Update expired slack link
for the record:
> This link doesn't expire.Need to change this? Deactivate your link and choose a new duration.
closes #2309

Update slack link

---

.travis.yml
build_helpers/publish_docker.sh
docs/bot-usage.md
docs/configuration.md
freqtrade/configuration/cli_options.py
freqtrade/configuration/configuration.py
freqtrade/constants.py
freqtrade/resolvers/strategy_resolver.py
tests/conftest.py
tests/strategy/test_strategy.py
tests/test_configuration.py

As discussed in #2281, this will remove defaulting to DefaultStrategy.
I'm merging this into args-aftersubcommand since there are a TON of conflicting changes.
- Require --strategy or "strategy" in configuration to be set.

Disable Defaulting to DefaultStrategy

---

docs/backtesting.md
docs/plotting.md

Fix typo in the documentation - --datadir currently needs to be before subcommands
closes  #2338

fix documentation error

---

tests/strategy/legacy_strategy.py

it's just used for limited tests and does not need the commented elements

[minor] Cleanup legacy strategy

---

freqtrade/plot/plotting.py
tests/test_plotting.py

This solves rendering of bolinger bands and removes duplicate plot elements.
Solves issue #2289 
Related to upstream bug defined in https://github.com/plotly/plotly.js/issues/2284
- substitutes  `plotly.graph_objects.Scatter` for `plotly.graph_objects.Scattergl`
- removes duplicate legend items
All uses of `Scattergl` were replaced including those that were not specifically problematic. After upstream bug is fixed, the change can be reverted. New logic checks `indicators1` list and removes `bb_upperband` and `bb_lowerband` if added by the user. Changed label for BB in legend.

Enhancements to BB plotting

---

tests/data/test_history.py

Removing os.path from this file reduces the complexity - also we should not hardcode the path to ../testdata, but use the testdatadir fixture instead.

[minor] Don't use os.path in test_history

---

CONTRIBUTING.md
docs/strategy-customization.md

As the title says, in docs/strategy-customization.md.

Fix minor typos in the docs

---

docs/utils.md
freqtrade/configuration/cli_options.py

Fix helpstring which shared between the list-exchanges and list-timeframes subcommands

---

.travis.yml
docs/bot-usage.md
docs/hyperopt.md
freqtrade/configuration/cli_options.py
freqtrade/resolvers/hyperopt_resolver.py
tests/optimize/test_hyperopt.py

Align --hyperopt specification to other commands (don't use --custom
Solve the issue: https://github.com/freqtrade/freqtrade/pull/2264#issuecomment-540287648

Rename --custom-hyperopt to --hyperopt

---

user_data/strategies/sample_strategy.py

Fixes my mistake I made in #2378 
It's better to fix it now than to recall it later...

Minor: Fix double comments for ADX

---

freqtrade/resolvers/hyperopt_resolver.py
freqtrade/resolvers/iresolver.py
freqtrade/resolvers/pairlist_resolver.py
freqtrade/resolvers/strategy_resolver.py

* Refactor search-path building to parent class
* return generator instead of next from `_get_valid_object()` (enables searching for all available objects in a future PR).

[minor] Iresolver small improvements

---

docs/backtesting.md

Outline another assumption that is taken, to be clear how backtesting works.

[minor] Improve assumptions

---

freqtrade/freqtradebot.py
tests/strategy/test_strategy.py
tests/test_configuration.py
tests/test_freqtradebot.py
tests/test_plotting.py

Fix some minor things that prevent tests on windows from passing.
- use Path to convert paths to windows / linux styles
- add grace-period for one test relying on time, since on windows this becomes flaky

[minor] Fix/tests windows

---

freqtrade/freqtradebot.py

...cosmetic changes after #2384.

Minor freqtradebot cleanup

---

docs/backtesting.md
docs/strategy-customization.md

Improve documentation regarding things to look out for in strategies to avoid looking into the future.
This list may be expanded as things happen - but for now it includes what i experienced and got reported so far.

[doc] Clearly highlight potential problems with looking into the future

---

freqtrade/resolvers/exchange_resolver.py

Fix small oversight from #2369 
- pass validate flag to the fallback exchange too.

Correctly pass validate flag to fallback exchange too

---

docs/configuration.md

The Ocean requires web3 package installed.

docs: add a tip for The Ocean exchange

---

docs/advanced-setup.md
docs/installation.md
mkdocs.yml

* systemd stuff is moved there from installation.md;
* detailed description for syslog and journald from #2418 is to be placed here as well;

docs: Create Advanced Post-installation Tasks section

---

docs/configuration.md

...in docs/configuration.md
from Slack channel (thanks to Escaliert@Slack)

minor: Fix typo in docs

---

docs/installation.md

Improve windows install documentation, reccomending 64bit  windows and conda as installation methods
Solve the issue: #2358

Improve windows Install documentation with hints

---

docs/developer.md

Update release-documentation to how we're working now - not basing on top of the latest develop.

[minor][docs] Update release-documentation to fit new release style

---

docs/faq.md

Update faq with examples of grepping the log

---

freqtrade/freqtradebot.py
tests/test_freqtradebot.py

The continue must happen irrespective of the outcome of this - otherwise
the below BUY will happen anyway.
Closes #2477
- Fix location of "continue" section.
- Adjust Test to cover this ...

Fix bug where bids_to_ask_delta causes doublebuys

---

docs/installation.md

Cosmetics addendum to #2495.
@gaugau3000 pls also review it.

minor: Wordings on top of #2495

---

docs/exchanges.md

...plus some minor change to wordings.

Minor: Exchange notes typographical cosmetics

---

docs/exchanges.md

* Formatting (structure of sections)
* Cosmetic changes
This was not noticed in terms of #2505

minor: Exchange notes docs

---

docs/exchanges.md

things still not noticed at the previous related PRs

minor: More cosmetics on Exchange Notes

---

docs/rest-api.md
freqtrade/rpc/api_server.py
tests/rpc/test_rpc_apiserver.py

Add an unauthenticated "ping" endpoint to verify easily (within a browser) that the API works.

Add ping endpoing

---

docs/rest-api.md

minor: Fix typo in the rest-api docs

---

.github/workflows/docker_update_readme.yml

Update dockerhub description from the github readme automatically
supplement to #2518 
- based on master (there can only be one description on dockerhub, and it should be the latest).

Update dockerhub description from github readme.md

---

.github/workflows/ci.yml
.travis.yml

Fix error in github actions test output for coverall

Try moving coveralls to github actions

---

.github/workflows/ci.yml

Do doc-check in a seperate step - this allows to easily identify if this did fail.

seperate docs job

---

user_data/strategies/sample_strategy.py

...into comment in the SampleStrategy.
(from Slack)

minor: Add example of usage for Aroon, Aroon Oscillator

---

freqtrade/rpc/api_server.py
scripts/rest_client.py
tests/rpc/test_rpc_apiserver.py

Fix some issues and inconsistencies with the rest client.
Unfortunately, the rest-client now a dependency on rapidjson (previously the only dependency was `requests`).
closes #2528
- accept "commented" configs
- return empty list intead of error when calling `status` when no trade is open
- fail if config is not found (it won't work without config anyway since the username / password is required).

Improve rest api client / status response

---

freqtrade/strategy/interface.py

Fixes second part of https://github.com/freqtrade/freqtrade-strategies/issues/51

minor: Fix second part of freqtrade-strategies #51

---

.github/workflows/ci.yml

This should reenable slack notifications (for PR's from this repo )...

reenable slack

---

.github/workflows/ci.yml

Coveralls should comment here ...

Try coveralls fixing (again ...) 

---

docs/advanced-setup.md

minor: Fix formatting typo in docs

---

docs/utils.md

Left after merging #2581, oops

minor: Fix documentation formatting

---

docs/webhook-config.md
freqtrade/freqtradebot.py
freqtrade/rpc/telegram.py
tests/rpc/test_rpc_telegram.py
tests/test_freqtradebot.py

Show the duration of the trade together with the sell notifiction.
Trade-duration is something very interresting ... (did the bot make 2% in 1 day? in 1 hour? ...)
- Add Duration to sell-notification

Telegram / sell duration

---

docs/developer.md

Expand release-doc with a explanation on how to create a collapsible section, as used in the [latest release](https://github.com/freqtrade/freqtrade/releases/tag/2019.11).

[minor][doc] Add release section about collapsible section

---

tests/data/test_history.py

As mentioned in https://github.com/freqtrade/freqtrade/pull/2672#discussion_r358653686 ... we should not import history in 2 ways in the test file.
- Import each method explicitly

Align usage of history import in test

---

.github/workflows/ci.yml
tests/test_main.py
tests/test_utils.py

Fix random test failure.
The 2 i've investigated did not occur anymore, unfortunately only time will tell if it's really fixed since even with the same seed, it's not always occuring.
todo:

Fix random test failure. 

---

docs/data-analysis.md

Update doucmentation to show how to install a kernel in jupyter, but also refer to the jupyter documentation for more details.
Closes #2670

Document usage of jupyter with venv kernel

---

freqtrade/freqtradebot.py

Small cleanup in Freqtradebot for readability:
* Separate BUY and SELL parts of the business logic with the block comments
* Move `enter_positions()` up in the BUY part to align the position of the `exit_positions()` in its SELL part of the code
* Fix comment

Cosmetics in freqtradebot

---

docs/installation.md

Since it happened several times now that the same installation error on Macos Appeared (namely #1675, #1774 and #2708) - we should add a trouble-shooting section mentioning this to our documentation, so we can reference users to that easily.
Closes #2708

Add note about MacOS installation

---

docs/backtesting.md

Taken from https://github.com/freqtrade/freqtrade/issues/2738#issuecomment-570687230. slightly reworded.

Minor: Refine fee example in the docs

---

freqtrade/optimize/backtesting.py

Refactored the comment on the backtesting.py file
- Modified comment statement to fit with the indentation

Update comments on backtesting

---

docs/index.md

Reorganize feature doc section
Solve the issue: #2497
- 9199fd5 change the introduction of freqtrade in the documentation
- 0e9e6b3 organize feature based on the workflow of the end user
- impact changes after validation in [readme-> feature](https://github.com/freqtrade/freqtrade#features)
Have a nice day

Doc feature section

---

freqtrade/freqtradebot.py
freqtrade/rpc/rpc.py
freqtrade/rpc/rpc_manager.py
tests/test_configuration.py

Remove .get calls for dry_run - it's a mandatory property
I'm certain there are other properties where the same applies - but one step at a time ...

remove default value calls for dry_run

---

build_helpers/install_windows.ps1

Trying to fix windows CI errors seen in the last 2 Pull requests
* Upgrade pip ...

upgrade pip in windows environment

---

tests/test_freqtradebot.py

To support the claims i made about the calculations in #2792 - i've refactored the tests for this part of the code into one parametrized test (and added a few more cases).
- Parametrize tests previously called in sequence.

Add parametrized tests for get_buy_rate

---

freqtrade/commands/trade_commands.py

...to emphasize that it's not about circular dependencies...
(I just tried 😉 to move the import statement above to the module level as an 'improvement', after the refactoring made, which introduced the commands module... That was really a bad, incorrect idea...)

Minor cosmetics in start_trading

---

freqtrade/freqtradebot.py
freqtrade/worker.py

Refactor status notification interface method which is to be used by worker.
This simplifies worker and reduces its dependencies.

Add notify_status() to FreqtradeBot

---

freqtrade/freqtradebot.py

Added ask price, bid price, immediate ask quantity, and immediate bid quantity to check_depth_of_market_buy.
Also, the method now notifies the user if the delta condition was satisfied or not.

better logging on check_depth_of_market_buy()

---

freqtrade/optimize/backtesting.py
freqtrade/optimize/hyperopt.py

Some more line alignment fixes as formatted by flake8 in **freqtrade/optimize/backtesting.py** and **freqtrade/optimize/hyperopt.py**

fixed some more line alignments

---

freqtrade/optimize/hyperopt_loss_sharpe.py

No change of logic here, just updated hyperopt loss sharpe loss method for better readability to make it more consistent with the final version of sharpe loss daily loss method.

better readability on sharpe ratio loss method

---

freqtrade/freqtradebot.py

Just some more consistency changes on check_depth_of_market_buy, straight forward PR.

More consistency in check_depth_of_market_buy()

---

config_full.json.example
docs/configuration.md
freqtrade/constants.py
freqtrade/pairlist/SpreadFilter.py
freqtrade/pairlist/VolumePairList.py
tests/conftest.py
tests/pairlist/test_pairlist.py

add a pairlist filter to remove pairs above a specified difference between asks and bids

- added spread filter

---

docs/utils.md
freqtrade/commands/__init__.py
freqtrade/commands/arguments.py
freqtrade/commands/deploy_commands.py
freqtrade/commands/list_commands.py
freqtrade/constants.py
freqtrade/resolvers/strategy_resolver.py
tests/commands/test_commands.py
tests/test_freqtradebot.py

Pls verify I did not add an unsolicited dependency on hyperopt at the global level.
* Docs for `list-strategy` slightly refined to be aligned with `list-hyperopt`.

Add list-hyperopts subcommand

---

docs/configuration.md

Add some considerations for dry-run - which may be important to understand when using dry-run - and should answer a few questions up-front.
- Dry-run considerations

Add considerations for dry-run

---

CONTRIBUTING.md

...in CONTRIBUTING.md, with checking tests (may also fail with code changes made)

Minor: Adjust mypy and flake commands

---

docs/utils.md
freqtrade/commands/arguments.py
freqtrade/commands/cli_options.py
freqtrade/commands/hyperopt_commands.py
freqtrade/configuration/configuration.py
tests/commands/test_commands.py

Added filter options to "hyperopt-list" in order to easier find epochs.
PE8 conformant -> yes
Added options for "hyperopt-list"
--profitable
Select only profitable epochs.
--min-avg-time INT
Select epochs on above average time.
--max-avg-time INT
Select epochs on under average time.
--min-avg-profit FLOAT
Select epochs on above average profit.
--min-total-profit FLOAT
Select epochs on above total profit.
This will help to filter out unwanted results and present what you are after if it's related to profit or average time.
Example:
```
freqtrade hyperopt-list --min-avg-profit 0.4 --no-details
2020-02-09 00:46:11,665 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-09 00:46:11,665 - freqtrade.configuration.configuration - INFO - Parameter --min-avg-profit detected: 0.4
2020-02-09 …
```

Added filter options to "hyperopt-list" in order to easier find epochs.

---

tests/optimize/__init__.py
tests/optimize/test_backtest_detail.py

Fix an issue in tests detected by mypy
(better typing of an item and better check for default value)

Minor: Fix usage of an item from BTContainer in tests

---

tests/data/test_history.py

Fixes several mypy-detected errors in the tests for the history module.

Minor: Fix tests_history.py

---

docs/strategy-customization.md

Fixes #2911 (in strategy_customization.md)

Docs: Fix checking of runmode

---

freqtrade/templates/subtemplates/exchange_bittrex.j2

Add order_types into Bittrex config subtemplate

---

freqtrade/main.py

No reference to "previous behavior", which is okay now after months with new behavior and more than one master releases with this behavior.

Minor: Adjust message in main.py

---

build_helpers/publish_docker.sh

Fix failing docker build (can be seen [here](https://github.com/freqtrade/freqtrade/runs/457022091?check_suite_focus=true).

Use correct strategy path for docker testing

---

freqtrade/templates/sample_strategy.py
freqtrade/templates/subtemplates/indicators_full.j2

This doesn't affect much, it just adds some ordering and consistency onto **indicators_full.j2** file, along with adding a mention of Weighted Bollinger Bands (EMA based as opposed to SMA based), Ultimate Oscillator, and Keltner Channel.
I wasn't entirely sure if any logic in freqtrade depends on this file, so I didn't uncomment or comment anything.

indicators_full.j2 and sample_strategy.py ordering and added indicators

---

.github/workflows/ci.yml
docs/configuration.md

Quick fix and add extra info for configuration section in the doc. 
- 7d7318a Full or killed order doesn't exist.
- 76c449c Add extra info for VolumePairList.

 [Doc update config section] - [minor]

---

freqtrade/commands/list_commands.py

This PR is to standardize table style.
This change will align the list commands.
PEP8 = Yes
- Changed table for list- commands
Example of new style:
```
+-------------+--------------+---------+---------+----------+
|          Id |       Symbol |    Base |   Quote |   Active |
|-------------+--------------+---------+---------+----------|
|      ADABNB |      ADA/BNB |     ADA |     BNB |     True |
|      ADABTC |      ADA/BTC |     ADA |     BTC |     True |
|     ADABUSD |     ADA/BUSD |     ADA |    BUSD |     True |
|      ADAETH |      ADA/ETH |     ADA |     ETH |     True |
|      ADAPAX |      ADA/PAX |     ADA |     PAX |     True |
|     ADATUSD |     ADA/TUSD |     ADA |    TUSD |     True |
+-------------+--------------+---------+---------+----------+
```

Minor change to standardize table style.

---

docs/developer.md

Update release documentation with some details, and remove a section we're not using anymore.

[minor] improve and correct release documentation

---

docs/exchanges.md

Add general exchange section about "Nonce" errors.
Closes #2990

[minor] Add note about InvalidNonce to documentation

---

freqtrade/commands/hyperopt_commands.py

Simple code styling fix for hyperopt_interface.py

hyperopt_interface.py code styling

---

freqtrade/templates/base_hyperopt.py.j2
freqtrade/templates/sample_hyperopt.py
freqtrade/templates/sample_hyperopt_advanced.py

Update hyperopt samples docstring to link to the documentation, update link to advanced sample (and mention that it's available in userspace too).

Update hyperopt samples docstring

---

freqtrade/commands/optimize_commands.py
tests/optimize/test_backtesting.py
tests/optimize/test_hyperopt.py

Fixes #3048 
You may want to rephrase the text of the exception/error in the log.

Do not allow unlimited stake_amount for hyperopt

---

freqtrade/optimize/hyperopt_loss_sharpe.py
freqtrade/optimize/hyperopt_loss_sharpe_daily.py
freqtrade/optimize/hyperopt_loss_sortino.py
freqtrade/optimize/hyperopt_loss_sortino_daily.py

Fixes #3041, in the quick&dirty way.
I'll refactor handling of "bad" values returned from the loss function method later.

Adjust handling of zero stdev in loss functions

---

freqtrade/data/history/idatahandler.py

Trimming the dataframe can still return an empty dataframe, so check again for emptyiness

check again for emptiness after trimming dataframe

---

freqtrade/edge/edge_positioning.py
tests/edge/test_edge.py

Cosmetic changes: Align importing of items from data.history and constants

minor: Edge cosmetics

---

freqtrade/freqtradebot.py

Just a minor optimization and ordering of code logic, I caught in create_trade() .

minor create_trade() optimization

---

docs/configuration.md

Clarify documentation regarding max_open_trades (it's also limited by the pairlist length).
closes #3095

Update max_open_trades documentation

---

docs/hyperopt.md

Document how to instal hyperopt dependencies, since they are not installed by default.
closes #3180

document to install hyperopt dependencies

---

docs/configuration.md

minor: fix typo in the docs

---

freqtrade/optimize/hyperopt.py

No longer used after the tabular format was introduced

Minor: Remove unused methods in hyperopt

---

freqtrade/optimize/hyperopt.py
tests/commands/test_commands.py

* no print, use logger.info
* log csv file filename
* tests adjusted

Improve hyperopt-list logging

---

freqtrade/commands/hyperopt_commands.py
freqtrade/optimize/hyperopt.py
tests/optimize/test_hyperopt.py

Mostly cosmetics:
* Do not use 'trials' -- we have the 'results' and 'epochs' terms for this
* Improve slightly logging, method names.
* Remove the 'final' parameter in the save method -- it's only used for logging, which should better be done outside of the function.

Cleanup in Hyperopt

---

docs/backtesting.md

Clarify a potential doubt in the backtesting assumption section

Be clear on evaluation logic during backtesting

---

freqtrade/freqtradebot.py

Improve logmessage when falling back to wallet amount
While we log it in debug - having the values in info IF this case happens won't hurt.

[minor] Improve logmessage when falling back to wallet amount

---

freqtrade/rpc/rpc.py
freqtrade/rpc/telegram.py
freqtrade/state.py
tests/rpc/test_rpc_apiserver.py

Small improvements to the API, exposing state and max_open_trades.

Api improvements

---

docs/docker.md

Correct log path in documentation. This doesn't solve any issue.
- Update log path in documentation
Update log path from user_data/freqtrade.log -> `user_data/logs/freqtrade.log` in `docker` document.

Correct log path in doc.

---

docs/strategy-advanced.md

Fix sample (no timestamp in datetime, and not used in the samples)
As reported on Slack, thanks to @Prossi79

Docs: Fix samples in strategy-advanced.md

---

docs/installation.md

Update the installation documentation with the latest Ta_lib-0.4.18. 👍 
The requirements-common.txt has been updated previously on commit a379e68cf441407c9c04264714bfc7dbcc8e635d.
The documents will now reflect the same version

Update doc Ta_lib

---

docs/configuration.md

minor: fix typo in configuration.md

---

docs/strategy-customization.md

Minor fix in the strategy docs

---

docs/docker.md

Add a note explaining which image should be used on a raspberry.

Add note about PI and docker

---

freqtrade/exchange/binance.py
tests/exchange/test_binance.py

Fix stoploss on binance bug

---

freqtrade/pairlist/IPairList.py
freqtrade/pairlist/PrecisionFilter.py
freqtrade/pairlist/PriceFilter.py
freqtrade/pairlist/SpreadFilter.py
freqtrade/pairlist/StaticPairList.py
freqtrade/pairlist/VolumePairList.py
freqtrade/pairlist/pairlistmanager.py
tests/pairlist/test_pairlist.py

* unify a bit the structure of pairlists classes
* get rid of `filter()`
* various cosmetics (in pairlists and in the tests)

Cleanup in pairlists

---

freqtrade/worker.py

Refactor worker.py to have a small method managing sd_notify.
This removes the need to check and everything all the time.
No functional change - other than simplification ...

[minor] Simplify sd_notify usage

---

freqtrade/exchange/kraken.py

Minor: correct import of retrier

---

docs/configuration.md

Some improvements into the Pairlist docs

Improve Pairlist docs

---

freqtrade/pairlist/IPairList.py
freqtrade/pairlist/VolumePairList.py
freqtrade/pairlist/pairlistmanager.py

...to be it a method of pairlistmanager, which simplifies the usage (it has access to the blacklist stored in the attribute of pairlistmanager).

Refactor verify_blacklist()

---

freqtrade/rpc/api_server.py
tests/rpc/test_rpc_apiserver.py

needed on top of #3315 to support authenticated requests across domains

CORS - allow authenticated responses

---

docs/hyperopt.md

FIx outdated link in documentation.

[minor] Fix documentation link

---

freqtrade/pairlist/IPairList.py
freqtrade/pairlist/PrecisionFilter.py
freqtrade/pairlist/PriceFilter.py
freqtrade/pairlist/ShuffleFilter.py
freqtrade/pairlist/SpreadFilter.py
freqtrade/pairlist/VolumePairList.py

* Common generic implementation of filter_pairlist is moved to generic IPairList.
* The self._enabled attribute introduced for performance.
* type hints adjusted

Refactor filter_pairlists()

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

In almost every issue the first comment is "please fill out the issue template detailing your version".
we'll now also use seperate issue templates for issues and enhancements - hopefully this will turn out positive as well.
From now on, issues (not feature requests) that do not contain this section will be closed.
Also some rewording and hints that we expect copy/pasted text, not screenshots of logs.

Update issue template

---

freqtrade/plot/plotting.py

Plotting should not fail if one pair had no trades.

[minor] Plotting should not fail if one pair didn't produce any trades

---

requirements.txt

Manually Version bump pandas to 1.0.4

Version bump pandas to 1.0.4

---

docs/installation.md

Fixes broken link to virtualenv.
Fix #3401

Docs: fix #3401

---

docs/configuration.md

Fix a typo (duplicate link), on top of #3394

minor: Fix docs

---

docs/exchanges.md

Add note documenting the required rate-limit for Kraken datadownload
Closes #3429
might also fixx #3404 (in combination with #3432, obviously).

Add rate-limiting note for Kraken datadownload

---

freqtrade/rpc/telegram.py

Followup to #3449 - using json.dumps to print ask_strategy parameters.

Use json for *strategy dump

---

docs/hyperopt.md
docs/strategy-customization.md

Typo fixes
- Update english typo in strategy-customization
- Update command typo in hyperopt

Documentation fixes

---

docs/sql_cheatsheet.md

fix SQL cheatsheet query
Solve the issue: #3475 

fix SQL cheatsheet query (#3475)

---

docs/advanced-setup.md

Some cosmetics on top of #3481 
@muletman pls review as the author of the original addendum

Improve advanced-setup.md

---

docs/data-download.md

The correct argument is --datadir, not `--data-dir`.

Fix documentation typo

---

docs/backtesting.md

refers to issue 3413 @ https://github.com/freqtrade/freqtrade/issues/3413
--export trades command missing config and strategy declarations
Solve the issue: #3413
- added --config config.json to the command
- added --strategy SampleStrategy to the command
freqtrade backtesting --export trades --config config.json --strategy SampleStrategy

fixed --export trades command

---

Dockerfile
Dockerfile.armhf
docs/sql_cheatsheet.md

Fix wrong calculation in sql cheatsheet (as pointed out in #3568).
Also adds sqlite3 to the dockerfile, so editing the database is possible without much effort from within docker.
closes #3568

[minor] Fix typo in docs, install sqlite3 in docker image

---

docs/sql_cheatsheet.md

missing coma in sql request

---

docs/strategy-customization.md

Improve the sample code for informative pairs, highlighting the need to merge and ffill the dataframe, and not assign the value directly (which will cause very strange results).
- Change sample to RSI instead of ATR
- Show how to properly merge informative dataframe to the original dataframe

Improve informative pair sample

---

freqtrade/pairlist/PriceFilter.py
tests/conftest.py
tests/pairlist/test_pairlist.py

Pairfilter should not crash if last returns 0.
fixes  #3615

Fix pairfilter crash

---

docs/rest-api.md
docs/telegram-usage.md
freqtrade/rpc/api_server.py
freqtrade/rpc/rpc.py
freqtrade/rpc/telegram.py
scripts/rest_client.py
tests/rpc/test_rpc.py
tests/rpc/test_rpc_apiserver.py
tests/rpc/test_rpc_telegram.py

Add Telegram /delete command to immediately delete specific trade in the database
- Add Telegram /delete command

Add telegram /delete command

---

docs/edge.md

Re-arranged the introduction to better explain the theory of operation and the limitations of Edge. Added paragraphs at the bottom of "running edge independently" to better explain Edge's order of operations processing and potential differences between...
... historical output and live/dry-run operation.

improve Edge documentation

---

freqtrade/optimize/optimize_reports.py
tests/optimize/test_optimize_reports.py

Fix bug introduced in #3558 when a strategy produces 0 trades.

Fix bug in backtesting 

---

docs/deprecated.md
freqtrade/pairlist/VolumePairList.py
tests/pairlist/test_pairlist.py

Remove deprecated volumepairlist options

Remove deprectead volumepairlist options

---

docs/sql_cheatsheet.md

N/A
FIX: Docs - added missing ( to SQLite insert statement to avoid error.
- Docs code update
Doc update:
https://www.freqtrade.io/en/latest/sql_cheatsheet/#table-structure

FIX: Docs: added missing ( to SQLite insert statement to avoid error.

---

docs/hyperopt.md

5000 is an overkill for the hyperopt process, repetitive 500 produce better predictions

changed epochs from 5000 to 500

---

docs/data-download.md
freqtrade/commands/cli_options.py

1M and 1y timeframes added

---

freqtrade/misc.py
freqtrade/optimize/hyperopt.py

Allow surpressing log message when saving json file
Closes #3822

Fix hyperopt output

---

.github/workflows/ci.yml

Update actions image to ubuntu20.04, which is the latest supported ubuntu version by github actions.

Update actions image to ubuntu20.04

---

README.md
docs/index.md

added discord channel link in documentation 
added discord channel link in documentation

updated discord link to documentation.

---

README.md

update quick start steps

---

tests/optimize/conftest.py
tests/optimize/test_hyperopt.py
tests/optimize/test_hyperoptloss.py
tests/test_arguments.py
tests/test_wallets.py

Improve and refactor hyperopt tests
- Move loss-tests to their own file
- add conftest file for fixtures only used in optimize modules

Improve and refactor hyperopt tests

---

freqtrade/optimize/backtesting.py

Fix condition to support `--dmmp` again.
closes #3912

FIx bug with dmmp

---

docs/windows_installation.md

Fix typo in windows installation docs

Fix typo in windows installation docs

---

freqtrade/constants.py
freqtrade/data/converter.py
freqtrade/data/history/hdf5datahandler.py
freqtrade/data/history/history_utils.py
freqtrade/data/history/idatahandler.py
freqtrade/data/history/jsondatahandler.py
tests/data/test_converter.py
tests/data/test_history.py

Fix #3967
- refactor TradesList to constants
- Handle empty trade list when converting trades to OHLCV.

Fix bug when converting trades do ohlcv and no trades are available.

---

docs/includes/pairlists.md

Signed-off-by: hoeckxer <hawkeyenl@yahoo.com>
I have ran the steps as described in the CONTRIBUTING.md file.
During copy-paste from the documentation to my config file, I noticed an incorrect , that was included in the code sample
- Fixed typo
Fixed documentation incorrectness, which will prevent other users from copy-pasting the same error into their config file.

Fixed a small typo in the pairlist documentation

---

docs/backtesting.md
freqtrade/optimize/optimize_reports.py

New outputs of best / worst pair, as well as biggest winner / biggest looser.
- Reorder backtesting summary output
- Add best/worst pair and best/worst trade metrics

Enhance backtesting summary report

---

docs/installation.md
setup.sh

Update setup script and instruction to properly work for raspberry
closes #2871
- Detect raspberry and don't install hyperopt for it
- Ask for hyperopt / plot dependencies

improve setup.sh script

---

docs/edge.md

Put dollar sign after amount in edge.md

Put dollar sign after amount in edge.md

---

Dockerfile

This change reduce the image size about ~35%
Reduce the image size using multiple stages for docker.

Update dockerfile to multistage

---

docs/telegram-usage.md

add `/locks/` to command list in telegram documentation

added /locks to command list

---

docs/plotting.md
freqtrade/plot/plotting.py
tests/test_plotting.py

Sorry I deleted the first pull request, while fixing my history.
Here again, area plots.
I implemeted your suggestions and some simple test.
replaces #3372

Plot area between traces

---

tests/rpc/test_rpc_telegram.py

Extract telegram init to helper function to avoid code duplication
- introduce `get_telegram_testobject()`

simplify telegram tests

---

docs/freqai-feature-engineering.md
docs/telegram-usage.md
freqtrade/exchange/check_exchange.py
tests/exchange/test_exchange_utils.py

remove repetitive words
- <change log 1>
- <change log 1>

chore: remove repetitive words
